# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@cellar//bootstrap:host.bzl", "host_python_test")

host_python_test(
    name = "audit-trace-test",
    src = "test-audit-trace.py",
    resources = ["audit-trace.py"],
)

host_python_test(
    name = "audit-installation-test",
    src = "test-audit-installation.py",
    resources = ["audit-installation.py"],
)
