# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# Library sources visible to compilation. BUILD supplies the regenerated
# Unicode, DPD and BID tables in place of the shipped copies.
LIBCPP_FILES = [
    "libcpp/charset.c",
    "libcpp/directives-only.c",
    "libcpp/directives.c",
    "libcpp/errors.c",
    "libcpp/expr.c",
    "libcpp/files.c",
    "libcpp/identifiers.c",
    "libcpp/include/cpplib.h",
    "libcpp/include/line-map.h",
    "libcpp/include/mkdeps.h",
    "libcpp/include/symtab.h",
    "libcpp/init.c",
    "libcpp/internal.h",
    "libcpp/lex.c",
    "libcpp/line-map.c",
    "libcpp/macro.c",
    "libcpp/mkdeps.c",
    "libcpp/pch.c",
    "libcpp/symtab.c",
    "libcpp/system.h",
    "libcpp/traditional.c",
]

LIBDECNUMBER_FILES = [
    "libdecnumber/bid/bid-dpd.h",
    "libdecnumber/bid/bid2dpd_dpd2bid.c",
    "libdecnumber/bid/decimal128.c",
    "libdecnumber/bid/decimal128.h",
    "libdecnumber/bid/decimal128Local.h",
    "libdecnumber/bid/decimal128Symbols.h",
    "libdecnumber/bid/decimal32.c",
    "libdecnumber/bid/decimal32.h",
    "libdecnumber/bid/decimal32Symbols.h",
    "libdecnumber/bid/decimal64.c",
    "libdecnumber/bid/decimal64.h",
    "libdecnumber/bid/decimal64Symbols.h",
    "libdecnumber/bid/host-ieee128.c",
    "libdecnumber/bid/host-ieee32.c",
    "libdecnumber/bid/host-ieee64.c",
    "libdecnumber/dconfig.h",
    "libdecnumber/decBasic.c",
    "libdecnumber/decCommon.c",
    "libdecnumber/decCommonSymbols.h",
    "libdecnumber/decContext.c",
    "libdecnumber/decContext.h",
    "libdecnumber/decContextSymbols.h",
    "libdecnumber/decDPDSymbols.h",
    "libdecnumber/decDouble.c",
    "libdecnumber/decDouble.h",
    "libdecnumber/decDoubleSymbols.h",
    "libdecnumber/decExcept.c",
    "libdecnumber/decExcept.h",
    "libdecnumber/decLibrary.c",
    "libdecnumber/decNumber.c",
    "libdecnumber/decNumber.h",
    "libdecnumber/decNumberLocal.h",
    "libdecnumber/decNumberSymbols.h",
    "libdecnumber/decPacked.c",
    "libdecnumber/decPacked.h",
    "libdecnumber/decPackedSymbols.h",
    "libdecnumber/decQuad.c",
    "libdecnumber/decQuad.h",
    "libdecnumber/decQuadSymbols.h",
    "libdecnumber/decRound.c",
    "libdecnumber/decRound.h",
    "libdecnumber/decSingle.c",
    "libdecnumber/decSingle.h",
    "libdecnumber/decSingleSymbols.h",
    "libdecnumber/dpd/decimal128.c",
    "libdecnumber/dpd/decimal128.h",
    "libdecnumber/dpd/decimal128Local.h",
    "libdecnumber/dpd/decimal128Symbols.h",
    "libdecnumber/dpd/decimal32.c",
    "libdecnumber/dpd/decimal32.h",
    "libdecnumber/dpd/decimal32Symbols.h",
    "libdecnumber/dpd/decimal64.c",
    "libdecnumber/dpd/decimal64.h",
    "libdecnumber/dpd/decimal64Symbols.h",
]

# gtyp-input.list for the C and C++ front ends, in configure order. The two
# objdir entries are generated; every other entry is a shipped source.
GTYPE_INPUTS = [
    "libcpp/include/line-map.h",
    "libcpp/include/cpplib.h",
    "gcc/input.h",
    "gcc/coretypes.h",
    "auto-host.h",
    "include/ansidecl.h",
    "options.h",
    "gcc/config/vxworks-dummy.h",
    "gcc/config/i386/biarch64.h",
    "gcc/config/i386/i386.h",
    "gcc/config/i386/unix.h",
    "gcc/config/i386/att.h",
    "gcc/config/dbxelf.h",
    "gcc/config/elfos.h",
    "gcc/config/gnu-user.h",
    "gcc/config/glibc-stdint.h",
    "gcc/config/i386/x86-64.h",
    "gcc/config/i386/gnu-user-common.h",
    "gcc/config/i386/gnu-user64.h",
    "gcc/config/linux.h",
    "gcc/config/linux-android.h",
    "gcc/config/i386/linux-common.h",
    "gcc/config/i386/linux64.h",
    "gcc/config/initfini-array.h",
    "gcc/defaults.h",
    "include/hashtab.h",
    "include/splay-tree.h",
    "gcc/bitmap.h",
    "gcc/wide-int.h",
    "gcc/alias.h",
    "gcc/coverage.c",
    "gcc/rtl.h",
    "gcc/optabs.h",
    "gcc/tree.h",
    "gcc/tree-core.h",
    "gcc/libfuncs.h",
    "libcpp/include/symtab.h",
    "include/obstack.h",
    "gcc/real.h",
    "gcc/function.h",
    "gcc/insn-addr.h",
    "gcc/hwint.h",
    "gcc/fixed-value.h",
    "gcc/function-abi.h",
    "gcc/output.h",
    "gcc/cfgloop.h",
    "gcc/cfg.h",
    "gcc/profile-count.h",
    "gcc/cselib.h",
    "gcc/basic-block.h",
    "gcc/ipa-ref.h",
    "gcc/cgraph.h",
    "gcc/reload.h",
    "gcc/caller-save.c",
    "gcc/symtab.c",
    "gcc/alias.c",
    "gcc/bitmap.c",
    "gcc/cselib.c",
    "gcc/cgraph.c",
    "gcc/ipa-prop.c",
    "gcc/ipa-cp.c",
    "gcc/ipa-utils.h",
    "gcc/ipa-param-manipulation.h",
    "gcc/ipa-sra.c",
    "gcc/dbxout.c",
    "gcc/signop.h",
    "gcc/dwarf2out.h",
    "gcc/dwarf2asm.c",
    "gcc/dwarf2cfi.c",
    "gcc/dwarf2out.c",
    "gcc/tree-vect-generic.c",
    "gcc/dojump.c",
    "gcc/emit-rtl.h",
    "gcc/emit-rtl.c",
    "gcc/except.h",
    "gcc/explow.c",
    "gcc/expr.c",
    "gcc/expr.h",
    "gcc/function.c",
    "gcc/except.c",
    "gcc/ggc-tests.c",
    "gcc/gcse.c",
    "gcc/godump.c",
    "gcc/lists.c",
    "gcc/optabs-libfuncs.c",
    "gcc/profile.c",
    "gcc/mcf.c",
    "gcc/reg-stack.c",
    "gcc/cfgrtl.c",
    "gcc/stor-layout.c",
    "gcc/stringpool.c",
    "gcc/tree.c",
    "gcc/varasm.c",
    "gcc/gimple.h",
    "gcc/gimple-ssa.h",
    "gcc/tree-ssanames.c",
    "gcc/tree-eh.c",
    "gcc/tree-ssa-address.c",
    "gcc/tree-cfg.c",
    "gcc/tree-ssa-loop-ivopts.c",
    "gcc/tree-dfa.c",
    "gcc/tree-iterator.c",
    "gcc/gimple-expr.c",
    "gcc/tree-chrec.h",
    "gcc/tree-scalar-evolution.c",
    "gcc/tree-ssa-operands.h",
    "gcc/tree-profile.c",
    "gcc/tree-nested.c",
    "gcc/omp-offload.h",
    "gcc/omp-offload.c",
    "gcc/omp-expand.c",
    "gcc/omp-low.c",
    "gcc/targhooks.c",
    "gcc/config/i386/i386.c",
    "gcc/passes.c",
    "gcc/cgraphunit.c",
    "gcc/cgraphclones.c",
    "gcc/tree-phinodes.c",
    "gcc/tree-ssa-alias.h",
    "gcc/tree-ssanames.h",
    "gcc/tree-vrp.h",
    "gcc/ipa-prop.h",
    "gcc/trans-mem.c",
    "gcc/lto-streamer.h",
    "gcc/target-globals.h",
    "gcc/ipa-predicate.h",
    "gcc/ipa-fnsummary.h",
    "gcc/value-range.h",
    "gcc/vtable-verify.c",
    "gcc/asan.c",
    "gcc/ubsan.c",
    "gcc/tsan.c",
    "gcc/sanopt.c",
    "gcc/sancov.c",
    "gcc/ipa-devirt.c",
    "gcc/internal-fn.h",
    "gcc/hsa-common.c",
    "gcc/calls.c",
    "gcc/omp-general.h",
    "gcc/config/i386/i386-builtins.c",
    "gcc/config/i386/i386-expand.c",
    "gcc/config/i386/i386-options.c",
    "[c]",
    "gcc/c/c-lang.c",
    "gcc/c/c-tree.h",
    "gcc/c/c-decl.c",
    "gcc/c-family/c-common.c",
    "gcc/c-family/c-common.h",
    "gcc/c-family/c-objc.h",
    "gcc/c-family/c-cppbuiltin.c",
    "gcc/c-family/c-pragma.h",
    "gcc/c-family/c-pragma.c",
    "gcc/c-family/c-format.c",
    "gcc/c/c-objc-common.c",
    "gcc/c/c-parser.h",
    "gcc/c/c-parser.c",
    "gcc/c/c-lang.h",
    "[cp]",
    "gcc/cp/name-lookup.h",
    "gcc/cp/cp-tree.h",
    "gcc/c-family/c-common.h",
    "gcc/c-family/c-objc.h",
    "gcc/c-family/c-pragma.h",
    "gcc/cp/decl.h",
    "gcc/cp/parser.h",
    "gcc/c-family/c-common.c",
    "gcc/c-family/c-format.c",
    "gcc/c-family/c-cppbuiltin.c",
    "gcc/c-family/c-pragma.c",
    "gcc/cp/call.c",
    "gcc/cp/class.c",
    "gcc/cp/constexpr.c",
    "gcc/cp/constraint.cc",
    "gcc/cp/coroutines.cc",
    "gcc/cp/cp-gimplify.c",
    "gcc/cp/cp-lang.c",
    "gcc/cp/cp-objcp-common.c",
    "gcc/cp/decl.c",
    "gcc/cp/decl2.c",
    "gcc/cp/except.c",
    "gcc/cp/friend.c",
    "gcc/cp/init.c",
    "gcc/cp/lambda.c",
    "gcc/cp/lex.c",
    "gcc/cp/logic.cc",
    "gcc/cp/mangle.c",
    "gcc/cp/method.c",
    "gcc/cp/name-lookup.c",
    "gcc/cp/parser.c",
    "gcc/cp/pt.c",
    "gcc/cp/rtti.c",
    "gcc/cp/semantics.c",
    "gcc/cp/tree.c",
    "gcc/cp/typeck2.c",
    "gcc/cp/vtable-class-hierarchy.c",
]

# Files gengtype writes for GTYPE_INPUTS.
GTYPE_OUTPUTS = [
    "gtype-desc.c",
    "gtype-desc.h",
    "gtype-c.h",
    "gtype-cp.h",
    "gt-alias.h",
    "gt-asan.h",
    "gt-bitmap.h",
    "gt-c-c-decl.h",
    "gt-c-c-parser.h",
    "gt-c-family-c-common.h",
    "gt-c-family-c-cppbuiltin.h",
    "gt-c-family-c-format.h",
    "gt-c-family-c-pragma.h",
    "gt-caller-save.h",
    "gt-calls.h",
    "gt-cfgrtl.h",
    "gt-cgraph.h",
    "gt-cgraphclones.h",
    "gt-cgraphunit.h",
    "gt-coverage.h",
    "gt-cp-call.h",
    "gt-cp-class.h",
    "gt-cp-constexpr.h",
    "gt-cp-constraint.h",
    "gt-cp-coroutines.h",
    "gt-cp-cp-gimplify.h",
    "gt-cp-cp-lang.h",
    "gt-cp-cp-objcp-common.h",
    "gt-cp-decl.h",
    "gt-cp-decl2.h",
    "gt-cp-except.h",
    "gt-cp-friend.h",
    "gt-cp-init.h",
    "gt-cp-lambda.h",
    "gt-cp-lex.h",
    "gt-cp-logic.h",
    "gt-cp-mangle.h",
    "gt-cp-method.h",
    "gt-cp-name-lookup.h",
    "gt-cp-parser.h",
    "gt-cp-pt.h",
    "gt-cp-rtti.h",
    "gt-cp-semantics.h",
    "gt-cp-tree.h",
    "gt-cp-typeck2.h",
    "gt-cp-vtable-class-hierarchy.h",
    "gt-cselib.h",
    "gt-dbxout.h",
    "gt-dojump.h",
    "gt-dwarf2asm.h",
    "gt-dwarf2cfi.h",
    "gt-dwarf2out.h",
    "gt-emit-rtl.h",
    "gt-except.h",
    "gt-explow.h",
    "gt-function.h",
    "gt-gcse.h",
    "gt-ggc-tests.h",
    "gt-gimple-expr.h",
    "gt-godump.h",
    "gt-hsa-common.h",
    "gt-i386-builtins.h",
    "gt-i386-expand.h",
    "gt-i386-options.h",
    "gt-i386.h",
    "gt-ipa-devirt.h",
    "gt-ipa-prop.h",
    "gt-ipa-sra.h",
    "gt-lists.h",
    "gt-omp-expand.h",
    "gt-omp-low.h",
    "gt-optabs-libfuncs.h",
    "gt-stor-layout.h",
    "gt-stringpool.h",
    "gt-targhooks.h",
    "gt-trans-mem.h",
    "gt-tree-iterator.h",
    "gt-tree-nested.h",
    "gt-tree-phinodes.h",
    "gt-tree-profile.h",
    "gt-tree-scalar-evolution.h",
    "gt-tree-ssa-address.h",
    "gt-tree-ssa-loop-ivopts.h",
    "gt-tree-vect-generic.h",
    "gt-tree.h",
    "gt-ubsan.h",
    "gt-varasm.h",
    "gt-vtable-verify.h",
]

# gcc/ sources the C and C++ compilers, their generators and the x86_64
# target can read. BUILD supplies regenerated or patched replacements for
# gengtype-lex.c, genmatch.c and cp/cfns.h.
GCC_FILES = [
    "gcc/ABOUT-GCC-NLS",
    "gcc/BASE-VER",
    "gcc/DATESTAMP",
    "gcc/DEV-PHASE",
    "gcc/addresses.h",
    "gcc/alias.c",
    "gcc/alias.h",
    "gcc/align.h",
    "gcc/alloc-pool.c",
    "gcc/alloc-pool.h",
    "gcc/array-traits.h",
    "gcc/asan.c",
    "gcc/asan.h",
    "gcc/attribs.c",
    "gcc/attribs.h",
    "gcc/auto-inc-dec.c",
    "gcc/auto-profile.c",
    "gcc/auto-profile.h",
    "gcc/backend.h",
    "gcc/basic-block.h",
    "gcc/bb-reorder.c",
    "gcc/bb-reorder.h",
    "gcc/bitmap.c",
    "gcc/bitmap.h",
    "gcc/brig-builtins.def",
    "gcc/builtin-attrs.def",
    "gcc/builtin-types.def",
    "gcc/builtins.c",
    "gcc/builtins.def",
    "gcc/builtins.h",
    "gcc/caller-save.c",
    "gcc/calls.c",
    "gcc/calls.h",
    "gcc/ccmp.c",
    "gcc/ccmp.h",
    "gcc/cfg-flags.def",
    "gcc/cfg.c",
    "gcc/cfg.h",
    "gcc/cfganal.c",
    "gcc/cfganal.h",
    "gcc/cfgbuild.c",
    "gcc/cfgbuild.h",
    "gcc/cfgcleanup.c",
    "gcc/cfgcleanup.h",
    "gcc/cfgexpand.c",
    "gcc/cfgexpand.h",
    "gcc/cfghooks.c",
    "gcc/cfghooks.h",
    "gcc/cfgloop.c",
    "gcc/cfgloop.h",
    "gcc/cfgloopanal.c",
    "gcc/cfgloopmanip.c",
    "gcc/cfgloopmanip.h",
    "gcc/cfgrtl.c",
    "gcc/cfgrtl.h",
    "gcc/cgraph.c",
    "gcc/cgraph.h",
    "gcc/cgraphbuild.c",
    "gcc/cgraphclones.c",
    "gcc/cgraphunit.c",
    "gcc/cif-code.def",
    "gcc/collect-utils.c",
    "gcc/collect-utils.h",
    "gcc/collect2-aix.c",
    "gcc/collect2-aix.h",
    "gcc/collect2.c",
    "gcc/collect2.h",
    "gcc/color-macros.h",
    "gcc/combine-stack-adj.c",
    "gcc/combine.c",
    "gcc/common.md",
    "gcc/common.opt",
    "gcc/compare-elim.c",
    "gcc/conditions.h",
    "gcc/config.build",
    "gcc/context.c",
    "gcc/context.h",
    "gcc/convert.c",
    "gcc/convert.h",
    "gcc/coretypes.h",
    "gcc/coroutine-builtins.def",
    "gcc/coroutine-passes.cc",
    "gcc/coverage.c",
    "gcc/coverage.h",
    "gcc/cppbuiltin.c",
    "gcc/cppbuiltin.h",
    "gcc/cppdefault.c",
    "gcc/cppdefault.h",
    "gcc/cprop.c",
    "gcc/cse.c",
    "gcc/cselib.c",
    "gcc/cselib.h",
    "gcc/cstamp-h.in",
    "gcc/data-streamer-in.c",
    "gcc/data-streamer-out.c",
    "gcc/data-streamer.c",
    "gcc/data-streamer.h",
    "gcc/dbgcnt.c",
    "gcc/dbgcnt.def",
    "gcc/dbgcnt.h",
    "gcc/dbxout.c",
    "gcc/dbxout.h",
    "gcc/dce.c",
    "gcc/dce.h",
    "gcc/ddg.c",
    "gcc/ddg.h",
    "gcc/debug.c",
    "gcc/debug.h",
    "gcc/defaults.h",
    "gcc/df-core.c",
    "gcc/df-problems.c",
    "gcc/df-scan.c",
    "gcc/df.h",
    "gcc/dfp.c",
    "gcc/dfp.h",
    "gcc/diagnostic-color.c",
    "gcc/diagnostic-color.h",
    "gcc/diagnostic-core.h",
    "gcc/diagnostic-event-id.h",
    "gcc/diagnostic-format-json.cc",
    "gcc/diagnostic-metadata.h",
    "gcc/diagnostic-path.h",
    "gcc/diagnostic-show-locus.c",
    "gcc/diagnostic-url.h",
    "gcc/diagnostic.c",
    "gcc/diagnostic.def",
    "gcc/diagnostic.h",
    "gcc/digraph.cc",
    "gcc/digraph.h",
    "gcc/dojump.c",
    "gcc/dojump.h",
    "gcc/dominance.c",
    "gcc/dominance.h",
    "gcc/domwalk.c",
    "gcc/domwalk.h",
    "gcc/double-int.c",
    "gcc/double-int.h",
    "gcc/dse.c",
    "gcc/dump-context.h",
    "gcc/dumpfile.c",
    "gcc/dumpfile.h",
    "gcc/dwarf2asm.c",
    "gcc/dwarf2asm.h",
    "gcc/dwarf2cfi.c",
    "gcc/dwarf2out.c",
    "gcc/dwarf2out.h",
    "gcc/early-remat.c",
    "gcc/edit-context.c",
    "gcc/edit-context.h",
    "gcc/emit-rtl.c",
    "gcc/emit-rtl.h",
    "gcc/errors.c",
    "gcc/errors.h",
    "gcc/escaped_string.h",
    "gcc/et-forest.c",
    "gcc/et-forest.h",
    "gcc/except.c",
    "gcc/except.h",
    "gcc/exec-tool.in",
    "gcc/explow.c",
    "gcc/explow.h",
    "gcc/expmed.c",
    "gcc/expmed.h",
    "gcc/expr.c",
    "gcc/expr.h",
    "gcc/fibonacci_heap.c",
    "gcc/fibonacci_heap.h",
    "gcc/file-find.c",
    "gcc/file-find.h",
    "gcc/file-prefix-map.c",
    "gcc/file-prefix-map.h",
    "gcc/final.c",
    "gcc/fixed-value.c",
    "gcc/fixed-value.h",
    "gcc/flag-types.h",
    "gcc/flags.h",
    "gcc/fold-const-call.c",
    "gcc/fold-const-call.h",
    "gcc/fold-const.c",
    "gcc/fold-const.h",
    "gcc/fp-test.c",
    "gcc/function-abi.cc",
    "gcc/function-abi.h",
    "gcc/function-tests.c",
    "gcc/function.c",
    "gcc/function.h",
    "gcc/fwprop.c",
    "gcc/gcc-ar.c",
    "gcc/gcc-main.c",
    "gcc/gcc-plugin.h",
    "gcc/gcc-rich-location.c",
    "gcc/gcc-rich-location.h",
    "gcc/gcc-symtab.h",
    "gcc/gcc.c",
    "gcc/gcc.h",
    "gcc/gcov-counter.def",
    "gcc/gcov-dump.c",
    "gcc/gcov-io.c",
    "gcc/gcov-io.h",
    "gcc/gcov-iov.c",
    "gcc/gcov-tool.c",
    "gcc/gcov.c",
    "gcc/gcse-common.c",
    "gcc/gcse-common.h",
    "gcc/gcse.c",
    "gcc/gcse.h",
    "gcc/gdbasan.in",
    "gcc/gdbhooks.py",
    "gcc/gdbinit.in",
    "gcc/gen-pass-instances.awk",
    "gcc/genattr-common.c",
    "gcc/genattr.c",
    "gcc/genattrtab.c",
    "gcc/genautomata.c",
    "gcc/gencfn-macros.c",
    "gcc/gencheck.c",
    "gcc/genchecksum.c",
    "gcc/gencodes.c",
    "gcc/genconditions.c",
    "gcc/genconfig.c",
    "gcc/genconstants.c",
    "gcc/genemit.c",
    "gcc/genenums.c",
    "gcc/generic-match-head.c",
    "gcc/generic-match.h",
    "gcc/genextract.c",
    "gcc/genflags.c",
    "gcc/gengenrtl.c",
    "gcc/gengtype-lex.l",
    "gcc/gengtype-parse.c",
    "gcc/gengtype-state.c",
    "gcc/gengtype.c",
    "gcc/gengtype.h",
    "gcc/genhooks.c",
    "gcc/genmddeps.c",
    "gcc/genmddump.c",
    "gcc/genmodes.c",
    "gcc/genmultilib",
    "gcc/genopinit.c",
    "gcc/genoutput.c",
    "gcc/genpeep.c",
    "gcc/genpreds.c",
    "gcc/genrecog.c",
    "gcc/gensupport.c",
    "gcc/gensupport.h",
    "gcc/gentarget-def.c",
    "gcc/ggc-common.c",
    "gcc/ggc-internal.h",
    "gcc/ggc-none.c",
    "gcc/ggc-page.c",
    "gcc/ggc-tests.c",
    "gcc/ggc.h",
    "gcc/gimple-builder.c",
    "gcc/gimple-builder.h",
    "gcc/gimple-expr.c",
    "gcc/gimple-expr.h",
    "gcc/gimple-fold.c",
    "gcc/gimple-fold.h",
    "gcc/gimple-iterator.c",
    "gcc/gimple-iterator.h",
    "gcc/gimple-laddress.c",
    "gcc/gimple-loop-interchange.cc",
    "gcc/gimple-loop-jam.c",
    "gcc/gimple-loop-versioning.cc",
    "gcc/gimple-low.c",
    "gcc/gimple-low.h",
    "gcc/gimple-match-head.c",
    "gcc/gimple-match.h",
    "gcc/gimple-predict.h",
    "gcc/gimple-pretty-print.c",
    "gcc/gimple-pretty-print.h",
    "gcc/gimple-ssa-backprop.c",
    "gcc/gimple-ssa-evrp-analyze.c",
    "gcc/gimple-ssa-evrp-analyze.h",
    "gcc/gimple-ssa-evrp.c",
    "gcc/gimple-ssa-isolate-paths.c",
    "gcc/gimple-ssa-nonnull-compare.c",
    "gcc/gimple-ssa-split-paths.c",
    "gcc/gimple-ssa-sprintf.c",
    "gcc/gimple-ssa-store-merging.c",
    "gcc/gimple-ssa-strength-reduction.c",
    "gcc/gimple-ssa-warn-alloca.c",
    "gcc/gimple-ssa-warn-restrict.c",
    "gcc/gimple-ssa-warn-restrict.h",
    "gcc/gimple-ssa.h",
    "gcc/gimple-streamer-in.c",
    "gcc/gimple-streamer-out.c",
    "gcc/gimple-streamer.h",
    "gcc/gimple-walk.c",
    "gcc/gimple-walk.h",
    "gcc/gimple.c",
    "gcc/gimple.def",
    "gcc/gimple.h",
    "gcc/gimplify-me.c",
    "gcc/gimplify-me.h",
    "gcc/gimplify.c",
    "gcc/gimplify.h",
    "gcc/glimits.h",
    "gcc/godump.c",
    "gcc/graph.c",
    "gcc/graph.h",
    "gcc/graphds.c",
    "gcc/graphds.h",
    "gcc/graphite-dependences.c",
    "gcc/graphite-isl-ast-to-gimple.c",
    "gcc/graphite-optimize-isl.c",
    "gcc/graphite-poly.c",
    "gcc/graphite-scop-detection.c",
    "gcc/graphite-sese-to-poly.c",
    "gcc/graphite.c",
    "gcc/graphite.h",
    "gcc/graphviz.cc",
    "gcc/graphviz.h",
    "gcc/gsstruct.def",
    "gcc/gstab.h",
    "gcc/gsyms.h",
    "gcc/gsyslimits.h",
    "gcc/gtm-builtins.def",
    "gcc/haifa-sched.c",
    "gcc/hard-reg-set.h",
    "gcc/hash-map-tests.c",
    "gcc/hash-map-traits.h",
    "gcc/hash-map.h",
    "gcc/hash-set-tests.c",
    "gcc/hash-set.h",
    "gcc/hash-table.c",
    "gcc/hash-table.h",
    "gcc/hash-traits.h",
    "gcc/highlev-plugin-common.h",
    "gcc/hooks.c",
    "gcc/hooks.h",
    "gcc/host-default.c",
    "gcc/hosthooks-def.h",
    "gcc/hosthooks.h",
    "gcc/hsa-brig-format.h",
    "gcc/hsa-brig.c",
    "gcc/hsa-builtins.def",
    "gcc/hsa-common.c",
    "gcc/hsa-common.h",
    "gcc/hsa-dump.c",
    "gcc/hsa-gen.c",
    "gcc/hsa-regalloc.c",
    "gcc/hw-doloop.c",
    "gcc/hw-doloop.h",
    "gcc/hwint.c",
    "gcc/hwint.h",
    "gcc/ifcvt.c",
    "gcc/ifcvt.h",
    "gcc/inchash.c",
    "gcc/inchash.h",
    "gcc/incpath.c",
    "gcc/incpath.h",
    "gcc/init-regs.c",
    "gcc/input.c",
    "gcc/input.h",
    "gcc/insn-addr.h",
    "gcc/insn-notes.def",
    "gcc/int-vector-builder.h",
    "gcc/internal-fn.c",
    "gcc/internal-fn.def",
    "gcc/internal-fn.h",
    "gcc/intl.c",
    "gcc/intl.h",
    "gcc/ipa-comdats.c",
    "gcc/ipa-cp.c",
    "gcc/ipa-devirt.c",
    "gcc/ipa-fnsummary.c",
    "gcc/ipa-fnsummary.h",
    "gcc/ipa-hsa.c",
    "gcc/ipa-icf-gimple.c",
    "gcc/ipa-icf-gimple.h",
    "gcc/ipa-icf.c",
    "gcc/ipa-icf.h",
    "gcc/ipa-inline-analysis.c",
    "gcc/ipa-inline-transform.c",
    "gcc/ipa-inline.c",
    "gcc/ipa-inline.h",
    "gcc/ipa-param-manipulation.c",
    "gcc/ipa-param-manipulation.h",
    "gcc/ipa-polymorphic-call.c",
    "gcc/ipa-predicate.c",
    "gcc/ipa-predicate.h",
    "gcc/ipa-profile.c",
    "gcc/ipa-prop.c",
    "gcc/ipa-prop.h",
    "gcc/ipa-pure-const.c",
    "gcc/ipa-ref.c",
    "gcc/ipa-ref.h",
    "gcc/ipa-reference.c",
    "gcc/ipa-reference.h",
    "gcc/ipa-split.c",
    "gcc/ipa-sra.c",
    "gcc/ipa-utils.c",
    "gcc/ipa-utils.h",
    "gcc/ipa-visibility.c",
    "gcc/ipa.c",
    "gcc/ira-build.c",
    "gcc/ira-color.c",
    "gcc/ira-conflicts.c",
    "gcc/ira-costs.c",
    "gcc/ira-emit.c",
    "gcc/ira-int.h",
    "gcc/ira-lives.c",
    "gcc/ira.c",
    "gcc/ira.h",
    "gcc/is-a.h",
    "gcc/json.cc",
    "gcc/json.h",
    "gcc/jump.c",
    "gcc/langhooks-def.h",
    "gcc/langhooks.c",
    "gcc/langhooks.h",
    "gcc/lcm.c",
    "gcc/lcm.h",
    "gcc/libfuncs.h",
    "gcc/limitx.h",
    "gcc/limity.h",
    "gcc/lists.c",
    "gcc/lock-and-run.sh",
    "gcc/loop-doloop.c",
    "gcc/loop-init.c",
    "gcc/loop-invariant.c",
    "gcc/loop-iv.c",
    "gcc/loop-unroll.c",
    "gcc/loop-unroll.h",
    "gcc/lower-subreg.c",
    "gcc/lower-subreg.h",
    "gcc/lra-assigns.c",
    "gcc/lra-coalesce.c",
    "gcc/lra-constraints.c",
    "gcc/lra-eliminations.c",
    "gcc/lra-int.h",
    "gcc/lra-lives.c",
    "gcc/lra-remat.c",
    "gcc/lra-spills.c",
    "gcc/lra.c",
    "gcc/lra.h",
    "gcc/lto-cgraph.c",
    "gcc/lto-compress.c",
    "gcc/lto-compress.h",
    "gcc/lto-opts.c",
    "gcc/lto-section-in.c",
    "gcc/lto-section-names.h",
    "gcc/lto-section-out.c",
    "gcc/lto-streamer-in.c",
    "gcc/lto-streamer-out.c",
    "gcc/lto-streamer.c",
    "gcc/lto-streamer.h",
    "gcc/lto-wrapper.c",
    "gcc/machmode.def",
    "gcc/machmode.h",
    "gcc/main.c",
    "gcc/match.pd",
    "gcc/mcf.c",
    "gcc/mem-stats-traits.h",
    "gcc/mem-stats.h",
    "gcc/memmodel.h",
    "gcc/memory-block.cc",
    "gcc/memory-block.h",
    "gcc/mkconfig.sh",
    "gcc/mode-classes.def",
    "gcc/mode-switching.c",
    "gcc/modulo-sched.c",
    "gcc/multiple_target.c",
    "gcc/omp-builtins.def",
    "gcc/omp-expand.c",
    "gcc/omp-expand.h",
    "gcc/omp-general.c",
    "gcc/omp-general.h",
    "gcc/omp-grid.c",
    "gcc/omp-grid.h",
    "gcc/omp-low.c",
    "gcc/omp-low.h",
    "gcc/omp-offload.c",
    "gcc/omp-offload.h",
    "gcc/omp-simd-clone.c",
    "gcc/omp-simd-clone.h",
    "gcc/opt-functions.awk",
    "gcc/opt-gather.awk",
    "gcc/opt-include.awk",
    "gcc/opt-problem.cc",
    "gcc/opt-problem.h",
    "gcc/opt-read.awk",
    "gcc/opt-suggestions.c",
    "gcc/opt-suggestions.h",
    "gcc/optabs-libfuncs.c",
    "gcc/optabs-libfuncs.h",
    "gcc/optabs-query.c",
    "gcc/optabs-query.h",
    "gcc/optabs-tree.c",
    "gcc/optabs-tree.h",
    "gcc/optabs.c",
    "gcc/optabs.def",
    "gcc/optabs.h",
    "gcc/optc-gen.awk",
    "gcc/optc-save-gen.awk",
    "gcc/opth-gen.awk",
    "gcc/optinfo-emit-json.cc",
    "gcc/optinfo-emit-json.h",
    "gcc/optinfo.cc",
    "gcc/optinfo.h",
    "gcc/opts-common.c",
    "gcc/opts-diagnostic.h",
    "gcc/opts-global.c",
    "gcc/opts-jobserver.h",
    "gcc/opts.c",
    "gcc/opts.h",
    "gcc/ordered-hash-map-tests.cc",
    "gcc/ordered-hash-map.h",
    "gcc/output.h",
    "gcc/params.opt",
    "gcc/pass_manager.h",
    "gcc/passes.c",
    "gcc/passes.def",
    "gcc/plugin.c",
    "gcc/plugin.def",
    "gcc/plugin.h",
    "gcc/poly-int-types.h",
    "gcc/poly-int.h",
    "gcc/postreload-gcse.c",
    "gcc/postreload.c",
    "gcc/predict.c",
    "gcc/predict.def",
    "gcc/predict.h",
    "gcc/prefix.c",
    "gcc/prefix.h",
    "gcc/pretty-print.c",
    "gcc/pretty-print.h",
    "gcc/print-rtl-function.c",
    "gcc/print-rtl.c",
    "gcc/print-rtl.h",
    "gcc/print-tree.c",
    "gcc/print-tree.h",
    "gcc/profile-count.c",
    "gcc/profile-count.h",
    "gcc/profile.c",
    "gcc/profile.h",
    "gcc/range-op.cc",
    "gcc/range-op.h",
    "gcc/range.cc",
    "gcc/range.h",
    "gcc/read-md.c",
    "gcc/read-md.h",
    "gcc/read-rtl-function.c",
    "gcc/read-rtl-function.h",
    "gcc/read-rtl.c",
    "gcc/real.c",
    "gcc/real.h",
    "gcc/realmpfr.c",
    "gcc/realmpfr.h",
    "gcc/recog.c",
    "gcc/recog.h",
    "gcc/ree.c",
    "gcc/reg-notes.def",
    "gcc/reg-stack.c",
    "gcc/regcprop.c",
    "gcc/regcprop.h",
    "gcc/reginfo.c",
    "gcc/regrename.c",
    "gcc/regrename.h",
    "gcc/regs.h",
    "gcc/regset.h",
    "gcc/regstat.c",
    "gcc/reload.c",
    "gcc/reload.h",
    "gcc/reload1.c",
    "gcc/reorg.c",
    "gcc/resource.c",
    "gcc/resource.h",
    "gcc/rtl-error.c",
    "gcc/rtl-error.h",
    "gcc/rtl-iter.h",
    "gcc/rtl-tests.c",
    "gcc/rtl.c",
    "gcc/rtl.def",
    "gcc/rtl.h",
    "gcc/rtlanal.c",
    "gcc/rtlhash.c",
    "gcc/rtlhash.h",
    "gcc/rtlhooks-def.h",
    "gcc/rtlhooks.c",
    "gcc/rtx-vector-builder.c",
    "gcc/rtx-vector-builder.h",
    "gcc/run-rtl-passes.c",
    "gcc/run-rtl-passes.h",
    "gcc/sancov.c",
    "gcc/sanitizer.def",
    "gcc/sanopt.c",
    "gcc/sbitmap.c",
    "gcc/sbitmap.h",
    "gcc/sched-deps.c",
    "gcc/sched-ebb.c",
    "gcc/sched-int.h",
    "gcc/sched-rgn.c",
    "gcc/sel-sched-dump.c",
    "gcc/sel-sched-dump.h",
    "gcc/sel-sched-ir.c",
    "gcc/sel-sched-ir.h",
    "gcc/sel-sched.c",
    "gcc/sel-sched.h",
    "gcc/selftest-diagnostic.c",
    "gcc/selftest-diagnostic.h",
    "gcc/selftest-rtl.c",
    "gcc/selftest-rtl.h",
    "gcc/selftest-run-tests.c",
    "gcc/selftest.c",
    "gcc/selftest.h",
    "gcc/sese.c",
    "gcc/sese.h",
    "gcc/shortest-paths.h",
    "gcc/shrink-wrap.c",
    "gcc/shrink-wrap.h",
    "gcc/signop.h",
    "gcc/simplify-rtx.c",
    "gcc/sort.cc",
    "gcc/sparseset.c",
    "gcc/sparseset.h",
    "gcc/spellcheck-tree.c",
    "gcc/spellcheck-tree.h",
    "gcc/spellcheck.c",
    "gcc/spellcheck.h",
    "gcc/sreal.c",
    "gcc/sreal.h",
    "gcc/ssa-iterators.h",
    "gcc/ssa.h",
    "gcc/stab.def",
    "gcc/stack-ptr-mod.c",
    "gcc/statistics.c",
    "gcc/statistics.h",
    "gcc/stmt.c",
    "gcc/stmt.h",
    "gcc/stor-layout.c",
    "gcc/stor-layout.h",
    "gcc/store-motion.c",
    "gcc/streamer-hooks.c",
    "gcc/streamer-hooks.h",
    "gcc/stringpool.c",
    "gcc/stringpool.h",
    "gcc/substring-locations.c",
    "gcc/substring-locations.h",
    "gcc/symbol-summary.h",
    "gcc/symtab.c",
    "gcc/sync-builtins.def",
    "gcc/system.h",
    "gcc/target-def.h",
    "gcc/target-globals.c",
    "gcc/target-globals.h",
    "gcc/target-hooks-macros.h",
    "gcc/target-insns.def",
    "gcc/target.def",
    "gcc/target.h",
    "gcc/targhooks.c",
    "gcc/targhooks.h",
    "gcc/timevar.c",
    "gcc/timevar.def",
    "gcc/timevar.h",
    "gcc/toplev.c",
    "gcc/toplev.h",
    "gcc/tracer.c",
    "gcc/tracer.h",
    "gcc/trans-mem.c",
    "gcc/trans-mem.h",
    "gcc/tree-affine.c",
    "gcc/tree-affine.h",
    "gcc/tree-call-cdce.c",
    "gcc/tree-cfg.c",
    "gcc/tree-cfg.h",
    "gcc/tree-cfgcleanup.c",
    "gcc/tree-cfgcleanup.h",
    "gcc/tree-chrec.c",
    "gcc/tree-chrec.h",
    "gcc/tree-complex.c",
    "gcc/tree-core.h",
    "gcc/tree-data-ref.c",
    "gcc/tree-data-ref.h",
    "gcc/tree-dfa.c",
    "gcc/tree-dfa.h",
    "gcc/tree-diagnostic-path.cc",
    "gcc/tree-diagnostic.c",
    "gcc/tree-diagnostic.h",
    "gcc/tree-dump.c",
    "gcc/tree-dump.h",
    "gcc/tree-eh.c",
    "gcc/tree-eh.h",
    "gcc/tree-emutls.c",
    "gcc/tree-hash-traits.h",
    "gcc/tree-hasher.h",
    "gcc/tree-if-conv.c",
    "gcc/tree-if-conv.h",
    "gcc/tree-inline.c",
    "gcc/tree-inline.h",
    "gcc/tree-into-ssa.c",
    "gcc/tree-into-ssa.h",
    "gcc/tree-iterator.c",
    "gcc/tree-iterator.h",
    "gcc/tree-loop-distribution.c",
    "gcc/tree-nested.c",
    "gcc/tree-nested.h",
    "gcc/tree-nrv.c",
    "gcc/tree-object-size.c",
    "gcc/tree-object-size.h",
    "gcc/tree-outof-ssa.c",
    "gcc/tree-outof-ssa.h",
    "gcc/tree-parloops.c",
    "gcc/tree-parloops.h",
    "gcc/tree-pass.h",
    "gcc/tree-phinodes.c",
    "gcc/tree-phinodes.h",
    "gcc/tree-predcom.c",
    "gcc/tree-pretty-print.c",
    "gcc/tree-pretty-print.h",
    "gcc/tree-profile.c",
    "gcc/tree-scalar-evolution.c",
    "gcc/tree-scalar-evolution.h",
    "gcc/tree-sra.c",
    "gcc/tree-sra.h",
    "gcc/tree-ssa-address.c",
    "gcc/tree-ssa-address.h",
    "gcc/tree-ssa-alias.c",
    "gcc/tree-ssa-alias.h",
    "gcc/tree-ssa-ccp.c",
    "gcc/tree-ssa-ccp.h",
    "gcc/tree-ssa-coalesce.c",
    "gcc/tree-ssa-coalesce.h",
    "gcc/tree-ssa-copy.c",
    "gcc/tree-ssa-dce.c",
    "gcc/tree-ssa-dce.h",
    "gcc/tree-ssa-dom.c",
    "gcc/tree-ssa-dom.h",
    "gcc/tree-ssa-dse.c",
    "gcc/tree-ssa-dse.h",
    "gcc/tree-ssa-forwprop.c",
    "gcc/tree-ssa-ifcombine.c",
    "gcc/tree-ssa-live.c",
    "gcc/tree-ssa-live.h",
    "gcc/tree-ssa-loop-ch.c",
    "gcc/tree-ssa-loop-im.c",
    "gcc/tree-ssa-loop-ivcanon.c",
    "gcc/tree-ssa-loop-ivopts.c",
    "gcc/tree-ssa-loop-ivopts.h",
    "gcc/tree-ssa-loop-manip.c",
    "gcc/tree-ssa-loop-manip.h",
    "gcc/tree-ssa-loop-niter.c",
    "gcc/tree-ssa-loop-niter.h",
    "gcc/tree-ssa-loop-prefetch.c",
    "gcc/tree-ssa-loop-split.c",
    "gcc/tree-ssa-loop-unswitch.c",
    "gcc/tree-ssa-loop.c",
    "gcc/tree-ssa-loop.h",
    "gcc/tree-ssa-math-opts.c",
    "gcc/tree-ssa-operands.c",
    "gcc/tree-ssa-operands.h",
    "gcc/tree-ssa-phiopt.c",
    "gcc/tree-ssa-phiprop.c",
    "gcc/tree-ssa-pre.c",
    "gcc/tree-ssa-propagate.c",
    "gcc/tree-ssa-propagate.h",
    "gcc/tree-ssa-reassoc.c",
    "gcc/tree-ssa-sccvn.c",
    "gcc/tree-ssa-sccvn.h",
    "gcc/tree-ssa-scopedtables.c",
    "gcc/tree-ssa-scopedtables.h",
    "gcc/tree-ssa-sink.c",
    "gcc/tree-ssa-strlen.c",
    "gcc/tree-ssa-strlen.h",
    "gcc/tree-ssa-structalias.c",
    "gcc/tree-ssa-tail-merge.c",
    "gcc/tree-ssa-ter.c",
    "gcc/tree-ssa-ter.h",
    "gcc/tree-ssa-threadbackward.c",
    "gcc/tree-ssa-threadedge.c",
    "gcc/tree-ssa-threadedge.h",
    "gcc/tree-ssa-threadupdate.c",
    "gcc/tree-ssa-threadupdate.h",
    "gcc/tree-ssa-uncprop.c",
    "gcc/tree-ssa-uninit.c",
    "gcc/tree-ssa.c",
    "gcc/tree-ssa.h",
    "gcc/tree-ssanames.c",
    "gcc/tree-ssanames.h",
    "gcc/tree-stdarg.c",
    "gcc/tree-stdarg.h",
    "gcc/tree-streamer-in.c",
    "gcc/tree-streamer-out.c",
    "gcc/tree-streamer.c",
    "gcc/tree-streamer.h",
    "gcc/tree-switch-conversion.c",
    "gcc/tree-switch-conversion.h",
    "gcc/tree-tailcall.c",
    "gcc/tree-vect-data-refs.c",
    "gcc/tree-vect-generic.c",
    "gcc/tree-vect-loop-manip.c",
    "gcc/tree-vect-loop.c",
    "gcc/tree-vect-patterns.c",
    "gcc/tree-vect-slp.c",
    "gcc/tree-vect-stmts.c",
    "gcc/tree-vector-builder.c",
    "gcc/tree-vector-builder.h",
    "gcc/tree-vectorizer.c",
    "gcc/tree-vectorizer.h",
    "gcc/tree-vrp.c",
    "gcc/tree-vrp.h",
    "gcc/tree.c",
    "gcc/tree.def",
    "gcc/tree.h",
    "gcc/treestruct.def",
    "gcc/tristate.cc",
    "gcc/tristate.h",
    "gcc/tsan.c",
    "gcc/tsan.h",
    "gcc/tsystem.h",
    "gcc/typeclass.h",
    "gcc/typed-splay-tree.c",
    "gcc/typed-splay-tree.h",
    "gcc/ubsan.c",
    "gcc/ubsan.h",
    "gcc/unique-ptr-tests.cc",
    "gcc/valtrack.c",
    "gcc/valtrack.h",
    "gcc/value-prof.c",
    "gcc/value-prof.h",
    "gcc/value-range.cc",
    "gcc/value-range.h",
    "gcc/var-tracking.c",
    "gcc/varasm.c",
    "gcc/varasm.h",
    "gcc/varpool.c",
    "gcc/vec-perm-indices.c",
    "gcc/vec-perm-indices.h",
    "gcc/vec.c",
    "gcc/vec.h",
    "gcc/vector-builder.h",
    "gcc/version.c",
    "gcc/version.h",
    "gcc/vmsdbg.h",
    "gcc/vmsdbgout.c",
    "gcc/vr-values.c",
    "gcc/vr-values.h",
    "gcc/vtable-verify.c",
    "gcc/vtable-verify.h",
    "gcc/web.c",
    "gcc/wide-int-bitmask.h",
    "gcc/wide-int-print.cc",
    "gcc/wide-int-print.h",
    "gcc/wide-int.cc",
    "gcc/wide-int.h",
    "gcc/xcoff.h",
    "gcc/xcoffout.c",
    "gcc/xcoffout.h",
    "gcc/c/Make-lang.in",
    "gcc/c/c-aux-info.c",
    "gcc/c/c-convert.c",
    "gcc/c/c-decl.c",
    "gcc/c/c-errors.c",
    "gcc/c/c-fold.c",
    "gcc/c/c-lang.c",
    "gcc/c/c-lang.h",
    "gcc/c/c-objc-common.c",
    "gcc/c/c-objc-common.h",
    "gcc/c/c-parser.c",
    "gcc/c/c-parser.h",
    "gcc/c/c-tree.h",
    "gcc/c/c-typeck.c",
    "gcc/c/config-lang.in",
    "gcc/c/gccspec.c",
    "gcc/c/gimple-parser.c",
    "gcc/c/gimple-parser.h",
    "gcc/c-family/c-ada-spec.c",
    "gcc/c-family/c-ada-spec.h",
    "gcc/c-family/c-attribs.c",
    "gcc/c-family/c-common.c",
    "gcc/c-family/c-common.def",
    "gcc/c-family/c-common.h",
    "gcc/c-family/c-cppbuiltin.c",
    "gcc/c-family/c-dump.c",
    "gcc/c-family/c-format.c",
    "gcc/c-family/c-format.h",
    "gcc/c-family/c-gimplify.c",
    "gcc/c-family/c-indentation.c",
    "gcc/c-family/c-indentation.h",
    "gcc/c-family/c-lex.c",
    "gcc/c-family/c-objc.h",
    "gcc/c-family/c-omp.c",
    "gcc/c-family/c-opts.c",
    "gcc/c-family/c-pch.c",
    "gcc/c-family/c-ppoutput.c",
    "gcc/c-family/c-pragma.c",
    "gcc/c-family/c-pragma.h",
    "gcc/c-family/c-pretty-print.c",
    "gcc/c-family/c-pretty-print.h",
    "gcc/c-family/c-semantics.c",
    "gcc/c-family/c-spellcheck.cc",
    "gcc/c-family/c-spellcheck.h",
    "gcc/c-family/c-target-def.h",
    "gcc/c-family/c-target.def",
    "gcc/c-family/c-target.h",
    "gcc/c-family/c-ubsan.c",
    "gcc/c-family/c-ubsan.h",
    "gcc/c-family/c-warn.c",
    "gcc/c-family/c.opt",
    "gcc/c-family/cppspec.c",
    "gcc/c-family/known-headers.cc",
    "gcc/c-family/known-headers.h",
    "gcc/c-family/name-hint.h",
    "gcc/c-family/stub-objc.c",
    "gcc/cp/Make-lang.in",
    "gcc/cp/NEWS",
    "gcc/cp/call.c",
    "gcc/cp/cfns.gperf",
    "gcc/cp/class.c",
    "gcc/cp/config-lang.in",
    "gcc/cp/constexpr.c",
    "gcc/cp/constraint.cc",
    "gcc/cp/coroutines.cc",
    "gcc/cp/cp-gimplify.c",
    "gcc/cp/cp-lang.c",
    "gcc/cp/cp-name-hint.h",
    "gcc/cp/cp-objcp-common.c",
    "gcc/cp/cp-objcp-common.h",
    "gcc/cp/cp-tree.def",
    "gcc/cp/cp-tree.h",
    "gcc/cp/cp-ubsan.c",
    "gcc/cp/cvt.c",
    "gcc/cp/cxx-pretty-print.c",
    "gcc/cp/cxx-pretty-print.h",
    "gcc/cp/decl.c",
    "gcc/cp/decl.h",
    "gcc/cp/decl2.c",
    "gcc/cp/dump.c",
    "gcc/cp/error.c",
    "gcc/cp/except.c",
    "gcc/cp/expr.c",
    "gcc/cp/friend.c",
    "gcc/cp/g++spec.c",
    "gcc/cp/init.c",
    "gcc/cp/lambda.c",
    "gcc/cp/lang-specs.h",
    "gcc/cp/lex.c",
    "gcc/cp/logic.cc",
    "gcc/cp/mangle.c",
    "gcc/cp/method.c",
    "gcc/cp/name-lookup.c",
    "gcc/cp/name-lookup.h",
    "gcc/cp/operators.def",
    "gcc/cp/optimize.c",
    "gcc/cp/parser.c",
    "gcc/cp/parser.h",
    "gcc/cp/pt.c",
    "gcc/cp/ptree.c",
    "gcc/cp/rtti.c",
    "gcc/cp/search.c",
    "gcc/cp/semantics.c",
    "gcc/cp/tree.c",
    "gcc/cp/type-utils.h",
    "gcc/cp/typeck.c",
    "gcc/cp/typeck2.c",
    "gcc/cp/vtable-class-hierarchy.c",
    "gcc/common/common-target-def.h",
    "gcc/common/common-target.def",
    "gcc/common/common-target.h",
    "gcc/common/common-targhooks.c",
    "gcc/common/common-targhooks.h",
    "gcc/analyzer/analysis-plan.cc",
    "gcc/analyzer/analysis-plan.h",
    "gcc/analyzer/analyzer-logging.cc",
    "gcc/analyzer/analyzer-logging.h",
    "gcc/analyzer/analyzer-pass.cc",
    "gcc/analyzer/analyzer-selftests.cc",
    "gcc/analyzer/analyzer-selftests.h",
    "gcc/analyzer/analyzer.cc",
    "gcc/analyzer/analyzer.h",
    "gcc/analyzer/analyzer.opt",
    "gcc/analyzer/bar-chart.cc",
    "gcc/analyzer/bar-chart.h",
    "gcc/analyzer/call-string.cc",
    "gcc/analyzer/call-string.h",
    "gcc/analyzer/checker-path.cc",
    "gcc/analyzer/checker-path.h",
    "gcc/analyzer/constraint-manager.cc",
    "gcc/analyzer/constraint-manager.h",
    "gcc/analyzer/diagnostic-manager.cc",
    "gcc/analyzer/diagnostic-manager.h",
    "gcc/analyzer/engine.cc",
    "gcc/analyzer/engine.h",
    "gcc/analyzer/exploded-graph.h",
    "gcc/analyzer/function-set.cc",
    "gcc/analyzer/function-set.h",
    "gcc/analyzer/pending-diagnostic.cc",
    "gcc/analyzer/pending-diagnostic.h",
    "gcc/analyzer/program-point.cc",
    "gcc/analyzer/program-point.h",
    "gcc/analyzer/program-state.cc",
    "gcc/analyzer/program-state.h",
    "gcc/analyzer/reachability.h",
    "gcc/analyzer/region-model.cc",
    "gcc/analyzer/region-model.h",
    "gcc/analyzer/sm-file.cc",
    "gcc/analyzer/sm-malloc.cc",
    "gcc/analyzer/sm-malloc.dot",
    "gcc/analyzer/sm-pattern-test.cc",
    "gcc/analyzer/sm-sensitive.cc",
    "gcc/analyzer/sm-signal.cc",
    "gcc/analyzer/sm-taint.cc",
    "gcc/analyzer/sm.cc",
    "gcc/analyzer/sm.h",
    "gcc/analyzer/state-purge.cc",
    "gcc/analyzer/state-purge.h",
    "gcc/analyzer/supergraph.cc",
    "gcc/analyzer/supergraph.h",
    "gcc/config/README",
    "gcc/config/darwin-c.c",
    "gcc/config/darwin-driver.c",
    "gcc/config/darwin-f.c",
    "gcc/config/darwin-ppc-ldouble-patch.def",
    "gcc/config/darwin-protos.h",
    "gcc/config/darwin-sections.def",
    "gcc/config/darwin.c",
    "gcc/config/darwin.h",
    "gcc/config/darwin.opt",
    "gcc/config/dbx.h",
    "gcc/config/dbxcoff.h",
    "gcc/config/dbxelf.h",
    "gcc/config/default-c.c",
    "gcc/config/default-d.c",
    "gcc/config/dragonfly-stdint.h",
    "gcc/config/dragonfly.h",
    "gcc/config/dragonfly.opt",
    "gcc/config/elfos.h",
    "gcc/config/flat.h",
    "gcc/config/freebsd-nthr.h",
    "gcc/config/freebsd-spec.h",
    "gcc/config/freebsd-stdint.h",
    "gcc/config/freebsd.h",
    "gcc/config/freebsd.opt",
    "gcc/config/fuchsia.h",
    "gcc/config/fused-madd.opt",
    "gcc/config/g.opt",
    "gcc/config/glibc-c.c",
    "gcc/config/glibc-d.c",
    "gcc/config/glibc-stdint.h",
    "gcc/config/gnu-user.h",
    "gcc/config/gnu-user.opt",
    "gcc/config/gnu.h",
    "gcc/config/host-darwin.c",
    "gcc/config/host-darwin.h",
    "gcc/config/host-hpux.c",
    "gcc/config/host-linux.c",
    "gcc/config/host-netbsd.c",
    "gcc/config/host-openbsd.c",
    "gcc/config/host-solaris.c",
    "gcc/config/hpux-stdint.h",
    "gcc/config/hpux11.opt",
    "gcc/config/initfini-array.h",
    "gcc/config/kfreebsd-gnu.h",
    "gcc/config/kopensolaris-gnu.h",
    "gcc/config/linux-android.h",
    "gcc/config/linux-android.opt",
    "gcc/config/linux-protos.h",
    "gcc/config/linux.c",
    "gcc/config/linux.h",
    "gcc/config/linux.opt",
    "gcc/config/lynx.h",
    "gcc/config/lynx.opt",
    "gcc/config/netbsd-d.c",
    "gcc/config/netbsd-elf.h",
    "gcc/config/netbsd-elf.opt",
    "gcc/config/netbsd-protos.h",
    "gcc/config/netbsd-stdint.h",
    "gcc/config/netbsd.c",
    "gcc/config/netbsd.h",
    "gcc/config/netbsd.opt",
    "gcc/config/newlib-stdint.h",
    "gcc/config/openbsd-libpthread.h",
    "gcc/config/openbsd-stdint.h",
    "gcc/config/openbsd.h",
    "gcc/config/openbsd.opt",
    "gcc/config/phoenix.h",
    "gcc/config/print-sysroot-suffix.sh",
    "gcc/config/rpath.opt",
    "gcc/config/rtems.h",
    "gcc/config/rtems.opt",
    "gcc/config/sol2-c.c",
    "gcc/config/sol2-clearcap.map",
    "gcc/config/sol2-clearcapv2.map",
    "gcc/config/sol2-cxx.c",
    "gcc/config/sol2-d.c",
    "gcc/config/sol2-protos.h",
    "gcc/config/sol2-stubs.c",
    "gcc/config/sol2.c",
    "gcc/config/sol2.h",
    "gcc/config/sol2.opt",
    "gcc/config/t-darwin",
    "gcc/config/t-glibc",
    "gcc/config/t-libunwind",
    "gcc/config/t-linux",
    "gcc/config/t-lynx",
    "gcc/config/t-musl",
    "gcc/config/t-netbsd",
    "gcc/config/t-openbsd",
    "gcc/config/t-pnt16-warn",
    "gcc/config/t-rtems",
    "gcc/config/t-slibgcc",
    "gcc/config/t-sol2",
    "gcc/config/t-sysroot-suffix",
    "gcc/config/t-uclibc",
    "gcc/config/t-vxworks",
    "gcc/config/t-winnt",
    "gcc/config/tm-dwarf2.h",
    "gcc/config/usegas.h",
    "gcc/config/usegld.h",
    "gcc/config/vx-common.h",
    "gcc/config/vxworks-c.c",
    "gcc/config/vxworks-dummy.h",
    "gcc/config/vxworks-stdint.h",
    "gcc/config/vxworks.c",
    "gcc/config/vxworks.h",
    "gcc/config/vxworks.opt",
    "gcc/config/vxworksae.h",
    "gcc/config/winnt-c.c",
    "gcc/config/x-cflags-O1",
    "gcc/config/x-darwin",
    "gcc/config/x-hpux",
    "gcc/config/x-linux",
    "gcc/config/x-netbsd",
    "gcc/config/x-openbsd",
    "gcc/config/x-solaris",
    "gcc/config/i386/adxintrin.h",
    "gcc/config/i386/ammintrin.h",
    "gcc/config/i386/athlon.md",
    "gcc/config/i386/atom.md",
    "gcc/config/i386/att.h",
    "gcc/config/i386/avx2intrin.h",
    "gcc/config/i386/avx5124fmapsintrin.h",
    "gcc/config/i386/avx5124vnniwintrin.h",
    "gcc/config/i386/avx512bf16intrin.h",
    "gcc/config/i386/avx512bf16vlintrin.h",
    "gcc/config/i386/avx512bitalgintrin.h",
    "gcc/config/i386/avx512bwintrin.h",
    "gcc/config/i386/avx512cdintrin.h",
    "gcc/config/i386/avx512dqintrin.h",
    "gcc/config/i386/avx512erintrin.h",
    "gcc/config/i386/avx512fintrin.h",
    "gcc/config/i386/avx512ifmaintrin.h",
    "gcc/config/i386/avx512ifmavlintrin.h",
    "gcc/config/i386/avx512pfintrin.h",
    "gcc/config/i386/avx512vbmi2intrin.h",
    "gcc/config/i386/avx512vbmi2vlintrin.h",
    "gcc/config/i386/avx512vbmiintrin.h",
    "gcc/config/i386/avx512vbmivlintrin.h",
    "gcc/config/i386/avx512vlbwintrin.h",
    "gcc/config/i386/avx512vldqintrin.h",
    "gcc/config/i386/avx512vlintrin.h",
    "gcc/config/i386/avx512vnniintrin.h",
    "gcc/config/i386/avx512vnnivlintrin.h",
    "gcc/config/i386/avx512vp2intersectintrin.h",
    "gcc/config/i386/avx512vp2intersectvlintrin.h",
    "gcc/config/i386/avx512vpopcntdqintrin.h",
    "gcc/config/i386/avx512vpopcntdqvlintrin.h",
    "gcc/config/i386/avxintrin.h",
    "gcc/config/i386/avxmath.h",
    "gcc/config/i386/bdver1.md",
    "gcc/config/i386/bdver3.md",
    "gcc/config/i386/biarch64.h",
    "gcc/config/i386/biarchx32.h",
    "gcc/config/i386/bmi2intrin.h",
    "gcc/config/i386/bmiintrin.h",
    "gcc/config/i386/bmmintrin.h",
    "gcc/config/i386/bsd.h",
    "gcc/config/i386/btver2.md",
    "gcc/config/i386/cet.c",
    "gcc/config/i386/cet.h",
    "gcc/config/i386/cetintrin.h",
    "gcc/config/i386/cldemoteintrin.h",
    "gcc/config/i386/clflushoptintrin.h",
    "gcc/config/i386/clwbintrin.h",
    "gcc/config/i386/clzerointrin.h",
    "gcc/config/i386/constraints.md",
    "gcc/config/i386/core2.md",
    "gcc/config/i386/cpuid.h",
    "gcc/config/i386/cross-stdarg.h",
    "gcc/config/i386/crtdll.h",
    "gcc/config/i386/cygming.h",
    "gcc/config/i386/cygming.opt",
    "gcc/config/i386/cygwin-stdint.h",
    "gcc/config/i386/cygwin-w64.h",
    "gcc/config/i386/cygwin.h",
    "gcc/config/i386/cygwin.opt",
    "gcc/config/i386/darwin.h",
    "gcc/config/i386/darwin32-biarch.h",
    "gcc/config/i386/darwin64-biarch.h",
    "gcc/config/i386/djgpp-stdint.h",
    "gcc/config/i386/djgpp.c",
    "gcc/config/i386/djgpp.h",
    "gcc/config/i386/djgpp.opt",
    "gcc/config/i386/dragonfly.h",
    "gcc/config/i386/driver-i386.c",
    "gcc/config/i386/driver-mingw32.c",
    "gcc/config/i386/emmintrin.h",
    "gcc/config/i386/enqcmdintrin.h",
    "gcc/config/i386/f16cintrin.h",
    "gcc/config/i386/fma4intrin.h",
    "gcc/config/i386/fmaintrin.h",
    "gcc/config/i386/freebsd.h",
    "gcc/config/i386/freebsd64.h",
    "gcc/config/i386/fxsrintrin.h",
    "gcc/config/i386/gas.h",
    "gcc/config/i386/gcc-auto-profile",
    "gcc/config/i386/geode.md",
    "gcc/config/i386/gfniintrin.h",
    "gcc/config/i386/glm.md",
    "gcc/config/i386/gmm_malloc.h",
    "gcc/config/i386/gnu-user-common.h",
    "gcc/config/i386/gnu-user.h",
    "gcc/config/i386/gnu-user64.h",
    "gcc/config/i386/gnu.h",
    "gcc/config/i386/haswell.md",
    "gcc/config/i386/host-cygwin.c",
    "gcc/config/i386/host-i386-darwin.c",
    "gcc/config/i386/host-mingw32.c",
    "gcc/config/i386/i386-builtin-types.awk",
    "gcc/config/i386/i386-builtin-types.def",
    "gcc/config/i386/i386-builtin.def",
    "gcc/config/i386/i386-builtins.c",
    "gcc/config/i386/i386-builtins.h",
    "gcc/config/i386/i386-c.c",
    "gcc/config/i386/i386-d.c",
    "gcc/config/i386/i386-expand.c",
    "gcc/config/i386/i386-expand.h",
    "gcc/config/i386/i386-features.c",
    "gcc/config/i386/i386-features.h",
    "gcc/config/i386/i386-modes.def",
    "gcc/config/i386/i386-options.c",
    "gcc/config/i386/i386-options.h",
    "gcc/config/i386/i386-opts.h",
    "gcc/config/i386/i386-passes.def",
    "gcc/config/i386/i386-protos.h",
    "gcc/config/i386/i386.c",
    "gcc/config/i386/i386.h",
    "gcc/config/i386/i386.md",
    "gcc/config/i386/i386.opt",
    "gcc/config/i386/i386elf.h",
    "gcc/config/i386/ia32intrin.h",
    "gcc/config/i386/iamcu.h",
    "gcc/config/i386/immintrin.h",
    "gcc/config/i386/intelmic-mkoffload.c",
    "gcc/config/i386/intelmic-offload.h",
    "gcc/config/i386/k6.md",
    "gcc/config/i386/kfreebsd-gnu.h",
    "gcc/config/i386/kfreebsd-gnu64.h",
    "gcc/config/i386/kopensolaris-gnu.h",
    "gcc/config/i386/linux-common.h",
    "gcc/config/i386/linux.h",
    "gcc/config/i386/linux64.h",
    "gcc/config/i386/lwpintrin.h",
    "gcc/config/i386/lynx.h",
    "gcc/config/i386/lzcntintrin.h",
    "gcc/config/i386/mingw-pthread.h",
    "gcc/config/i386/mingw-stdint.h",
    "gcc/config/i386/mingw-w64.h",
    "gcc/config/i386/mingw-w64.opt",
    "gcc/config/i386/mingw.opt",
    "gcc/config/i386/mingw32.h",
    "gcc/config/i386/mm3dnow.h",
    "gcc/config/i386/mmintrin.h",
    "gcc/config/i386/mmx.md",
    "gcc/config/i386/movdirintrin.h",
    "gcc/config/i386/msformat-c.c",
    "gcc/config/i386/mwaitxintrin.h",
    "gcc/config/i386/netbsd-elf.h",
    "gcc/config/i386/netbsd64.h",
    "gcc/config/i386/nmmintrin.h",
    "gcc/config/i386/nto.h",
    "gcc/config/i386/nto.opt",
    "gcc/config/i386/openbsdelf.h",
    "gcc/config/i386/pconfigintrin.h",
    "gcc/config/i386/pentium.md",
    "gcc/config/i386/pkuintrin.h",
    "gcc/config/i386/pmm_malloc.h",
    "gcc/config/i386/pmmintrin.h",
    "gcc/config/i386/popcntintrin.h",
    "gcc/config/i386/ppro.md",
    "gcc/config/i386/predicates.md",
    "gcc/config/i386/prfchwintrin.h",
    "gcc/config/i386/rdos.h",
    "gcc/config/i386/rdos64.h",
    "gcc/config/i386/rdseedintrin.h",
    "gcc/config/i386/rtemself.h",
    "gcc/config/i386/rtmintrin.h",
    "gcc/config/i386/sgxintrin.h",
    "gcc/config/i386/shaintrin.h",
    "gcc/config/i386/slm.md",
    "gcc/config/i386/smmintrin.h",
    "gcc/config/i386/sol2.h",
    "gcc/config/i386/sse.md",
    "gcc/config/i386/ssemath.h",
    "gcc/config/i386/stringop.def",
    "gcc/config/i386/subst.md",
    "gcc/config/i386/sync.md",
    "gcc/config/i386/sysv4.h",
    "gcc/config/i386/t-cet",
    "gcc/config/i386/t-cygming",
    "gcc/config/i386/t-cygwin-w64",
    "gcc/config/i386/t-darwin32-biarch",
    "gcc/config/i386/t-darwin64-biarch",
    "gcc/config/i386/t-djgpp",
    "gcc/config/i386/t-freebsd64",
    "gcc/config/i386/t-gmm_malloc",
    "gcc/config/i386/t-gnu",
    "gcc/config/i386/t-i386",
    "gcc/config/i386/t-intelmic",
    "gcc/config/i386/t-kfreebsd",
    "gcc/config/i386/t-linux",
    "gcc/config/i386/t-linux64",
    "gcc/config/i386/t-mingw-w32",
    "gcc/config/i386/t-mingw-w64",
    "gcc/config/i386/t-omp-device",
    "gcc/config/i386/t-pmm_malloc",
    "gcc/config/i386/t-rtems",
    "gcc/config/i386/t-sol2",
    "gcc/config/i386/t-vxworks",
    "gcc/config/i386/t-vxworksae",
    "gcc/config/i386/tbmintrin.h",
    "gcc/config/i386/tmmintrin.h",
    "gcc/config/i386/unix.h",
    "gcc/config/i386/vaesintrin.h",
    "gcc/config/i386/vpclmulqdqintrin.h",
    "gcc/config/i386/vxworks.h",
    "gcc/config/i386/vxworksae.h",
    "gcc/config/i386/waitpkgintrin.h",
    "gcc/config/i386/wbnoinvdintrin.h",
    "gcc/config/i386/winnt-cxx.c",
    "gcc/config/i386/winnt-stubs.c",
    "gcc/config/i386/winnt.c",
    "gcc/config/i386/wmmintrin.h",
    "gcc/config/i386/x-cygwin",
    "gcc/config/i386/x-darwin",
    "gcc/config/i386/x-i386",
    "gcc/config/i386/x-mingw32",
    "gcc/config/i386/x86-64.h",
    "gcc/config/i386/x86-tune-costs.h",
    "gcc/config/i386/x86-tune-sched-atom.c",
    "gcc/config/i386/x86-tune-sched-bd.c",
    "gcc/config/i386/x86-tune-sched-core.c",
    "gcc/config/i386/x86-tune-sched.c",
    "gcc/config/i386/x86-tune.def",
    "gcc/config/i386/x86intrin.h",
    "gcc/config/i386/xm-cygwin.h",
    "gcc/config/i386/xm-djgpp.h",
    "gcc/config/i386/xm-mingw32.h",
    "gcc/config/i386/xmmintrin.h",
    "gcc/config/i386/xopintrin.h",
    "gcc/config/i386/xsavecintrin.h",
    "gcc/config/i386/xsaveintrin.h",
    "gcc/config/i386/xsaveoptintrin.h",
    "gcc/config/i386/xsavesintrin.h",
    "gcc/config/i386/xtestintrin.h",
    "gcc/config/i386/znver1.md",
    "gcc/ginclude/float.h",
    "gcc/ginclude/iso646.h",
    "gcc/ginclude/stdalign.h",
    "gcc/ginclude/stdarg.h",
    "gcc/ginclude/stdatomic.h",
    "gcc/ginclude/stdbool.h",
    "gcc/ginclude/stddef.h",
    "gcc/ginclude/stdfix.h",
    "gcc/ginclude/stdint-gcc.h",
    "gcc/ginclude/stdint-wrap.h",
    "gcc/ginclude/stdnoreturn.h",
    "gcc/ginclude/tgmath.h",
    "gcc/ginclude/unwind-arm-common.h",
    "gcc/ginclude/varargs.h",
    "gcc/common/config/i386/i386-common.c",
    "gcc/common/config/i386/i386-cpuinfo.h",
    "gcc/lto/lang.opt",
    "gcc/d/d-target.def",
]

# Objects in libbackend.a, in upstream archive order (gcc/Makefile.in OBJS).
BACKEND_OBJECTS = [
    "gimple-match",
    "generic-match",
    "insn-attrtab",
    "insn-automata",
    "insn-dfatab",
    "insn-emit",
    "insn-extract",
    "insn-latencytab",
    "insn-modes",
    "insn-opinit",
    "insn-output",
    "insn-peep",
    "insn-preds",
    "insn-recog",
    "insn-enums",
    "ggc-page",
    "alias",
    "alloc-pool",
    "auto-inc-dec",
    "auto-profile",
    "bb-reorder",
    "bitmap",
    "builtins",
    "caller-save",
    "calls",
    "ccmp",
    "cfg",
    "cfganal",
    "cfgbuild",
    "cfgcleanup",
    "cfgexpand",
    "cfghooks",
    "cfgloop",
    "cfgloopanal",
    "cfgloopmanip",
    "cfgrtl",
    "symtab",
    "cgraph",
    "cgraphbuild",
    "cgraphunit",
    "cgraphclones",
    "combine",
    "combine-stack-adj",
    "compare-elim",
    "context",
    "convert",
    "coroutine-passes",
    "coverage",
    "cppbuiltin",
    "cppdefault",
    "cprop",
    "cse",
    "cselib",
    "data-streamer",
    "data-streamer-in",
    "data-streamer-out",
    "dbxout",
    "dbgcnt",
    "dce",
    "ddg",
    "debug",
    "df-core",
    "df-problems",
    "df-scan",
    "dfp",
    "digraph",
    "dojump",
    "dominance",
    "domwalk",
    "double-int",
    "dse",
    "dumpfile",
    "dwarf2asm",
    "dwarf2cfi",
    "dwarf2out",
    "early-remat",
    "emit-rtl",
    "et-forest",
    "except",
    "explow",
    "expmed",
    "expr",
    "fibonacci_heap",
    "file-prefix-map",
    "final",
    "fixed-value",
    "fold-const",
    "fold-const-call",
    "function",
    "function-abi",
    "function-tests",
    "fwprop",
    "gcc-rich-location",
    "gcse",
    "gcse-common",
    "ggc-common",
    "ggc-tests",
    "gimple",
    "gimple-builder",
    "gimple-expr",
    "gimple-iterator",
    "gimple-fold",
    "gimple-laddress",
    "gimple-loop-interchange",
    "gimple-loop-jam",
    "gimple-loop-versioning",
    "gimple-low",
    "gimple-pretty-print",
    "gimple-ssa-backprop",
    "gimple-ssa-evrp",
    "gimple-ssa-evrp-analyze",
    "gimple-ssa-isolate-paths",
    "gimple-ssa-nonnull-compare",
    "gimple-ssa-split-paths",
    "gimple-ssa-store-merging",
    "gimple-ssa-strength-reduction",
    "gimple-ssa-sprintf",
    "gimple-ssa-warn-alloca",
    "gimple-ssa-warn-restrict",
    "gimple-streamer-in",
    "gimple-streamer-out",
    "gimple-walk",
    "gimplify",
    "gimplify-me",
    "godump",
    "graph",
    "graphds",
    "graphviz",
    "graphite",
    "graphite-isl-ast-to-gimple",
    "graphite-dependences",
    "graphite-optimize-isl",
    "graphite-poly",
    "graphite-scop-detection",
    "graphite-sese-to-poly",
    "gtype-desc",
    "haifa-sched",
    "hash-map-tests",
    "hash-set-tests",
    "hsa-common",
    "hsa-gen",
    "hsa-regalloc",
    "hsa-brig",
    "hsa-dump",
    "hw-doloop",
    "hwint",
    "ifcvt",
    "ree",
    "inchash",
    "incpath",
    "init-regs",
    "internal-fn",
    "ipa-cp",
    "ipa-sra",
    "ipa-devirt",
    "ipa-fnsummary",
    "ipa-polymorphic-call",
    "ipa-split",
    "ipa-inline",
    "ipa-comdats",
    "ipa-visibility",
    "ipa-inline-analysis",
    "ipa-inline-transform",
    "ipa-predicate",
    "ipa-profile",
    "ipa-prop",
    "ipa-param-manipulation",
    "ipa-pure-const",
    "ipa-icf",
    "ipa-icf-gimple",
    "ipa-reference",
    "ipa-hsa",
    "ipa-ref",
    "ipa-utils",
    "ipa",
    "ira",
    "ira-build",
    "ira-costs",
    "ira-conflicts",
    "ira-color",
    "ira-emit",
    "ira-lives",
    "jump",
    "langhooks",
    "lcm",
    "lists",
    "loop-doloop",
    "loop-init",
    "loop-invariant",
    "loop-iv",
    "loop-unroll",
    "lower-subreg",
    "lra",
    "lra-assigns",
    "lra-coalesce",
    "lra-constraints",
    "lra-eliminations",
    "lra-lives",
    "lra-remat",
    "lra-spills",
    "lto-cgraph",
    "lto-streamer",
    "lto-streamer-in",
    "lto-streamer-out",
    "lto-section-in",
    "lto-section-out",
    "lto-opts",
    "lto-compress",
    "mcf",
    "mode-switching",
    "modulo-sched",
    "multiple_target",
    "omp-offload",
    "omp-expand",
    "omp-general",
    "omp-grid",
    "omp-low",
    "omp-simd-clone",
    "opt-problem",
    "optabs",
    "optabs-libfuncs",
    "optabs-query",
    "optabs-tree",
    "optinfo",
    "optinfo-emit-json",
    "options-save",
    "opts-global",
    "ordered-hash-map-tests",
    "passes",
    "plugin",
    "postreload-gcse",
    "postreload",
    "predict",
    "print-rtl",
    "print-rtl-function",
    "print-tree",
    "profile",
    "profile-count",
    "range",
    "range-op",
    "read-md",
    "read-rtl",
    "read-rtl-function",
    "real",
    "realmpfr",
    "recog",
    "reg-stack",
    "regcprop",
    "reginfo",
    "regrename",
    "regstat",
    "reload",
    "reload1",
    "reorg",
    "resource",
    "rtl-error",
    "rtl-tests",
    "rtl",
    "rtlhash",
    "rtlanal",
    "rtlhooks",
    "rtx-vector-builder",
    "run-rtl-passes",
    "sched-deps",
    "sched-ebb",
    "sched-rgn",
    "sel-sched-ir",
    "sel-sched-dump",
    "sel-sched",
    "selftest-rtl",
    "selftest-run-tests",
    "sese",
    "shrink-wrap",
    "simplify-rtx",
    "sparseset",
    "spellcheck",
    "spellcheck-tree",
    "sreal",
    "stack-ptr-mod",
    "statistics",
    "stmt",
    "stor-layout",
    "store-motion",
    "streamer-hooks",
    "stringpool",
    "substring-locations",
    "target-globals",
    "targhooks",
    "timevar",
    "toplev",
    "tracer",
    "trans-mem",
    "tree-affine",
    "asan",
    "tsan",
    "ubsan",
    "sanopt",
    "sancov",
    "tree-call-cdce",
    "tree-cfg",
    "tree-cfgcleanup",
    "tree-chrec",
    "tree-complex",
    "tree-data-ref",
    "tree-dfa",
    "tree-diagnostic",
    "tree-diagnostic-path",
    "tree-dump",
    "tree-eh",
    "tree-emutls",
    "tree-if-conv",
    "tree-inline",
    "tree-into-ssa",
    "tree-iterator",
    "tree-loop-distribution",
    "tree-nested",
    "tree-nrv",
    "tree-object-size",
    "tree-outof-ssa",
    "tree-parloops",
    "tree-phinodes",
    "tree-predcom",
    "tree-pretty-print",
    "tree-profile",
    "tree-scalar-evolution",
    "tree-sra",
    "tree-switch-conversion",
    "tree-ssa-address",
    "tree-ssa-alias",
    "tree-ssa-ccp",
    "tree-ssa-coalesce",
    "tree-ssa-copy",
    "tree-ssa-dce",
    "tree-ssa-dom",
    "tree-ssa-dse",
    "tree-ssa-forwprop",
    "tree-ssa-ifcombine",
    "tree-ssa-live",
    "tree-ssa-loop-ch",
    "tree-ssa-loop-im",
    "tree-ssa-loop-ivcanon",
    "tree-ssa-loop-ivopts",
    "tree-ssa-loop-manip",
    "tree-ssa-loop-niter",
    "tree-ssa-loop-prefetch",
    "tree-ssa-loop-split",
    "tree-ssa-loop-unswitch",
    "tree-ssa-loop",
    "tree-ssa-math-opts",
    "tree-ssa-operands",
    "tree-ssa-phiopt",
    "tree-ssa-phiprop",
    "tree-ssa-pre",
    "tree-ssa-propagate",
    "tree-ssa-reassoc",
    "tree-ssa-sccvn",
    "tree-ssa-scopedtables",
    "tree-ssa-sink",
    "tree-ssa-strlen",
    "tree-ssa-structalias",
    "tree-ssa-tail-merge",
    "tree-ssa-ter",
    "tree-ssa-threadbackward",
    "tree-ssa-threadedge",
    "tree-ssa-threadupdate",
    "tree-ssa-uncprop",
    "tree-ssa-uninit",
    "tree-ssa",
    "tree-ssanames",
    "tree-stdarg",
    "tree-streamer",
    "tree-streamer-in",
    "tree-streamer-out",
    "tree-tailcall",
    "tree-vect-generic",
    "tree-vect-patterns",
    "tree-vect-data-refs",
    "tree-vect-stmts",
    "tree-vect-loop",
    "tree-vect-loop-manip",
    "tree-vect-slp",
    "tree-vectorizer",
    "tree-vector-builder",
    "tree-vrp",
    "tree",
    "tristate",
    "typed-splay-tree",
    "unique-ptr-tests",
    "valtrack",
    "value-range",
    "value-prof",
    "var-tracking",
    "varasm",
    "varpool",
    "vec-perm-indices",
    "vmsdbgout",
    "vr-values",
    "vtable-verify",
    "web",
    "wide-int",
    "wide-int-print",
    "xcoffout",
    "config/i386/i386",
    "analyzer/analysis-plan",
    "analyzer/analyzer",
    "analyzer/analyzer-logging",
    "analyzer/analyzer-pass",
    "analyzer/analyzer-selftests",
    "analyzer/bar-chart",
    "analyzer/call-string",
    "analyzer/checker-path",
    "analyzer/constraint-manager",
    "analyzer/diagnostic-manager",
    "analyzer/engine",
    "analyzer/function-set",
    "analyzer/pending-diagnostic",
    "analyzer/program-point",
    "analyzer/program-state",
    "analyzer/region-model",
    "analyzer/sm",
    "analyzer/sm-file",
    "analyzer/sm-malloc",
    "analyzer/sm-pattern-test",
    "analyzer/sm-sensitive",
    "analyzer/sm-signal",
    "analyzer/sm-taint",
    "analyzer/state-purge",
    "analyzer/supergraph",
    "config/i386/x86-tune-sched",
    "config/i386/x86-tune-sched-bd",
    "config/i386/x86-tune-sched-atom",
    "config/i386/x86-tune-sched-core",
    "config/i386/i386-options",
    "config/i386/i386-builtins",
    "config/i386/i386-expand",
    "config/i386/i386-features",
    "config/linux",
    "config/i386/cet",
    "config/host-linux",
]

# Objects in libcommon.a (OBJS-libcommon).
COMMON_OBJECTS = [
    "diagnostic",
    "diagnostic-color",
    "diagnostic-show-locus",
    "diagnostic-format-json",
    "json",
    "edit-context",
    "pretty-print",
    "intl",
    "sbitmap",
    "vec",
    "input",
    "version",
    "hash-table",
    "ggc-none",
    "memory-block",
    "selftest",
    "selftest-diagnostic",
    "sort",
]

# Objects in libcommon-target.a (OBJS-libcommon-target).
COMMON_TARGET_OBJECTS = [
    "common/config/i386/i386-common",
    "prefix",
    "opts",
    "opts-common",
    "options",
    "vec",
    "hooks",
    "common/common-targhooks",
    "hash-table",
    "file-find",
    "spellcheck",
    "selftest",
    "opt-suggestions",
]

# cc1's front-end objects (c/Make-lang.in C_OBJS).
C_OBJECTS = [
    "c/c-lang",
    "c-family/stub-objc",
    "attribs",
    "c/c-errors",
    "c/c-decl",
    "c/c-typeck",
    "c/c-convert",
    "c/c-aux-info",
    "c/c-objc-common",
    "c/c-parser",
    "c/c-fold",
    "c/gimple-parser",
    "c-family/c-common",
    "c-family/c-cppbuiltin",
    "c-family/c-dump",
    "c-family/c-format",
    "c-family/c-gimplify",
    "c-family/c-indentation",
    "c-family/c-lex",
    "c-family/c-omp",
    "c-family/c-opts",
    "c-family/c-pch",
    "c-family/c-ppoutput",
    "c-family/c-pragma",
    "c-family/c-pretty-print",
    "c-family/c-semantics",
    "c-family/c-ada-spec",
    "c-family/c-ubsan",
    "c-family/known-headers",
    "c-family/c-attribs",
    "c-family/c-warn",
    "c-family/c-spellcheck",
    "config/i386/i386-c",
    "config/glibc-c",
]

# cc1plus's front-end objects (cp/Make-lang.in CXX_OBJS).
CXX_OBJECTS = [
    "cp/cp-lang",
    "c-family/stub-objc",
    "cp/call",
    "cp/class",
    "cp/constexpr",
    "cp/constraint",
    "cp/coroutines",
    "cp/cp-gimplify",
    "cp/cp-objcp-common",
    "cp/cp-ubsan",
    "cp/cvt",
    "cp/cxx-pretty-print",
    "cp/decl",
    "cp/decl2",
    "cp/dump",
    "cp/error",
    "cp/except",
    "cp/expr",
    "cp/friend",
    "cp/init",
    "cp/lambda",
    "cp/lex",
    "cp/logic",
    "cp/mangle",
    "cp/method",
    "cp/name-lookup",
    "cp/optimize",
    "cp/parser",
    "cp/pt",
    "cp/ptree",
    "cp/rtti",
    "cp/search",
    "cp/semantics",
    "cp/tree",
    "cp/typeck",
    "cp/typeck2",
    "cp/vtable-class-hierarchy",
    "attribs",
    "incpath",
    "c-family/c-common",
    "c-family/c-cppbuiltin",
    "c-family/c-dump",
    "c-family/c-format",
    "c-family/c-gimplify",
    "c-family/c-indentation",
    "c-family/c-lex",
    "c-family/c-omp",
    "c-family/c-opts",
    "c-family/c-pch",
    "c-family/c-ppoutput",
    "c-family/c-pragma",
    "c-family/c-pretty-print",
    "c-family/c-semantics",
    "c-family/c-ada-spec",
    "c-family/c-ubsan",
    "c-family/known-headers",
    "c-family/c-attribs",
    "c-family/c-warn",
    "c-family/c-spellcheck",
    "config/i386/i386-c",
    "config/glibc-c",
]

# Compiled gcc/ sources named .cc rather than .c.
CC_SOURCES = [
    "analyzer/analysis-plan",
    "analyzer/analyzer",
    "analyzer/analyzer-logging",
    "analyzer/analyzer-pass",
    "analyzer/analyzer-selftests",
    "analyzer/bar-chart",
    "analyzer/call-string",
    "analyzer/checker-path",
    "analyzer/constraint-manager",
    "analyzer/diagnostic-manager",
    "analyzer/engine",
    "analyzer/function-set",
    "analyzer/pending-diagnostic",
    "analyzer/program-point",
    "analyzer/program-state",
    "analyzer/region-model",
    "analyzer/sm",
    "analyzer/sm-file",
    "analyzer/sm-malloc",
    "analyzer/sm-pattern-test",
    "analyzer/sm-sensitive",
    "analyzer/sm-signal",
    "analyzer/sm-taint",
    "analyzer/state-purge",
    "analyzer/supergraph",
    "c-family/c-spellcheck",
    "c-family/known-headers",
    "coroutine-passes",
    "cp/constraint",
    "cp/coroutines",
    "cp/logic",
    "diagnostic-format-json",
    "digraph",
    "function-abi",
    "gimple-loop-interchange",
    "gimple-loop-versioning",
    "graphviz",
    "json",
    "memory-block",
    "opt-problem",
    "optinfo",
    "optinfo-emit-json",
    "ordered-hash-map-tests",
    "range",
    "range-op",
    "sort",
    "tree-diagnostic-path",
    "tristate",
    "unique-ptr-tests",
    "value-range",
    "wide-int",
    "wide-int-print",
]

# Compiled sources generated in the objdir.
GENERATED_COMPILER_SOURCES = [
    "generic-match",
    "gimple-match",
    "gtype-desc",
    "insn-attrtab",
    "insn-automata",
    "insn-dfatab",
    "insn-emit",
    "insn-enums",
    "insn-extract",
    "insn-latencytab",
    "insn-modes",
    "insn-opinit",
    "insn-output",
    "insn-peep",
    "insn-preds",
    "insn-recog",
    "options",
    "options-save",
]

# libgcc.a members in upstream archive order: (object, source, defines, flags).
# libgcc/Makefile.in and the x86_64 Linux tmake fragments supply the flags.
LIBGCC_OBJECTS = [
    ("_muldi3", "libgcc/libgcc2.c", ["L_muldi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_negdi2", "libgcc/libgcc2.c", ["L_negdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_lshrdi3", "libgcc/libgcc2.c", ["L_lshrdi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_ashldi3", "libgcc/libgcc2.c", ["L_ashldi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_ashrdi3", "libgcc/libgcc2.c", ["L_ashrdi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_cmpdi2", "libgcc/libgcc2.c", ["L_cmpdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_ucmpdi2", "libgcc/libgcc2.c", ["L_ucmpdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_clear_cache", "libgcc/libgcc2.c", ["L_clear_cache"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_trampoline", "libgcc/libgcc2.c", ["L_trampoline"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("__main", "libgcc/libgcc2.c", ["L__main"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_absvsi2", "libgcc/libgcc2.c", ["L_absvsi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_absvdi2", "libgcc/libgcc2.c", ["L_absvdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_addvsi3", "libgcc/libgcc2.c", ["L_addvsi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_addvdi3", "libgcc/libgcc2.c", ["L_addvdi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_subvsi3", "libgcc/libgcc2.c", ["L_subvsi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_subvdi3", "libgcc/libgcc2.c", ["L_subvdi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_mulvsi3", "libgcc/libgcc2.c", ["L_mulvsi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_mulvdi3", "libgcc/libgcc2.c", ["L_mulvdi3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_negvsi2", "libgcc/libgcc2.c", ["L_negvsi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_negvdi2", "libgcc/libgcc2.c", ["L_negvdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_ctors", "libgcc/libgcc2.c", ["L_ctors"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_ffssi2", "libgcc/libgcc2.c", ["L_ffssi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_ffsdi2", "libgcc/libgcc2.c", ["L_ffsdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_clz", "libgcc/libgcc2.c", ["L_clz"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_clzsi2", "libgcc/libgcc2.c", ["L_clzsi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_clzdi2", "libgcc/libgcc2.c", ["L_clzdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_ctzsi2", "libgcc/libgcc2.c", ["L_ctzsi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_ctzdi2", "libgcc/libgcc2.c", ["L_ctzdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_popcount_tab", "libgcc/libgcc2.c", ["L_popcount_tab"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_popcountsi2", "libgcc/libgcc2.c", ["L_popcountsi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_popcountdi2", "libgcc/libgcc2.c", ["L_popcountdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_paritysi2", "libgcc/libgcc2.c", ["L_paritysi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_paritydi2", "libgcc/libgcc2.c", ["L_paritydi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_powisf2", "libgcc/libgcc2.c", ["L_powisf2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_powidf2", "libgcc/libgcc2.c", ["L_powidf2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_powixf2", "libgcc/libgcc2.c", ["L_powixf2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_mulhc3", "libgcc/libgcc2.c", ["L_mulhc3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_mulsc3", "libgcc/libgcc2.c", ["L_mulsc3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_muldc3", "libgcc/libgcc2.c", ["L_muldc3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_mulxc3", "libgcc/libgcc2.c", ["L_mulxc3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_divhc3", "libgcc/libgcc2.c", ["L_divhc3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_divsc3", "libgcc/libgcc2.c", ["L_divsc3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_divdc3", "libgcc/libgcc2.c", ["L_divdc3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_divxc3", "libgcc/libgcc2.c", ["L_divxc3"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_bswapsi2", "libgcc/libgcc2.c", ["L_bswapsi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_bswapdi2", "libgcc/libgcc2.c", ["L_bswapdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_clrsbsi2", "libgcc/libgcc2.c", ["L_clrsbsi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_clrsbdi2", "libgcc/libgcc2.c", ["L_clrsbdi2"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixunssfsi", "libgcc/libgcc2.c", ["L_fixunssfsi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixunsdfsi", "libgcc/libgcc2.c", ["L_fixunsdfsi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixunsxfsi", "libgcc/libgcc2.c", ["L_fixunsxfsi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixsfdi", "libgcc/libgcc2.c", ["L_fixsfdi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixdfdi", "libgcc/libgcc2.c", ["L_fixdfdi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixxfdi", "libgcc/libgcc2.c", ["L_fixxfdi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixunssfdi", "libgcc/libgcc2.c", ["L_fixunssfdi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixunsdfdi", "libgcc/libgcc2.c", ["L_fixunsdfdi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_fixunsxfdi", "libgcc/libgcc2.c", ["L_fixunsxfdi"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_floatdisf", "libgcc/libgcc2.c", ["L_floatdisf"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_floatdidf", "libgcc/libgcc2.c", ["L_floatdidf"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_floatdixf", "libgcc/libgcc2.c", ["L_floatdixf"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_floatundisf", "libgcc/libgcc2.c", ["L_floatundisf"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_floatundidf", "libgcc/libgcc2.c", ["L_floatundidf"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_floatundixf", "libgcc/libgcc2.c", ["L_floatundixf"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_eprintf", "libgcc/libgcc2.c", ["L_eprintf"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("__gcc_bcmp", "libgcc/libgcc2.c", ["L__gcc_bcmp"], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_divdi3", "libgcc/libgcc2.c", ["L_divdi3"], ["-fexceptions", "-fnon-call-exceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_moddi3", "libgcc/libgcc2.c", ["L_moddi3"], ["-fexceptions", "-fnon-call-exceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_divmoddi4", "libgcc/libgcc2.c", ["L_divmoddi4"], ["-fexceptions", "-fnon-call-exceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_udivdi3", "libgcc/libgcc2.c", ["L_udivdi3"], ["-fexceptions", "-fnon-call-exceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_umoddi3", "libgcc/libgcc2.c", ["L_umoddi3"], ["-fexceptions", "-fnon-call-exceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_udivmoddi4", "libgcc/libgcc2.c", ["L_udivmoddi4"], ["-fexceptions", "-fnon-call-exceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_udiv_w_sdiv", "libgcc/libgcc2.c", ["L_udiv_w_sdiv"], ["-fexceptions", "-fnon-call-exceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("bid_decimal_globals", "libgcc/config/libbid/bid_decimal_globals.c", [], []),
    ("bid_decimal_data", "libgcc/config/libbid/bid_decimal_data.c", [], []),
    ("bid_binarydecimal", "libgcc/config/libbid/bid_binarydecimal.c", [], []),
    ("bid_convert_data", "libgcc/config/libbid/bid_convert_data.c", [], []),
    ("_isinfd32", "libgcc/config/libbid/_isinfd32.c", [], []),
    ("_isinfd64", "libgcc/config/libbid/_isinfd64.c", [], []),
    ("_isinfd128", "libgcc/config/libbid/_isinfd128.c", [], []),
    ("bid64_noncomp", "libgcc/config/libbid/bid64_noncomp.c", [], []),
    ("bid128_noncomp", "libgcc/config/libbid/bid128_noncomp.c", [], []),
    ("bid128_fma", "libgcc/config/libbid/bid128_fma.c", [], []),
    ("bid_round", "libgcc/config/libbid/bid_round.c", [], []),
    ("bid_from_int", "libgcc/config/libbid/bid_from_int.c", [], []),
    ("bid64_add", "libgcc/config/libbid/bid64_add.c", [], []),
    ("bid128_add", "libgcc/config/libbid/bid128_add.c", [], []),
    ("bid64_div", "libgcc/config/libbid/bid64_div.c", [], []),
    ("bid128_div", "libgcc/config/libbid/bid128_div.c", [], []),
    ("bid64_mul", "libgcc/config/libbid/bid64_mul.c", [], []),
    ("bid128_mul", "libgcc/config/libbid/bid128_mul.c", [], []),
    ("bid64_compare", "libgcc/config/libbid/bid64_compare.c", [], []),
    ("bid128_compare", "libgcc/config/libbid/bid128_compare.c", [], []),
    ("bid128", "libgcc/config/libbid/bid128.c", [], []),
    ("bid32_to_bid64", "libgcc/config/libbid/bid32_to_bid64.c", [], []),
    ("bid32_to_bid128", "libgcc/config/libbid/bid32_to_bid128.c", [], []),
    ("bid64_to_bid128", "libgcc/config/libbid/bid64_to_bid128.c", [], []),
    ("bid64_to_int32", "libgcc/config/libbid/bid64_to_int32.c", [], []),
    ("bid64_to_int64", "libgcc/config/libbid/bid64_to_int64.c", [], []),
    ("bid64_to_uint32", "libgcc/config/libbid/bid64_to_uint32.c", [], []),
    ("bid64_to_uint64", "libgcc/config/libbid/bid64_to_uint64.c", [], []),
    ("bid128_to_int32", "libgcc/config/libbid/bid128_to_int32.c", [], []),
    ("bid128_to_int64", "libgcc/config/libbid/bid128_to_int64.c", [], []),
    ("bid128_to_uint32", "libgcc/config/libbid/bid128_to_uint32.c", [], []),
    ("bid128_to_uint64", "libgcc/config/libbid/bid128_to_uint64.c", [], []),
    ("_addsub_sd", "libgcc/config/libbid/_addsub_sd.c", ["FINE_GRAINED_LIBRARIES", "L_addsub_sd", "WIDTH=32"], []),
    ("_div_sd", "libgcc/config/libbid/_div_sd.c", ["FINE_GRAINED_LIBRARIES", "L_div_sd", "WIDTH=32"], []),
    ("_mul_sd", "libgcc/config/libbid/_mul_sd.c", ["FINE_GRAINED_LIBRARIES", "L_mul_sd", "WIDTH=32"], []),
    ("_eq_sd", "libgcc/config/libbid/_eq_sd.c", ["FINE_GRAINED_LIBRARIES", "L_eq_sd", "WIDTH=32"], []),
    ("_ne_sd", "libgcc/config/libbid/_ne_sd.c", ["FINE_GRAINED_LIBRARIES", "L_ne_sd", "WIDTH=32"], []),
    ("_lt_sd", "libgcc/config/libbid/_lt_sd.c", ["FINE_GRAINED_LIBRARIES", "L_lt_sd", "WIDTH=32"], []),
    ("_gt_sd", "libgcc/config/libbid/_gt_sd.c", ["FINE_GRAINED_LIBRARIES", "L_gt_sd", "WIDTH=32"], []),
    ("_le_sd", "libgcc/config/libbid/_le_sd.c", ["FINE_GRAINED_LIBRARIES", "L_le_sd", "WIDTH=32"], []),
    ("_ge_sd", "libgcc/config/libbid/_ge_sd.c", ["FINE_GRAINED_LIBRARIES", "L_ge_sd", "WIDTH=32"], []),
    ("_sd_to_si", "libgcc/config/libbid/_sd_to_si.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_si", "WIDTH=32"], []),
    ("_sd_to_di", "libgcc/config/libbid/_sd_to_di.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_di", "WIDTH=32"], []),
    ("_sd_to_usi", "libgcc/config/libbid/_sd_to_usi.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_usi", "WIDTH=32"], []),
    ("_sd_to_udi", "libgcc/config/libbid/_sd_to_udi.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_udi", "WIDTH=32"], []),
    ("_si_to_sd", "libgcc/config/libbid/_si_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_si_to_sd", "WIDTH=32"], []),
    ("_di_to_sd", "libgcc/config/libbid/_di_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_di_to_sd", "WIDTH=32"], []),
    ("_usi_to_sd", "libgcc/config/libbid/_usi_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_usi_to_sd", "WIDTH=32"], []),
    ("_udi_to_sd", "libgcc/config/libbid/_udi_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_udi_to_sd", "WIDTH=32"], []),
    ("_sd_to_sf", "libgcc/config/libbid/_sd_to_sf.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_sf", "WIDTH=32"], []),
    ("_sd_to_df", "libgcc/config/libbid/_sd_to_df.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_df", "WIDTH=32"], []),
    ("_sd_to_xf", "libgcc/config/libbid/_sd_to_xf.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_xf", "WIDTH=32"], []),
    ("_sd_to_tf", "libgcc/config/libbid/_sd_to_tf.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_tf", "WIDTH=32"], []),
    ("_sf_to_sd", "libgcc/config/libbid/_sf_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_sf_to_sd", "WIDTH=32"], []),
    ("_df_to_sd", "libgcc/config/libbid/_df_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_df_to_sd", "WIDTH=32"], []),
    ("_xf_to_sd", "libgcc/config/libbid/_xf_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_xf_to_sd", "WIDTH=32"], []),
    ("_tf_to_sd", "libgcc/config/libbid/_tf_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_tf_to_sd", "WIDTH=32"], []),
    ("_sd_to_dd", "libgcc/config/libbid/_sd_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_dd", "WIDTH=32"], []),
    ("_sd_to_td", "libgcc/config/libbid/_sd_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_sd_to_td", "WIDTH=32"], []),
    ("_unord_sd", "libgcc/config/libbid/_unord_sd.c", ["FINE_GRAINED_LIBRARIES", "L_unord_sd", "WIDTH=32"], []),
    ("_addsub_dd", "libgcc/config/libbid/_addsub_dd.c", ["FINE_GRAINED_LIBRARIES", "L_addsub_dd", "WIDTH=64"], []),
    ("_div_dd", "libgcc/config/libbid/_div_dd.c", ["FINE_GRAINED_LIBRARIES", "L_div_dd", "WIDTH=64"], []),
    ("_mul_dd", "libgcc/config/libbid/_mul_dd.c", ["FINE_GRAINED_LIBRARIES", "L_mul_dd", "WIDTH=64"], []),
    ("_eq_dd", "libgcc/config/libbid/_eq_dd.c", ["FINE_GRAINED_LIBRARIES", "L_eq_dd", "WIDTH=64"], []),
    ("_ne_dd", "libgcc/config/libbid/_ne_dd.c", ["FINE_GRAINED_LIBRARIES", "L_ne_dd", "WIDTH=64"], []),
    ("_lt_dd", "libgcc/config/libbid/_lt_dd.c", ["FINE_GRAINED_LIBRARIES", "L_lt_dd", "WIDTH=64"], []),
    ("_gt_dd", "libgcc/config/libbid/_gt_dd.c", ["FINE_GRAINED_LIBRARIES", "L_gt_dd", "WIDTH=64"], []),
    ("_le_dd", "libgcc/config/libbid/_le_dd.c", ["FINE_GRAINED_LIBRARIES", "L_le_dd", "WIDTH=64"], []),
    ("_ge_dd", "libgcc/config/libbid/_ge_dd.c", ["FINE_GRAINED_LIBRARIES", "L_ge_dd", "WIDTH=64"], []),
    ("_dd_to_si", "libgcc/config/libbid/_dd_to_si.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_si", "WIDTH=64"], []),
    ("_dd_to_di", "libgcc/config/libbid/_dd_to_di.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_di", "WIDTH=64"], []),
    ("_dd_to_usi", "libgcc/config/libbid/_dd_to_usi.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_usi", "WIDTH=64"], []),
    ("_dd_to_udi", "libgcc/config/libbid/_dd_to_udi.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_udi", "WIDTH=64"], []),
    ("_si_to_dd", "libgcc/config/libbid/_si_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_si_to_dd", "WIDTH=64"], []),
    ("_di_to_dd", "libgcc/config/libbid/_di_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_di_to_dd", "WIDTH=64"], []),
    ("_usi_to_dd", "libgcc/config/libbid/_usi_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_usi_to_dd", "WIDTH=64"], []),
    ("_udi_to_dd", "libgcc/config/libbid/_udi_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_udi_to_dd", "WIDTH=64"], []),
    ("_dd_to_sf", "libgcc/config/libbid/_dd_to_sf.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_sf", "WIDTH=64"], []),
    ("_dd_to_df", "libgcc/config/libbid/_dd_to_df.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_df", "WIDTH=64"], []),
    ("_dd_to_xf", "libgcc/config/libbid/_dd_to_xf.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_xf", "WIDTH=64"], []),
    ("_dd_to_tf", "libgcc/config/libbid/_dd_to_tf.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_tf", "WIDTH=64"], []),
    ("_sf_to_dd", "libgcc/config/libbid/_sf_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_sf_to_dd", "WIDTH=64"], []),
    ("_df_to_dd", "libgcc/config/libbid/_df_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_df_to_dd", "WIDTH=64"], []),
    ("_xf_to_dd", "libgcc/config/libbid/_xf_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_xf_to_dd", "WIDTH=64"], []),
    ("_tf_to_dd", "libgcc/config/libbid/_tf_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_tf_to_dd", "WIDTH=64"], []),
    ("_dd_to_sd", "libgcc/config/libbid/_dd_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_sd", "WIDTH=64"], []),
    ("_dd_to_td", "libgcc/config/libbid/_dd_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_dd_to_td", "WIDTH=64"], []),
    ("_unord_dd", "libgcc/config/libbid/_unord_dd.c", ["FINE_GRAINED_LIBRARIES", "L_unord_dd", "WIDTH=64"], []),
    ("_addsub_td", "libgcc/config/libbid/_addsub_td.c", ["FINE_GRAINED_LIBRARIES", "L_addsub_td", "WIDTH=128"], []),
    ("_div_td", "libgcc/config/libbid/_div_td.c", ["FINE_GRAINED_LIBRARIES", "L_div_td", "WIDTH=128"], []),
    ("_mul_td", "libgcc/config/libbid/_mul_td.c", ["FINE_GRAINED_LIBRARIES", "L_mul_td", "WIDTH=128"], []),
    ("_eq_td", "libgcc/config/libbid/_eq_td.c", ["FINE_GRAINED_LIBRARIES", "L_eq_td", "WIDTH=128"], []),
    ("_ne_td", "libgcc/config/libbid/_ne_td.c", ["FINE_GRAINED_LIBRARIES", "L_ne_td", "WIDTH=128"], []),
    ("_lt_td", "libgcc/config/libbid/_lt_td.c", ["FINE_GRAINED_LIBRARIES", "L_lt_td", "WIDTH=128"], []),
    ("_gt_td", "libgcc/config/libbid/_gt_td.c", ["FINE_GRAINED_LIBRARIES", "L_gt_td", "WIDTH=128"], []),
    ("_le_td", "libgcc/config/libbid/_le_td.c", ["FINE_GRAINED_LIBRARIES", "L_le_td", "WIDTH=128"], []),
    ("_ge_td", "libgcc/config/libbid/_ge_td.c", ["FINE_GRAINED_LIBRARIES", "L_ge_td", "WIDTH=128"], []),
    ("_td_to_si", "libgcc/config/libbid/_td_to_si.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_si", "WIDTH=128"], []),
    ("_td_to_di", "libgcc/config/libbid/_td_to_di.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_di", "WIDTH=128"], []),
    ("_td_to_usi", "libgcc/config/libbid/_td_to_usi.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_usi", "WIDTH=128"], []),
    ("_td_to_udi", "libgcc/config/libbid/_td_to_udi.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_udi", "WIDTH=128"], []),
    ("_si_to_td", "libgcc/config/libbid/_si_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_si_to_td", "WIDTH=128"], []),
    ("_di_to_td", "libgcc/config/libbid/_di_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_di_to_td", "WIDTH=128"], []),
    ("_usi_to_td", "libgcc/config/libbid/_usi_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_usi_to_td", "WIDTH=128"], []),
    ("_udi_to_td", "libgcc/config/libbid/_udi_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_udi_to_td", "WIDTH=128"], []),
    ("_td_to_sf", "libgcc/config/libbid/_td_to_sf.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_sf", "WIDTH=128"], []),
    ("_td_to_df", "libgcc/config/libbid/_td_to_df.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_df", "WIDTH=128"], []),
    ("_td_to_xf", "libgcc/config/libbid/_td_to_xf.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_xf", "WIDTH=128"], []),
    ("_td_to_tf", "libgcc/config/libbid/_td_to_tf.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_tf", "WIDTH=128"], []),
    ("_sf_to_td", "libgcc/config/libbid/_sf_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_sf_to_td", "WIDTH=128"], []),
    ("_df_to_td", "libgcc/config/libbid/_df_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_df_to_td", "WIDTH=128"], []),
    ("_xf_to_td", "libgcc/config/libbid/_xf_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_xf_to_td", "WIDTH=128"], []),
    ("_tf_to_td", "libgcc/config/libbid/_tf_to_td.c", ["FINE_GRAINED_LIBRARIES", "L_tf_to_td", "WIDTH=128"], []),
    ("_td_to_sd", "libgcc/config/libbid/_td_to_sd.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_sd", "WIDTH=128"], []),
    ("_td_to_dd", "libgcc/config/libbid/_td_to_dd.c", ["FINE_GRAINED_LIBRARIES", "L_td_to_dd", "WIDTH=128"], []),
    ("_unord_td", "libgcc/config/libbid/_unord_td.c", ["FINE_GRAINED_LIBRARIES", "L_unord_td", "WIDTH=128"], []),
    ("sfp-exceptions", "libgcc/config/i386/sfp-exceptions.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("addtf3", "libgcc/soft-fp/addtf3.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("divtf3", "libgcc/soft-fp/divtf3.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("multf3", "libgcc/soft-fp/multf3.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("negtf2", "libgcc/soft-fp/negtf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("subtf3", "libgcc/soft-fp/subtf3.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("unordtf2", "libgcc/soft-fp/unordtf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("fixtfsi", "libgcc/soft-fp/fixtfsi.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("fixunstfsi", "libgcc/soft-fp/fixunstfsi.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("floatsitf", "libgcc/soft-fp/floatsitf.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("floatunsitf", "libgcc/soft-fp/floatunsitf.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("fixtfdi", "libgcc/soft-fp/fixtfdi.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("fixunstfdi", "libgcc/soft-fp/fixunstfdi.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("floatditf", "libgcc/soft-fp/floatditf.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("floatunditf", "libgcc/soft-fp/floatunditf.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("fixtfti", "libgcc/soft-fp/fixtfti.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("fixunstfti", "libgcc/soft-fp/fixunstfti.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("floattitf", "libgcc/soft-fp/floattitf.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("floatuntitf", "libgcc/soft-fp/floatuntitf.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("extendsftf2", "libgcc/soft-fp/extendsftf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("extenddftf2", "libgcc/soft-fp/extenddftf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("extendxftf2", "libgcc/soft-fp/extendxftf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("trunctfsf2", "libgcc/soft-fp/trunctfsf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("trunctfdf2", "libgcc/soft-fp/trunctfdf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("trunctfxf2", "libgcc/soft-fp/trunctfxf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("getf2", "libgcc/config/i386/64/getf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("letf2", "libgcc/config/i386/64/letf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("eqtf2", "libgcc/config/i386/64/eqtf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS", "-Wno-missing-prototypes", "-Wno-type-limits"]),
    ("_divtc3", "libgcc/config/i386/64/_divtc3.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_multc3", "libgcc/config/i386/64/_multc3.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("_powitf2", "libgcc/config/i386/64/_powitf2.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("enable-execute-stack", "libgcc/enable-execute-stack-empty.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("cpuinfo", "libgcc/config/i386/cpuinfo.c", [], ["-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("avx_savms64", "libgcc/config/i386/avx_savms64.S", [], ["-xassembler-with-cpp"]),
    ("avx_resms64", "libgcc/config/i386/avx_resms64.S", [], ["-xassembler-with-cpp"]),
    ("avx_resms64x", "libgcc/config/i386/avx_resms64x.S", [], ["-xassembler-with-cpp"]),
    ("avx_savms64f", "libgcc/config/i386/avx_savms64f.S", [], ["-xassembler-with-cpp"]),
    ("avx_resms64f", "libgcc/config/i386/avx_resms64f.S", [], ["-xassembler-with-cpp"]),
    ("avx_resms64fx", "libgcc/config/i386/avx_resms64fx.S", [], ["-xassembler-with-cpp"]),
    ("sse_savms64", "libgcc/config/i386/sse_savms64.S", [], ["-xassembler-with-cpp"]),
    ("sse_resms64", "libgcc/config/i386/sse_resms64.S", [], ["-xassembler-with-cpp"]),
    ("sse_resms64x", "libgcc/config/i386/sse_resms64x.S", [], ["-xassembler-with-cpp"]),
    ("sse_savms64f", "libgcc/config/i386/sse_savms64f.S", [], ["-xassembler-with-cpp"]),
    ("sse_resms64f", "libgcc/config/i386/sse_resms64f.S", [], ["-xassembler-with-cpp"]),
    ("sse_resms64fx", "libgcc/config/i386/sse_resms64fx.S", [], ["-xassembler-with-cpp"]),
    ("unwind-dw2", "libgcc/unwind-dw2.c", [], ["-fexceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("unwind-dw2-fde-dip", "libgcc/unwind-dw2-fde-dip.c", [], ["-fexceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("unwind-sjlj", "libgcc/unwind-sjlj.c", [], ["-fexceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("unwind-c", "libgcc/unwind-c.c", [], ["-fexceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
    ("emutls", "libgcc/emutls.c", [], ["-fexceptions", "-fvisibility=hidden", "-DHIDE_EXPORTS"]),
]

# libgcov.a members: (object, source, define).
LIBGCOV_OBJECTS = [
    ("_gcov_merge_add", "libgcc/libgcov-merge.c", "L_gcov_merge_add"),
    ("_gcov_merge_topn", "libgcc/libgcov-merge.c", "L_gcov_merge_topn"),
    ("_gcov_merge_ior", "libgcc/libgcov-merge.c", "L_gcov_merge_ior"),
    ("_gcov_merge_time_profile", "libgcc/libgcov-merge.c", "L_gcov_merge_time_profile"),
    ("_gcov_interval_profiler", "libgcc/libgcov-profiler.c", "L_gcov_interval_profiler"),
    ("_gcov_interval_profiler_atomic", "libgcc/libgcov-profiler.c", "L_gcov_interval_profiler_atomic"),
    ("_gcov_pow2_profiler", "libgcc/libgcov-profiler.c", "L_gcov_pow2_profiler"),
    ("_gcov_pow2_profiler_atomic", "libgcc/libgcov-profiler.c", "L_gcov_pow2_profiler_atomic"),
    ("_gcov_topn_values_profiler", "libgcc/libgcov-profiler.c", "L_gcov_topn_values_profiler"),
    ("_gcov_topn_values_profiler_atomic", "libgcc/libgcov-profiler.c", "L_gcov_topn_values_profiler_atomic"),
    ("_gcov_average_profiler", "libgcc/libgcov-profiler.c", "L_gcov_average_profiler"),
    ("_gcov_average_profiler_atomic", "libgcc/libgcov-profiler.c", "L_gcov_average_profiler_atomic"),
    ("_gcov_ior_profiler", "libgcc/libgcov-profiler.c", "L_gcov_ior_profiler"),
    ("_gcov_ior_profiler_atomic", "libgcc/libgcov-profiler.c", "L_gcov_ior_profiler_atomic"),
    ("_gcov_indirect_call_profiler_v4", "libgcc/libgcov-profiler.c", "L_gcov_indirect_call_profiler_v4"),
    ("_gcov_time_profiler", "libgcc/libgcov-profiler.c", "L_gcov_time_profiler"),
    ("_gcov_dump", "libgcc/libgcov-interface.c", "L_gcov_dump"),
    ("_gcov_flush", "libgcc/libgcov-interface.c", "L_gcov_flush"),
    ("_gcov_fork", "libgcc/libgcov-interface.c", "L_gcov_fork"),
    ("_gcov_execl", "libgcc/libgcov-interface.c", "L_gcov_execl"),
    ("_gcov_execlp", "libgcc/libgcov-interface.c", "L_gcov_execlp"),
    ("_gcov_execle", "libgcc/libgcov-interface.c", "L_gcov_execle"),
    ("_gcov_execv", "libgcc/libgcov-interface.c", "L_gcov_execv"),
    ("_gcov_execvp", "libgcc/libgcov-interface.c", "L_gcov_execvp"),
    ("_gcov_execve", "libgcc/libgcov-interface.c", "L_gcov_execve"),
    ("_gcov_reset", "libgcc/libgcov-interface.c", "L_gcov_reset"),
    ("_gcov", "libgcc/libgcov-driver.c", "L_gcov"),
]
