# SPDX-FileCopyrightText: © 2024-2025 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@toolchains//cxx:defs.bzl", "path_clang_tools")

path_clang_tools(
    name = "path_clang_tools",
    visibility = ["PUBLIC"],
)
