# SPDX-FileCopyrightText: © 2024-2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@root//buck/shims:shims.bzl", "shims")

shims.constraint(
    name = "build-mode",
    values = [
        "debug",
        "release",
    ],
    default = "debug",
)
