# SPDX-FileCopyrightText: © 2024-2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load(":defs.bzl", "ocaml_toolchain")

ocaml_toolchain(
    name = "ocaml",
    compiler_flags = [
        "-w",
        "-40",
    ],
)
