# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@root//buck/shims:shims.bzl", "shims")

shims.go_test(
    name = "go-internal-runner",
    srcs = ["runner_test.go"],
    cgo_enabled = False,
)
