# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# Translation units in upstream archive order: (group, object, source, flags).
# libsupc++ objects are in both archives; filesystem objects form libstdc++fs.a.
# The flags are the per-directory and per-file Makefile.am additions.
LIBRARY_OBJECTS = [
    ("libsupc++", "array_type_info", "libstdc++-v3/libsupc++/array_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "atexit_arm", "libstdc++-v3/libsupc++/atexit_arm.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "atexit_thread", "libstdc++-v3/libsupc++/atexit_thread.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "atomicity", "libstdc++-v3/config/cpu/generic/atomicity_builtins/atomicity.h", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "bad_alloc", "libstdc++-v3/libsupc++/bad_alloc.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "bad_array_length", "libstdc++-v3/libsupc++/bad_array_length.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "bad_array_new", "libstdc++-v3/libsupc++/bad_array_new.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "bad_cast", "libstdc++-v3/libsupc++/bad_cast.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "bad_typeid", "libstdc++-v3/libsupc++/bad_typeid.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "class_type_info", "libstdc++-v3/libsupc++/class_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "del_op", "libstdc++-v3/libsupc++/del_op.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "del_ops", "libstdc++-v3/libsupc++/del_ops.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "del_opnt", "libstdc++-v3/libsupc++/del_opnt.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "del_opv", "libstdc++-v3/libsupc++/del_opv.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "del_opvs", "libstdc++-v3/libsupc++/del_opvs.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "del_opvnt", "libstdc++-v3/libsupc++/del_opvnt.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "dyncast", "libstdc++-v3/libsupc++/dyncast.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_alloc", "libstdc++-v3/libsupc++/eh_alloc.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_arm", "libstdc++-v3/libsupc++/eh_arm.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_aux_runtime", "libstdc++-v3/libsupc++/eh_aux_runtime.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_call", "libstdc++-v3/libsupc++/eh_call.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_catch", "libstdc++-v3/libsupc++/eh_catch.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_exception", "libstdc++-v3/libsupc++/eh_exception.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_globals", "libstdc++-v3/libsupc++/eh_globals.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_personality", "libstdc++-v3/libsupc++/eh_personality.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_ptr", "libstdc++-v3/libsupc++/eh_ptr.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_term_handler", "libstdc++-v3/libsupc++/eh_term_handler.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_terminate", "libstdc++-v3/libsupc++/eh_terminate.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_tm", "libstdc++-v3/libsupc++/eh_tm.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_throw", "libstdc++-v3/libsupc++/eh_throw.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_type", "libstdc++-v3/libsupc++/eh_type.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "eh_unex_handler", "libstdc++-v3/libsupc++/eh_unex_handler.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "enum_type_info", "libstdc++-v3/libsupc++/enum_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "function_type_info", "libstdc++-v3/libsupc++/function_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "fundamental_type_info", "libstdc++-v3/libsupc++/fundamental_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "guard", "libstdc++-v3/libsupc++/guard.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "guard_error", "libstdc++-v3/libsupc++/guard_error.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "hash_bytes", "libstdc++-v3/libsupc++/hash_bytes.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "nested_exception", "libstdc++-v3/libsupc++/nested_exception.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "new_handler", "libstdc++-v3/libsupc++/new_handler.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "new_op", "libstdc++-v3/libsupc++/new_op.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "new_opnt", "libstdc++-v3/libsupc++/new_opnt.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "new_opv", "libstdc++-v3/libsupc++/new_opv.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "new_opvnt", "libstdc++-v3/libsupc++/new_opvnt.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "new_opa", "libstdc++-v3/libsupc++/new_opa.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "new_opant", "libstdc++-v3/libsupc++/new_opant.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "new_opva", "libstdc++-v3/libsupc++/new_opva.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "new_opvant", "libstdc++-v3/libsupc++/new_opvant.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "del_opa", "libstdc++-v3/libsupc++/del_opa.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "del_opant", "libstdc++-v3/libsupc++/del_opant.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "del_opsa", "libstdc++-v3/libsupc++/del_opsa.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "del_opva", "libstdc++-v3/libsupc++/del_opva.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "del_opvant", "libstdc++-v3/libsupc++/del_opvant.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "del_opvsa", "libstdc++-v3/libsupc++/del_opvsa.cc", ["-std=gnu++17", "-fno-implicit-templates"]),
    ("libsupc++", "pbase_type_info", "libstdc++-v3/libsupc++/pbase_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "pmem_type_info", "libstdc++-v3/libsupc++/pmem_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "pointer_type_info", "libstdc++-v3/libsupc++/pointer_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "pure", "libstdc++-v3/libsupc++/pure.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "si_class_type_info", "libstdc++-v3/libsupc++/si_class_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "tinfo", "libstdc++-v3/libsupc++/tinfo.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "tinfo2", "libstdc++-v3/libsupc++/tinfo2.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "vec", "libstdc++-v3/libsupc++/vec.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "vmi_class_type_info", "libstdc++-v3/libsupc++/vmi_class_type_info.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "vterminate", "libstdc++-v3/libsupc++/vterminate.cc", ["-std=gnu++14", "-fno-implicit-templates"]),
    ("libsupc++", "cp-demangle", "libiberty/cp-demangle.c", ["-DHAVE_CONFIG_H", "-DIN_GLIBCPP_V3", "-Wno-error"]),
    ("c++98", "bitmap_allocator", "libstdc++-v3/src/c++98/bitmap_allocator.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "pool_allocator", "libstdc++-v3/src/c++98/pool_allocator.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "mt_allocator", "libstdc++-v3/src/c++98/mt_allocator.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "codecvt", "libstdc++-v3/src/c++98/codecvt.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "complex_io", "libstdc++-v3/src/c++98/complex_io.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "globals_io", "libstdc++-v3/src/c++98/globals_io.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "hash_tr1", "libstdc++-v3/src/c++98/hash_tr1.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "hashtable_tr1", "libstdc++-v3/src/c++98/hashtable_tr1.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "ios_failure", "libstdc++-v3/src/c++98/ios_failure.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "ios_init", "libstdc++-v3/src/c++98/ios_init.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "ios_locale", "libstdc++-v3/src/c++98/ios_locale.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "list", "libstdc++-v3/src/c++98/list.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "list-aux", "libstdc++-v3/src/c++98/list-aux.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "list-aux-2", "libstdc++-v3/src/c++98/list-aux-2.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "list_associated", "libstdc++-v3/src/c++98/list_associated.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "list_associated-2", "libstdc++-v3/src/c++98/list_associated-2.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "locale", "libstdc++-v3/src/c++98/locale.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "locale_init", "libstdc++-v3/src/c++98/locale_init.cc", ["-std=gnu++11", "-fno-implicit-templates", "-fchar8_t"]),
    ("c++98", "locale_facets", "libstdc++-v3/src/c++98/locale_facets.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "localename", "libstdc++-v3/src/c++98/localename.cc", ["-std=gnu++11", "-fno-implicit-templates", "-fchar8_t"]),
    ("c++98", "math_stubs_float", "libstdc++-v3/src/c++98/math_stubs_float.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "math_stubs_long_double", "libstdc++-v3/src/c++98/math_stubs_long_double.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "stdexcept", "libstdc++-v3/src/c++98/stdexcept.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "strstream", "libstdc++-v3/src/c++98/strstream.cc", ["-std=gnu++98", "-fno-implicit-templates", "-I<headers>/backward", "-Wno-deprecated"]),
    ("c++98", "tree", "libstdc++-v3/src/c++98/tree.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "istream", "libstdc++-v3/src/c++98/istream.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "istream-string", "libstdc++-v3/src/c++98/istream-string.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "streambuf", "libstdc++-v3/src/c++98/streambuf.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "valarray", "libstdc++-v3/src/c++98/valarray.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "cow-istream-string", "libstdc++-v3/src/c++98/cow-istream-string.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "collate_members_cow", "libstdc++-v3/config/locale/generic/collate_members.cc", ["-std=gnu++98", "-fno-implicit-templates", "-D_GLIBCXX_USE_CXX11_ABI=0", "-fimplicit-templates"]),
    ("c++98", "messages_members_cow", "libstdc++-v3/config/locale/generic/messages_members.cc", ["-std=gnu++98", "-fno-implicit-templates", "-D_GLIBCXX_USE_CXX11_ABI=0", "-fimplicit-templates"]),
    ("c++98", "monetary_members_cow", "libstdc++-v3/config/locale/generic/monetary_members.cc", ["-std=gnu++98", "-fno-implicit-templates", "-D_GLIBCXX_USE_CXX11_ABI=0", "-fimplicit-templates"]),
    ("c++98", "numeric_members_cow", "libstdc++-v3/config/locale/generic/numeric_members.cc", ["-std=gnu++98", "-fno-implicit-templates", "-D_GLIBCXX_USE_CXX11_ABI=0", "-fimplicit-templates"]),
    ("c++98", "codecvt_members", "libstdc++-v3/config/locale/generic/codecvt_members.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "collate_members", "libstdc++-v3/config/locale/generic/collate_members.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "messages_members", "libstdc++-v3/config/locale/generic/messages_members.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "monetary_members", "libstdc++-v3/config/locale/generic/monetary_members.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "numeric_members", "libstdc++-v3/config/locale/generic/numeric_members.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "time_members", "libstdc++-v3/config/locale/generic/time_members.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "basic_file", "libstdc++-v3/config/io/basic_file_stdio.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "c++locale", "libstdc++-v3/config/locale/generic/c_locale.cc", ["-std=gnu++98", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++98", "allocator-inst", "libstdc++-v3/src/c++98/allocator-inst.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "concept-inst", "libstdc++-v3/src/c++98/concept-inst.cc", ["-std=gnu++98", "-fno-implicit-templates", "-D_GLIBCXX_CONCEPT_CHECKS", "-fimplicit-templates"]),
    ("c++98", "ext-inst", "libstdc++-v3/src/c++98/ext-inst.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "misc-inst", "libstdc++-v3/src/c++98/misc-inst.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("c++98", "parallel_settings", "libstdc++-v3/src/c++98/parallel_settings.cc", ["-std=gnu++98", "-fno-implicit-templates", "-D_GLIBCXX_PARALLEL"]),
    ("c++11", "chrono", "libstdc++-v3/src/c++11/chrono.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "codecvt", "libstdc++-v3/src/c++11/codecvt.cc", ["-std=gnu++11", "-fno-implicit-templates", "-fchar8_t"]),
    ("c++11", "condition_variable", "libstdc++-v3/src/c++11/condition_variable.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-stdexcept", "libstdc++-v3/src/c++11/cow-stdexcept.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "ctype", "libstdc++-v3/src/c++11/ctype.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "debug", "libstdc++-v3/src/c++11/debug.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "functexcept", "libstdc++-v3/src/c++11/functexcept.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "functional", "libstdc++-v3/src/c++11/functional.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "futex", "libstdc++-v3/src/c++11/futex.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "future", "libstdc++-v3/src/c++11/future.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "hash_c++0x", "libstdc++-v3/src/c++11/hash_c++0x.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "hashtable_c++0x", "libstdc++-v3/src/c++11/hashtable_c++0x.cc", ["-std=gnu++11", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++11", "ios", "libstdc++-v3/src/c++11/ios.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "limits", "libstdc++-v3/src/c++11/limits.cc", ["-std=gnu++11", "-fno-implicit-templates", "-fchar8_t"]),
    ("c++11", "mutex", "libstdc++-v3/src/c++11/mutex.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "placeholders", "libstdc++-v3/src/c++11/placeholders.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "random", "libstdc++-v3/src/c++11/random.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "regex", "libstdc++-v3/src/c++11/regex.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "shared_ptr", "libstdc++-v3/src/c++11/shared_ptr.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "snprintf_lite", "libstdc++-v3/src/c++11/snprintf_lite.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "system_error", "libstdc++-v3/src/c++11/system_error.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "thread", "libstdc++-v3/src/c++11/thread.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-locale_init", "libstdc++-v3/src/c++11/cow-locale_init.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-shim_facets", "libstdc++-v3/src/c++11/cow-shim_facets.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cxx11-hash_tr1", "libstdc++-v3/src/c++11/cxx11-hash_tr1.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cxx11-ios_failure", "libstdc++-v3/src/c++11/cxx11-ios_failure.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cxx11-shim_facets", "libstdc++-v3/src/c++11/cxx11-shim_facets.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cxx11-stdexcept", "libstdc++-v3/src/c++11/cxx11-stdexcept.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "ctype_configure_char", "libstdc++-v3/config/os/generic/ctype_configure_char.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "ctype_members", "libstdc++-v3/config/locale/generic/ctype_members.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-fstream-inst", "libstdc++-v3/src/c++11/cow-fstream-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-sstream-inst", "libstdc++-v3/src/c++11/cow-sstream-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-string-inst", "libstdc++-v3/src/c++11/cow-string-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-string-io-inst", "libstdc++-v3/src/c++11/cow-string-io-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-wstring-inst", "libstdc++-v3/src/c++11/cow-wstring-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cow-wstring-io-inst", "libstdc++-v3/src/c++11/cow-wstring-io-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cxx11-locale-inst", "libstdc++-v3/src/c++11/cxx11-locale-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "cxx11-wlocale-inst", "libstdc++-v3/src/c++11/cxx11-wlocale-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "sso_string", "libstdc++-v3/src/c++11/sso_string.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "ext11-inst", "libstdc++-v3/src/c++11/ext11-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "fstream-inst", "libstdc++-v3/src/c++11/fstream-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "ios-inst", "libstdc++-v3/src/c++11/ios-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "iostream-inst", "libstdc++-v3/src/c++11/iostream-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "istream-inst", "libstdc++-v3/src/c++11/istream-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "locale-inst", "libstdc++-v3/src/c++11/locale-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "ostream-inst", "libstdc++-v3/src/c++11/ostream-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "sstream-inst", "libstdc++-v3/src/c++11/sstream-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "streambuf-inst", "libstdc++-v3/src/c++11/streambuf-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "string-inst", "libstdc++-v3/src/c++11/string-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "string-io-inst", "libstdc++-v3/src/c++11/string-io-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "wlocale-inst", "libstdc++-v3/src/c++11/wlocale-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "wstring-inst", "libstdc++-v3/src/c++11/wstring-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++11", "wstring-io-inst", "libstdc++-v3/src/c++11/wstring-io-inst.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("c++17", "fs_dir", "libstdc++-v3/src/c++17/fs_dir.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "fs_ops", "libstdc++-v3/src/c++17/fs_ops.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "fs_path", "libstdc++-v3/src/c++17/fs_path.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "memory_resource", "libstdc++-v3/src/c++17/memory_resource.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "cow-fs_dir", "libstdc++-v3/src/c++17/cow-fs_dir.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "cow-fs_ops", "libstdc++-v3/src/c++17/cow-fs_ops.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "cow-fs_path", "libstdc++-v3/src/c++17/cow-fs_path.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "ostream-inst", "libstdc++-v3/src/c++17/ostream-inst.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "string-inst", "libstdc++-v3/src/c++17/string-inst.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("c++17", "cow-string-inst", "libstdc++-v3/src/c++17/cow-string-inst.cc", ["-std=gnu++17", "-fno-implicit-templates", "-fimplicit-templates"]),
    ("compat", "compatibility", "libstdc++-v3/src/c++98/compatibility.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("compat", "compatibility-debug_list", "libstdc++-v3/src/c++98/compatibility-debug_list.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("compat", "compatibility-debug_list-2", "libstdc++-v3/src/c++98/compatibility-debug_list-2.cc", ["-std=gnu++98", "-fno-implicit-templates"]),
    ("compat", "compatibility-c++0x", "libstdc++-v3/src/c++11/compatibility-c++0x.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("compat", "compatibility-atomic-c++0x", "libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("compat", "compatibility-thread-c++0x", "libstdc++-v3/src/c++11/compatibility-thread-c++0x.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("compat", "compatibility-chrono", "libstdc++-v3/src/c++11/compatibility-chrono.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("compat", "compatibility-condvar", "libstdc++-v3/src/c++11/compatibility-condvar.cc", ["-std=gnu++11", "-fno-implicit-templates"]),
    ("filesystem", "dir", "libstdc++-v3/src/filesystem/dir.cc", ["-std=gnu++17"]),
    ("filesystem", "ops", "libstdc++-v3/src/filesystem/ops.cc", ["-std=gnu++17"]),
    ("filesystem", "path", "libstdc++-v3/src/filesystem/path.cc", ["-std=gnu++17"]),
    ("filesystem", "cow-dir", "libstdc++-v3/src/filesystem/cow-dir.cc", ["-std=gnu++17"]),
    ("filesystem", "cow-ops", "libstdc++-v3/src/filesystem/cow-ops.cc", ["-std=gnu++17"]),
    ("filesystem", "cow-path", "libstdc++-v3/src/filesystem/cow-path.cc", ["-std=gnu++17"]),
]

# Installed headers: path under include/c++/10.5.0 to archive source. The
# target headers are flattened into bits/, as in the GCC 4.7 port.
HEADER_FILES = {
    "algorithm": "libstdc++-v3/include/std/algorithm",
    "any": "libstdc++-v3/include/std/any",
    "array": "libstdc++-v3/include/std/array",
    "atomic": "libstdc++-v3/include/std/atomic",
    "bit": "libstdc++-v3/include/std/bit",
    "bitset": "libstdc++-v3/include/std/bitset",
    "charconv": "libstdc++-v3/include/std/charconv",
    "chrono": "libstdc++-v3/include/std/chrono",
    "codecvt": "libstdc++-v3/include/std/codecvt",
    "complex": "libstdc++-v3/include/std/complex",
    "concepts": "libstdc++-v3/include/std/concepts",
    "condition_variable": "libstdc++-v3/include/std/condition_variable",
    "coroutine": "libstdc++-v3/include/std/coroutine",
    "deque": "libstdc++-v3/include/std/deque",
    "execution": "libstdc++-v3/include/std/execution",
    "filesystem": "libstdc++-v3/include/std/filesystem",
    "forward_list": "libstdc++-v3/include/std/forward_list",
    "fstream": "libstdc++-v3/include/std/fstream",
    "functional": "libstdc++-v3/include/std/functional",
    "future": "libstdc++-v3/include/std/future",
    "iomanip": "libstdc++-v3/include/std/iomanip",
    "ios": "libstdc++-v3/include/std/ios",
    "iosfwd": "libstdc++-v3/include/std/iosfwd",
    "iostream": "libstdc++-v3/include/std/iostream",
    "istream": "libstdc++-v3/include/std/istream",
    "iterator": "libstdc++-v3/include/std/iterator",
    "limits": "libstdc++-v3/include/std/limits",
    "list": "libstdc++-v3/include/std/list",
    "locale": "libstdc++-v3/include/std/locale",
    "map": "libstdc++-v3/include/std/map",
    "memory": "libstdc++-v3/include/std/memory",
    "memory_resource": "libstdc++-v3/include/std/memory_resource",
    "mutex": "libstdc++-v3/include/std/mutex",
    "numbers": "libstdc++-v3/include/std/numbers",
    "numeric": "libstdc++-v3/include/std/numeric",
    "optional": "libstdc++-v3/include/std/optional",
    "ostream": "libstdc++-v3/include/std/ostream",
    "queue": "libstdc++-v3/include/std/queue",
    "random": "libstdc++-v3/include/std/random",
    "ranges": "libstdc++-v3/include/std/ranges",
    "ratio": "libstdc++-v3/include/std/ratio",
    "regex": "libstdc++-v3/include/std/regex",
    "scoped_allocator": "libstdc++-v3/include/std/scoped_allocator",
    "set": "libstdc++-v3/include/std/set",
    "shared_mutex": "libstdc++-v3/include/std/shared_mutex",
    "span": "libstdc++-v3/include/std/span",
    "sstream": "libstdc++-v3/include/std/sstream",
    "stack": "libstdc++-v3/include/std/stack",
    "stdexcept": "libstdc++-v3/include/std/stdexcept",
    "stop_token": "libstdc++-v3/include/std/stop_token",
    "streambuf": "libstdc++-v3/include/std/streambuf",
    "string": "libstdc++-v3/include/std/string",
    "string_view": "libstdc++-v3/include/std/string_view",
    "system_error": "libstdc++-v3/include/std/system_error",
    "thread": "libstdc++-v3/include/std/thread",
    "tuple": "libstdc++-v3/include/std/tuple",
    "typeindex": "libstdc++-v3/include/std/typeindex",
    "type_traits": "libstdc++-v3/include/std/type_traits",
    "unordered_map": "libstdc++-v3/include/std/unordered_map",
    "unordered_set": "libstdc++-v3/include/std/unordered_set",
    "utility": "libstdc++-v3/include/std/utility",
    "valarray": "libstdc++-v3/include/std/valarray",
    "variant": "libstdc++-v3/include/std/variant",
    "vector": "libstdc++-v3/include/std/vector",
    "version": "libstdc++-v3/include/std/version",
    "bits/algorithmfwd.h": "libstdc++-v3/include/bits/algorithmfwd.h",
    "bits/alloc_traits.h": "libstdc++-v3/include/bits/alloc_traits.h",
    "bits/allocated_ptr.h": "libstdc++-v3/include/bits/allocated_ptr.h",
    "bits/allocator.h": "libstdc++-v3/include/bits/allocator.h",
    "bits/atomic_base.h": "libstdc++-v3/include/bits/atomic_base.h",
    "bits/atomic_futex.h": "libstdc++-v3/include/bits/atomic_futex.h",
    "bits/basic_ios.h": "libstdc++-v3/include/bits/basic_ios.h",
    "bits/basic_ios.tcc": "libstdc++-v3/include/bits/basic_ios.tcc",
    "bits/basic_string.h": "libstdc++-v3/include/bits/basic_string.h",
    "bits/basic_string.tcc": "libstdc++-v3/include/bits/basic_string.tcc",
    "bits/boost_concept_check.h": "libstdc++-v3/include/bits/boost_concept_check.h",
    "bits/c++0x_warning.h": "libstdc++-v3/include/bits/c++0x_warning.h",
    "bits/char_traits.h": "libstdc++-v3/include/bits/char_traits.h",
    "bits/charconv.h": "libstdc++-v3/include/bits/charconv.h",
    "bits/codecvt.h": "libstdc++-v3/include/bits/codecvt.h",
    "bits/concept_check.h": "libstdc++-v3/include/bits/concept_check.h",
    "bits/cpp_type_traits.h": "libstdc++-v3/include/bits/cpp_type_traits.h",
    "bits/deque.tcc": "libstdc++-v3/include/bits/deque.tcc",
    "bits/enable_special_members.h": "libstdc++-v3/include/bits/enable_special_members.h",
    "bits/erase_if.h": "libstdc++-v3/include/bits/erase_if.h",
    "bits/forward_list.h": "libstdc++-v3/include/bits/forward_list.h",
    "bits/forward_list.tcc": "libstdc++-v3/include/bits/forward_list.tcc",
    "bits/fs_dir.h": "libstdc++-v3/include/bits/fs_dir.h",
    "bits/fs_fwd.h": "libstdc++-v3/include/bits/fs_fwd.h",
    "bits/fs_ops.h": "libstdc++-v3/include/bits/fs_ops.h",
    "bits/fs_path.h": "libstdc++-v3/include/bits/fs_path.h",
    "bits/fstream.tcc": "libstdc++-v3/include/bits/fstream.tcc",
    "bits/functexcept.h": "libstdc++-v3/include/bits/functexcept.h",
    "bits/functional_hash.h": "libstdc++-v3/include/bits/functional_hash.h",
    "bits/gslice.h": "libstdc++-v3/include/bits/gslice.h",
    "bits/gslice_array.h": "libstdc++-v3/include/bits/gslice_array.h",
    "bits/hashtable.h": "libstdc++-v3/include/bits/hashtable.h",
    "bits/hashtable_policy.h": "libstdc++-v3/include/bits/hashtable_policy.h",
    "bits/indirect_array.h": "libstdc++-v3/include/bits/indirect_array.h",
    "bits/invoke.h": "libstdc++-v3/include/bits/invoke.h",
    "bits/ios_base.h": "libstdc++-v3/include/bits/ios_base.h",
    "bits/istream.tcc": "libstdc++-v3/include/bits/istream.tcc",
    "bits/iterator_concepts.h": "libstdc++-v3/include/bits/iterator_concepts.h",
    "bits/list.tcc": "libstdc++-v3/include/bits/list.tcc",
    "bits/locale_classes.h": "libstdc++-v3/include/bits/locale_classes.h",
    "bits/locale_classes.tcc": "libstdc++-v3/include/bits/locale_classes.tcc",
    "bits/locale_conv.h": "libstdc++-v3/include/bits/locale_conv.h",
    "bits/locale_facets.h": "libstdc++-v3/include/bits/locale_facets.h",
    "bits/locale_facets.tcc": "libstdc++-v3/include/bits/locale_facets.tcc",
    "bits/locale_facets_nonio.h": "libstdc++-v3/include/bits/locale_facets_nonio.h",
    "bits/locale_facets_nonio.tcc": "libstdc++-v3/include/bits/locale_facets_nonio.tcc",
    "bits/localefwd.h": "libstdc++-v3/include/bits/localefwd.h",
    "bits/mask_array.h": "libstdc++-v3/include/bits/mask_array.h",
    "bits/memoryfwd.h": "libstdc++-v3/include/bits/memoryfwd.h",
    "bits/move.h": "libstdc++-v3/include/bits/move.h",
    "bits/node_handle.h": "libstdc++-v3/include/bits/node_handle.h",
    "bits/ostream.tcc": "libstdc++-v3/include/bits/ostream.tcc",
    "bits/ostream_insert.h": "libstdc++-v3/include/bits/ostream_insert.h",
    "bits/parse_numbers.h": "libstdc++-v3/include/bits/parse_numbers.h",
    "bits/postypes.h": "libstdc++-v3/include/bits/postypes.h",
    "bits/predefined_ops.h": "libstdc++-v3/include/bits/predefined_ops.h",
    "bits/ptr_traits.h": "libstdc++-v3/include/bits/ptr_traits.h",
    "bits/quoted_string.h": "libstdc++-v3/include/bits/quoted_string.h",
    "bits/random.h": "libstdc++-v3/include/bits/random.h",
    "bits/random.tcc": "libstdc++-v3/include/bits/random.tcc",
    "bits/range_access.h": "libstdc++-v3/include/bits/range_access.h",
    "bits/range_cmp.h": "libstdc++-v3/include/bits/range_cmp.h",
    "bits/ranges_algobase.h": "libstdc++-v3/include/bits/ranges_algobase.h",
    "bits/ranges_algo.h": "libstdc++-v3/include/bits/ranges_algo.h",
    "bits/ranges_uninitialized.h": "libstdc++-v3/include/bits/ranges_uninitialized.h",
    "bits/refwrap.h": "libstdc++-v3/include/bits/refwrap.h",
    "bits/regex.h": "libstdc++-v3/include/bits/regex.h",
    "bits/regex.tcc": "libstdc++-v3/include/bits/regex.tcc",
    "bits/regex_constants.h": "libstdc++-v3/include/bits/regex_constants.h",
    "bits/regex_error.h": "libstdc++-v3/include/bits/regex_error.h",
    "bits/regex_scanner.h": "libstdc++-v3/include/bits/regex_scanner.h",
    "bits/regex_scanner.tcc": "libstdc++-v3/include/bits/regex_scanner.tcc",
    "bits/regex_automaton.h": "libstdc++-v3/include/bits/regex_automaton.h",
    "bits/regex_automaton.tcc": "libstdc++-v3/include/bits/regex_automaton.tcc",
    "bits/regex_compiler.h": "libstdc++-v3/include/bits/regex_compiler.h",
    "bits/regex_compiler.tcc": "libstdc++-v3/include/bits/regex_compiler.tcc",
    "bits/regex_executor.h": "libstdc++-v3/include/bits/regex_executor.h",
    "bits/regex_executor.tcc": "libstdc++-v3/include/bits/regex_executor.tcc",
    "bits/shared_ptr.h": "libstdc++-v3/include/bits/shared_ptr.h",
    "bits/shared_ptr_atomic.h": "libstdc++-v3/include/bits/shared_ptr_atomic.h",
    "bits/shared_ptr_base.h": "libstdc++-v3/include/bits/shared_ptr_base.h",
    "bits/slice_array.h": "libstdc++-v3/include/bits/slice_array.h",
    "bits/specfun.h": "libstdc++-v3/include/bits/specfun.h",
    "bits/sstream.tcc": "libstdc++-v3/include/bits/sstream.tcc",
    "bits/std_abs.h": "libstdc++-v3/include/bits/std_abs.h",
    "bits/std_function.h": "libstdc++-v3/include/bits/std_function.h",
    "bits/std_mutex.h": "libstdc++-v3/include/bits/std_mutex.h",
    "bits/stl_algo.h": "libstdc++-v3/include/bits/stl_algo.h",
    "bits/stl_algobase.h": "libstdc++-v3/include/bits/stl_algobase.h",
    "bits/stl_bvector.h": "libstdc++-v3/include/bits/stl_bvector.h",
    "bits/stl_construct.h": "libstdc++-v3/include/bits/stl_construct.h",
    "bits/stl_deque.h": "libstdc++-v3/include/bits/stl_deque.h",
    "bits/stl_function.h": "libstdc++-v3/include/bits/stl_function.h",
    "bits/stl_heap.h": "libstdc++-v3/include/bits/stl_heap.h",
    "bits/stl_iterator.h": "libstdc++-v3/include/bits/stl_iterator.h",
    "bits/stl_iterator_base_funcs.h": "libstdc++-v3/include/bits/stl_iterator_base_funcs.h",
    "bits/stl_iterator_base_types.h": "libstdc++-v3/include/bits/stl_iterator_base_types.h",
    "bits/stl_list.h": "libstdc++-v3/include/bits/stl_list.h",
    "bits/stl_map.h": "libstdc++-v3/include/bits/stl_map.h",
    "bits/stl_multimap.h": "libstdc++-v3/include/bits/stl_multimap.h",
    "bits/stl_multiset.h": "libstdc++-v3/include/bits/stl_multiset.h",
    "bits/stl_numeric.h": "libstdc++-v3/include/bits/stl_numeric.h",
    "bits/stl_pair.h": "libstdc++-v3/include/bits/stl_pair.h",
    "bits/stl_queue.h": "libstdc++-v3/include/bits/stl_queue.h",
    "bits/stl_raw_storage_iter.h": "libstdc++-v3/include/bits/stl_raw_storage_iter.h",
    "bits/stl_relops.h": "libstdc++-v3/include/bits/stl_relops.h",
    "bits/stl_set.h": "libstdc++-v3/include/bits/stl_set.h",
    "bits/stl_stack.h": "libstdc++-v3/include/bits/stl_stack.h",
    "bits/stl_tempbuf.h": "libstdc++-v3/include/bits/stl_tempbuf.h",
    "bits/stl_tree.h": "libstdc++-v3/include/bits/stl_tree.h",
    "bits/stl_uninitialized.h": "libstdc++-v3/include/bits/stl_uninitialized.h",
    "bits/stl_vector.h": "libstdc++-v3/include/bits/stl_vector.h",
    "bits/stream_iterator.h": "libstdc++-v3/include/bits/stream_iterator.h",
    "bits/streambuf_iterator.h": "libstdc++-v3/include/bits/streambuf_iterator.h",
    "bits/streambuf.tcc": "libstdc++-v3/include/bits/streambuf.tcc",
    "bits/stringfwd.h": "libstdc++-v3/include/bits/stringfwd.h",
    "bits/string_view.tcc": "libstdc++-v3/include/bits/string_view.tcc",
    "bits/uniform_int_dist.h": "libstdc++-v3/include/bits/uniform_int_dist.h",
    "bits/unique_lock.h": "libstdc++-v3/include/bits/unique_lock.h",
    "bits/unique_ptr.h": "libstdc++-v3/include/bits/unique_ptr.h",
    "bits/unordered_map.h": "libstdc++-v3/include/bits/unordered_map.h",
    "bits/unordered_set.h": "libstdc++-v3/include/bits/unordered_set.h",
    "bits/uses_allocator.h": "libstdc++-v3/include/bits/uses_allocator.h",
    "bits/valarray_array.h": "libstdc++-v3/include/bits/valarray_array.h",
    "bits/valarray_array.tcc": "libstdc++-v3/include/bits/valarray_array.tcc",
    "bits/valarray_before.h": "libstdc++-v3/include/bits/valarray_before.h",
    "bits/valarray_after.h": "libstdc++-v3/include/bits/valarray_after.h",
    "bits/vector.tcc": "libstdc++-v3/include/bits/vector.tcc",
    "backward/auto_ptr.h": "libstdc++-v3/include/backward/auto_ptr.h",
    "backward/backward_warning.h": "libstdc++-v3/include/backward/backward_warning.h",
    "backward/binders.h": "libstdc++-v3/include/backward/binders.h",
    "backward/hash_map": "libstdc++-v3/include/backward/hash_map",
    "backward/hash_set": "libstdc++-v3/include/backward/hash_set",
    "backward/hash_fun.h": "libstdc++-v3/include/backward/hash_fun.h",
    "backward/hashtable.h": "libstdc++-v3/include/backward/hashtable.h",
    "backward/strstream": "libstdc++-v3/include/backward/strstream",
    "ext/algorithm": "libstdc++-v3/include/ext/algorithm",
    "ext/aligned_buffer.h": "libstdc++-v3/include/ext/aligned_buffer.h",
    "ext/alloc_traits.h": "libstdc++-v3/include/ext/alloc_traits.h",
    "ext/atomicity.h": "libstdc++-v3/include/ext/atomicity.h",
    "ext/bitmap_allocator.h": "libstdc++-v3/include/ext/bitmap_allocator.h",
    "ext/cast.h": "libstdc++-v3/include/ext/cast.h",
    "ext/cmath": "libstdc++-v3/include/ext/cmath",
    "ext/codecvt_specializations.h": "libstdc++-v3/include/ext/codecvt_specializations.h",
    "ext/concurrence.h": "libstdc++-v3/include/ext/concurrence.h",
    "ext/debug_allocator.h": "libstdc++-v3/include/ext/debug_allocator.h",
    "ext/enc_filebuf.h": "libstdc++-v3/include/ext/enc_filebuf.h",
    "ext/extptr_allocator.h": "libstdc++-v3/include/ext/extptr_allocator.h",
    "ext/stdio_filebuf.h": "libstdc++-v3/include/ext/stdio_filebuf.h",
    "ext/stdio_sync_filebuf.h": "libstdc++-v3/include/ext/stdio_sync_filebuf.h",
    "ext/functional": "libstdc++-v3/include/ext/functional",
    "ext/iterator": "libstdc++-v3/include/ext/iterator",
    "ext/malloc_allocator.h": "libstdc++-v3/include/ext/malloc_allocator.h",
    "ext/memory": "libstdc++-v3/include/ext/memory",
    "ext/mt_allocator.h": "libstdc++-v3/include/ext/mt_allocator.h",
    "ext/new_allocator.h": "libstdc++-v3/include/ext/new_allocator.h",
    "ext/numeric": "libstdc++-v3/include/ext/numeric",
    "ext/numeric_traits.h": "libstdc++-v3/include/ext/numeric_traits.h",
    "ext/pod_char_traits.h": "libstdc++-v3/include/ext/pod_char_traits.h",
    "ext/pointer.h": "libstdc++-v3/include/ext/pointer.h",
    "ext/pool_allocator.h": "libstdc++-v3/include/ext/pool_allocator.h",
    "ext/rb_tree": "libstdc++-v3/include/ext/rb_tree",
    "ext/random": "libstdc++-v3/include/ext/random",
    "ext/random.tcc": "libstdc++-v3/include/ext/random.tcc",
    "ext/rope": "libstdc++-v3/include/ext/rope",
    "ext/ropeimpl.h": "libstdc++-v3/include/ext/ropeimpl.h",
    "ext/slist": "libstdc++-v3/include/ext/slist",
    "ext/string_conversions.h": "libstdc++-v3/include/ext/string_conversions.h",
    "ext/throw_allocator.h": "libstdc++-v3/include/ext/throw_allocator.h",
    "ext/typelist.h": "libstdc++-v3/include/ext/typelist.h",
    "ext/type_traits.h": "libstdc++-v3/include/ext/type_traits.h",
    "ext/rc_string_base.h": "libstdc++-v3/include/ext/rc_string_base.h",
    "ext/sso_string_base.h": "libstdc++-v3/include/ext/sso_string_base.h",
    "ext/vstring.h": "libstdc++-v3/include/ext/vstring.h",
    "ext/vstring.tcc": "libstdc++-v3/include/ext/vstring.tcc",
    "ext/vstring_fwd.h": "libstdc++-v3/include/ext/vstring_fwd.h",
    "ext/vstring_util.h": "libstdc++-v3/include/ext/vstring_util.h",
    "ext/hash_set": "libstdc++-v3/include/backward/hash_set",
    "ext/hash_map": "libstdc++-v3/include/backward/hash_map",
    "tr1/array": "libstdc++-v3/include/tr1/array",
    "tr1/bessel_function.tcc": "libstdc++-v3/include/tr1/bessel_function.tcc",
    "tr1/beta_function.tcc": "libstdc++-v3/include/tr1/beta_function.tcc",
    "tr1/ccomplex": "libstdc++-v3/include/tr1/ccomplex",
    "tr1/cctype": "libstdc++-v3/include/tr1/cctype",
    "tr1/cfenv": "libstdc++-v3/include/tr1/cfenv",
    "tr1/cfloat": "libstdc++-v3/include/tr1/cfloat",
    "tr1/cinttypes": "libstdc++-v3/include/tr1/cinttypes",
    "tr1/climits": "libstdc++-v3/include/tr1/climits",
    "tr1/cmath": "libstdc++-v3/include/tr1/cmath",
    "tr1/complex": "libstdc++-v3/include/tr1/complex",
    "tr1/complex.h": "libstdc++-v3/include/tr1/complex.h",
    "tr1/cstdarg": "libstdc++-v3/include/tr1/cstdarg",
    "tr1/cstdbool": "libstdc++-v3/include/tr1/cstdbool",
    "tr1/cstdint": "libstdc++-v3/include/tr1/cstdint",
    "tr1/cstdio": "libstdc++-v3/include/tr1/cstdio",
    "tr1/cstdlib": "libstdc++-v3/include/tr1/cstdlib",
    "tr1/ctgmath": "libstdc++-v3/include/tr1/ctgmath",
    "tr1/ctime": "libstdc++-v3/include/tr1/ctime",
    "tr1/ctype.h": "libstdc++-v3/include/tr1/ctype.h",
    "tr1/cwchar": "libstdc++-v3/include/tr1/cwchar",
    "tr1/cwctype": "libstdc++-v3/include/tr1/cwctype",
    "tr1/ell_integral.tcc": "libstdc++-v3/include/tr1/ell_integral.tcc",
    "tr1/exp_integral.tcc": "libstdc++-v3/include/tr1/exp_integral.tcc",
    "tr1/fenv.h": "libstdc++-v3/include/tr1/fenv.h",
    "tr1/float.h": "libstdc++-v3/include/tr1/float.h",
    "tr1/functional": "libstdc++-v3/include/tr1/functional",
    "tr1/functional_hash.h": "libstdc++-v3/include/tr1/functional_hash.h",
    "tr1/gamma.tcc": "libstdc++-v3/include/tr1/gamma.tcc",
    "tr1/hypergeometric.tcc": "libstdc++-v3/include/tr1/hypergeometric.tcc",
    "tr1/hashtable.h": "libstdc++-v3/include/tr1/hashtable.h",
    "tr1/hashtable_policy.h": "libstdc++-v3/include/tr1/hashtable_policy.h",
    "tr1/inttypes.h": "libstdc++-v3/include/tr1/inttypes.h",
    "tr1/limits.h": "libstdc++-v3/include/tr1/limits.h",
    "tr1/math.h": "libstdc++-v3/include/tr1/math.h",
    "tr1/memory": "libstdc++-v3/include/tr1/memory",
    "tr1/modified_bessel_func.tcc": "libstdc++-v3/include/tr1/modified_bessel_func.tcc",
    "tr1/poly_hermite.tcc": "libstdc++-v3/include/tr1/poly_hermite.tcc",
    "tr1/poly_laguerre.tcc": "libstdc++-v3/include/tr1/poly_laguerre.tcc",
    "tr1/legendre_function.tcc": "libstdc++-v3/include/tr1/legendre_function.tcc",
    "tr1/random": "libstdc++-v3/include/tr1/random",
    "tr1/random.h": "libstdc++-v3/include/tr1/random.h",
    "tr1/random.tcc": "libstdc++-v3/include/tr1/random.tcc",
    "tr1/regex": "libstdc++-v3/include/tr1/regex",
    "tr1/riemann_zeta.tcc": "libstdc++-v3/include/tr1/riemann_zeta.tcc",
    "tr1/shared_ptr.h": "libstdc++-v3/include/tr1/shared_ptr.h",
    "tr1/special_function_util.h": "libstdc++-v3/include/tr1/special_function_util.h",
    "tr1/stdarg.h": "libstdc++-v3/include/tr1/stdarg.h",
    "tr1/stdbool.h": "libstdc++-v3/include/tr1/stdbool.h",
    "tr1/stdint.h": "libstdc++-v3/include/tr1/stdint.h",
    "tr1/stdio.h": "libstdc++-v3/include/tr1/stdio.h",
    "tr1/stdlib.h": "libstdc++-v3/include/tr1/stdlib.h",
    "tr1/tgmath.h": "libstdc++-v3/include/tr1/tgmath.h",
    "tr1/tuple": "libstdc++-v3/include/tr1/tuple",
    "tr1/type_traits": "libstdc++-v3/include/tr1/type_traits",
    "tr1/unordered_map": "libstdc++-v3/include/tr1/unordered_map",
    "tr1/unordered_map.h": "libstdc++-v3/include/tr1/unordered_map.h",
    "tr1/unordered_set": "libstdc++-v3/include/tr1/unordered_set",
    "tr1/unordered_set.h": "libstdc++-v3/include/tr1/unordered_set.h",
    "tr1/utility": "libstdc++-v3/include/tr1/utility",
    "tr1/wchar.h": "libstdc++-v3/include/tr1/wchar.h",
    "tr1/wctype.h": "libstdc++-v3/include/tr1/wctype.h",
    "tr2/bool_set": "libstdc++-v3/include/tr2/bool_set",
    "tr2/bool_set.tcc": "libstdc++-v3/include/tr2/bool_set.tcc",
    "tr2/dynamic_bitset": "libstdc++-v3/include/tr2/dynamic_bitset",
    "tr2/dynamic_bitset.tcc": "libstdc++-v3/include/tr2/dynamic_bitset.tcc",
    "tr2/ratio": "libstdc++-v3/include/tr2/ratio",
    "tr2/type_traits": "libstdc++-v3/include/tr2/type_traits",
    "decimal/decimal": "libstdc++-v3/include/decimal/decimal",
    "decimal/decimal.h": "libstdc++-v3/include/decimal/decimal.h",
    "experimental/algorithm": "libstdc++-v3/include/experimental/algorithm",
    "experimental/any": "libstdc++-v3/include/experimental/any",
    "experimental/array": "libstdc++-v3/include/experimental/array",
    "experimental/buffer": "libstdc++-v3/include/experimental/buffer",
    "experimental/chrono": "libstdc++-v3/include/experimental/chrono",
    "experimental/deque": "libstdc++-v3/include/experimental/deque",
    "experimental/executor": "libstdc++-v3/include/experimental/executor",
    "experimental/forward_list": "libstdc++-v3/include/experimental/forward_list",
    "experimental/functional": "libstdc++-v3/include/experimental/functional",
    "experimental/internet": "libstdc++-v3/include/experimental/internet",
    "experimental/io_context": "libstdc++-v3/include/experimental/io_context",
    "experimental/iterator": "libstdc++-v3/include/experimental/iterator",
    "experimental/list": "libstdc++-v3/include/experimental/list",
    "experimental/map": "libstdc++-v3/include/experimental/map",
    "experimental/memory": "libstdc++-v3/include/experimental/memory",
    "experimental/memory_resource": "libstdc++-v3/include/experimental/memory_resource",
    "experimental/net": "libstdc++-v3/include/experimental/net",
    "experimental/netfwd": "libstdc++-v3/include/experimental/netfwd",
    "experimental/numeric": "libstdc++-v3/include/experimental/numeric",
    "experimental/optional": "libstdc++-v3/include/experimental/optional",
    "experimental/propagate_const": "libstdc++-v3/include/experimental/propagate_const",
    "experimental/random": "libstdc++-v3/include/experimental/random",
    "experimental/ratio": "libstdc++-v3/include/experimental/ratio",
    "experimental/regex": "libstdc++-v3/include/experimental/regex",
    "experimental/set": "libstdc++-v3/include/experimental/set",
    "experimental/socket": "libstdc++-v3/include/experimental/socket",
    "experimental/source_location": "libstdc++-v3/include/experimental/source_location",
    "experimental/string": "libstdc++-v3/include/experimental/string",
    "experimental/string_view": "libstdc++-v3/include/experimental/string_view",
    "experimental/system_error": "libstdc++-v3/include/experimental/system_error",
    "experimental/timer": "libstdc++-v3/include/experimental/timer",
    "experimental/tuple": "libstdc++-v3/include/experimental/tuple",
    "experimental/type_traits": "libstdc++-v3/include/experimental/type_traits",
    "experimental/unordered_map": "libstdc++-v3/include/experimental/unordered_map",
    "experimental/unordered_set": "libstdc++-v3/include/experimental/unordered_set",
    "experimental/utility": "libstdc++-v3/include/experimental/utility",
    "experimental/vector": "libstdc++-v3/include/experimental/vector",
    "experimental/filesystem": "libstdc++-v3/include/experimental/filesystem",
    "experimental/bits/lfts_config.h": "libstdc++-v3/include/experimental/bits/lfts_config.h",
    "experimental/bits/net.h": "libstdc++-v3/include/experimental/bits/net.h",
    "experimental/bits/shared_ptr.h": "libstdc++-v3/include/experimental/bits/shared_ptr.h",
    "experimental/bits/string_view.tcc": "libstdc++-v3/include/experimental/bits/string_view.tcc",
    "experimental/bits/fs_dir.h": "libstdc++-v3/include/experimental/bits/fs_dir.h",
    "experimental/bits/fs_fwd.h": "libstdc++-v3/include/experimental/bits/fs_fwd.h",
    "experimental/bits/fs_ops.h": "libstdc++-v3/include/experimental/bits/fs_ops.h",
    "experimental/bits/fs_path.h": "libstdc++-v3/include/experimental/bits/fs_path.h",
    "cassert": "libstdc++-v3/include/c_global/cassert",
    "ccomplex": "libstdc++-v3/include/c_global/ccomplex",
    "cctype": "libstdc++-v3/include/c_global/cctype",
    "cerrno": "libstdc++-v3/include/c_global/cerrno",
    "cfenv": "libstdc++-v3/include/c_global/cfenv",
    "cfloat": "libstdc++-v3/include/c_global/cfloat",
    "cinttypes": "libstdc++-v3/include/c_global/cinttypes",
    "ciso646": "libstdc++-v3/include/c_global/ciso646",
    "climits": "libstdc++-v3/include/c_global/climits",
    "clocale": "libstdc++-v3/include/c_global/clocale",
    "cmath": "libstdc++-v3/include/c_global/cmath",
    "csetjmp": "libstdc++-v3/include/c_global/csetjmp",
    "csignal": "libstdc++-v3/include/c_global/csignal",
    "cstdalign": "libstdc++-v3/include/c_global/cstdalign",
    "cstdarg": "libstdc++-v3/include/c_global/cstdarg",
    "cstdbool": "libstdc++-v3/include/c_global/cstdbool",
    "cstddef": "libstdc++-v3/include/c_global/cstddef",
    "cstdint": "libstdc++-v3/include/c_global/cstdint",
    "cstdio": "libstdc++-v3/include/c_global/cstdio",
    "cstdlib": "libstdc++-v3/include/c_global/cstdlib",
    "cstring": "libstdc++-v3/include/c_global/cstring",
    "ctgmath": "libstdc++-v3/include/c_global/ctgmath",
    "ctime": "libstdc++-v3/include/c_global/ctime",
    "cuchar": "libstdc++-v3/include/c_global/cuchar",
    "cwchar": "libstdc++-v3/include/c_global/cwchar",
    "cwctype": "libstdc++-v3/include/c_global/cwctype",
    "complex.h": "libstdc++-v3/include/c_compatibility/complex.h",
    "fenv.h": "libstdc++-v3/include/c_compatibility/fenv.h",
    "tgmath.h": "libstdc++-v3/include/c_compatibility/tgmath.h",
    "math.h": "libstdc++-v3/include/c_compatibility/math.h",
    "stdlib.h": "libstdc++-v3/include/c_compatibility/stdlib.h",
    "debug/array": "libstdc++-v3/include/debug/array",
    "debug/assertions.h": "libstdc++-v3/include/debug/assertions.h",
    "debug/bitset": "libstdc++-v3/include/debug/bitset",
    "debug/debug.h": "libstdc++-v3/include/debug/debug.h",
    "debug/deque": "libstdc++-v3/include/debug/deque",
    "debug/formatter.h": "libstdc++-v3/include/debug/formatter.h",
    "debug/forward_list": "libstdc++-v3/include/debug/forward_list",
    "debug/functions.h": "libstdc++-v3/include/debug/functions.h",
    "debug/helper_functions.h": "libstdc++-v3/include/debug/helper_functions.h",
    "debug/list": "libstdc++-v3/include/debug/list",
    "debug/map": "libstdc++-v3/include/debug/map",
    "debug/macros.h": "libstdc++-v3/include/debug/macros.h",
    "debug/map.h": "libstdc++-v3/include/debug/map.h",
    "debug/multimap.h": "libstdc++-v3/include/debug/multimap.h",
    "debug/multiset.h": "libstdc++-v3/include/debug/multiset.h",
    "debug/safe_base.h": "libstdc++-v3/include/debug/safe_base.h",
    "debug/safe_container.h": "libstdc++-v3/include/debug/safe_container.h",
    "debug/safe_iterator.h": "libstdc++-v3/include/debug/safe_iterator.h",
    "debug/safe_iterator.tcc": "libstdc++-v3/include/debug/safe_iterator.tcc",
    "debug/safe_local_iterator.h": "libstdc++-v3/include/debug/safe_local_iterator.h",
    "debug/safe_local_iterator.tcc": "libstdc++-v3/include/debug/safe_local_iterator.tcc",
    "debug/safe_sequence.h": "libstdc++-v3/include/debug/safe_sequence.h",
    "debug/safe_sequence.tcc": "libstdc++-v3/include/debug/safe_sequence.tcc",
    "debug/safe_unordered_base.h": "libstdc++-v3/include/debug/safe_unordered_base.h",
    "debug/safe_unordered_container.h": "libstdc++-v3/include/debug/safe_unordered_container.h",
    "debug/safe_unordered_container.tcc": "libstdc++-v3/include/debug/safe_unordered_container.tcc",
    "debug/set": "libstdc++-v3/include/debug/set",
    "debug/set.h": "libstdc++-v3/include/debug/set.h",
    "debug/stl_iterator.h": "libstdc++-v3/include/debug/stl_iterator.h",
    "debug/string": "libstdc++-v3/include/debug/string",
    "debug/unordered_map": "libstdc++-v3/include/debug/unordered_map",
    "debug/unordered_set": "libstdc++-v3/include/debug/unordered_set",
    "debug/vector": "libstdc++-v3/include/debug/vector",
    "parallel/algo.h": "libstdc++-v3/include/parallel/algo.h",
    "parallel/algobase.h": "libstdc++-v3/include/parallel/algobase.h",
    "parallel/algorithm": "libstdc++-v3/include/parallel/algorithm",
    "parallel/algorithmfwd.h": "libstdc++-v3/include/parallel/algorithmfwd.h",
    "parallel/balanced_quicksort.h": "libstdc++-v3/include/parallel/balanced_quicksort.h",
    "parallel/base.h": "libstdc++-v3/include/parallel/base.h",
    "parallel/basic_iterator.h": "libstdc++-v3/include/parallel/basic_iterator.h",
    "parallel/checkers.h": "libstdc++-v3/include/parallel/checkers.h",
    "parallel/compatibility.h": "libstdc++-v3/include/parallel/compatibility.h",
    "parallel/compiletime_settings.h": "libstdc++-v3/include/parallel/compiletime_settings.h",
    "parallel/equally_split.h": "libstdc++-v3/include/parallel/equally_split.h",
    "parallel/features.h": "libstdc++-v3/include/parallel/features.h",
    "parallel/find.h": "libstdc++-v3/include/parallel/find.h",
    "parallel/find_selectors.h": "libstdc++-v3/include/parallel/find_selectors.h",
    "parallel/for_each.h": "libstdc++-v3/include/parallel/for_each.h",
    "parallel/for_each_selectors.h": "libstdc++-v3/include/parallel/for_each_selectors.h",
    "parallel/iterator.h": "libstdc++-v3/include/parallel/iterator.h",
    "parallel/list_partition.h": "libstdc++-v3/include/parallel/list_partition.h",
    "parallel/losertree.h": "libstdc++-v3/include/parallel/losertree.h",
    "parallel/merge.h": "libstdc++-v3/include/parallel/merge.h",
    "parallel/multiseq_selection.h": "libstdc++-v3/include/parallel/multiseq_selection.h",
    "parallel/multiway_merge.h": "libstdc++-v3/include/parallel/multiway_merge.h",
    "parallel/multiway_mergesort.h": "libstdc++-v3/include/parallel/multiway_mergesort.h",
    "parallel/numeric": "libstdc++-v3/include/parallel/numeric",
    "parallel/numericfwd.h": "libstdc++-v3/include/parallel/numericfwd.h",
    "parallel/omp_loop.h": "libstdc++-v3/include/parallel/omp_loop.h",
    "parallel/omp_loop_static.h": "libstdc++-v3/include/parallel/omp_loop_static.h",
    "parallel/par_loop.h": "libstdc++-v3/include/parallel/par_loop.h",
    "parallel/parallel.h": "libstdc++-v3/include/parallel/parallel.h",
    "parallel/partial_sum.h": "libstdc++-v3/include/parallel/partial_sum.h",
    "parallel/partition.h": "libstdc++-v3/include/parallel/partition.h",
    "parallel/queue.h": "libstdc++-v3/include/parallel/queue.h",
    "parallel/quicksort.h": "libstdc++-v3/include/parallel/quicksort.h",
    "parallel/random_number.h": "libstdc++-v3/include/parallel/random_number.h",
    "parallel/random_shuffle.h": "libstdc++-v3/include/parallel/random_shuffle.h",
    "parallel/search.h": "libstdc++-v3/include/parallel/search.h",
    "parallel/set_operations.h": "libstdc++-v3/include/parallel/set_operations.h",
    "parallel/settings.h": "libstdc++-v3/include/parallel/settings.h",
    "parallel/sort.h": "libstdc++-v3/include/parallel/sort.h",
    "parallel/tags.h": "libstdc++-v3/include/parallel/tags.h",
    "parallel/types.h": "libstdc++-v3/include/parallel/types.h",
    "parallel/unique_copy.h": "libstdc++-v3/include/parallel/unique_copy.h",
    "parallel/workstealing.h": "libstdc++-v3/include/parallel/workstealing.h",
    "pstl/algorithm_fwd.h": "libstdc++-v3/include/pstl/algorithm_fwd.h",
    "pstl/algorithm_impl.h": "libstdc++-v3/include/pstl/algorithm_impl.h",
    "pstl/execution_defs.h": "libstdc++-v3/include/pstl/execution_defs.h",
    "pstl/execution_impl.h": "libstdc++-v3/include/pstl/execution_impl.h",
    "pstl/glue_algorithm_defs.h": "libstdc++-v3/include/pstl/glue_algorithm_defs.h",
    "pstl/glue_algorithm_impl.h": "libstdc++-v3/include/pstl/glue_algorithm_impl.h",
    "pstl/glue_execution_defs.h": "libstdc++-v3/include/pstl/glue_execution_defs.h",
    "pstl/glue_memory_defs.h": "libstdc++-v3/include/pstl/glue_memory_defs.h",
    "pstl/glue_memory_impl.h": "libstdc++-v3/include/pstl/glue_memory_impl.h",
    "pstl/glue_numeric_defs.h": "libstdc++-v3/include/pstl/glue_numeric_defs.h",
    "pstl/glue_numeric_impl.h": "libstdc++-v3/include/pstl/glue_numeric_impl.h",
    "pstl/memory_impl.h": "libstdc++-v3/include/pstl/memory_impl.h",
    "pstl/numeric_fwd.h": "libstdc++-v3/include/pstl/numeric_fwd.h",
    "pstl/numeric_impl.h": "libstdc++-v3/include/pstl/numeric_impl.h",
    "pstl/parallel_backend.h": "libstdc++-v3/include/pstl/parallel_backend.h",
    "pstl/parallel_backend_tbb.h": "libstdc++-v3/include/pstl/parallel_backend_tbb.h",
    "pstl/parallel_backend_serial.h": "libstdc++-v3/include/pstl/parallel_backend_serial.h",
    "pstl/parallel_backend_utils.h": "libstdc++-v3/include/pstl/parallel_backend_utils.h",
    "pstl/parallel_impl.h": "libstdc++-v3/include/pstl/parallel_impl.h",
    "pstl/pstl_config.h": "libstdc++-v3/include/pstl/pstl_config.h",
    "pstl/unseq_backend_simd.h": "libstdc++-v3/include/pstl/unseq_backend_simd.h",
    "pstl/utils.h": "libstdc++-v3/include/pstl/utils.h",
    "ext/pb_ds/assoc_container.hpp": "libstdc++-v3/include/ext/pb_ds/assoc_container.hpp",
    "ext/pb_ds/exception.hpp": "libstdc++-v3/include/ext/pb_ds/exception.hpp",
    "ext/pb_ds/hash_policy.hpp": "libstdc++-v3/include/ext/pb_ds/hash_policy.hpp",
    "ext/pb_ds/list_update_policy.hpp": "libstdc++-v3/include/ext/pb_ds/list_update_policy.hpp",
    "ext/pb_ds/priority_queue.hpp": "libstdc++-v3/include/ext/pb_ds/priority_queue.hpp",
    "ext/pb_ds/tag_and_trait.hpp": "libstdc++-v3/include/ext/pb_ds/tag_and_trait.hpp",
    "ext/pb_ds/tree_policy.hpp": "libstdc++-v3/include/ext/pb_ds/tree_policy.hpp",
    "ext/pb_ds/trie_policy.hpp": "libstdc++-v3/include/ext/pb_ds/trie_policy.hpp",
    "ext/pb_ds/detail/branch_policy/branch_policy.hpp": "libstdc++-v3/include/ext/pb_ds/detail/branch_policy/branch_policy.hpp",
    "ext/pb_ds/detail/branch_policy/null_node_metadata.hpp": "libstdc++-v3/include/ext/pb_ds/detail/branch_policy/null_node_metadata.hpp",
    "ext/pb_ds/detail/branch_policy/traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/branch_policy/traits.hpp",
    "ext/pb_ds/detail/binary_heap_/binary_heap_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/binary_heap_.hpp",
    "ext/pb_ds/detail/binary_heap_/const_iterator.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/const_iterator.hpp",
    "ext/pb_ds/detail/binary_heap_/point_const_iterator.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/point_const_iterator.hpp",
    "ext/pb_ds/detail/binary_heap_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/entry_cmp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/entry_cmp.hpp",
    "ext/pb_ds/detail/binary_heap_/entry_pred.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/entry_pred.hpp",
    "ext/pb_ds/detail/binary_heap_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/find_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/info_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/iterators_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/iterators_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/policy_access_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/policy_access_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/resize_policy.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/resize_policy.hpp",
    "ext/pb_ds/detail/binary_heap_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/binary_heap_/trace_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binary_heap_/trace_fn_imps.hpp",
    "ext/pb_ds/detail/binomial_heap_base_/binomial_heap_base_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_base_/binomial_heap_base_.hpp",
    "ext/pb_ds/detail/binomial_heap_base_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_base_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/binomial_heap_base_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_base_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/binomial_heap_base_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_base_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/binomial_heap_base_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_base_/find_fn_imps.hpp",
    "ext/pb_ds/detail/binomial_heap_base_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_base_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/binomial_heap_base_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_base_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/binomial_heap_/binomial_heap_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_/binomial_heap_.hpp",
    "ext/pb_ds/detail/binomial_heap_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/binomial_heap_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/binomial_heap_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/bin_search_tree_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/bin_search_tree_.hpp",
    "ext/pb_ds/detail/bin_search_tree_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/find_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/info_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/iterators_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/iterators_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/node_iterators.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/node_iterators.hpp",
    "ext/pb_ds/detail/bin_search_tree_/point_iterators.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/point_iterators.hpp",
    "ext/pb_ds/detail/bin_search_tree_/policy_access_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/policy_access_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/r_erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/r_erase_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/rotate_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/rotate_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/bin_search_tree_/traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/bin_search_tree_/traits.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/cc_ht_map_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/cc_ht_map_.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/cmp_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/cmp_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/cond_key_dtor_entry_dealtor.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/cond_key_dtor_entry_dealtor.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/debug_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/debug_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/debug_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/debug_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/entry_list_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/entry_list_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/erase_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/erase_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/erase_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/erase_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/find_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/find_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/find_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/info_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/insert_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/insert_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/insert_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/insert_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/iterators_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/iterators_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/policy_access_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/policy_access_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/resize_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/resize_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/resize_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/resize_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/resize_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/resize_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/size_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/size_fn_imps.hpp",
    "ext/pb_ds/detail/cc_hash_table_map_/trace_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cc_hash_table_map_/trace_fn_imps.hpp",
    "ext/pb_ds/detail/cond_dealtor.hpp": "libstdc++-v3/include/ext/pb_ds/detail/cond_dealtor.hpp",
    "ext/pb_ds/detail/container_base_dispatch.hpp": "libstdc++-v3/include/ext/pb_ds/detail/container_base_dispatch.hpp",
    "ext/pb_ds/detail/eq_fn/eq_by_less.hpp": "libstdc++-v3/include/ext/pb_ds/detail/eq_fn/eq_by_less.hpp",
    "ext/pb_ds/detail/eq_fn/hash_eq_fn.hpp": "libstdc++-v3/include/ext/pb_ds/detail/eq_fn/hash_eq_fn.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/debug_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/debug_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/debug_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/debug_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/erase_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/erase_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/erase_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/erase_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/find_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/find_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/find_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/find_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/find_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/gp_ht_map_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/gp_ht_map_.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/info_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/insert_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/insert_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/insert_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/insert_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/iterator_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/iterator_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/policy_access_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/policy_access_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/resize_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/resize_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/resize_no_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/resize_no_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/resize_store_hash_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/resize_store_hash_fn_imps.hpp",
    "ext/pb_ds/detail/gp_hash_table_map_/trace_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/gp_hash_table_map_/trace_fn_imps.hpp",
    "ext/pb_ds/detail/hash_fn/direct_mask_range_hashing_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/direct_mask_range_hashing_imp.hpp",
    "ext/pb_ds/detail/hash_fn/direct_mod_range_hashing_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/direct_mod_range_hashing_imp.hpp",
    "ext/pb_ds/detail/hash_fn/linear_probe_fn_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/linear_probe_fn_imp.hpp",
    "ext/pb_ds/detail/hash_fn/mask_based_range_hashing.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/mask_based_range_hashing.hpp",
    "ext/pb_ds/detail/hash_fn/mod_based_range_hashing.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/mod_based_range_hashing.hpp",
    "ext/pb_ds/detail/hash_fn/probe_fn_base.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/probe_fn_base.hpp",
    "ext/pb_ds/detail/hash_fn/quadratic_probe_fn_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/quadratic_probe_fn_imp.hpp",
    "ext/pb_ds/detail/hash_fn/ranged_hash_fn.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/ranged_hash_fn.hpp",
    "ext/pb_ds/detail/hash_fn/ranged_probe_fn.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/ranged_probe_fn.hpp",
    "ext/pb_ds/detail/hash_fn/sample_probe_fn.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/sample_probe_fn.hpp",
    "ext/pb_ds/detail/hash_fn/sample_ranged_hash_fn.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/sample_ranged_hash_fn.hpp",
    "ext/pb_ds/detail/hash_fn/sample_ranged_probe_fn.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/sample_ranged_probe_fn.hpp",
    "ext/pb_ds/detail/hash_fn/sample_range_hashing.hpp": "libstdc++-v3/include/ext/pb_ds/detail/hash_fn/sample_range_hashing.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/const_iterator.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/const_iterator.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/point_const_iterator.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/point_const_iterator.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/info_fn_imps.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/iterators_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/iterators_fn_imps.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/left_child_next_sibling_heap_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/left_child_next_sibling_heap_.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/node.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/node.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/policy_access_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/policy_access_fn_imps.hpp",
    "ext/pb_ds/detail/left_child_next_sibling_heap_/trace_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/left_child_next_sibling_heap_/trace_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_map_/constructor_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/constructor_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_map_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_map_/entry_metadata_base.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/entry_metadata_base.hpp",
    "ext/pb_ds/detail/list_update_map_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_map_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/find_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_map_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/info_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_map_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_map_/iterators_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/iterators_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_map_/lu_map_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/lu_map_.hpp",
    "ext/pb_ds/detail/list_update_map_/trace_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_map_/trace_fn_imps.hpp",
    "ext/pb_ds/detail/list_update_policy/lu_counter_metadata.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_policy/lu_counter_metadata.hpp",
    "ext/pb_ds/detail/list_update_policy/sample_update_policy.hpp": "libstdc++-v3/include/ext/pb_ds/detail/list_update_policy/sample_update_policy.hpp",
    "ext/pb_ds/detail/debug_map_base.hpp": "libstdc++-v3/include/ext/pb_ds/detail/debug_map_base.hpp",
    "ext/pb_ds/detail/ov_tree_map_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/ov_tree_map_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/ov_tree_map_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/ov_tree_map_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/info_fn_imps.hpp",
    "ext/pb_ds/detail/ov_tree_map_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/ov_tree_map_/iterators_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/iterators_fn_imps.hpp",
    "ext/pb_ds/detail/ov_tree_map_/node_iterators.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/node_iterators.hpp",
    "ext/pb_ds/detail/ov_tree_map_/ov_tree_map_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/ov_tree_map_.hpp",
    "ext/pb_ds/detail/ov_tree_map_/policy_access_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/policy_access_fn_imps.hpp",
    "ext/pb_ds/detail/ov_tree_map_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/ov_tree_map_/traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/ov_tree_map_/traits.hpp",
    "ext/pb_ds/detail/pairing_heap_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pairing_heap_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/pairing_heap_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pairing_heap_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/pairing_heap_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pairing_heap_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/pairing_heap_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pairing_heap_/find_fn_imps.hpp",
    "ext/pb_ds/detail/pairing_heap_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pairing_heap_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/pairing_heap_/pairing_heap_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pairing_heap_/pairing_heap_.hpp",
    "ext/pb_ds/detail/pairing_heap_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pairing_heap_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/find_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/info_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/insert_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/insert_join_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/iterators_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/iterators_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/pat_trie_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/pat_trie_.hpp",
    "ext/pb_ds/detail/pat_trie_/pat_trie_base.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/pat_trie_base.hpp",
    "ext/pb_ds/detail/pat_trie_/policy_access_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/policy_access_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/r_erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/r_erase_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/rotate_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/rotate_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/split_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/split_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/synth_access_traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/synth_access_traits.hpp",
    "ext/pb_ds/detail/pat_trie_/trace_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/trace_fn_imps.hpp",
    "ext/pb_ds/detail/pat_trie_/traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/traits.hpp",
    "ext/pb_ds/detail/pat_trie_/update_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/pat_trie_/update_fn_imps.hpp",
    "ext/pb_ds/detail/priority_queue_base_dispatch.hpp": "libstdc++-v3/include/ext/pb_ds/detail/priority_queue_base_dispatch.hpp",
    "ext/pb_ds/detail/rb_tree_map_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/rb_tree_map_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/rb_tree_map_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/rb_tree_map_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/find_fn_imps.hpp",
    "ext/pb_ds/detail/rb_tree_map_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/info_fn_imps.hpp",
    "ext/pb_ds/detail/rb_tree_map_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/rb_tree_map_/node.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/node.hpp",
    "ext/pb_ds/detail/rb_tree_map_/rb_tree_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/rb_tree_.hpp",
    "ext/pb_ds/detail/rb_tree_map_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/rb_tree_map_/traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rb_tree_map_/traits.hpp",
    "ext/pb_ds/detail/rc_binomial_heap_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rc_binomial_heap_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/rc_binomial_heap_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rc_binomial_heap_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/rc_binomial_heap_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rc_binomial_heap_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/rc_binomial_heap_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rc_binomial_heap_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/rc_binomial_heap_/rc_binomial_heap_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rc_binomial_heap_/rc_binomial_heap_.hpp",
    "ext/pb_ds/detail/rc_binomial_heap_/rc.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rc_binomial_heap_/rc.hpp",
    "ext/pb_ds/detail/rc_binomial_heap_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rc_binomial_heap_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/rc_binomial_heap_/trace_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/rc_binomial_heap_/trace_fn_imps.hpp",
    "ext/pb_ds/detail/resize_policy/cc_hash_max_collision_check_resize_trigger_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/cc_hash_max_collision_check_resize_trigger_imp.hpp",
    "ext/pb_ds/detail/resize_policy/hash_exponential_size_policy_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/hash_exponential_size_policy_imp.hpp",
    "ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_imp.hpp",
    "ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_size_base.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_size_base.hpp",
    "ext/pb_ds/detail/resize_policy/hash_prime_size_policy_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/hash_prime_size_policy_imp.hpp",
    "ext/pb_ds/detail/resize_policy/hash_standard_resize_policy_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/hash_standard_resize_policy_imp.hpp",
    "ext/pb_ds/detail/resize_policy/sample_resize_policy.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/sample_resize_policy.hpp",
    "ext/pb_ds/detail/resize_policy/sample_resize_trigger.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/sample_resize_trigger.hpp",
    "ext/pb_ds/detail/resize_policy/sample_size_policy.hpp": "libstdc++-v3/include/ext/pb_ds/detail/resize_policy/sample_size_policy.hpp",
    "ext/pb_ds/detail/splay_tree_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/splay_tree_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/splay_tree_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/splay_tree_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/find_fn_imps.hpp",
    "ext/pb_ds/detail/splay_tree_/info_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/info_fn_imps.hpp",
    "ext/pb_ds/detail/splay_tree_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/splay_tree_/node.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/node.hpp",
    "ext/pb_ds/detail/splay_tree_/splay_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/splay_fn_imps.hpp",
    "ext/pb_ds/detail/splay_tree_/splay_tree_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/splay_tree_.hpp",
    "ext/pb_ds/detail/splay_tree_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/splay_tree_/traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/splay_tree_/traits.hpp",
    "ext/pb_ds/detail/standard_policies.hpp": "libstdc++-v3/include/ext/pb_ds/detail/standard_policies.hpp",
    "ext/pb_ds/detail/thin_heap_/constructors_destructor_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/thin_heap_/constructors_destructor_fn_imps.hpp",
    "ext/pb_ds/detail/thin_heap_/debug_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/thin_heap_/debug_fn_imps.hpp",
    "ext/pb_ds/detail/thin_heap_/erase_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/thin_heap_/erase_fn_imps.hpp",
    "ext/pb_ds/detail/thin_heap_/find_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/thin_heap_/find_fn_imps.hpp",
    "ext/pb_ds/detail/thin_heap_/insert_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/thin_heap_/insert_fn_imps.hpp",
    "ext/pb_ds/detail/thin_heap_/split_join_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/thin_heap_/split_join_fn_imps.hpp",
    "ext/pb_ds/detail/thin_heap_/thin_heap_.hpp": "libstdc++-v3/include/ext/pb_ds/detail/thin_heap_/thin_heap_.hpp",
    "ext/pb_ds/detail/thin_heap_/trace_fn_imps.hpp": "libstdc++-v3/include/ext/pb_ds/detail/thin_heap_/trace_fn_imps.hpp",
    "ext/pb_ds/detail/tree_policy/node_metadata_selector.hpp": "libstdc++-v3/include/ext/pb_ds/detail/tree_policy/node_metadata_selector.hpp",
    "ext/pb_ds/detail/tree_policy/order_statistics_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/tree_policy/order_statistics_imp.hpp",
    "ext/pb_ds/detail/tree_policy/sample_tree_node_update.hpp": "libstdc++-v3/include/ext/pb_ds/detail/tree_policy/sample_tree_node_update.hpp",
    "ext/pb_ds/detail/tree_trace_base.hpp": "libstdc++-v3/include/ext/pb_ds/detail/tree_trace_base.hpp",
    "ext/pb_ds/detail/trie_policy/node_metadata_selector.hpp": "libstdc++-v3/include/ext/pb_ds/detail/trie_policy/node_metadata_selector.hpp",
    "ext/pb_ds/detail/trie_policy/order_statistics_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/trie_policy/order_statistics_imp.hpp",
    "ext/pb_ds/detail/trie_policy/prefix_search_node_update_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/trie_policy/prefix_search_node_update_imp.hpp",
    "ext/pb_ds/detail/trie_policy/sample_trie_access_traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/trie_policy/sample_trie_access_traits.hpp",
    "ext/pb_ds/detail/trie_policy/sample_trie_node_update.hpp": "libstdc++-v3/include/ext/pb_ds/detail/trie_policy/sample_trie_node_update.hpp",
    "ext/pb_ds/detail/trie_policy/trie_string_access_traits_imp.hpp": "libstdc++-v3/include/ext/pb_ds/detail/trie_policy/trie_string_access_traits_imp.hpp",
    "ext/pb_ds/detail/trie_policy/trie_policy_base.hpp": "libstdc++-v3/include/ext/pb_ds/detail/trie_policy/trie_policy_base.hpp",
    "ext/pb_ds/detail/types_traits.hpp": "libstdc++-v3/include/ext/pb_ds/detail/types_traits.hpp",
    "ext/pb_ds/detail/type_utils.hpp": "libstdc++-v3/include/ext/pb_ds/detail/type_utils.hpp",
    "ext/pb_ds/detail/unordered_iterator/const_iterator.hpp": "libstdc++-v3/include/ext/pb_ds/detail/unordered_iterator/const_iterator.hpp",
    "ext/pb_ds/detail/unordered_iterator/point_const_iterator.hpp": "libstdc++-v3/include/ext/pb_ds/detail/unordered_iterator/point_const_iterator.hpp",
    "ext/pb_ds/detail/unordered_iterator/iterator.hpp": "libstdc++-v3/include/ext/pb_ds/detail/unordered_iterator/iterator.hpp",
    "ext/pb_ds/detail/unordered_iterator/point_iterator.hpp": "libstdc++-v3/include/ext/pb_ds/detail/unordered_iterator/point_iterator.hpp",
    "bits/ctype_base.h": "libstdc++-v3/config/os/generic/ctype_base.h",
    "bits/ctype_inline.h": "libstdc++-v3/config/os/generic/ctype_inline.h",
    "bits/os_defines.h": "libstdc++-v3/config/os/generic/os_defines.h",
    "bits/atomic_word.h": "libstdc++-v3/config/cpu/generic/atomic_word.h",
    "bits/cxxabi_tweaks.h": "libstdc++-v3/config/cpu/generic/cxxabi_tweaks.h",
    "bits/cpu_defines.h": "libstdc++-v3/config/cpu/generic/cpu_defines.h",
    "bits/error_constants.h": "libstdc++-v3/config/os/generic/error_constants.h",
    "bits/stdc++.h": "libstdc++-v3/include/precompiled/stdc++.h",
    "bits/stdtr1c++.h": "libstdc++-v3/include/precompiled/stdtr1c++.h",
    "bits/extc++.h": "libstdc++-v3/include/precompiled/extc++.h",
    "bits/opt_random.h": "libstdc++-v3/config/cpu/i486/opt/bits/opt_random.h",
    "ext/opt_random.h": "libstdc++-v3/config/cpu/i486/opt/ext/opt_random.h",
    "compare": "libstdc++-v3/libsupc++/compare",
    "cxxabi.h": "libstdc++-v3/libsupc++/cxxabi.h",
    "exception": "libstdc++-v3/libsupc++/exception",
    "initializer_list": "libstdc++-v3/libsupc++/initializer_list",
    "new": "libstdc++-v3/libsupc++/new",
    "typeinfo": "libstdc++-v3/libsupc++/typeinfo",
    "bits/atomic_lockfree_defines.h": "libstdc++-v3/libsupc++/atomic_lockfree_defines.h",
    "bits/cxxabi_forced.h": "libstdc++-v3/libsupc++/cxxabi_forced.h",
    "bits/exception_defines.h": "libstdc++-v3/libsupc++/exception_defines.h",
    "bits/exception_ptr.h": "libstdc++-v3/libsupc++/exception_ptr.h",
    "bits/hash_bytes.h": "libstdc++-v3/libsupc++/hash_bytes.h",
    "bits/nested_exception.h": "libstdc++-v3/libsupc++/nested_exception.h",
    "bits/exception.h": "libstdc++-v3/libsupc++/exception.h",
    "bits/cxxabi_init_exception.h": "libstdc++-v3/libsupc++/cxxabi_init_exception.h",
    "bits/basic_file.h": "libstdc++-v3/config/io/basic_file_stdio.h",
    "bits/c++allocator.h": "libstdc++-v3/config/allocator/new_allocator_base.h",
    "bits/c++io.h": "libstdc++-v3/config/io/c_io_stdio.h",
    "bits/c++locale.h": "libstdc++-v3/config/locale/generic/c_locale.h",
    "bits/messages_members.h": "libstdc++-v3/config/locale/generic/messages_members.h",
    "bits/time_members.h": "libstdc++-v3/config/locale/generic/time_members.h",
}
