# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# pyconfig.h decisions for CPython 3.14.7 on x86_64 Linux with musl 1.2.5 and
# GCC 13.5. The target is a fully static binary with no dynamic module loading,
# a default release build with pymalloc and mimalloc, threads and IPv6. Each
# entry records what a native configure run would compute for that target,
# but where a comment names the choice that overrides it.
#
# pyconfig.h.in has 651 plain "#undef" lines. The indented
# AC_USE_SYSTEM_EXTENSIONS block and WORDS_BIGENDIAN add 22 more, and
# _DARWIN_C_SOURCE, _NETBSD_SOURCE and _XOPEN_SOURCE each appear twice, for
# 670 distinct names. The three lists cover each distinct name once.
#
# PYCONFIG_ON entries are defined to 1, PYCONFIG_VALUES entries to the given C
# text, and PYCONFIG_OFF entries stay undefined.

PYCONFIG_ON = [
    "DOUBLE_IS_LITTLE_ENDIAN_IEEE754",
    "ENABLE_IPV6",
    "HAVE_ACCEPT",
    "HAVE_ACCEPT4",
    "HAVE_ACOSH",
    "HAVE_ADDRINFO",
    "HAVE_ALARM",
    "HAVE_ALLOCA_H",
    "HAVE_ASINH",
    "HAVE_ASM_TYPES_H",
    "HAVE_ATANH",
    "HAVE_BIND",
    "HAVE_BIND_TEXTDOMAIN_CODESET",
    "HAVE_BUILTIN_ATOMIC",
    "HAVE_CHMOD",
    "HAVE_CHOWN",
    # PY_CHECK_FUNC needs a prototype; musl declares chroot, getpagesize, prlimit and memfd_create under _GNU_SOURCE.
    "HAVE_CHROOT",
    "HAVE_CLOCK",
    "HAVE_CLOCK_GETRES",
    "HAVE_CLOCK_GETTIME",
    "HAVE_CLOCK_NANOSLEEP",
    "HAVE_CLOCK_SETTIME",
    "HAVE_CLOCK_T",
    # Run probe passes with GCC; USE_COMPUTED_GOTOS stays undefined and ceval.c turns them on from this.
    "HAVE_COMPUTED_GOTOS",
    "HAVE_CONFSTR",
    "HAVE_CONNECT",
    "HAVE_COPY_FILE_RANGE",
    "HAVE_CTERMID",
    "HAVE_DECL_RTLD_GLOBAL",
    "HAVE_DECL_RTLD_LAZY",
    "HAVE_DECL_RTLD_LOCAL",
    "HAVE_DECL_RTLD_NODELETE",
    "HAVE_DECL_RTLD_NOLOAD",
    "HAVE_DECL_RTLD_NOW",
    # musl utmp.h defines UT_NAMESIZE 32; AC_CHECK_DECLS also defines HAVE_UT_NAMESIZE.
    "HAVE_DECL_UT_NAMESIZE",
    "HAVE_DEVICE_MACROS",
    # AC_CHECK_FILE on the build host; a cross build must preset ac_cv_file__dev_ptmx=yes.
    "HAVE_DEV_PTMX",
    "HAVE_DIRENT_D_TYPE",
    "HAVE_DIRENT_H",
    "HAVE_DIRFD",
    # musl libc.a has a weak dladdr stub that returns 0, so the link probe passes; getpath.c only calls it under Py_ENABLE_SHARED.
    "HAVE_DLADDR",
    "HAVE_DLFCN_H",
    # musl libc.a implements it for static binaries; only _ctypes reads it.
    "HAVE_DL_ITERATE_PHDR",
    "HAVE_DUP",
    "HAVE_DUP2",
    "HAVE_DUP3",
    "HAVE_ENDIAN_H",
    "HAVE_EPOLL",
    "HAVE_EPOLL_CREATE1",
    "HAVE_ERF",
    "HAVE_ERFC",
    "HAVE_ERRNO_H",
    "HAVE_EVENTFD",
    "HAVE_EXECV",
    "HAVE_EXPLICIT_BZERO",
    "HAVE_EXPM1",
    "HAVE_FACCESSAT",
    "HAVE_FCHDIR",
    "HAVE_FCHMOD",
    "HAVE_FCHMODAT",
    "HAVE_FCHOWN",
    "HAVE_FCHOWNAT",
    "HAVE_FCNTL_H",
    "HAVE_FDATASYNC",
    "HAVE_FDOPENDIR",
    "HAVE_FEXECVE",
    "HAVE_FLOCK",
    "HAVE_FORK",
    "HAVE_FORKPTY",
    "HAVE_FPATHCONF",
    "HAVE_FSEEKO",
    "HAVE_FSTATAT",
    "HAVE_FSTATVFS",
    "HAVE_FSYNC",
    "HAVE_FTELLO",
    "HAVE_FTIME",
    "HAVE_FTRUNCATE",
    "HAVE_FUTIMENS",
    "HAVE_FUTIMES",
    "HAVE_FUTIMESAT",
    "HAVE_GAI_STRERROR",
    "HAVE_GCC_ASM_FOR_X64",
    # fnstcw/fldcw still assemble on x86_64, so the link probe passes even though doubles use SSE2.
    "HAVE_GCC_ASM_FOR_X87",
    "HAVE_GCC_UINT128_T",
    "HAVE_GETADDRINFO",
    "HAVE_GETC_UNLOCKED",
    "HAVE_GETEGID",
    "HAVE_GETENTROPY",
    "HAVE_GETEUID",
    "HAVE_GETGID",
    "HAVE_GETGRENT",
    "HAVE_GETGRGID",
    "HAVE_GETGRGID_R",
    "HAVE_GETGRNAM_R",
    "HAVE_GETGROUPLIST",
    "HAVE_GETGROUPS",
    "HAVE_GETHOSTBYADDR",
    "HAVE_GETHOSTBYNAME",
    "HAVE_GETHOSTBYNAME_R",
    # musl declares the glibc-style 6-argument gethostbyname_r under _GNU_SOURCE.
    "HAVE_GETHOSTBYNAME_R_6_ARG",
    "HAVE_GETHOSTNAME",
    "HAVE_GETITIMER",
    "HAVE_GETLOADAVG",
    "HAVE_GETLOGIN",
    "HAVE_GETLOGIN_R",
    "HAVE_GETNAMEINFO",
    "HAVE_GETPAGESIZE",
    "HAVE_GETPEERNAME",
    "HAVE_GETPGID",
    "HAVE_GETPGRP",
    "HAVE_GETPID",
    "HAVE_GETPPID",
    "HAVE_GETPRIORITY",
    "HAVE_GETPROTOBYNAME",
    "HAVE_GETPWENT",
    "HAVE_GETPWNAM_R",
    "HAVE_GETPWUID",
    "HAVE_GETPWUID_R",
    "HAVE_GETRANDOM",
    "HAVE_GETRANDOM_SYSCALL",
    "HAVE_GETRESGID",
    "HAVE_GETRESUID",
    "HAVE_GETRUSAGE",
    "HAVE_GETSERVBYNAME",
    "HAVE_GETSERVBYPORT",
    "HAVE_GETSID",
    "HAVE_GETSOCKNAME",
    "HAVE_GETSPENT",
    "HAVE_GETSPNAM",
    "HAVE_GETUID",
    "HAVE_GRANTPT",
    "HAVE_GRP_H",
    "HAVE_HSTRERROR",
    "HAVE_HTOLE64",
    "HAVE_IF_NAMEINDEX",
    "HAVE_INET_ATON",
    "HAVE_INET_NTOA",
    "HAVE_INET_PTON",
    "HAVE_INITGROUPS",
    "HAVE_INTTYPES_H",
    "HAVE_KILL",
    "HAVE_KILLPG",
    "HAVE_LANGINFO_H",
    "HAVE_LCHOWN",
    # musl ships libintl.h and gettext in libc.a; WITH_LIBINTL stays off because there is no -lintl.
    "HAVE_LIBINTL_H",
    "HAVE_LINK",
    "HAVE_LINKAT",
    "HAVE_LINK_H",
    "HAVE_LINUX_AUXVEC_H",
    "HAVE_LINUX_CAN_BCM_H",
    "HAVE_LINUX_CAN_H",
    "HAVE_LINUX_CAN_J1939_H",
    "HAVE_LINUX_CAN_RAW_FD_FRAMES",
    "HAVE_LINUX_CAN_RAW_H",
    "HAVE_LINUX_CAN_RAW_JOIN_FILTERS",
    "HAVE_LINUX_FS_H",
    "HAVE_LINUX_LIMITS_H",
    "HAVE_LINUX_MEMFD_H",
    # Compiles against the UAPI headers under the default includes; no CPython source reads it.
    "HAVE_LINUX_NETFILTER_IPV4_H",
    "HAVE_LINUX_NETLINK_H",
    "HAVE_LINUX_QRTR_H",
    "HAVE_LINUX_RANDOM_H",
    "HAVE_LINUX_SCHED_H",
    "HAVE_LINUX_SOUNDCARD_H",
    "HAVE_LINUX_TIPC_H",
    "HAVE_LINUX_VM_SOCKETS_H",
    "HAVE_LINUX_WAIT_H",
    "HAVE_LISTEN",
    "HAVE_LOCKF",
    "HAVE_LOG1P",
    "HAVE_LOG2",
    # AC_SEARCH_LIBS finds login_tty in libc first, so configure adds no -lutil. openpty and forkpty behave the same.
    "HAVE_LOGIN_TTY",
    "HAVE_LONG_DOUBLE",
    "HAVE_LSTAT",
    "HAVE_LUTIMES",
    "HAVE_MADVISE",
    "HAVE_MAKEDEV",
    "HAVE_MBRTOWC",
    "HAVE_MEMFD_CREATE",
    "HAVE_MEMRCHR",
    "HAVE_MKDIRAT",
    "HAVE_MKFIFO",
    "HAVE_MKFIFOAT",
    "HAVE_MKNOD",
    "HAVE_MKNODAT",
    "HAVE_MKTIME",
    "HAVE_MMAP",
    "HAVE_MREMAP",
    "HAVE_NANOSLEEP",
    "HAVE_NETDB_H",
    "HAVE_NETINET_IN_H",
    "HAVE_NETPACKET_PACKET_H",
    "HAVE_NET_ETHERNET_H",
    "HAVE_NET_IF_H",
    "HAVE_NICE",
    "HAVE_OPENAT",
    "HAVE_OPENDIR",
    "HAVE_OPENPTY",
    "HAVE_PATHCONF",
    "HAVE_PAUSE",
    "HAVE_PIPE",
    "HAVE_PIPE2",
    "HAVE_POLL",
    "HAVE_POLL_H",
    "HAVE_POSIX_FADVISE",
    "HAVE_POSIX_FALLOCATE",
    "HAVE_POSIX_OPENPT",
    "HAVE_POSIX_SPAWN",
    "HAVE_POSIX_SPAWNP",
    "HAVE_PREAD",
    "HAVE_PREADV",
    "HAVE_PREADV2",
    "HAVE_PRLIMIT",
    "HAVE_PROCESS_VM_READV",
    "HAVE_PROTOTYPES",
    "HAVE_PTHREAD_CONDATTR_SETCLOCK",
    "HAVE_PTHREAD_GETATTR_NP",
    "HAVE_PTHREAD_GETCPUCLOCKID",
    "HAVE_PTHREAD_GETNAME_NP",
    "HAVE_PTHREAD_H",
    "HAVE_PTHREAD_KILL",
    "HAVE_PTHREAD_SETNAME_NP",
    "HAVE_PTHREAD_SIGMASK",
    "HAVE_PTSNAME",
    "HAVE_PTSNAME_R",
    "HAVE_PTY_H",
    "HAVE_PWRITE",
    "HAVE_PWRITEV",
    "HAVE_PWRITEV2",
    "HAVE_READLINK",
    "HAVE_READLINKAT",
    "HAVE_READV",
    "HAVE_REALPATH",
    "HAVE_RECVFROM",
    "HAVE_RENAMEAT",
    "HAVE_SCHED_GET_PRIORITY_MAX",
    "HAVE_SCHED_H",
    "HAVE_SCHED_RR_GET_INTERVAL",
    "HAVE_SCHED_SETAFFINITY",
    "HAVE_SCHED_SETPARAM",
    "HAVE_SCHED_SETSCHEDULER",
    "HAVE_SEM_GETVALUE",
    "HAVE_SEM_OPEN",
    "HAVE_SEM_TIMEDWAIT",
    "HAVE_SEM_UNLINK",
    "HAVE_SENDFILE",
    "HAVE_SENDTO",
    "HAVE_SETEGID",
    "HAVE_SETEUID",
    "HAVE_SETGID",
    "HAVE_SETGROUPS",
    "HAVE_SETHOSTNAME",
    "HAVE_SETITIMER",
    "HAVE_SETJMP_H",
    "HAVE_SETLOCALE",
    "HAVE_SETNS",
    "HAVE_SETPGID",
    "HAVE_SETPGRP",
    "HAVE_SETPRIORITY",
    "HAVE_SETREGID",
    "HAVE_SETRESGID",
    "HAVE_SETRESUID",
    "HAVE_SETREUID",
    "HAVE_SETSID",
    "HAVE_SETSOCKOPT",
    "HAVE_SETUID",
    "HAVE_SETVBUF",
    "HAVE_SHADOW_H",
    "HAVE_SHM_OPEN",
    "HAVE_SHM_UNLINK",
    "HAVE_SHUTDOWN",
    "HAVE_SIGACTION",
    "HAVE_SIGALTSTACK",
    "HAVE_SIGFILLSET",
    # musl exposes si_band as a macro into the siginfo union, which the member probe accepts.
    "HAVE_SIGINFO_T_SI_BAND",
    "HAVE_SIGINTERRUPT",
    "HAVE_SIGNAL_H",
    "HAVE_SIGPENDING",
    "HAVE_SIGRELSE",
    "HAVE_SIGTIMEDWAIT",
    "HAVE_SIGWAIT",
    "HAVE_SIGWAITINFO",
    "HAVE_SNPRINTF",
    "HAVE_SOCKADDR_ALG",
    "HAVE_SOCKADDR_STORAGE",
    "HAVE_SOCKET",
    "HAVE_SOCKETPAIR",
    "HAVE_SOCKLEN_T",
    "HAVE_SPAWN_H",
    "HAVE_SPLICE",
    "HAVE_SSIZE_T",
    "HAVE_STATVFS",
    "HAVE_STAT_TV_NSEC",
    "HAVE_STDINT_H",
    "HAVE_STDIO_H",
    "HAVE_STDLIB_H",
    # GCC 13 stdatomic.h links without -latomic; WITH_MIMALLOC defaults to this result.
    "HAVE_STD_ATOMIC",
    "HAVE_STRFTIME",
    "HAVE_STRINGS_H",
    "HAVE_STRING_H",
    "HAVE_STRLCPY",
    # musl still ships stropts.h with the I_* constants, so fcntl exposes them. glibc dropped the header.
    "HAVE_STROPTS_H",
    "HAVE_STRSIGNAL",
    "HAVE_STRUCT_PASSWD_PW_GECOS",
    "HAVE_STRUCT_PASSWD_PW_PASSWD",
    "HAVE_STRUCT_STAT_ST_BLKSIZE",
    "HAVE_STRUCT_STAT_ST_BLOCKS",
    "HAVE_STRUCT_STAT_ST_RDEV",
    # musl renames __tm_zone to tm_zone under _GNU_SOURCE, which confdefs.h defines.
    "HAVE_STRUCT_TM_TM_ZONE",
    "HAVE_SYMLINK",
    "HAVE_SYMLINKAT",
    "HAVE_SYNC",
    "HAVE_SYSCONF",
    "HAVE_SYSEXITS_H",
    "HAVE_SYSLOG_H",
    "HAVE_SYSTEM",
    "HAVE_SYS_AUXV_H",
    "HAVE_SYS_EPOLL_H",
    "HAVE_SYS_EVENTFD_H",
    "HAVE_SYS_FILE_H",
    "HAVE_SYS_IOCTL_H",
    "HAVE_SYS_MMAN_H",
    "HAVE_SYS_PARAM_H",
    # musl's sys/poll.h is a #warning redirect to poll.h; a warning does not fail the probe. selectmodule.c prefers poll.h.
    "HAVE_SYS_POLL_H",
    "HAVE_SYS_RANDOM_H",
    "HAVE_SYS_RESOURCE_H",
    "HAVE_SYS_SELECT_H",
    "HAVE_SYS_SENDFILE_H",
    "HAVE_SYS_SOCKET_H",
    # musl's sys/soundcard.h forwards to linux/soundcard.h from the UAPI headers.
    "HAVE_SYS_SOUNDCARD_H",
    "HAVE_SYS_STATVFS_H",
    "HAVE_SYS_STAT_H",
    "HAVE_SYS_SYSCALL_H",
    "HAVE_SYS_SYSMACROS_H",
    "HAVE_SYS_TIMERFD_H",
    "HAVE_SYS_TIMES_H",
    "HAVE_SYS_TIME_H",
    "HAVE_SYS_TYPES_H",
    "HAVE_SYS_UIO_H",
    "HAVE_SYS_UN_H",
    "HAVE_SYS_UTSNAME_H",
    "HAVE_SYS_WAIT_H",
    "HAVE_SYS_XATTR_H",
    "HAVE_TCGETPGRP",
    "HAVE_TCSETPGRP",
    "HAVE_TEMPNAM",
    "HAVE_TERMIOS_H",
    "HAVE_TIMEGM",
    "HAVE_TIMERFD_CREATE",
    "HAVE_TIMES",
    "HAVE_TMPFILE",
    "HAVE_TMPNAM",
    "HAVE_TM_ZONE",
    "HAVE_TRUNCATE",
    "HAVE_TTYNAME_R",
    "HAVE_UMASK",
    "HAVE_UNAME",
    "HAVE_UNISTD_H",
    "HAVE_UNLINKAT",
    "HAVE_UNLOCKPT",
    "HAVE_UNSHARE",
    "HAVE_UTIMENSAT",
    "HAVE_UTIMES",
    "HAVE_UTIME_H",
    "HAVE_UTMP_H",
    "HAVE_UT_NAMESIZE",
    "HAVE_VFORK",
    "HAVE_WAIT",
    "HAVE_WAIT3",
    "HAVE_WAIT4",
    "HAVE_WAITID",
    "HAVE_WAITPID",
    "HAVE_WCHAR_H",
    "HAVE_WCSCOLL",
    "HAVE_WCSFTIME",
    "HAVE_WCSXFRM",
    "HAVE_WMEMCMP",
    # Run probe; musl parses POSIX TZ rules and fills tm_zone. A cross build defaults this off.
    "HAVE_WORKING_TZSET",
    "HAVE_WRITEV",
    "HAVE___UINT128_T",
    # Autoconf 2.72 AC_HEADER_MAJOR only checks that sys/sysmacros.h exists, after sys/mkdev.h fails.
    "MAJOR_IN_SYSMACROS",
    "PTHREAD_KEY_T_IS_COMPATIBLE_WITH_INT",
    # Run probe; musl accepts PTHREAD_SCOPE_SYSTEM. A cross build defaults this off.
    "PTHREAD_SYSTEM_SCHED_SUPPORTED",
    "PY_COERCE_C_LOCALE",
    # configure defines this to 1 whether or not OpenSSL exists.
    "PY_SSL_DEFAULT_CIPHERS",
    # --with-remote-debug defaults to yes; it is active on Linux because HAVE_PROCESS_VM_READV is set.
    "Py_REMOTE_DEBUG",
    # A size, listed here only because its value is 1.
    "SIZEOF__BOOL",
    "STDC_HEADERS",
    "SYS_SELECT_WITH_SYS_TIME",
    "WITH_DECIMAL_CONTEXTVAR",
    "WITH_DOC_STRINGS",
    "WITH_MIMALLOC",
    "WITH_PYMALLOC",
    # AC_USE_SYSTEM_EXTENSIONS always defines this, _GNU_SOURCE, _OPENBSD_SOURCE, _TANDEM_SOURCE and the __STDC_WANT_* macros.
    "_ALL_SOURCE",
    # Appears twice in pyconfig.h.in, from Python's AC_DEFINE and from AC_USE_SYSTEM_EXTENSIONS; both give 1.
    "_DARWIN_C_SOURCE",
    "_GNU_SOURCE",
    "_HPUX_ALT_XOPEN_SOCKET_API",
    "_LARGEFILE_SOURCE",
    # Appears twice in pyconfig.h.in, from Python's AC_DEFINE and from AC_USE_SYSTEM_EXTENSIONS; both give 1.
    "_NETBSD_SOURCE",
    "_OPENBSD_SOURCE",
    "_POSIX_PTHREAD_SEMANTICS",
    "_Py_STACK_GROWS_DOWN",
    # pthread_create links with no flags on musl, so ac_cv_pthread_is_default=yes defines this and leaves _POSIX_THREADS off.
    "_REENTRANT",
    "_TANDEM_SOURCE",
    "_XOPEN_SOURCE_EXTENDED",
    # Python defines this for FreeBSD on every platform.
    "__BSD_VISIBLE",
    # AC_USE_SYSTEM_EXTENSIONS defines it once a test compile with it succeeds, which it does on musl.
    "__EXTENSIONS__",
    "__STDC_WANT_IEC_60559_ATTRIBS_EXT__",
    "__STDC_WANT_IEC_60559_BFP_EXT__",
    "__STDC_WANT_IEC_60559_DFP_EXT__",
    "__STDC_WANT_IEC_60559_EXT__",
    "__STDC_WANT_IEC_60559_FUNCS_EXT__",
    "__STDC_WANT_IEC_60559_TYPES_EXT__",
    "__STDC_WANT_LIB_EXT2__",
    "__STDC_WANT_MATH_SPEC_FUNCS__",
]

PYCONFIG_VALUES = {
    "ALIGNOF_LONG": "8",
    "ALIGNOF_MAX_ALIGN_T": "16",
    "ALIGNOF_SIZE_T": "8",
    # AC_CHECK_DECLS writes 0 when a macro is missing; musl dlfcn.h lacks RTLD_DEEPBIND and RTLD_MEMBER.
    "HAVE_DECL_RTLD_DEEPBIND": "0",
    "HAVE_DECL_RTLD_MEMBER": "0",
    "PY_BUILTIN_HASHLIB_HASHES": "\"md5,sha1,sha2,sha3,blake2\"",
    # The PEP 11 table only lists linux-gnu hosts, so x86_64-*-linux-musl/gcc gets 0.
    "PY_SUPPORT_TIER": "0",
    "RETSIGTYPE": "void",
    "SIZEOF_DOUBLE": "8",
    "SIZEOF_FLOAT": "4",
    # musl's fpos_t is a 16-byte union.
    "SIZEOF_FPOS_T": "16",
    "SIZEOF_INT": "4",
    "SIZEOF_LONG": "8",
    # x87 80-bit long double padded to 16 bytes.
    "SIZEOF_LONG_DOUBLE": "16",
    "SIZEOF_LONG_LONG": "8",
    "SIZEOF_OFF_T": "8",
    "SIZEOF_PID_T": "4",
    # musl's pthread_key_t is unsigned, so PTHREAD_KEY_T_IS_COMPATIBLE_WITH_INT holds.
    "SIZEOF_PTHREAD_KEY_T": "4",
    "SIZEOF_PTHREAD_T": "8",
    "SIZEOF_SHORT": "2",
    "SIZEOF_SIZE_T": "8",
    "SIZEOF_TIME_T": "8",
    "SIZEOF_UINTPTR_T": "8",
    "SIZEOF_VOID_P": "8",
    "SIZEOF_WCHAR_T": "4",
    # configure always defines it; musl ignores it because off_t is always 64-bit.
    "_FILE_OFFSET_BITS": "64",
    "_POSIX_C_SOURCE": "200809L",
    # Non-framework builds define it to an empty string literal.
    "_PYTHONFRAMEWORK": "\"\"",
    "_PYTHREAD_NAME_MAXLEN": "15",
    # Native run probe sees musl's 128 KiB default; the link must also pass -Wl,-z,stack-size=1048576.
    "_Py_LINKER_THREAD_STACK_SIZE": "1048576",
    # Appears twice in pyconfig.h.in; the AC_USE_SYSTEM_EXTENSIONS 500 fallback does not fire since musl wchar.h has mbstate_t.
    "_XOPEN_SOURCE": "700",
}

PYCONFIG_OFF = [
    "AC_APPLE_UNIVERSAL_BUILD",
    "AIX_BUILDDATE",
    "AIX_GENUINE_CPLUSPLUS",
    "ALT_SOABI",
    "ANDROID_API_LEVEL",
    "DOUBLE_IS_ARM_MIXED_ENDIAN_IEEE754",
    "DOUBLE_IS_BIG_ENDIAN_IEEE754",
    "GETPGRP_HAVE_ARG",
    # Run probe passes on x86_64; a cross build defaults to yes, which would switch str hashing to FNV.
    "HAVE_ALIGNED_REQUIRED",
    "HAVE_ALTZONE",
    # Probed only after execinfo.h, link.h or dlfcn.h is found; musl has the last two but neither function.
    "HAVE_BACKTRACE",
    "HAVE_BLUETOOTH_BLUETOOTH_H",
    "HAVE_BLUETOOTH_H",
    "HAVE_BROKEN_MBSTOWCS",
    "HAVE_BROKEN_NICE",
    "HAVE_BROKEN_PIPE_BUF",
    "HAVE_BROKEN_POLL",
    "HAVE_BROKEN_POSIX_SEMAPHORES",
    "HAVE_BROKEN_PTHREAD_SIGMASK",
    # Run probe passes on musl; a cross build defaults this on.
    "HAVE_BROKEN_SEM_GETVALUE",
    "HAVE_BROKEN_UNSETENV",
    "HAVE_BZLIB_H",
    "HAVE_CHFLAGS",
    "HAVE_CLOSEFROM",
    "HAVE_CLOSE_RANGE",
    "HAVE_CONIO_H",
    "HAVE_CTERMID_R",
    "HAVE_CURSES_ESCDELAY",
    "HAVE_CURSES_FILTER",
    "HAVE_CURSES_GETMOUSE",
    "HAVE_CURSES_H",
    "HAVE_CURSES_HAS_KEY",
    "HAVE_CURSES_IMMEDOK",
    "HAVE_CURSES_IS_PAD",
    "HAVE_CURSES_IS_TERM_RESIZED",
    "HAVE_CURSES_RESIZETERM",
    "HAVE_CURSES_RESIZE_TERM",
    "HAVE_CURSES_SET_ESCDELAY",
    "HAVE_CURSES_SET_TABSIZE",
    "HAVE_CURSES_SYNCOK",
    "HAVE_CURSES_TABSIZE",
    "HAVE_CURSES_TYPEAHEAD",
    "HAVE_CURSES_USE_ENV",
    "HAVE_CURSES_WCHGAT",
    "HAVE_DB_H",
    # AC_STRUCT_TIMEZONE only probes tzname when struct tm lacks tm_zone, so this stays undefined, not 0.
    "HAVE_DECL_TZNAME",
    "HAVE_DEV_PTC",
    "HAVE_DIRECT_H",
    "HAVE_DLADDR1",
    # Forced off with ac_cv_func_dlopen=no. musl libc.a has a dlopen stub, so plain configure would pick dynload_shlib.o.
    "HAVE_DLOPEN",
    "HAVE_DYLD_SHARED_CACHE_CONTAINS_PATH",
    # Off because DYNLOADFILE is dynload_stub.o once dlopen is off.
    "HAVE_DYNAMIC_LOADING",
    "HAVE_EDITLINE_READLINE_H",
    "HAVE_EXECINFO_H",
    "HAVE_EXPLICIT_MEMSET",
    "HAVE_FDWALK",
    "HAVE_FFI_CLOSURE_ALLOC",
    "HAVE_FFI_PREP_CIF_VAR",
    "HAVE_FFI_PREP_CLOSURE_LOC",
    "HAVE_FORK1",
    "HAVE_FSEEK64",
    "HAVE_FTELL64",
    "HAVE_GCC_ASM_FOR_MC68881",
    "HAVE_GDBM_DASH_NDBM_H",
    "HAVE_GDBM_H",
    "HAVE_GDBM_NDBM_H",
    "HAVE_GETHOSTBYNAME_R_3_ARG",
    "HAVE_GETHOSTBYNAME_R_5_ARG",
    "HAVE_GETWD",
    "HAVE_GLIBC_MEMMOVE_BUG",
    "HAVE_IO_H",
    "HAVE_IPA_PURE_CONST_BUG",
    "HAVE_KQUEUE",
    # off_t and long are both 8 bytes on LP64, so off_t is not wider.
    "HAVE_LARGEFILE_SUPPORT",
    "HAVE_LCHFLAGS",
    # configure.ac skips the lchmod probe when MACHDEP is linux, even though musl has it.
    "HAVE_LCHMOD",
    "HAVE_LIBDB",
    # Forced off with ac_cv_lib_dl_dlopen=no. musl's empty libdl.a would make configure say yes, but no C source reads it.
    "HAVE_LIBDL",
    "HAVE_LIBDLD",
    "HAVE_LIBIEEE",
    "HAVE_LIBSENDFILE",
    "HAVE_LIBSQLITE3",
    "HAVE_LIBUTIL_H",
    "HAVE_LZMA_H",
    "HAVE_MAXLOGNAME",
    "HAVE_MINIX_CONFIG_H",
    "HAVE_NCURSES",
    "HAVE_NCURSESW",
    "HAVE_NCURSESW_CURSES_H",
    "HAVE_NCURSESW_NCURSES_H",
    "HAVE_NCURSESW_PANEL_H",
    "HAVE_NCURSES_CURSES_H",
    "HAVE_NCURSES_H",
    "HAVE_NCURSES_NCURSES_H",
    "HAVE_NCURSES_PANEL_H",
    "HAVE_NDBM_H",
    "HAVE_NDIR_H",
    "HAVE_NETCAN_CAN_H",
    "HAVE_NETLINK_NETLINK_H",
    "HAVE_NON_UNICODE_WCHAR_T_REPRESENTATION",
    "HAVE_PANEL",
    "HAVE_PANELW",
    "HAVE_PANEL_H",
    "HAVE_PLOCK",
    "HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSEFROM_NP",
    "HAVE_PROCESS_H",
    "HAVE_PTHREAD_COND_TIMEDWAIT_RELATIVE_NP",
    "HAVE_PTHREAD_DESTRUCTOR",
    "HAVE_PTHREAD_GET_NAME_NP",
    "HAVE_PTHREAD_INIT",
    "HAVE_PTHREAD_SET_NAME_NP",
    "HAVE_PTHREAD_STUBS",
    "HAVE_READLINE_READLINE_H",
    "HAVE_RL_APPEND_HISTORY",
    "HAVE_RL_CATCH_SIGNAL",
    "HAVE_RL_COMPDISP_FUNC_T",
    "HAVE_RL_COMPLETION_APPEND_CHARACTER",
    "HAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK",
    "HAVE_RL_COMPLETION_MATCHES",
    "HAVE_RL_COMPLETION_SUPPRESS_APPEND",
    "HAVE_RL_PRE_INPUT_HOOK",
    "HAVE_RL_RESIZE_TERMINAL",
    "HAVE_RTPSPAWN",
    "HAVE_SEM_CLOCKWAIT",
    "HAVE_SOCKADDR_SA_LEN",
    "HAVE_STAT_TV_NSEC2",
    "HAVE_STRUCT_STAT_ST_BIRTHTIME",
    "HAVE_STRUCT_STAT_ST_FLAGS",
    "HAVE_STRUCT_STAT_ST_GEN",
    "HAVE_SYSCTLBYNAME",
    "HAVE_SYS_AUDIOIO_H",
    "HAVE_SYS_BSDTTY_H",
    "HAVE_SYS_DEVPOLL_H",
    # AC_HEADER_DIRENT stops at dirent.h, so sys/dir.h is never probed even though musl ships it.
    "HAVE_SYS_DIR_H",
    "HAVE_SYS_ENDIAN_H",
    "HAVE_SYS_EVENT_H",
    "HAVE_SYS_KERN_CONTROL_H",
    "HAVE_SYS_LOADAVG_H",
    "HAVE_SYS_LOCK_H",
    "HAVE_SYS_MEMFD_H",
    "HAVE_SYS_MKDEV_H",
    "HAVE_SYS_MODEM_H",
    "HAVE_SYS_NDIR_H",
    "HAVE_SYS_PIDFD_H",
    "HAVE_SYS_SYSCTL_H",
    "HAVE_SYS_SYS_DOMAIN_H",
    "HAVE_SYS_TERMIO_H",
    "HAVE_TERM_H",
    "HAVE_TMPNAM_R",
    "HAVE_TZNAME",
    # wchar_t is a signed int on x86_64 musl.
    "HAVE_USABLE_WCHAR_T",
    "HAVE_UTIL_H",
    "HAVE_UUID_CREATE",
    "HAVE_UUID_ENC_BE",
    "HAVE_UUID_GENERATE_TIME_SAFE",
    "HAVE_UUID_GENERATE_TIME_SAFE_STABLE_MAC",
    "HAVE_UUID_H",
    "HAVE_UUID_UUID_H",
    "HAVE_ZDICT_H",
    "HAVE_ZLIB_COPY",
    "HAVE_ZLIB_H",
    "HAVE_ZSTD_H",
    "HAVE__GETPTY",
    "MAJOR_IN_MKDEV",
    "MVWDELCH_IS_EXPRESSION",
    # configure strips every PACKAGE_ define from confdefs.h.
    "PACKAGE_BUGREPORT",
    "PACKAGE_NAME",
    "PACKAGE_STRING",
    "PACKAGE_TARNAME",
    "PACKAGE_URL",
    "PACKAGE_VERSION",
    # Run probe needs a working sem_open on the build host, which means a mounted /dev/shm.
    "POSIX_SEMAPHORES_NOT_ENABLED",
    # Only --enable-big-digits sets it; pyport.h then picks 30.
    "PYLONG_BITS_IN_DIGIT",
    # configure enables it only for the x86_64-linux-gnu and aarch64-linux-gnu triplets.
    "PY_HAVE_PERF_TRAMPOLINE",
    "PY_SQLITE_ENABLE_LOAD_EXTENSION",
    "PY_SQLITE_HAVE_SERIALIZE",
    "PY_SSL_DEFAULT_CIPHER_STRING",
    "Py_DEBUG",
    "Py_ENABLE_SHARED",
    "Py_GIL_DISABLED",
    # Only --with-hash-algorithm sets it; pyhash.h then picks SipHash13.
    "Py_HASH_ALGORITHM",
    "Py_RL_STARTUP_HOOK_TAKES_ARGS",
    "Py_STATS",
    "Py_SUNOS_VERSION",
    "Py_TAIL_CALL_INTERP",
    "Py_TRACE_REFS",
    "SETPGRP_HAVE_ARG",
    "SIGNED_RIGHT_SHIFT_ZERO_FILLS",
    # configure only sets it on Darwin and iOS; musl gets its size from _Py_LINKER_THREAD_STACK_SIZE and PT_GNU_STACK.
    "THREAD_STACK_SIZE",
    # clock_gettime is in libc, so configure never falls back to -lrt.
    "TIMEMODULE_LIB",
    "TM_IN_SYS_TIME",
    # Only an explicit --with-computed-gotos or --without-computed-gotos sets it.
    "USE_COMPUTED_GOTOS",
    "WINDOW_HAS_FLAGS",
    "WITH_DTRACE",
    "WITH_DYLD",
    "WITH_EDITLINE",
    # musl has no libintl.a, so the -lintl textdomain probe fails; gettext comes from libc.
    "WITH_LIBINTL",
    "WITH_NEXT_FRAMEWORK",
    "WITH_VALGRIND",
    "WORDS_BIGENDIAN",
    # Run probe; x86_64 does double math in SSE2 registers.
    "X87_DOUBLE_ROUNDING",
    "_BSD_SOURCE",
    "_INCLUDE__STDC_A1_SOURCE",
    "_LARGE_FILES",
    # _MINIX, _POSIX_SOURCE and _POSIX_1_SOURCE need minix/config.h.
    "_MINIX",
    "_POSIX_1_SOURCE",
    "_POSIX_SOURCE",
    # Only defined on the fallback path where unistd.h lacks it; musl takes the pthread_is_default path.
    "_POSIX_THREADS",
    "_Py_FFI_SUPPORT_C_COMPLEX",
    # GCC accepts the SIMD flags, but only the portable Blake2 objects are
    # built, as sources.bzl lists them.
    "_Py_HACL_CAN_COMPILE_VEC128",
    "_Py_HACL_CAN_COMPILE_VEC256",
    "_WASI_EMULATED_GETPID",
    "_WASI_EMULATED_PROCESS_CLOCKS",
    "_WASI_EMULATED_SIGNAL",
    "clock_t",
    "const",
    "gid_t",
    "mode_t",
    "off_t",
    "pid_t",
    "signed",
    "size_t",
    "socklen_t",
    "uid_t",
]
