# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# The object lists of Makefile.pre.in, as C sources without their extension,
# and the modules of Modules/Setup.bootstrap.in and Setup.stdlib.in that the
# interpreter builds in.

PARSER_SOURCES = [
    "Parser/token",
    "Parser/myreadline",
]

PEGEN_SOURCES = [
    "Parser/pegen",
    "Parser/pegen_errors",
    "Parser/action_helpers",
    "Parser/parser",
    "Parser/string_parser",
    "Parser/peg_api",
]

TOKENIZER_SOURCES = [
    "Parser/lexer/buffer",
    "Parser/lexer/lexer",
    "Parser/lexer/state",
    "Parser/tokenizer/file_tokenizer",
    "Parser/tokenizer/readline_tokenizer",
    "Parser/tokenizer/string_tokenizer",
    "Parser/tokenizer/utf8_tokenizer",
    "Parser/tokenizer/helpers",
]

OBJECT_SOURCES = [
    "Objects/abstract",
    "Objects/boolobject",
    "Objects/bytes_methods",
    "Objects/bytearrayobject",
    "Objects/bytesobject",
    "Objects/call",
    "Objects/capsule",
    "Objects/cellobject",
    "Objects/classobject",
    "Objects/codeobject",
    "Objects/complexobject",
    "Objects/descrobject",
    "Objects/enumobject",
    "Objects/exceptions",
    "Objects/genericaliasobject",
    "Objects/genobject",
    "Objects/fileobject",
    "Objects/floatobject",
    "Objects/frameobject",
    "Objects/funcobject",
    "Objects/interpolationobject",
    "Objects/iterobject",
    "Objects/listobject",
    "Objects/longobject",
    "Objects/dictobject",
    "Objects/odictobject",
    "Objects/memoryobject",
    "Objects/methodobject",
    "Objects/moduleobject",
    "Objects/namespaceobject",
    "Objects/object",
    "Objects/obmalloc",
    "Objects/picklebufobject",
    "Objects/rangeobject",
    "Objects/setobject",
    "Objects/sliceobject",
    "Objects/structseq",
    "Objects/templateobject",
    "Objects/tupleobject",
    "Objects/typeobject",
    "Objects/typevarobject",
    "Objects/unicodeobject",
    "Objects/unicodectype",
    "Objects/unionobject",
    "Objects/weakrefobject",
]

PYTHON_SOURCES = [
    "Python/_contextvars",
    "Python/_warnings",
    "Python/Python-ast",
    "Python/Python-tokenize",
    "Python/asdl",
    "Python/assemble",
    "Python/ast",
    "Python/ast_preprocess",
    "Python/ast_unparse",
    "Python/bltinmodule",
    "Python/brc",
    "Python/ceval",
    "Python/codecs",
    "Python/codegen",
    "Python/compile",
    "Python/context",
    "Python/critical_section",
    "Python/crossinterp",
    "Python/dynamic_annotations",
    "Python/errors",
    "Python/flowgraph",
    "Python/frame",
    "Python/frozenmain",
    "Python/future",
    "Python/gc",
    "Python/gc_free_threading",
    "Python/gc_gil",
    "Python/getargs",
    "Python/getcompiler",
    "Python/getcopyright",
    "Python/getplatform",
    "Python/getversion",
    "Python/ceval_gil",
    "Python/hamt",
    "Python/hashtable",
    "Python/import",
    "Python/importdl",
    "Python/index_pool",
    "Python/initconfig",
    "Python/interpconfig",
    "Python/instrumentation",
    "Python/instruction_sequence",
    "Python/intrinsics",
    "Python/jit",
    "Python/legacy_tracing",
    "Python/lock",
    "Python/marshal",
    "Python/modsupport",
    "Python/mysnprintf",
    "Python/mystrtoul",
    "Python/object_stack",
    "Python/optimizer",
    "Python/optimizer_analysis",
    "Python/optimizer_symbols",
    "Python/parking_lot",
    "Python/pathconfig",
    "Python/preconfig",
    "Python/pyarena",
    "Python/pyctype",
    "Python/pyfpe",
    "Python/pyhash",
    "Python/pylifecycle",
    "Python/pymath",
    "Python/pystate",
    "Python/pythonrun",
    "Python/pytime",
    "Python/qsbr",
    "Python/bootstrap_hash",
    "Python/specialize",
    "Python/stackrefs",
    "Python/structmember",
    "Python/symtable",
    "Python/sysmodule",
    "Python/thread",
    "Python/traceback",
    "Python/tracemalloc",
    "Python/uniqueid",
    "Python/getopt",
    "Python/pystrcmp",
    "Python/pystrtod",
    "Python/pystrhex",
    "Python/dtoa",
    "Python/formatter_unicode",
    "Python/fileutils",
    "Python/suggestions",
    "Python/perf_trampoline",
    "Python/perf_jit_trampoline",
    "Python/remote_debugging",
]

LIBMPDEC_SOURCES = [
    "Modules/_decimal/libmpdec/basearith",
    "Modules/_decimal/libmpdec/constants",
    "Modules/_decimal/libmpdec/context",
    "Modules/_decimal/libmpdec/convolute",
    "Modules/_decimal/libmpdec/crt",
    "Modules/_decimal/libmpdec/difradix2",
    "Modules/_decimal/libmpdec/fnt",
    "Modules/_decimal/libmpdec/fourstep",
    "Modules/_decimal/libmpdec/io",
    "Modules/_decimal/libmpdec/mpalloc",
    "Modules/_decimal/libmpdec/mpdecimal",
    "Modules/_decimal/libmpdec/numbertheory",
    "Modules/_decimal/libmpdec/sixstep",
    "Modules/_decimal/libmpdec/transpose",
]

LIBEXPAT_SOURCES = [
    "Modules/expat/xmlparse",
    "Modules/expat/xmlrole",
    "Modules/expat/xmltok",
]

# Modules/Setup.bootstrap.in, by module name, as sources under Modules/.
BOOTSTRAP_MODULES = {
    "atexit": ["atexitmodule"],
    "faulthandler": ["faulthandler"],
    "posix": ["posixmodule"],
    "_signal": ["signalmodule"],
    "_tracemalloc": ["_tracemalloc"],
    "_suggestions": ["_suggestions"],
    "_datetime": ["_datetimemodule"],
    "_codecs": ["_codecsmodule"],
    "_collections": ["_collectionsmodule"],
    "errno": ["errnomodule"],
    "_io": [
        "_io/_iomodule",
        "_io/iobase",
        "_io/fileio",
        "_io/bytesio",
        "_io/bufferedio",
        "_io/textio",
        "_io/stringio",
    ],
    "itertools": ["itertoolsmodule"],
    "_sre": ["_sre/sre"],
    "_sysconfig": ["_sysconfig"],
    "_thread": ["_threadmodule"],
    "time": ["timemodule"],
    "_types": ["_typesmodule"],
    "_typing": ["_typingmodule"],
    "_weakref": ["_weakref"],
    "_abc": ["_abc"],
    "_functools": ["_functoolsmodule"],
    "_locale": ["_localemodule"],
    "_opcode": ["_opcode"],
    "_operator": ["_operator"],
    "_stat": ["_stat"],
    "_symtable": ["symtablemodule"],
    "pwd": ["pwdmodule"],
}

# The Setup.stdlib.in modules configure enables here, with zlib the only
# external library. bz2, lzma, zstd, dbm, readline, ctypes, curses, sqlite3,
# ssl, hashlib (OpenSSL), uuid and tkinter need libraries the final GCC
# stage does not build; the test modules are left out.
STDLIB_MODULES = {
    "array": ["arraymodule"],
    "_asyncio": ["_asynciomodule"],
    "_bisect": ["_bisectmodule"],
    "_csv": ["_csv"],
    "_heapq": ["_heapqmodule"],
    "_json": ["_json"],
    "_lsprof": [
        "_lsprof",
        "rotatingtree",
    ],
    "_pickle": ["_pickle"],
    "_queue": ["_queuemodule"],
    "_random": ["_randommodule"],
    "_remote_debugging": ["_remote_debugging_module"],
    "_struct": ["_struct"],
    "_interpreters": ["_interpretersmodule"],
    "_interpchannels": ["_interpchannelsmodule"],
    "_interpqueues": ["_interpqueuesmodule"],
    "_zoneinfo": ["_zoneinfo"],
    "math": ["mathmodule"],
    "cmath": ["cmathmodule"],
    "_statistics": ["_statisticsmodule"],
    "_decimal": ["_decimal/_decimal"],
    "binascii": ["binascii"],
    "zlib": ["zlibmodule"],
    "_md5": ["md5module"],
    "_sha1": ["sha1module"],
    "_sha2": ["sha2module"],
    "_sha3": ["sha3module"],
    "_blake2": ["blake2module"],
    "_hmac": ["hmacmodule"],
    "pyexpat": ["pyexpat"],
    "_elementtree": ["_elementtree"],
    "_codecs_cn": ["cjkcodecs/_codecs_cn"],
    "_codecs_hk": ["cjkcodecs/_codecs_hk"],
    "_codecs_iso2022": ["cjkcodecs/_codecs_iso2022"],
    "_codecs_jp": ["cjkcodecs/_codecs_jp"],
    "_codecs_kr": ["cjkcodecs/_codecs_kr"],
    "_codecs_tw": ["cjkcodecs/_codecs_tw"],
    "_multibytecodec": ["cjkcodecs/multibytecodec"],
    "unicodedata": ["unicodedata"],
    "fcntl": ["fcntlmodule"],
    "grp": ["grpmodule"],
    "mmap": ["mmapmodule"],
    "_posixsubprocess": ["_posixsubprocess"],
    "resource": ["resource"],
    "select": ["selectmodule"],
    "_socket": ["socketmodule"],
    "syslog": ["syslogmodule"],
    "termios": ["termios"],
    "_posixshmem": ["_multiprocessing/posixshmem"],
    "_multiprocessing": [
        "_multiprocessing/multiprocessing",
        "_multiprocessing/semaphore",
    ],
}

# The HACL* objects the hash modules and _hmac link, without the optional
# SIMD Blake2 implementations.
LIBHACL_SOURCES = [
    "Modules/_hacl/Hacl_Hash_MD5",
    "Modules/_hacl/Hacl_Hash_SHA1",
    "Modules/_hacl/Hacl_Hash_SHA2",
    "Modules/_hacl/Hacl_Hash_SHA3",
    "Modules/_hacl/Hacl_Hash_Blake2s",
    "Modules/_hacl/Hacl_Hash_Blake2b",
    "Modules/_hacl/Lib_Memzero0",
    "Modules/_hacl/Hacl_HMAC",
    "Modules/_hacl/Hacl_Streaming_HMAC",
]

# The modules Makefile.pre.in freezes, with their sources. getpath is frozen
# by hand there; the rest follow Tools/build/freeze_modules.py.
FROZEN_MODULES = {
    "getpath": "Modules/getpath.py",
    "importlib._bootstrap": "Lib/importlib/_bootstrap.py",
    "importlib._bootstrap_external": "Lib/importlib/_bootstrap_external.py",
    "zipimport": "Lib/zipimport.py",
    "abc": "Lib/abc.py",
    "codecs": "Lib/codecs.py",
    "io": "Lib/io.py",
    "_collections_abc": "Lib/_collections_abc.py",
    "_sitebuiltins": "Lib/_sitebuiltins.py",
    "genericpath": "Lib/genericpath.py",
    "ntpath": "Lib/ntpath.py",
    "posixpath": "Lib/posixpath.py",
    "os": "Lib/os.py",
    "site": "Lib/site.py",
    "stat": "Lib/stat.py",
    "importlib.util": "Lib/importlib/util.py",
    "importlib.machinery": "Lib/importlib/machinery.py",
    "runpy": "Lib/runpy.py",
    "__hello__": "Lib/__hello__.py",
    "__phello__": "Lib/__phello__/__init__.py",
    "__phello__.ham": "Lib/__phello__/ham/__init__.py",
    "__phello__.ham.eggs": "Lib/__phello__/ham/eggs.py",
    "__phello__.spam": "Lib/__phello__/spam.py",
    "frozen_only": "Tools/freeze/flag.py",
}

# The standard library, by top-level entry of Lib/, without the test suite,

# the Tk GUI modules and ensurepip, which bundles a pip wheel.

LIB_ENTRIES = [
    "__future__.py",
    "__hello__.py",
    "__phello__",
    "_aix_support.py",
    "_android_support.py",
    "_apple_support.py",
    "_ast_unparse.py",
    "_collections_abc.py",
    "_colorize.py",
    "_compat_pickle.py",
    "_ios_support.py",
    "_markupbase.py",
    "_opcode_metadata.py",
    "_osx_support.py",
    "_py_abc.py",
    "_py_warnings.py",
    "_pydatetime.py",
    "_pydecimal.py",
    "_pyio.py",
    "_pylong.py",
    "_pyrepl",
    "_sitebuiltins.py",
    "_strptime.py",
    "_threading_local.py",
    "_weakrefset.py",
    "abc.py",
    "annotationlib.py",
    "antigravity.py",
    "argparse.py",
    "ast.py",
    "asyncio",
    "base64.py",
    "bdb.py",
    "bisect.py",
    "bz2.py",
    "cProfile.py",
    "calendar.py",
    "cmd.py",
    "code.py",
    "codecs.py",
    "codeop.py",
    "collections",
    "colorsys.py",
    "compileall.py",
    "compression",
    "concurrent",
    "configparser.py",
    "contextlib.py",
    "contextvars.py",
    "copy.py",
    "copyreg.py",
    "csv.py",
    "ctypes",
    "curses",
    "dataclasses.py",
    "datetime.py",
    "dbm",
    "decimal.py",
    "difflib.py",
    "dis.py",
    "doctest.py",
    "email",
    "encodings",
    "enum.py",
    "filecmp.py",
    "fileinput.py",
    "fnmatch.py",
    "fractions.py",
    "ftplib.py",
    "functools.py",
    "genericpath.py",
    "getopt.py",
    "getpass.py",
    "gettext.py",
    "glob.py",
    "graphlib.py",
    "gzip.py",
    "hashlib.py",
    "heapq.py",
    "hmac.py",
    "html",
    "http",
    "imaplib.py",
    "importlib",
    "inspect.py",
    "io.py",
    "ipaddress.py",
    "json",
    "keyword.py",
    "linecache.py",
    "locale.py",
    "logging",
    "lzma.py",
    "mailbox.py",
    "mimetypes.py",
    "modulefinder.py",
    "multiprocessing",
    "netrc.py",
    "ntpath.py",
    "nturl2path.py",
    "numbers.py",
    "opcode.py",
    "operator.py",
    "optparse.py",
    "os.py",
    "pathlib",
    "pdb.py",
    "pickle.py",
    "pickletools.py",
    "pkgutil.py",
    "platform.py",
    "plistlib.py",
    "poplib.py",
    "posixpath.py",
    "pprint.py",
    "profile.py",
    "pstats.py",
    "pty.py",
    "py_compile.py",
    "pyclbr.py",
    "pydoc.py",
    "pydoc_data",
    "queue.py",
    "quopri.py",
    "random.py",
    "re",
    "reprlib.py",
    "rlcompleter.py",
    "runpy.py",
    "sched.py",
    "secrets.py",
    "selectors.py",
    "shelve.py",
    "shlex.py",
    "shutil.py",
    "signal.py",
    "site-packages",
    "site.py",
    "smtplib.py",
    "socket.py",
    "socketserver.py",
    "sqlite3",
    "sre_compile.py",
    "sre_constants.py",
    "sre_parse.py",
    "ssl.py",
    "stat.py",
    "statistics.py",
    "string",
    "stringprep.py",
    "struct.py",
    "subprocess.py",
    "symtable.py",
    "sysconfig",
    "tabnanny.py",
    "tarfile.py",
    "tempfile.py",
    "textwrap.py",
    "this.py",
    "threading.py",
    "timeit.py",
    "token.py",
    "tokenize.py",
    "tomllib",
    "trace.py",
    "traceback.py",
    "tracemalloc.py",
    "tty.py",
    "types.py",
    "typing.py",
    "unittest",
    "urllib",
    "uuid.py",
    "venv",
    "warnings.py",
    "wave.py",
    "weakref.py",
    "webbrowser.py",
    "wsgiref",
    "xml",
    "xmlrpc",
    "zipapp.py",
    "zipfile",
    "zipimport.py",
    "zoneinfo",
]
