# SPDX-FileCopyrightText: © 2024-2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load(":defs.bzl", "system_golang_toolchain")

system_golang_toolchain(
    name="golang",
    visibility=["PUBLIC"],
)
