# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# The GCC 4.7.4 archive members that BUILD reads. The object lists name the
# translation units BUILD compiles; each *_FILES list adds the headers and
# other files those units need.

# Upstream REQUIRED_OFILES, libcpp_a_OBJS and native BID libdecnumber objects.
LIBIBERTY = [
    "regex",
    "cplus-dem",
    "cp-demangle",
    "md5",
    "sha1",
    "alloca",
    "argv",
    "choose-temp",
    "concat",
    "cp-demint",
    "crc32",
    "dyn-string",
    "fdmatch",
    "fibheap",
    "filename_cmp",
    "floatformat",
    "fnmatch",
    "fopen_unlocked",
    "getopt",
    "getopt1",
    "getpwd",
    "getruntime",
    "hashtab",
    "hex",
    "lbasename",
    "lrealpath",
    "make-relative-prefix",
    "make-temp-file",
    "objalloc",
    "obstack",
    "partition",
    "pexecute",
    "physmem",
    "pex-common",
    "pex-one",
    "pex-unix",
    "safe-ctype",
    "simple-object",
    "simple-object-coff",
    "simple-object-elf",
    "simple-object-mach-o",
    "sort",
    "spaces",
    "splay-tree",
    "stack-limit",
    "strerror",
    "strsignal",
    "timeval-utils",
    "unlink-if-ordinary",
    "xatexit",
    "xexit",
    "xmalloc",
    "xmemdup",
    "xstrdup",
    "xstrerror",
    "xstrndup",
]

LIBCPP = [
    "charset",
    "directives",
    "directives-only",
    "errors",
    "expr",
    "files",
    "identifiers",
    "init",
    "lex",
    "line-map",
    "macro",
    "mkdeps",
    "pch",
    "symtab",
    "traditional",
]

LIBDECNUMBER = [
    "decNumber",
    "decContext",
    "bid/decimal32",
    "bid/decimal64",
    "bid/decimal128",
    "bid/bid2dpd_dpd2bid",
    "bid/host-ieee32",
    "bid/host-ieee64",
    "bid/host-ieee128",
]

# Headers, and the DPD sources that the BID sources include.
_LIBRARY_HEADERS = [
    "libdecnumber/dpd/decimal32.c",
    "libdecnumber/dpd/decimal64.c",
    "libdecnumber/dpd/decimal128.c",
    "include/ansidecl.h",
    "include/demangle.h",
    "include/dwarf2.h",
    "include/dyn-string.h",
    "include/fibheap.h",
    "include/filenames.h",
    "include/floatformat.h",
    "include/fnmatch.h",
    "include/getopt.h",
    "include/hashtab.h",
    "include/libiberty.h",
    "include/lto-symtab.h",
    "include/md5.h",
    "include/objalloc.h",
    "include/obstack.h",
    "include/partition.h",
    "include/plugin-api.h",
    "include/safe-ctype.h",
    "include/sha1.h",
    "include/simple-object.h",
    "include/sort.h",
    "include/splay-tree.h",
    "include/symcat.h",
    "include/timeval-utils.h",
    "include/xregex.h",
    "include/xregex2.h",
    "include/xtensa-config.h",
    "libiberty/cp-demangle.h",
    "libiberty/pex-common.h",
    "libiberty/simple-object-common.h",
    "libcpp/include/cpp-id-data.h",
    "libcpp/include/cpplib.h",
    "libcpp/include/line-map.h",
    "libcpp/include/mkdeps.h",
    "libcpp/include/symtab.h",
    "libcpp/internal.h",
    "libcpp/system.h",
    "libdecnumber/bid/bid-dpd.h",
    "libdecnumber/bid/decimal128.h",
    "libdecnumber/bid/decimal128Local.h",
    "libdecnumber/bid/decimal128Symbols.h",
    "libdecnumber/bid/decimal32.h",
    "libdecnumber/bid/decimal32Symbols.h",
    "libdecnumber/bid/decimal64.h",
    "libdecnumber/bid/decimal64Symbols.h",
    "libdecnumber/dconfig.h",
    "libdecnumber/decCommonSymbols.h",
    "libdecnumber/decContext.h",
    "libdecnumber/decContextSymbols.h",
    "libdecnumber/decDPDSymbols.h",
    "libdecnumber/decDouble.h",
    "libdecnumber/decDoubleSymbols.h",
    "libdecnumber/decExcept.h",
    "libdecnumber/decNumber.h",
    "libdecnumber/decNumberLocal.h",
    "libdecnumber/decNumberSymbols.h",
    "libdecnumber/decPacked.h",
    "libdecnumber/decPackedSymbols.h",
    "libdecnumber/decQuad.h",
    "libdecnumber/decQuadSymbols.h",
    "libdecnumber/decRound.h",
    "libdecnumber/decSingle.h",
    "libdecnumber/decSingleSymbols.h",
    "libdecnumber/dpd/decimal128.h",
    "libdecnumber/dpd/decimal128Local.h",
    "libdecnumber/dpd/decimal128Symbols.h",
    "libdecnumber/dpd/decimal32.h",
    "libdecnumber/dpd/decimal32Symbols.h",
    "libdecnumber/dpd/decimal64.h",
    "libdecnumber/dpd/decimal64Symbols.h",
]

# Libiberty's crc32.c is regenerated; the archive copy is only a fixture.
LIBRARY_FILES = ["libiberty/" + name + ".c" for name in LIBIBERTY if name != "crc32"] + ["libcpp/" + name + ".c" for name in LIBCPP] + ["libdecnumber/" + name + ".c" for name in LIBDECNUMBER] + _LIBRARY_HEADERS

BASE_GENERATORS = [
    "gencheck",
    "gengenrtl",
    "genmodes",
    "genhooks",
]

_EARLY_GENERATOR_HEADERS = [
    "gcc/addresses.h",
    "gcc/alias.h",
    "gcc/alloc-pool.h",
    "gcc/basic-block.h",
    "gcc/bb-reorder.h",
    "gcc/bitmap.h",
    "gcc/builtin-attrs.def",
    "gcc/builtin-types.def",
    "gcc/builtins.def",
    "gcc/builtins.h",
    "gcc/c-family/c-common.def",
    "gcc/c-family/c-target.def",
    "gcc/c-lang.h",
    "gcc/c-objc-common.h",
    "gcc/c-tree.h",
    "gcc/cfghooks.h",
    "gcc/cfglayout.h",
    "gcc/cfgloop.h",
    "gcc/cgraph.h",
    "gcc/cif-code.def",
    "gcc/collect2-aix.h",
    "gcc/collect2.h",
    "gcc/common/common-target.def",
    "gcc/conditions.h",
    "gcc/config/dbxelf.h",
    "gcc/config/elfos.h",
    "gcc/config/glibc-stdint.h",
    "gcc/config/gnu-user.h",
    "gcc/config/i386/att.h",
    "gcc/config/i386/biarch64.h",
    "gcc/config/i386/gnu-user64.h",
    "gcc/config/i386/i386-modes.def",
    "gcc/config/i386/i386-opts.h",
    "gcc/config/i386/i386-protos.h",
    "gcc/config/i386/i386.h",
    "gcc/config/i386/linux64.h",
    "gcc/config/i386/unix.h",
    "gcc/config/i386/x86-64.h",
    "gcc/config/linux-android.h",
    "gcc/config/linux.h",
    "gcc/config/linux.opt",
    "gcc/config/vxworks-dummy.h",
    "gcc/convert.h",
    "gcc/coretypes.h",
    "gcc/coverage.h",
    "gcc/cp/cp-tree.def",
    "gcc/cppbuiltin.h",
    "gcc/cppdefault.h",
    "gcc/cselib.h",
    "gcc/data-streamer.h",
    "gcc/dbgcnt.def",
    "gcc/dbgcnt.h",
    "gcc/dbxout.h",
    "gcc/dce.h",
    "gcc/ddg.h",
    "gcc/debug.h",
    "gcc/defaults.h",
    "gcc/df.h",
    "gcc/dfp.h",
    "gcc/diagnostic-core.h",
    "gcc/diagnostic.def",
    "gcc/diagnostic.h",
    "gcc/domwalk.h",
    "gcc/double-int.h",
    "gcc/dse.h",
    "gcc/dwarf2asm.h",
    "gcc/dwarf2out.h",
    "gcc/ebitmap.h",
    "gcc/emit-rtl.h",
    "gcc/errors.h",
    "gcc/et-forest.h",
    "gcc/except.h",
    "gcc/expmed.h",
    "gcc/expr.h",
    "gcc/fixed-value.h",
    "gcc/flag-types.h",
    "gcc/flags.h",
    "gcc/function.h",
    "gcc/gcc-plugin.h",
    "gcc/gcc.h",
    "gcc/gcov-io.h",
    "gcc/gcse.h",
    "gcc/gengtype.h",
    "gcc/gensupport.h",
    "gcc/ggc-internal.h",
    "gcc/ggc.h",
    "gcc/gimple-fold.h",
    "gcc/gimple-pretty-print.h",
    "gcc/gimple-streamer.h",
    "gcc/gimple.def",
    "gcc/gimple.h",
    "gcc/glimits.h",
    "gcc/graph.h",
    "gcc/graphds.h",
    "gcc/graphite-clast-to-gimple.h",
    "gcc/graphite-cloog-compat.h",
    "gcc/graphite-cloog-util.h",
    "gcc/graphite-dependences.h",
    "gcc/graphite-poly.h",
    "gcc/graphite-ppl.h",
    "gcc/graphite-scop-detection.h",
    "gcc/graphite-sese-to-poly.h",
    "gcc/gsstruct.def",
    "gcc/gstab.h",
    "gcc/gsyms.h",
    "gcc/gsyslimits.h",
    "gcc/gtm-builtins.def",
    "gcc/hard-reg-set.h",
    "gcc/highlev-plugin-common.h",
    "gcc/hooks.h",
    "gcc/hosthooks-def.h",
    "gcc/hosthooks.h",
    "gcc/hw-doloop.h",
    "gcc/hwint.h",
    "gcc/incpath.h",
    "gcc/input.h",
    "gcc/insn-addr.h",
    "gcc/insn-notes.def",
    "gcc/integrate.h",
    "gcc/internal-fn.def",
    "gcc/internal-fn.h",
    "gcc/intl.h",
    "gcc/ipa-inline.h",
    "gcc/ipa-prop.h",
    "gcc/ipa-ref-inline.h",
    "gcc/ipa-ref.h",
    "gcc/ipa-reference.h",
    "gcc/ipa-utils.h",
    "gcc/ira-int.h",
    "gcc/ira.h",
    "gcc/langhooks-def.h",
    "gcc/langhooks.h",
    "gcc/libfuncs.h",
    "gcc/limitx.h",
    "gcc/limity.h",
    "gcc/lto-compress.h",
    "gcc/lto-streamer.h",
    "gcc/machmode.def",
    "gcc/machmode.h",
    "gcc/mode-classes.def",
    "gcc/omega.h",
    "gcc/omp-builtins.def",
    "gcc/optabs.h",
    "gcc/opts-diagnostic.h",
    "gcc/opts.h",
    "gcc/output.h",
    "gcc/params.def",
    "gcc/params.h",
    "gcc/plugin.def",
    "gcc/plugin.h",
    "gcc/pointer-set.h",
    "gcc/predict.def",
    "gcc/predict.h",
    "gcc/prefix.h",
    "gcc/pretty-print.h",
    "gcc/profile.h",
    "gcc/read-md.h",
    "gcc/real.h",
    "gcc/realmpfr.h",
    "gcc/recog.h",
    "gcc/reg-notes.def",
    "gcc/regrename.h",
    "gcc/regs.h",
    "gcc/regset.h",
    "gcc/reload.h",
    "gcc/resource.h",
    "gcc/rtl-error.h",
    "gcc/rtl.def",
    "gcc/rtl.h",
    "gcc/rtlhooks-def.h",
    "gcc/sbitmap.h",
    "gcc/sched-int.h",
    "gcc/sdbout.h",
    "gcc/sel-sched-dump.h",
    "gcc/sel-sched-ir.h",
    "gcc/sel-sched.h",
    "gcc/sese.h",
    "gcc/sparseset.h",
    "gcc/sreal.h",
    "gcc/ssaexpand.h",
    "gcc/stab.def",
    "gcc/statistics.h",
    "gcc/streamer-hooks.h",
    "gcc/sync-builtins.def",
    "gcc/system.h",
    "gcc/target-def.h",
    "gcc/target-globals.h",
    "gcc/target-hooks-macros.h",
    "gcc/target.def",
    "gcc/target.h",
    "gcc/targhooks.h",
    "gcc/timevar.def",
    "gcc/timevar.h",
    "gcc/toplev.h",
    "gcc/trans-mem.h",
    "gcc/tree-affine.h",
    "gcc/tree-browser.def",
    "gcc/tree-chrec.h",
    "gcc/tree-data-ref.h",
    "gcc/tree-diagnostic.h",
    "gcc/tree-dump.h",
    "gcc/tree-flow-inline.h",
    "gcc/tree-flow.h",
    "gcc/tree-inline.h",
    "gcc/tree-iterator.h",
    "gcc/tree-mudflap.h",
    "gcc/tree-pass.h",
    "gcc/tree-pretty-print.h",
    "gcc/tree-scalar-evolution.h",
    "gcc/tree-ssa-alias.h",
    "gcc/tree-ssa-live.h",
    "gcc/tree-ssa-operands.h",
    "gcc/tree-ssa-propagate.h",
    "gcc/tree-ssa-sccvn.h",
    "gcc/tree-stdarg.h",
    "gcc/tree-streamer.h",
    "gcc/tree-vectorizer.h",
    "gcc/tree.def",
    "gcc/tree.h",
    "gcc/treestruct.def",
    "gcc/tsystem.h",
    "gcc/typeclass.h",
    "gcc/value-prof.h",
    "gcc/vec.h",
    "gcc/vecir.h",
    "gcc/vecprim.h",
    "gcc/version.h",
    "gcc/vmsdbg.h",
    "gcc/xcoff.h",
    "gcc/xcoffout.h",
]

EARLY_GENERATOR_FILES = _EARLY_GENERATOR_HEADERS + ["gcc/" + name + ".c" for name in BASE_GENERATORS + ["errors"]]

MACHINE_GENERATORS = [
    "genattr",
    "genattr-common",
    "genattrtab",
    "genautomata",
    "gencodes",
    "genconditions",
    "genconfig",
    "genemit",
    "genextract",
    "genflags",
    "genopinit",
    "genoutput",
    "genpeep",
    "genpreds",
    "genrecog",
    "genconstants",
    "genenums",
]

RTL_SUPPORT = [
    "rtl",
    "read-rtl",
    "ggc-none",
    "vec",
    "gensupport",
    "print-rtl",
]

# Option files, machine descriptions and the awk scripts that read them.
_MACHINE_DESCRIPTIONS = [
    "gcc/lto/lang.opt",
    "gcc/c-family/c.opt",
    "gcc/common.opt",
    "gcc/config/fused-madd.opt",
    "gcc/config/gnu-user.opt",
    "gcc/config/i386/athlon.md",
    "gcc/config/i386/atom.md",
    "gcc/config/i386/bdver1.md",
    "gcc/config/i386/constraints.md",
    "gcc/config/i386/core2.md",
    "gcc/config/i386/geode.md",
    "gcc/config/i386/i386-builtin-types.awk",
    "gcc/config/i386/i386-builtin-types.def",
    "gcc/config/i386/i386.md",
    "gcc/config/i386/i386.opt",
    "gcc/config/i386/k6.md",
    "gcc/config/i386/mmx.md",
    "gcc/config/i386/pentium.md",
    "gcc/config/i386/ppro.md",
    "gcc/config/i386/predicates.md",
    "gcc/config/i386/sse.md",
    "gcc/config/i386/sync.md",
    "gcc/config/linux-android.opt",
    "gcc/config/linux.opt",
    "gcc/opt-functions.awk",
    "gcc/opt-gather.awk",
    "gcc/opt-read.awk",
    "gcc/optc-gen.awk",
    "gcc/optc-save-gen.awk",
    "gcc/opth-gen.awk",
]

MACHINE_GENERATOR_FILES = _MACHINE_DESCRIPTIONS + ["gcc/" + name + ".c" for name in RTL_SUPPORT + ["read-md"] + MACHINE_GENERATORS]

# The target's tm_file headers, in upstream order.
TARGET_HEADERS = [
    "i386/biarch64.h",
    "i386/i386.h",
    "linux-android.h",
    "i386/unix.h",
    "i386/att.h",
    "dbxelf.h",
    "elfos.h",
    "gnu-user.h",
    "glibc-stdint.h",
    "i386/x86-64.h",
    "i386/gnu-user64.h",
    "linux.h",
    "i386/linux64.h",
]

# Gengtype's input list, in upstream order; bracketed lines start a front end.
GTYPE_INPUTS = [
    "libcpp/include/line-map.h",
    "libcpp/include/cpplib.h",
    "gcc/options.h",
    "libcpp/include/cpp-id-data.h",
    "gcc/input.h",
    "gcc/coretypes.h",
    "gcc/vecprim.h",
    "gcc/vecir.h",
] + ["gcc/config/" + path for path in TARGET_HEADERS] + [
    "include/hashtab.h",
    "include/splay-tree.h",
    "gcc/bitmap.h",
    "gcc/alias.h",
    "gcc/coverage.c",
    "gcc/rtl.h",
    "gcc/optabs.h",
    "gcc/tree.h",
    "gcc/libfuncs.h",
    "libcpp/include/symtab.h",
    "include/obstack.h",
    "gcc/real.h",
    "gcc/function.h",
    "gcc/insn-addr.h",
    "gcc/hwint.h",
    "gcc/fixed-value.h",
    "gcc/output.h",
    "gcc/cfgloop.h",
    "gcc/cselib.h",
    "gcc/basic-block.h",
    "gcc/ipa-ref.h",
    "gcc/cgraph.h",
    "gcc/reload.h",
    "gcc/caller-save.c",
    "gcc/alias.c",
    "gcc/bitmap.c",
    "gcc/cselib.c",
    "gcc/cgraph.c",
    "gcc/ipa-prop.c",
    "gcc/ipa-cp.c",
    "gcc/matrix-reorg.c",
    "gcc/dbxout.c",
    "gcc/dwarf2out.h",
    "gcc/dwarf2asm.c",
    "gcc/dwarf2cfi.c",
    "gcc/dwarf2out.c",
    "gcc/tree-vect-generic.c",
    "gcc/dojump.c",
    "gcc/emit-rtl.c",
    "gcc/except.h",
    "gcc/explow.c",
    "gcc/expr.c",
    "gcc/expr.h",
    "gcc/function.c",
    "gcc/except.c",
    "gcc/gcse.c",
    "gcc/godump.c",
    "gcc/integrate.c",
    "gcc/lists.c",
    "gcc/optabs.c",
    "gcc/profile.c",
    "gcc/mcf.c",
    "gcc/reg-stack.c",
    "gcc/cfglayout.c",
    "gcc/cfglayout.h",
    "gcc/sdbout.c",
    "gcc/stor-layout.c",
    "gcc/stringpool.c",
    "gcc/tree.c",
    "gcc/varasm.c",
    "gcc/gimple.h",
    "gcc/gimple.c",
    "gcc/tree-mudflap.c",
    "gcc/tree-flow.h",
    "gcc/tree-ssanames.c",
    "gcc/tree-eh.c",
    "gcc/tree-ssa-address.c",
    "gcc/tree-cfg.c",
    "gcc/tree-dfa.c",
    "gcc/tree-iterator.c",
    "gcc/gimplify.c",
    "gcc/tree-chrec.h",
    "gcc/tree-scalar-evolution.c",
    "gcc/tree-ssa-operands.h",
    "gcc/tree-profile.c",
    "gcc/tree-nested.c",
    "gcc/varpool.c",
    "gcc/tree-parloops.c",
    "gcc/omp-low.c",
    "gcc/targhooks.c",
    "gcc/config/i386/i386.c",
    "gcc/passes.c",
    "gcc/cgraphunit.c",
    "gcc/tree-ssa-propagate.c",
    "gcc/tree-phinodes.c",
    "gcc/lto-symtab.c",
    "gcc/tree-ssa-alias.h",
    "gcc/ipa-prop.h",
    "gcc/trans-mem.c",
    "gcc/lto-streamer.h",
    "gcc/target-globals.h",
    "gcc/ipa-inline.h",
    "[cp]",
    "gcc/cp/rtti.c",
    "gcc/cp/mangle.c",
    "gcc/cp/name-lookup.h",
    "gcc/cp/name-lookup.c",
    "gcc/cp/cp-tree.h",
    "gcc/cp/decl.h",
    "gcc/cp/call.c",
    "gcc/cp/decl.c",
    "gcc/cp/decl2.c",
    "gcc/cp/pt.c",
    "gcc/cp/repo.c",
    "gcc/cp/semantics.c",
    "gcc/cp/tree.c",
    "gcc/cp/parser.h",
    "gcc/cp/parser.c",
    "gcc/cp/method.c",
    "gcc/cp/typeck2.c",
    "gcc/c-family/c-common.c",
    "gcc/c-family/c-common.h",
    "gcc/c-family/c-objc.h",
    "gcc/c-family/c-lex.c",
    "gcc/c-family/c-pragma.h",
    "gcc/c-family/c-pragma.c",
    "gcc/cp/class.c",
    "gcc/cp/cp-objcp-common.c",
    "gcc/cp/cp-lang.c",
    "gcc/cp/except.c",
    "[c]",
    "gcc/c-lang.c",
    "gcc/c-tree.h",
    "gcc/c-decl.c",
    "gcc/c-family/c-common.c",
    "gcc/c-family/c-common.h",
    "gcc/c-family/c-objc.h",
    "gcc/c-family/c-cppbuiltin.c",
    "gcc/c-family/c-pragma.h",
    "gcc/c-family/c-pragma.c",
    "gcc/c-objc-common.c",
    "gcc/c-parser.c",
    "gcc/c-lang.h",
]

GTYPE_OBJECTS = [
    "gengtype",
    "gengtype-lex",
    "gengtype-parse",
    "gengtype-state",
    "version",
]

# The generated options.h comes from each stage's option generators.
GTYPE_FILES = sorted({path: None for path in GTYPE_INPUTS if path.startswith("gcc/") and path != "gcc/options.h"}) + ["gcc/" + name + (".l" if name == "gengtype-lex" else ".c") for name in GTYPE_OBJECTS]

GENERATOR_FILES = EARLY_GENERATOR_FILES + MACHINE_GENERATOR_FILES + GTYPE_FILES

BACKEND_OBJECTS = [
    "insn-attrtab",
    "insn-automata",
    "insn-emit",
    "insn-extract",
    "insn-modes",
    "insn-opinit",
    "insn-output",
    "insn-peep",
    "insn-preds",
    "insn-recog",
    "insn-enums",
    "ggc-page",
    "alias",
    "alloc-pool",
    "auto-inc-dec",
    "bb-reorder",
    "bitmap",
    "bt-load",
    "builtins",
    "caller-save",
    "calls",
    "cfg",
    "cfganal",
    "cfgbuild",
    "cfgcleanup",
    "cfgexpand",
    "cfghooks",
    "cfglayout",
    "cfgloop",
    "cfgloopanal",
    "cfgloopmanip",
    "cfgrtl",
    "cgraph",
    "cgraphbuild",
    "cgraphunit",
    "combine",
    "combine-stack-adj",
    "compare-elim",
    "convert",
    "coverage",
    "cppbuiltin",
    "cppdefault",
    "cprop",
    "cse",
    "cselib",
    "data-streamer",
    "data-streamer-in",
    "data-streamer-out",
    "dbxout",
    "dbgcnt",
    "dce",
    "ddg",
    "debug",
    "df-core",
    "df-problems",
    "df-scan",
    "dfp",
    "dojump",
    "dominance",
    "domwalk",
    "double-int",
    "dse",
    "dwarf2asm",
    "dwarf2cfi",
    "dwarf2out",
    "ebitmap",
    "emit-rtl",
    "et-forest",
    "except",
    "explow",
    "expmed",
    "expr",
    "final",
    "fixed-value",
    "fold-const",
    "function",
    "fwprop",
    "gcse",
    "ggc-common",
    "gimple",
    "gimple-iterator",
    "gimple-fold",
    "gimple-low",
    "gimple-pretty-print",
    "gimple-streamer-in",
    "gimple-streamer-out",
    "gimplify",
    "godump",
    "graph",
    "graphds",
    "graphite",
    "graphite-blocking",
    "graphite-clast-to-gimple",
    "graphite-cloog-util",
    "graphite-dependences",
    "graphite-flattening",
    "graphite-interchange",
    "graphite-poly",
    "graphite-ppl",
    "graphite-scop-detection",
    "graphite-sese-to-poly",
    "gtype-desc",
    "haifa-sched",
    "hw-doloop",
    "hwint",
    "ifcvt",
    "ree",
    "incpath",
    "init-regs",
    "integrate",
    "internal-fn",
    "ipa-cp",
    "ipa-split",
    "ipa-inline",
    "ipa-inline-analysis",
    "ipa-inline-transform",
    "ipa-prop",
    "ipa-pure-const",
    "ipa-reference",
    "ipa-ref",
    "ipa-utils",
    "ipa",
    "ira",
    "ira-build",
    "ira-costs",
    "ira-conflicts",
    "ira-color",
    "ira-emit",
    "ira-lives",
    "jump",
    "langhooks",
    "lcm",
    "lists",
    "loop-doloop",
    "loop-init",
    "loop-invariant",
    "loop-iv",
    "loop-unroll",
    "loop-unswitch",
    "lower-subreg",
    "lto-cgraph",
    "lto-streamer",
    "lto-streamer-in",
    "lto-streamer-out",
    "lto-section-in",
    "lto-section-out",
    "lto-symtab",
    "lto-opts",
    "lto-compress",
    "matrix-reorg",
    "mcf",
    "mode-switching",
    "modulo-sched",
    "omega",
    "omp-low",
    "optabs",
    "options-save",
    "opts-global",
    "passes",
    "plugin",
    "pointer-set",
    "postreload-gcse",
    "postreload",
    "predict",
    "print-rtl",
    "print-tree",
    "profile",
    "real",
    "realmpfr",
    "recog",
    "reg-stack",
    "regcprop",
    "reginfo",
    "regmove",
    "regrename",
    "regstat",
    "reload",
    "reload1",
    "reorg",
    "resource",
    "rtl-error",
    "rtl",
    "rtlanal",
    "rtlhooks",
    "sbitmap",
    "sched-deps",
    "sched-ebb",
    "sched-rgn",
    "sched-vis",
    "sdbout",
    "sel-sched-ir",
    "sel-sched-dump",
    "sel-sched",
    "sese",
    "simplify-rtx",
    "sparseset",
    "sreal",
    "stack-ptr-mod",
    "statistics",
    "stmt",
    "stor-layout",
    "store-motion",
    "streamer-hooks",
    "stringpool",
    "target-globals",
    "targhooks",
    "timevar",
    "toplev",
    "tracer",
    "trans-mem",
    "tree-affine",
    "tree-call-cdce",
    "tree-cfg",
    "tree-cfgcleanup",
    "tree-chrec",
    "tree-complex",
    "tree-data-ref",
    "tree-dfa",
    "tree-diagnostic",
    "tree-dump",
    "tree-eh",
    "tree-emutls",
    "tree-if-conv",
    "tree-inline",
    "tree-into-ssa",
    "tree-iterator",
    "tree-loop-distribution",
    "tree-nested",
    "tree-nomudflap",
    "tree-nrv",
    "tree-object-size",
    "tree-optimize",
    "tree-outof-ssa",
    "tree-parloops",
    "tree-phinodes",
    "tree-predcom",
    "tree-pretty-print",
    "tree-profile",
    "tree-scalar-evolution",
    "tree-sra",
    "tree-switch-conversion",
    "tree-ssa-address",
    "tree-ssa-alias",
    "tree-ssa-ccp",
    "tree-ssa-coalesce",
    "tree-ssa-copy",
    "tree-ssa-copyrename",
    "tree-ssa-dce",
    "tree-ssa-dom",
    "tree-ssa-dse",
    "tree-ssa-forwprop",
    "tree-ssa-ifcombine",
    "tree-ssa-live",
    "tree-ssa-loop-ch",
    "tree-ssa-loop-im",
    "tree-ssa-loop-ivcanon",
    "tree-ssa-loop-ivopts",
    "tree-ssa-loop-manip",
    "tree-ssa-loop-niter",
    "tree-ssa-loop-prefetch",
    "tree-ssa-loop-unswitch",
    "tree-ssa-loop",
    "tree-ssa-math-opts",
    "tree-ssa-operands",
    "tree-ssa-phiopt",
    "tree-ssa-phiprop",
    "tree-ssa-pre",
    "tree-ssa-propagate",
    "tree-ssa-reassoc",
    "tree-ssa-sccvn",
    "tree-ssa-sink",
    "tree-ssa-strlen",
    "tree-ssa-structalias",
    "tree-ssa-tail-merge",
    "tree-ssa-ter",
    "tree-ssa-threadedge",
    "tree-ssa-threadupdate",
    "tree-ssa-uncprop",
    "tree-ssa-uninit",
    "tree-ssa",
    "tree-ssanames",
    "tree-stdarg",
    "tree-streamer",
    "tree-streamer-in",
    "tree-streamer-out",
    "tree-tailcall",
    "tree-vect-generic",
    "tree-vect-patterns",
    "tree-vect-data-refs",
    "tree-vect-stmts",
    "tree-vect-loop",
    "tree-vect-loop-manip",
    "tree-vect-slp",
    "tree-vectorizer",
    "tree-vrp",
    "tree",
    "value-prof",
    "var-tracking",
    "varasm",
    "varpool",
    "vmsdbgout",
    "web",
    "xcoffout",
    "config/i386/i386",
    "config/host-linux",
]

C_OBJECTS = [
    "c-lang",
    "c-family/stub-objc",
    "attribs",
    "c-errors",
    "c-decl",
    "c-typeck",
    "c-convert",
    "c-aux-info",
    "c-objc-common",
    "c-parser",
    "tree-mudflap",
    "c-family/c-common",
    "c-family/c-cppbuiltin",
    "c-family/c-dump",
    "c-family/c-format",
    "c-family/c-gimplify",
    "c-family/c-lex",
    "c-family/c-omp",
    "c-family/c-opts",
    "c-family/c-pch",
    "c-family/c-ppoutput",
    "c-family/c-pragma",
    "c-family/c-pretty-print",
    "c-family/c-semantics",
    "c-family/c-ada-spec",
    "config/i386/i386-c",
    "config/default-c",
]

CXX_OBJECTS = [
    "cp/cp-lang",
    "c-family/stub-objc",
    "cp/call",
    "cp/decl",
    "cp/expr",
    "cp/pt",
    "cp/typeck2",
    "cp/class",
    "cp/decl2",
    "cp/error",
    "cp/lex",
    "cp/parser",
    "cp/ptree",
    "cp/rtti",
    "cp/typeck",
    "cp/cvt",
    "cp/except",
    "cp/friend",
    "cp/init",
    "cp/method",
    "cp/search",
    "cp/semantics",
    "cp/tree",
    "cp/repo",
    "cp/dump",
    "cp/optimize",
    "cp/mangle",
    "cp/cp-objcp-common",
    "cp/name-lookup",
    "cp/cxx-pretty-print",
    "cp/cp-gimplify",
    "tree-mudflap",
    "attribs",
    "incpath",
    "c-family/c-common",
    "c-family/c-cppbuiltin",
    "c-family/c-dump",
    "c-family/c-format",
    "c-family/c-gimplify",
    "c-family/c-lex",
    "c-family/c-omp",
    "c-family/c-opts",
    "c-family/c-pch",
    "c-family/c-ppoutput",
    "c-family/c-pragma",
    "c-family/c-pretty-print",
    "c-family/c-semantics",
    "c-family/c-ada-spec",
    "config/i386/i386-c",
    "config/default-c",
]

COMMON_OBJECTS = [
    "diagnostic",
    "pretty-print",
    "intl",
    "input",
    "version",
]

COMMON_TARGET_OBJECTS = [
    "common/config/i386/i386-common",
    "prefix",
    "params",
    "opts",
    "opts-common",
    "options",
    "vec",
    "hooks",
    "common/common-targhooks",
]

COMPILER_OBJECTS = {name: "gcc/" + name + ".c" for name in BACKEND_OBJECTS + C_OBJECTS + CXX_OBJECTS + COMMON_OBJECTS + COMMON_TARGET_OBJECTS + ["main"]}

INTRINSIC_HEADERS = [
    "ammintrin.h",
    "avx2intrin.h",
    "avxintrin.h",
    "bmi2intrin.h",
    "bmiintrin.h",
    "bmmintrin.h",
    "emmintrin.h",
    "f16cintrin.h",
    "fma4intrin.h",
    "fmaintrin.h",
    "ia32intrin.h",
    "immintrin.h",
    "lwpintrin.h",
    "lzcntintrin.h",
    "mmintrin.h",
    "nmmintrin.h",
    "pmmintrin.h",
    "popcntintrin.h",
    "smmintrin.h",
    "tbmintrin.h",
    "tmmintrin.h",
    "wmmintrin.h",
    "x86intrin.h",
    "xmmintrin.h",
    "xopintrin.h",
    "cpuid.h",
]

# The compiler tree's other headers, gcov-io.c, and the sources of the
# checksum and gcov-iov generators.
_COMPILER_EXTRA_FILES = [
    "gcc/c-family/c-ada-spec.h",
    "gcc/c-family/c-format.h",
    "gcc/c-family/c-pretty-print.h",
    "gcc/c-family/c-target-def.h",
    "gcc/c-family/c-target.h",
    "gcc/common/common-target-def.h",
    "gcc/common/common-target.h",
    "gcc/common/common-targhooks.h",
    "gcc/config/i386/avxmath.h",
    "gcc/config/i386/bsd.h",
    "gcc/config/i386/cross-stdarg.h",
    "gcc/config/i386/crtdll.h",
    "gcc/config/i386/cygming.h",
    "gcc/config/i386/cygwin-stdint.h",
    "gcc/config/i386/cygwin.h",
    "gcc/config/i386/darwin.h",
    "gcc/config/i386/darwin64.h",
    "gcc/config/i386/djgpp-stdint.h",
    "gcc/config/i386/djgpp.h",
    "gcc/config/i386/freebsd.h",
    "gcc/config/i386/freebsd64.h",
    "gcc/config/i386/gas.h",
    "gcc/config/i386/gmm_malloc.h",
    "gcc/config/i386/gnu-user.h",
    "gcc/config/i386/gnu.h",
    "gcc/config/i386/gstabs.h",
    "gcc/config/i386/i386-interix.h",
    "gcc/config/i386/i386elf.h",
    "gcc/config/i386/kfreebsd-gnu.h",
    "gcc/config/i386/kfreebsd-gnu64.h",
    "gcc/config/i386/knetbsd-gnu.h",
    "gcc/config/i386/kopensolaris-gnu.h",
    "gcc/config/i386/linux.h",
    "gcc/config/i386/lynx.h",
    "gcc/config/i386/mingw-pthread.h",
    "gcc/config/i386/mingw-stdint.h",
    "gcc/config/i386/mingw-w64.h",
    "gcc/config/i386/mingw32.h",
    "gcc/config/i386/mm3dnow.h",
    "gcc/config/i386/netbsd-elf.h",
    "gcc/config/i386/netbsd64.h",
    "gcc/config/i386/nto.h",
    "gcc/config/i386/openbsd.h",
    "gcc/config/i386/openbsdelf.h",
    "gcc/config/i386/pmm_malloc.h",
    "gcc/config/i386/rtemself.h",
    "gcc/config/i386/sol2-bi.h",
    "gcc/config/i386/sol2.h",
    "gcc/config/i386/ssemath.h",
    "gcc/config/i386/sysv4.h",
    "gcc/config/i386/vx-common.h",
    "gcc/config/i386/vxworks.h",
    "gcc/config/i386/vxworksae.h",
    "gcc/config/i386/xm-cygwin.h",
    "gcc/config/i386/xm-djgpp.h",
    "gcc/config/i386/xm-mingw32.h",
    "gcc/cp/cp-objcp-common.h",
    "gcc/cp/cxx-pretty-print.h",
    "gcc/cp/lang-specs.h",
    "gcc/cp/operators.def",
    "gcc/gcov-io.c",
    "gcc/gcov-iov.c",
    "gcc/genchecksum.c",
]

# The insn-*, gtype-desc and options sources come from each stage's generators.
COMPILER_FILES = sorted([path for name, path in COMPILER_OBJECTS.items() if path not in GENERATOR_FILES and not name.startswith("insn-") and name not in [
    "gtype-desc",
    "options",
    "options-save",
]] + ["gcc/config/i386/" + name for name in INTRINSIC_HEADERS] + _COMPILER_EXTRA_FILES)

DRIVER_OBJECTS = {
    "gcc": "gcc.c",
    "gccspec": "gccspec.c",
    "cppspec": "cppspec.c",
    "g++spec": "cp/g++spec.c",
    "ggc-none": "ggc-none.c",
    "driver-i386": "config/i386/driver-i386.c",
    "gcov": "gcov.c",
    "gcov-dump": "gcov-dump.c",
}

COMPILER_HEADERS = [
    "float.h",
    "iso646.h",
    "stdarg.h",
    "stdbool.h",
    "stddef.h",
    "varargs.h",
    "stdalign.h",
    "stdnoreturn.h",
    "stdfix.h",
    "stdint-gcc.h",
]

DRIVER_FILES = ["gcc/" + source for source in DRIVER_OBJECTS.values()] + ["gcc/ginclude/" + name for name in COMPILER_HEADERS + ["stdint-wrap.h"]]

RUNTIME_OBJECTS = {
    "unwind-dw2": "libgcc/unwind-dw2.c",
    "unwind-dw2-fde-dip": "libgcc/unwind-dw2-fde-dip.c",
    "unwind-sjlj": "libgcc/unwind-sjlj.c",
    "unwind-c": "libgcc/unwind-c.c",
    "emutls": "libgcc/emutls.c",
    "enable-execute-stack-empty": "libgcc/enable-execute-stack-empty.c",
    "addtf3": "libgcc/soft-fp/addtf3.c",
    "divtf3": "libgcc/soft-fp/divtf3.c",
    "eqtf2": "libgcc/config/i386/64/eqtf2.c",
    "getf2": "libgcc/config/i386/64/getf2.c",
    "letf2": "libgcc/config/i386/64/letf2.c",
    "multf3": "libgcc/soft-fp/multf3.c",
    "negtf2": "libgcc/soft-fp/negtf2.c",
    "subtf3": "libgcc/soft-fp/subtf3.c",
    "unordtf2": "libgcc/soft-fp/unordtf2.c",
    "fixtfsi": "libgcc/soft-fp/fixtfsi.c",
    "fixunstfsi": "libgcc/soft-fp/fixunstfsi.c",
    "fixtfdi": "libgcc/soft-fp/fixtfdi.c",
    "fixunstfdi": "libgcc/soft-fp/fixunstfdi.c",
    "fixtfti": "libgcc/soft-fp/fixtfti.c",
    "fixunstfti": "libgcc/soft-fp/fixunstfti.c",
    "floatsitf": "libgcc/soft-fp/floatsitf.c",
    "floatunsitf": "libgcc/soft-fp/floatunsitf.c",
    "floatditf": "libgcc/soft-fp/floatditf.c",
    "floatunditf": "libgcc/soft-fp/floatunditf.c",
    "floattitf": "libgcc/soft-fp/floattitf.c",
    "floatuntitf": "libgcc/soft-fp/floatuntitf.c",
    "extendsftf2": "libgcc/soft-fp/extendsftf2.c",
    "extenddftf2": "libgcc/soft-fp/extenddftf2.c",
    "extendxftf2": "libgcc/soft-fp/extendxftf2.c",
    "trunctfsf2": "libgcc/soft-fp/trunctfsf2.c",
    "trunctfdf2": "libgcc/soft-fp/trunctfdf2.c",
    "trunctfxf2": "libgcc/soft-fp/trunctfxf2.c",
    "_divtc3": "libgcc/config/i386/64/_divtc3.c",
    "_multc3": "libgcc/config/i386/64/_multc3.c",
    "_powitf2": "libgcc/config/i386/64/_powitf2.c",
    "bid_decimal_globals": "libgcc/config/libbid/bid_decimal_globals.c",
    "bid_decimal_data": "libgcc/config/libbid/bid_decimal_data.c",
    "bid_binarydecimal": "libgcc/config/libbid/bid_binarydecimal.c",
    "bid_convert_data": "libgcc/config/libbid/bid_convert_data.c",
    "_isinfd32": "libgcc/config/libbid/_isinfd32.c",
    "_isinfd64": "libgcc/config/libbid/_isinfd64.c",
    "_isinfd128": "libgcc/config/libbid/_isinfd128.c",
    "bid64_noncomp": "libgcc/config/libbid/bid64_noncomp.c",
    "bid128_noncomp": "libgcc/config/libbid/bid128_noncomp.c",
    "bid128_fma": "libgcc/config/libbid/bid128_fma.c",
    "bid_round": "libgcc/config/libbid/bid_round.c",
    "bid_from_int": "libgcc/config/libbid/bid_from_int.c",
    "bid64_add": "libgcc/config/libbid/bid64_add.c",
    "bid128_add": "libgcc/config/libbid/bid128_add.c",
    "bid64_div": "libgcc/config/libbid/bid64_div.c",
    "bid128_div": "libgcc/config/libbid/bid128_div.c",
    "bid64_mul": "libgcc/config/libbid/bid64_mul.c",
    "bid128_mul": "libgcc/config/libbid/bid128_mul.c",
    "bid64_compare": "libgcc/config/libbid/bid64_compare.c",
    "bid128_compare": "libgcc/config/libbid/bid128_compare.c",
    "bid128": "libgcc/config/libbid/bid128.c",
    "bid32_to_bid64": "libgcc/config/libbid/bid32_to_bid64.c",
    "bid32_to_bid128": "libgcc/config/libbid/bid32_to_bid128.c",
    "bid64_to_bid128": "libgcc/config/libbid/bid64_to_bid128.c",
    "bid64_to_int32": "libgcc/config/libbid/bid64_to_int32.c",
    "bid64_to_int64": "libgcc/config/libbid/bid64_to_int64.c",
    "bid64_to_uint32": "libgcc/config/libbid/bid64_to_uint32.c",
    "bid64_to_uint64": "libgcc/config/libbid/bid64_to_uint64.c",
    "bid128_to_int32": "libgcc/config/libbid/bid128_to_int32.c",
    "bid128_to_int64": "libgcc/config/libbid/bid128_to_int64.c",
    "bid128_to_uint32": "libgcc/config/libbid/bid128_to_uint32.c",
    "bid128_to_uint64": "libgcc/config/libbid/bid128_to_uint64.c",
}

DFP_OBJECTS = {
    "32": [
        "_addsub_sd",
        "_div_sd",
        "_mul_sd",
        "_eq_sd",
        "_ne_sd",
        "_lt_sd",
        "_gt_sd",
        "_le_sd",
        "_ge_sd",
        "_sd_to_si",
        "_sd_to_di",
        "_sd_to_usi",
        "_sd_to_udi",
        "_si_to_sd",
        "_di_to_sd",
        "_usi_to_sd",
        "_udi_to_sd",
        "_sd_to_sf",
        "_sd_to_df",
        "_sd_to_xf",
        "_sd_to_tf",
        "_sf_to_sd",
        "_df_to_sd",
        "_xf_to_sd",
        "_tf_to_sd",
        "_sd_to_dd",
        "_sd_to_td",
        "_unord_sd",
    ],
    "64": [
        "_addsub_dd",
        "_div_dd",
        "_mul_dd",
        "_eq_dd",
        "_ne_dd",
        "_lt_dd",
        "_gt_dd",
        "_le_dd",
        "_ge_dd",
        "_dd_to_si",
        "_dd_to_di",
        "_dd_to_usi",
        "_dd_to_udi",
        "_si_to_dd",
        "_di_to_dd",
        "_usi_to_dd",
        "_udi_to_dd",
        "_dd_to_sf",
        "_dd_to_df",
        "_dd_to_xf",
        "_dd_to_tf",
        "_sf_to_dd",
        "_df_to_dd",
        "_xf_to_dd",
        "_tf_to_dd",
        "_dd_to_sd",
        "_dd_to_td",
        "_unord_dd",
    ],
    "128": [
        "_addsub_td",
        "_div_td",
        "_mul_td",
        "_eq_td",
        "_ne_td",
        "_lt_td",
        "_gt_td",
        "_le_td",
        "_ge_td",
        "_td_to_si",
        "_td_to_di",
        "_td_to_usi",
        "_td_to_udi",
        "_si_to_td",
        "_di_to_td",
        "_usi_to_td",
        "_udi_to_td",
        "_td_to_sf",
        "_td_to_df",
        "_td_to_xf",
        "_td_to_tf",
        "_sf_to_td",
        "_df_to_td",
        "_xf_to_td",
        "_tf_to_td",
        "_td_to_sd",
        "_td_to_dd",
        "_unord_td",
    ],
}

# Headers, included sources, and the sources that BUILD compiles directly.
_RUNTIME_EXTRA_FILES = [
    "libgcc/config/i386/64/sfp-machine.h",
    "libgcc/config/i386/crtfastmath.c",
    "libgcc/config/i386/crtprec.c",
    "libgcc/config/i386/darwin-lib.h",
    "libgcc/config/i386/gthr-win32.h",
    "libgcc/config/i386/linux-unwind.h",
    "libgcc/config/i386/sfp-machine.h",
    "libgcc/config/i386/sol2-unwind.h",
    "libgcc/config/i386/value-unwind.h",
    "libgcc/config/i386/w32-unwind.h",
    "libgcc/config/libbid/bid128_2_str.h",
    "libgcc/config/libbid/bid128_2_str_macros.h",
    "libgcc/config/libbid/bid_b2d.h",
    "libgcc/config/libbid/bid_conf.h",
    "libgcc/config/libbid/bid_div_macros.h",
    "libgcc/config/libbid/bid_functions.h",
    "libgcc/config/libbid/bid_gcc_intrinsics.h",
    "libgcc/config/libbid/bid_inline_add.h",
    "libgcc/config/libbid/bid_internal.h",
    "libgcc/config/libbid/bid_sqrt_macros.h",
    "libgcc/crtstuff.c",
    "libgcc/dfp-bit.h",
    "libgcc/fixed-bit.h",
    "libgcc/fp-bit.h",
    "libgcc/gbl-ctors.h",
    "libgcc/generic-morestack.h",
    "libgcc/gstdint.h",
    "libgcc/gthr-posix.h",
    "libgcc/gthr-single.h",
    "libgcc/gthr.h",
    "libgcc/libgcc2.c",
    "libgcc/libgcc2.h",
    "libgcc/libgcov.c",
    "libgcc/longlong.h",
    "libgcc/soft-fp/double.h",
    "libgcc/soft-fp/eqtf2.c",
    "libgcc/soft-fp/extended.h",
    "libgcc/soft-fp/getf2.c",
    "libgcc/soft-fp/letf2.c",
    "libgcc/soft-fp/op-1.h",
    "libgcc/soft-fp/op-2.h",
    "libgcc/soft-fp/op-4.h",
    "libgcc/soft-fp/op-8.h",
    "libgcc/soft-fp/op-common.h",
    "libgcc/soft-fp/quad.h",
    "libgcc/soft-fp/single.h",
    "libgcc/soft-fp/soft-fp.h",
    "libgcc/unwind-compat.h",
    "libgcc/unwind-dw2-fde.c",
    "libgcc/unwind-dw2-fde.h",
    "libgcc/unwind-dw2.h",
    "libgcc/unwind-generic.h",
    "libgcc/unwind-pe.h",
    "libgcc/unwind.inc",
]

RUNTIME_FILES = sorted(list(RUNTIME_OBJECTS.values()) + ["libgcc/config/libbid/" + name + ".c" for names in DFP_OBJECTS.values() for name in names] + _RUNTIME_EXTRA_FILES)
