# SPDX-FileCopyrightText: © 2024-2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# The C sources of GNU Mes 0.27's x86_64 libraries and interpreter, from
# build-aux/configure-lib.sh. A library's list is its archive member order.

_ARCH = "lib/linux/x86_64-mes-mescc/"

# A minimal C library for the first programs.
LIBC_MINI_SOURCES = [
    "lib/mes/__init_io.c",
    "lib/mes/eputs.c",
    "lib/mes/oputs.c",
    "lib/mes/globals.c",
    "lib/stdlib/exit.c",
    "lib/stdlib/puts.c",
    "lib/string/strlen.c",
    "lib/mes/write.c",
    _ARCH + "_exit.c",
    _ARCH + "_write.c",
]

# MesCC's compiler support library.
LIBMESCC_SOURCES = [
    "lib/mes/globals.c",
    _ARCH + "syscall-internal.c",
]

LIBC_SOURCES = [
    "lib/mes/__init_io.c",
    "lib/mes/eputs.c",
    "lib/mes/oputs.c",
    "lib/mes/globals.c",
    "lib/stdlib/exit.c",
    "lib/stdlib/puts.c",
    "lib/string/strlen.c",
    "lib/ctype/isnumber.c",
    "lib/mes/abtol.c",
    "lib/mes/cast.c",
    "lib/mes/eputc.c",
    "lib/mes/fdgetc.c",
    "lib/mes/fdputc.c",
    "lib/mes/fdputs.c",
    "lib/mes/fdungetc.c",
    "lib/mes/itoa.c",
    "lib/mes/ltoa.c",
    "lib/mes/ltoab.c",
    "lib/mes/mes_open.c",
    "lib/mes/ntoab.c",
    "lib/mes/oputc.c",
    "lib/mes/ultoa.c",
    "lib/mes/utoa.c",
    "lib/stub/__raise.c",
    "lib/ctype/isdigit.c",
    "lib/ctype/isspace.c",
    "lib/ctype/isxdigit.c",
    "lib/mes/assert_msg.c",
    "lib/posix/write.c",
    "lib/stdlib/atoi.c",
    "lib/linux/lseek.c",
    "lib/dirent/__getdirentries.c",
    "lib/dirent/closedir.c",
    "lib/dirent/opendir.c",
    "lib/mes/__assert_fail.c",
    "lib/mes/__buffered_read.c",
    "lib/mes/__mes_debug.c",
    "lib/posix/execv.c",
    "lib/posix/getcwd.c",
    "lib/posix/getenv.c",
    "lib/posix/isatty.c",
    "lib/posix/open.c",
    "lib/posix/buffered-read.c",
    "lib/posix/setenv.c",
    "lib/posix/wait.c",
    "lib/stdio/fgetc.c",
    "lib/stdio/fputc.c",
    "lib/stdio/fputs.c",
    "lib/stdio/getc.c",
    "lib/stdio/getchar.c",
    "lib/stdio/putc.c",
    "lib/stdio/putchar.c",
    "lib/stdio/ungetc.c",
    "lib/stdlib/calloc.c",
    "lib/stdlib/free.c",
    "lib/stdlib/realloc.c",
    "lib/string/memchr.c",
    "lib/string/memcmp.c",
    "lib/string/memcpy.c",
    "lib/string/memmove.c",
    "lib/string/memset.c",
    "lib/string/strcmp.c",
    "lib/string/strcpy.c",
    "lib/string/strncmp.c",
    "lib/posix/raise.c",
    "lib/linux/access.c",
    "lib/linux/brk.c",
    "lib/linux/chdir.c",
    "lib/linux/chmod.c",
    "lib/linux/clock_gettime.c",
    "lib/linux/close.c",
    "lib/linux/dup.c",
    "lib/linux/dup2.c",
    "lib/linux/execve.c",
    "lib/linux/fcntl.c",
    "lib/linux/fork.c",
    "lib/linux/fstat.c",
    "lib/linux/fsync.c",
    "lib/linux/_getcwd.c",
    "lib/linux/getdents.c",
    "lib/linux/gettimeofday.c",
    "lib/linux/ioctl3.c",
    "lib/linux/link.c",
    "lib/linux/lstat.c",
    "lib/linux/_open3.c",
    "lib/linux/malloc.c",
    "lib/linux/mkdir.c",
    "lib/linux/nanosleep.c",
    "lib/linux/pipe.c",
    "lib/linux/_read.c",
    "lib/linux/readdir.c",
    "lib/linux/rename.c",
    "lib/linux/rmdir.c",
    "lib/linux/stat.c",
    "lib/linux/symlink.c",
    "lib/linux/time.c",
    "lib/linux/umask.c",
    "lib/linux/uname.c",
    "lib/linux/unlink.c",
    "lib/linux/utimensat.c",
    "lib/linux/wait4.c",
    "lib/linux/waitpid.c",
    "lib/linux/getpid.c",
    "lib/linux/kill.c",
    _ARCH + "_exit.c",
    _ARCH + "_write.c",
    _ARCH + "syscall.c",
]

# The C library that TCC needs, a superset of LIBC_SOURCES.
LIBC_TCC_SOURCES = LIBC_SOURCES + [
    "lib/ctype/islower.c",
    "lib/ctype/isupper.c",
    "lib/ctype/tolower.c",
    "lib/ctype/toupper.c",
    "lib/mes/abtod.c",
    "lib/mes/dtoab.c",
    "lib/mes/search-path.c",
    "lib/posix/execvp.c",
    "lib/stdio/fclose.c",
    "lib/stdio/fdopen.c",
    "lib/stdio/ferror.c",
    "lib/stdio/fflush.c",
    "lib/stdio/fopen.c",
    "lib/stdio/fprintf.c",
    "lib/stdio/fread.c",
    "lib/stdio/fseek.c",
    "lib/stdio/ftell.c",
    "lib/stdio/fwrite.c",
    "lib/stdio/printf.c",
    "lib/stdio/remove.c",
    "lib/stdio/snprintf.c",
    "lib/stdio/sprintf.c",
    "lib/stdio/sscanf.c",
    "lib/stdio/vfprintf.c",
    "lib/stdio/vprintf.c",
    "lib/stdio/vsnprintf.c",
    "lib/stdio/vsprintf.c",
    "lib/stdio/vsscanf.c",
    "lib/stdlib/abort.c",
    "lib/stdlib/qsort.c",
    "lib/stdlib/strtod.c",
    "lib/stdlib/strtof.c",
    "lib/stdlib/strtol.c",
    "lib/stdlib/strtold.c",
    "lib/stdlib/strtoll.c",
    "lib/stdlib/strtoul.c",
    "lib/stdlib/strtoull.c",
    "lib/string/memmem.c",
    "lib/string/strcat.c",
    "lib/string/strchr.c",
    "lib/string/strlwr.c",
    "lib/string/strncpy.c",
    "lib/string/strrchr.c",
    "lib/string/strstr.c",
    "lib/string/strupr.c",
    "lib/stub/sigaction.c",
    "lib/stub/ldexp.c",
    "lib/stub/mprotect.c",
    "lib/stub/localtime.c",
    "lib/stub/putenv.c",
    "lib/stub/realpath.c",
    "lib/stub/sigemptyset.c",
    "lib/x86_64-mes-mescc/setjmp.c",
]

# The Scheme interpreter.
MES_SOURCES = [
    "src/builtins.c",
    "src/cc.c",
    "src/core.c",
    "src/display.c",
    "src/eval-apply.c",
    "src/gc.c",
    "src/globals.c",
    "src/hash.c",
    "src/lib.c",
    "src/math.c",
    "src/mes.c",
    "src/module.c",
    "src/posix.c",
    "src/reader.c",
    "src/stack.c",
    "src/string.c",
    "src/struct.c",
    "src/symbol.c",
    "src/variable.c",
    "src/vector.c",
]
