# SPDX-FileCopyrightText: © 2024-2025 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@root//buck/shims:shims.bzl", "shims")

# UV toolchain configuration
# Currently a placeholder - uv is expected to be available in the environment
shims.export_file(
    name = "uv",
    src = "defs.bzl",
    visibility = ["PUBLIC"],
)
