# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@root//buck/shims:shims.bzl", depot = "shims")

depot.rust_library(
    name = "fozzie",
    srcs = ["lib.rs"],
    crate = "fozzie",
    crate_root = "lib.rs",
    visibility = ["PUBLIC"],
)
