# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@root//buck/shims:shims.bzl", depot = "shims")

depot.filegroup(
    name = "image",
    srcs = [
        "Dockerfile",
        "celld-browser",
    ],
    visibility = ["PUBLIC"],
)
