// SPDX-FileCopyrightText: © 2026 Austin Seipp
// SPDX-License-Identifier: Apache-2.0

/**
 * Parses arguments for the literal-import bootstrap generated by
 * `sieve_json_schema` in `../defs.bzl`. The build rule binds the schema
 * module to a declared dependency before type checking; no runtime
 * computed import bypasses the toolchain's ownership guard.
 *
 * @module
 */

import type { JsonSchemaOptions } from "@celld/sieve/json-schema";

function usage(): never {
  throw new Error(
    "usage: emit.ts <module> <out.json> [--io input|output] [--unrepresentable throw|any]",
  );
}

/** Parses the command line into a module, an output path and options. */
export function parseArgs(args: readonly string[]): {
  module: string;
  out: string;
  options: JsonSchemaOptions;
} {
  const positional: string[] = [];
  let io: JsonSchemaOptions["io"];
  let unrepresentable: JsonSchemaOptions["unrepresentable"];
  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (arg === "--io") {
      const value = args[++index];
      if (value !== "input" && value !== "output") usage();
      io = value;
    } else if (arg === "--unrepresentable") {
      const value = args[++index];
      if (value !== "throw" && value !== "any") usage();
      unrepresentable = value;
    } else {
      positional.push(arg);
    }
  }
  if (positional.length !== 2) usage();
  return {
    module: positional[0],
    out: positional[1],
    options: {
      ...(io === undefined ? {} : { io }),
      ...(unrepresentable === undefined ? {} : { unrepresentable }),
    },
  };
}
