load(
    "@cellar//bootstrap/stage0-posix:stage0.bzl",
    "stage0_platform",
)

stage0_platform(
    host_arch = "amd64",
    arch = "amd64",
    m2libc_dir = "amd64",
    arch_dir_upper = "AMD64",
    filegroup_name = "amd64-files",
    catm_src = "catm.hex2",
    catm_bin = ":hex2-0",
)
