# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# Explicit inventories from GMP 6.2.1 Makefile.am/configure.ac, never executed.

BASE_SOURCES = [
    "assert.c",
    "compat.c",
    "errno.c",
    "extract-dbl.c",
    "invalid.c",
    "memory.c",
    "mp_bpl.c",
    "mp_clz_tab.c",
    "mp_dv_tab.c",
    "mp_minv_tab.c",
    "mp_get_fns.c",
    "mp_set_fns.c",
    "version.c",
    "nextprime.c",
    "primesieve.c",
    "tal-reent.c",
]

API_SOURCES = {
    "mpz": [
        "mpz/2fac_ui.c",
        "mpz/add.c",
        "mpz/add_ui.c",
        "mpz/abs.c",
        "mpz/aorsmul.c",
        "mpz/aorsmul_i.c",
        "mpz/and.c",
        "mpz/array_init.c",
        "mpz/bin_ui.c",
        "mpz/bin_uiui.c",
        "mpz/cdiv_q.c",
        "mpz/cdiv_q_ui.c",
        "mpz/cdiv_qr.c",
        "mpz/cdiv_qr_ui.c",
        "mpz/cdiv_r.c",
        "mpz/cdiv_r_ui.c",
        "mpz/cdiv_ui.c",
        "mpz/cfdiv_q_2exp.c",
        "mpz/cfdiv_r_2exp.c",
        "mpz/clear.c",
        "mpz/clears.c",
        "mpz/clrbit.c",
        "mpz/cmp.c",
        "mpz/cmp_d.c",
        "mpz/cmp_si.c",
        "mpz/cmp_ui.c",
        "mpz/cmpabs.c",
        "mpz/cmpabs_d.c",
        "mpz/cmpabs_ui.c",
        "mpz/com.c",
        "mpz/combit.c",
        "mpz/cong.c",
        "mpz/cong_2exp.c",
        "mpz/cong_ui.c",
        "mpz/divexact.c",
        "mpz/divegcd.c",
        "mpz/dive_ui.c",
        "mpz/divis.c",
        "mpz/divis_ui.c",
        "mpz/divis_2exp.c",
        "mpz/dump.c",
        "mpz/export.c",
        "mpz/fac_ui.c",
        "mpz/fdiv_q.c",
        "mpz/fdiv_q_ui.c",
        "mpz/fdiv_qr.c",
        "mpz/fdiv_qr_ui.c",
        "mpz/fdiv_r.c",
        "mpz/fdiv_r_ui.c",
        "mpz/fdiv_ui.c",
        "mpz/fib_ui.c",
        "mpz/fib2_ui.c",
        "mpz/fits_sint.c",
        "mpz/fits_slong.c",
        "mpz/fits_sshort.c",
        "mpz/fits_uint.c",
        "mpz/fits_ulong.c",
        "mpz/fits_ushort.c",
        "mpz/gcd.c",
        "mpz/gcd_ui.c",
        "mpz/gcdext.c",
        "mpz/get_d.c",
        "mpz/get_d_2exp.c",
        "mpz/get_si.c",
        "mpz/get_str.c",
        "mpz/get_ui.c",
        "mpz/getlimbn.c",
        "mpz/hamdist.c",
        "mpz/import.c",
        "mpz/init.c",
        "mpz/init2.c",
        "mpz/inits.c",
        "mpz/inp_raw.c",
        "mpz/inp_str.c",
        "mpz/invert.c",
        "mpz/ior.c",
        "mpz/iset.c",
        "mpz/iset_d.c",
        "mpz/iset_si.c",
        "mpz/iset_str.c",
        "mpz/iset_ui.c",
        "mpz/jacobi.c",
        "mpz/kronsz.c",
        "mpz/kronuz.c",
        "mpz/kronzs.c",
        "mpz/kronzu.c",
        "mpz/lcm.c",
        "mpz/lcm_ui.c",
        "mpz/limbs_read.c",
        "mpz/limbs_write.c",
        "mpz/limbs_modify.c",
        "mpz/limbs_finish.c",
        "mpz/lucnum_ui.c",
        "mpz/lucnum2_ui.c",
        "mpz/lucmod.c",
        "mpz/mfac_uiui.c",
        "mpz/millerrabin.c",
        "mpz/mod.c",
        "mpz/mul.c",
        "mpz/mul_2exp.c",
        "mpz/mul_si.c",
        "mpz/mul_ui.c",
        "mpz/n_pow_ui.c",
        "mpz/neg.c",
        "mpz/nextprime.c",
        "mpz/oddfac_1.c",
        "mpz/out_raw.c",
        "mpz/out_str.c",
        "mpz/perfpow.c",
        "mpz/perfsqr.c",
        "mpz/popcount.c",
        "mpz/pow_ui.c",
        "mpz/powm.c",
        "mpz/powm_sec.c",
        "mpz/powm_ui.c",
        "mpz/pprime_p.c",
        "mpz/prodlimbs.c",
        "mpz/primorial_ui.c",
        "mpz/random.c",
        "mpz/random2.c",
        "mpz/realloc.c",
        "mpz/realloc2.c",
        "mpz/remove.c",
        "mpz/roinit_n.c",
        "mpz/root.c",
        "mpz/rootrem.c",
        "mpz/rrandomb.c",
        "mpz/scan0.c",
        "mpz/scan1.c",
        "mpz/set.c",
        "mpz/set_d.c",
        "mpz/set_f.c",
        "mpz/set_q.c",
        "mpz/set_si.c",
        "mpz/set_str.c",
        "mpz/set_ui.c",
        "mpz/setbit.c",
        "mpz/size.c",
        "mpz/sizeinbase.c",
        "mpz/sqrt.c",
        "mpz/sqrtrem.c",
        "mpz/stronglucas.c",
        "mpz/sub.c",
        "mpz/sub_ui.c",
        "mpz/swap.c",
        "mpz/tdiv_ui.c",
        "mpz/tdiv_q.c",
        "mpz/tdiv_q_2exp.c",
        "mpz/tdiv_q_ui.c",
        "mpz/tdiv_qr.c",
        "mpz/tdiv_qr_ui.c",
        "mpz/tdiv_r.c",
        "mpz/tdiv_r_2exp.c",
        "mpz/tdiv_r_ui.c",
        "mpz/tstbit.c",
        "mpz/ui_pow_ui.c",
        "mpz/ui_sub.c",
        "mpz/urandomb.c",
        "mpz/urandomm.c",
        "mpz/xor.c",
    ],
    "mpq": [
        "mpq/abs.c",
        "mpq/aors.c",
        "mpq/canonicalize.c",
        "mpq/clear.c",
        "mpq/clears.c",
        "mpq/cmp.c",
        "mpq/cmp_si.c",
        "mpq/cmp_ui.c",
        "mpq/div.c",
        "mpq/equal.c",
        "mpq/get_d.c",
        "mpq/get_den.c",
        "mpq/get_num.c",
        "mpq/get_str.c",
        "mpq/init.c",
        "mpq/inits.c",
        "mpq/inp_str.c",
        "mpq/inv.c",
        "mpq/md_2exp.c",
        "mpq/mul.c",
        "mpq/neg.c",
        "mpq/out_str.c",
        "mpq/set.c",
        "mpq/set_den.c",
        "mpq/set_num.c",
        "mpq/set_si.c",
        "mpq/set_str.c",
        "mpq/set_ui.c",
        "mpq/set_z.c",
        "mpq/set_d.c",
        "mpq/set_f.c",
        "mpq/swap.c",
    ],
    "mpf": [
        "mpf/init.c",
        "mpf/init2.c",
        "mpf/inits.c",
        "mpf/set.c",
        "mpf/set_ui.c",
        "mpf/set_si.c",
        "mpf/set_str.c",
        "mpf/set_d.c",
        "mpf/set_z.c",
        "mpf/set_q.c",
        "mpf/iset.c",
        "mpf/iset_ui.c",
        "mpf/iset_si.c",
        "mpf/iset_str.c",
        "mpf/iset_d.c",
        "mpf/clear.c",
        "mpf/clears.c",
        "mpf/get_str.c",
        "mpf/dump.c",
        "mpf/size.c",
        "mpf/eq.c",
        "mpf/reldiff.c",
        "mpf/sqrt.c",
        "mpf/random2.c",
        "mpf/inp_str.c",
        "mpf/out_str.c",
        "mpf/add.c",
        "mpf/add_ui.c",
        "mpf/sub.c",
        "mpf/sub_ui.c",
        "mpf/ui_sub.c",
        "mpf/mul.c",
        "mpf/mul_ui.c",
        "mpf/div.c",
        "mpf/div_ui.c",
        "mpf/cmp.c",
        "mpf/cmp_d.c",
        "mpf/cmp_z.c",
        "mpf/cmp_si.c",
        "mpf/cmp_ui.c",
        "mpf/mul_2exp.c",
        "mpf/div_2exp.c",
        "mpf/abs.c",
        "mpf/neg.c",
        "mpf/get_d.c",
        "mpf/get_d_2exp.c",
        "mpf/set_dfl_prec.c",
        "mpf/set_prc.c",
        "mpf/set_prc_raw.c",
        "mpf/get_dfl_prec.c",
        "mpf/get_prc.c",
        "mpf/ui_div.c",
        "mpf/sqrt_ui.c",
        "mpf/pow_ui.c",
        "mpf/urandomb.c",
        "mpf/swap.c",
        "mpf/get_si.c",
        "mpf/get_ui.c",
        "mpf/int_p.c",
        "mpf/ceilfloor.c",
        "mpf/trunc.c",
        "mpf/fits_sint.c",
        "mpf/fits_slong.c",
        "mpf/fits_sshort.c",
        "mpf/fits_uint.c",
        "mpf/fits_ulong.c",
        "mpf/fits_ushort.c",
    ],
    "rand": [
        "rand/rand.c",
        "rand/randclr.c",
        "rand/randdef.c",
        "rand/randiset.c",
        "rand/randlc2s.c",
        "rand/randlc2x.c",
        "rand/randmt.c",
        "rand/randmts.c",
        "rand/rands.c",
        "rand/randsd.c",
        "rand/randsdui.c",
        "rand/randbui.c",
        "rand/randmui.c",
    ],
    "printf": [
        "printf/asprintf.c",
        "printf/asprntffuns.c",
        "printf/doprnt.c",
        "printf/doprntf.c",
        "printf/doprnti.c",
        "printf/fprintf.c",
        "printf/obprintf.c",
        "printf/obvprintf.c",
        "printf/obprntffuns.c",
        "printf/printf.c",
        "printf/printffuns.c",
        "printf/snprintf.c",
        "printf/snprntffuns.c",
        "printf/sprintf.c",
        "printf/sprintffuns.c",
        "printf/vasprintf.c",
        "printf/vfprintf.c",
        "printf/vprintf.c",
        "printf/vsnprintf.c",
        "printf/vsprintf.c",
        "printf/repl-vsnprintf.c",
    ],
    "scanf": [
        "scanf/doscan.c",
        "scanf/fscanf.c",
        "scanf/fscanffuns.c",
        "scanf/scanf.c",
        "scanf/sscanf.c",
        "scanf/sscanffuns.c",
        "scanf/vfscanf.c",
        "scanf/vscanf.c",
        "scanf/vsscanf.c",
    ],
}

MPN_SOURCES = {
    "add": "mpn/generic/add.c",
    "add_1": "mpn/generic/add_1.c",
    "add_n": "mpn/generic/add_n.c",
    "sub": "mpn/generic/sub.c",
    "sub_1": "mpn/generic/sub_1.c",
    "sub_n": "mpn/generic/sub_n.c",
    "cnd_add_n": "mpn/generic/cnd_add_n.c",
    "cnd_sub_n": "mpn/generic/cnd_sub_n.c",
    "cnd_swap": "mpn/generic/cnd_swap.c",
    "neg": "mpn/generic/neg.c",
    "com": "mpn/generic/com.c",
    "mul_1": "mpn/generic/mul_1.c",
    "addmul_1": "mpn/generic/addmul_1.c",
    "submul_1": "mpn/generic/submul_1.c",
    "add_err1_n": "mpn/generic/add_err1_n.c",
    "add_err2_n": "mpn/generic/add_err2_n.c",
    "add_err3_n": "mpn/generic/add_err3_n.c",
    "sub_err1_n": "mpn/generic/sub_err1_n.c",
    "sub_err2_n": "mpn/generic/sub_err2_n.c",
    "sub_err3_n": "mpn/generic/sub_err3_n.c",
    "lshift": "mpn/generic/lshift.c",
    "rshift": "mpn/generic/rshift.c",
    "dive_1": "mpn/generic/dive_1.c",
    "diveby3": "mpn/generic/diveby3.c",
    "divis": "mpn/generic/divis.c",
    "divrem": "mpn/generic/divrem.c",
    "divrem_1": "mpn/generic/divrem_1.c",
    "divrem_2": "mpn/generic/divrem_2.c",
    "fib2_ui": "mpn/generic/fib2_ui.c",
    "fib2m": "mpn/generic/fib2m.c",
    "mod_1": "mpn/generic/mod_1.c",
    "mod_34lsub1": "mpn/generic/mod_34lsub1.c",
    "mode1o": "mpn/generic/mode1o.c",
    "pre_divrem_1": "mpn/generic/pre_divrem_1.c",
    "pre_mod_1": "mpn/generic/pre_mod_1.c",
    "dump": "mpn/generic/dump.c",
    "mod_1_1": "mpn/generic/mod_1_1.c",
    "mod_1_2": "mpn/generic/mod_1_2.c",
    "mod_1_3": "mpn/generic/mod_1_3.c",
    "mod_1_4": "mpn/generic/mod_1_4.c",
    "lshiftc": "mpn/generic/lshiftc.c",
    "mul": "mpn/generic/mul.c",
    "mul_fft": "mpn/generic/mul_fft.c",
    "mul_n": "mpn/generic/mul_n.c",
    "sqr": "mpn/generic/sqr.c",
    "mul_basecase": "mpn/generic/mul_basecase.c",
    "sqr_basecase": "mpn/generic/sqr_basecase.c",
    "nussbaumer_mul": "mpn/generic/nussbaumer_mul.c",
    "mulmid_basecase": "mpn/generic/mulmid_basecase.c",
    "toom42_mulmid": "mpn/generic/toom42_mulmid.c",
    "mulmid_n": "mpn/generic/mulmid_n.c",
    "mulmid": "mpn/generic/mulmid.c",
    "random": "mpn/generic/random.c",
    "random2": "mpn/generic/random2.c",
    "pow_1": "mpn/generic/pow_1.c",
    "rootrem": "mpn/generic/rootrem.c",
    "sqrtrem": "mpn/generic/sqrtrem.c",
    "sizeinbase": "mpn/generic/sizeinbase.c",
    "get_str": "mpn/generic/get_str.c",
    "set_str": "mpn/generic/set_str.c",
    "compute_powtab": "mpn/generic/compute_powtab.c",
    "scan0": "mpn/generic/scan0.c",
    "scan1": "mpn/generic/scan1.c",
    "popcount": "mpn/generic/popham.c",
    "hamdist": "mpn/generic/popham.c",
    "cmp": "mpn/generic/cmp.c",
    "zero_p": "mpn/generic/zero_p.c",
    "perfsqr": "mpn/generic/perfsqr.c",
    "perfpow": "mpn/generic/perfpow.c",
    "strongfibo": "mpn/generic/strongfibo.c",
    "gcd_11": "mpn/generic/gcd_11.c",
    "gcd_22": "mpn/generic/gcd_22.c",
    "gcd_1": "mpn/generic/gcd_1.c",
    "gcd": "mpn/generic/gcd.c",
    "gcdext_1": "mpn/generic/gcdext_1.c",
    "gcdext": "mpn/generic/gcdext.c",
    "gcd_subdiv_step": "mpn/generic/gcd_subdiv_step.c",
    "gcdext_lehmer": "mpn/generic/gcdext_lehmer.c",
    "div_q": "mpn/generic/div_q.c",
    "tdiv_qr": "mpn/generic/tdiv_qr.c",
    "jacbase": "mpn/generic/jacbase.c",
    "jacobi_2": "mpn/generic/jacobi_2.c",
    "jacobi": "mpn/generic/jacobi.c",
    "get_d": "mpn/generic/get_d.c",
    "matrix22_mul": "mpn/generic/matrix22_mul.c",
    "matrix22_mul1_inverse_vector": "mpn/generic/matrix22_mul1_inverse_vector.c",
    "hgcd_matrix": "mpn/generic/hgcd_matrix.c",
    "hgcd2": "mpn/generic/hgcd2.c",
    "hgcd_step": "mpn/generic/hgcd_step.c",
    "hgcd_reduce": "mpn/generic/hgcd_reduce.c",
    "hgcd": "mpn/generic/hgcd.c",
    "hgcd_appr": "mpn/generic/hgcd_appr.c",
    "hgcd2_jacobi": "mpn/generic/hgcd2_jacobi.c",
    "hgcd_jacobi": "mpn/generic/hgcd_jacobi.c",
    "mullo_n": "mpn/generic/mullo_n.c",
    "mullo_basecase": "mpn/generic/mullo_basecase.c",
    "sqrlo": "mpn/generic/sqrlo.c",
    "sqrlo_basecase": "mpn/generic/sqrlo_basecase.c",
    "toom22_mul": "mpn/generic/toom22_mul.c",
    "toom32_mul": "mpn/generic/toom32_mul.c",
    "toom42_mul": "mpn/generic/toom42_mul.c",
    "toom52_mul": "mpn/generic/toom52_mul.c",
    "toom62_mul": "mpn/generic/toom62_mul.c",
    "toom33_mul": "mpn/generic/toom33_mul.c",
    "toom43_mul": "mpn/generic/toom43_mul.c",
    "toom53_mul": "mpn/generic/toom53_mul.c",
    "toom54_mul": "mpn/generic/toom54_mul.c",
    "toom63_mul": "mpn/generic/toom63_mul.c",
    "toom44_mul": "mpn/generic/toom44_mul.c",
    "toom6h_mul": "mpn/generic/toom6h_mul.c",
    "toom6_sqr": "mpn/generic/toom6_sqr.c",
    "toom8h_mul": "mpn/generic/toom8h_mul.c",
    "toom8_sqr": "mpn/generic/toom8_sqr.c",
    "toom_couple_handling": "mpn/generic/toom_couple_handling.c",
    "toom2_sqr": "mpn/generic/toom2_sqr.c",
    "toom3_sqr": "mpn/generic/toom3_sqr.c",
    "toom4_sqr": "mpn/generic/toom4_sqr.c",
    "toom_eval_dgr3_pm1": "mpn/generic/toom_eval_dgr3_pm1.c",
    "toom_eval_dgr3_pm2": "mpn/generic/toom_eval_dgr3_pm2.c",
    "toom_eval_pm1": "mpn/generic/toom_eval_pm1.c",
    "toom_eval_pm2": "mpn/generic/toom_eval_pm2.c",
    "toom_eval_pm2exp": "mpn/generic/toom_eval_pm2exp.c",
    "toom_eval_pm2rexp": "mpn/generic/toom_eval_pm2rexp.c",
    "toom_interpolate_5pts": "mpn/generic/toom_interpolate_5pts.c",
    "toom_interpolate_6pts": "mpn/generic/toom_interpolate_6pts.c",
    "toom_interpolate_7pts": "mpn/generic/toom_interpolate_7pts.c",
    "toom_interpolate_8pts": "mpn/generic/toom_interpolate_8pts.c",
    "toom_interpolate_12pts": "mpn/generic/toom_interpolate_12pts.c",
    "toom_interpolate_16pts": "mpn/generic/toom_interpolate_16pts.c",
    "invertappr": "mpn/generic/invertappr.c",
    "invert": "mpn/generic/invert.c",
    "binvert": "mpn/generic/binvert.c",
    "mulmod_bnm1": "mpn/generic/mulmod_bnm1.c",
    "sqrmod_bnm1": "mpn/generic/sqrmod_bnm1.c",
    "div_qr_1": "mpn/generic/div_qr_1.c",
    "div_qr_1n_pi1": "mpn/generic/div_qr_1n_pi1.c",
    "div_qr_2": "mpn/generic/div_qr_2.c",
    "div_qr_2n_pi1": "mpn/generic/div_qr_2n_pi1.c",
    "div_qr_2u_pi1": "mpn/generic/div_qr_2u_pi1.c",
    "sbpi1_div_q": "mpn/generic/sbpi1_div_q.c",
    "sbpi1_div_qr": "mpn/generic/sbpi1_div_qr.c",
    "sbpi1_divappr_q": "mpn/generic/sbpi1_divappr_q.c",
    "dcpi1_div_q": "mpn/generic/dcpi1_div_q.c",
    "dcpi1_div_qr": "mpn/generic/dcpi1_div_qr.c",
    "dcpi1_divappr_q": "mpn/generic/dcpi1_divappr_q.c",
    "mu_div_qr": "mpn/generic/mu_div_qr.c",
    "mu_divappr_q": "mpn/generic/mu_divappr_q.c",
    "mu_div_q": "mpn/generic/mu_div_q.c",
    "bdiv_q_1": "mpn/generic/bdiv_q_1.c",
    "sbpi1_bdiv_q": "mpn/generic/sbpi1_bdiv_q.c",
    "sbpi1_bdiv_qr": "mpn/generic/sbpi1_bdiv_qr.c",
    "sbpi1_bdiv_r": "mpn/generic/sbpi1_bdiv_r.c",
    "dcpi1_bdiv_q": "mpn/generic/dcpi1_bdiv_q.c",
    "dcpi1_bdiv_qr": "mpn/generic/dcpi1_bdiv_qr.c",
    "mu_bdiv_q": "mpn/generic/mu_bdiv_q.c",
    "mu_bdiv_qr": "mpn/generic/mu_bdiv_qr.c",
    "bdiv_q": "mpn/generic/bdiv_q.c",
    "bdiv_qr": "mpn/generic/bdiv_qr.c",
    "broot": "mpn/generic/broot.c",
    "brootinv": "mpn/generic/brootinv.c",
    "bsqrt": "mpn/generic/bsqrt.c",
    "bsqrtinv": "mpn/generic/bsqrtinv.c",
    "divexact": "mpn/generic/divexact.c",
    "bdiv_dbm1c": "mpn/generic/bdiv_dbm1c.c",
    "redc_1": "mpn/generic/redc_1.c",
    "redc_2": "mpn/generic/redc_2.c",
    "redc_n": "mpn/generic/redc_n.c",
    "powm": "mpn/generic/powm.c",
    "powlo": "mpn/generic/powlo.c",
    "sec_powm": "mpn/generic/sec_powm.c",
    "sec_mul": "mpn/generic/sec_mul.c",
    "sec_sqr": "mpn/generic/sec_sqr.c",
    "sec_div_qr": "mpn/generic/sec_div.c",
    "sec_div_r": "mpn/generic/sec_div.c",
    "sec_pi1_div_qr": "mpn/generic/sec_pi1_div.c",
    "sec_pi1_div_r": "mpn/generic/sec_pi1_div.c",
    "sec_add_1": "mpn/generic/sec_aors_1.c",
    "sec_sub_1": "mpn/generic/sec_aors_1.c",
    "sec_invert": "mpn/generic/sec_invert.c",
    "trialdiv": "mpn/generic/trialdiv.c",
    "remove": "mpn/generic/remove.c",
    "and_n": "mpn/generic/logops_n.c",
    "andn_n": "mpn/generic/logops_n.c",
    "nand_n": "mpn/generic/logops_n.c",
    "ior_n": "mpn/generic/logops_n.c",
    "iorn_n": "mpn/generic/logops_n.c",
    "nior_n": "mpn/generic/logops_n.c",
    "xor_n": "mpn/generic/logops_n.c",
    "xnor_n": "mpn/generic/logops_n.c",
    "copyi": "mpn/generic/copyi.c",
    "copyd": "mpn/generic/copyd.c",
    "zero": "mpn/generic/zero.c",
    "sec_tabselect": "mpn/generic/sec_tabselect.c",
    "comb_tables": "mpn/generic/comb_tables.c",
    "add_n_sub_n": "mpn/generic/add_n_sub_n.c",
}

HEADERS = [
    "gmp-impl.h",
    "longlong.h",
    "gmp-h.in",
    "mpz/aors.h",
    "mpz/aors_ui.h",
    "mpz/fits_s.h",
    "mpz/mul_i.h",
    "mpf/fits_s.h",
    "mpf/fits_u.h",
    "rand/randmt.h",
    "mpn/generic/gmp-mparam.h",
]

TEST_SUPPORT = [
    "tests/memory.c",
    "tests/misc.c",
    "tests/refmpf.c",
    "tests/refmpn.c",
    "tests/refmpq.c",
    "tests/refmpz.c",
    "tests/spinner.c",
    "tests/trace.c",
]

TESTS = {
    "t-bswap": "tests/t-bswap.c",
    "t-constants": "tests/t-constants.c",
    "t-count_zeros": "tests/t-count_zeros.c",
    "t-hightomask": "tests/t-hightomask.c",
    "t-modlinv": "tests/t-modlinv.c",
    "t-popc": "tests/t-popc.c",
    "t-parity": "tests/t-parity.c",
    "t-sub": "tests/t-sub.c",
    "mpz-reuse": "tests/mpz/reuse.c",
    "mpz-t-addsub": "tests/mpz/t-addsub.c",
    "mpz-t-cmp": "tests/mpz/t-cmp.c",
    "mpz-t-mul": "tests/mpz/t-mul.c",
    "mpz-t-mul_i": "tests/mpz/t-mul_i.c",
    "mpz-t-tdiv": "tests/mpz/t-tdiv.c",
    "mpz-t-tdiv_ui": "tests/mpz/t-tdiv_ui.c",
    "mpz-t-fdiv": "tests/mpz/t-fdiv.c",
    "mpz-t-fdiv_ui": "tests/mpz/t-fdiv_ui.c",
    "mpz-t-cdiv_ui": "tests/mpz/t-cdiv_ui.c",
    "mpz-t-gcd": "tests/mpz/t-gcd.c",
    "mpz-t-gcd_ui": "tests/mpz/t-gcd_ui.c",
    "mpz-t-lcm": "tests/mpz/t-lcm.c",
    "mpz-t-invert": "tests/mpz/t-invert.c",
    "mpz-dive": "tests/mpz/dive.c",
    "mpz-dive_ui": "tests/mpz/dive_ui.c",
    "mpz-t-sqrtrem": "tests/mpz/t-sqrtrem.c",
    "mpz-convert": "tests/mpz/convert.c",
    "mpz-logic": "tests/mpz/logic.c",
    "mpz-t-bit": "tests/mpz/t-bit.c",
    "mpz-t-powm": "tests/mpz/t-powm.c",
    "mpz-t-powm_ui": "tests/mpz/t-powm_ui.c",
    "mpz-t-pow": "tests/mpz/t-pow.c",
    "mpz-t-div_2exp": "tests/mpz/t-div_2exp.c",
    "mpz-t-root": "tests/mpz/t-root.c",
    "mpz-t-perfsqr": "tests/mpz/t-perfsqr.c",
    "mpz-t-perfpow": "tests/mpz/t-perfpow.c",
    "mpz-t-jac": "tests/mpz/t-jac.c",
    "mpz-t-bin": "tests/mpz/t-bin.c",
    "mpz-t-get_d": "tests/mpz/t-get_d.c",
    "mpz-t-get_d_2exp": "tests/mpz/t-get_d_2exp.c",
    "mpz-t-get_si": "tests/mpz/t-get_si.c",
    "mpz-t-set_d": "tests/mpz/t-set_d.c",
    "mpz-t-set_si": "tests/mpz/t-set_si.c",
    "mpz-t-lucm": "tests/mpz/t-lucm.c",
    "mpz-t-fac_ui": "tests/mpz/t-fac_ui.c",
    "mpz-t-mfac_uiui": "tests/mpz/t-mfac_uiui.c",
    "mpz-t-primorial_ui": "tests/mpz/t-primorial_ui.c",
    "mpz-t-fib_ui": "tests/mpz/t-fib_ui.c",
    "mpz-t-lucnum_ui": "tests/mpz/t-lucnum_ui.c",
    "mpz-t-scan": "tests/mpz/t-scan.c",
    "mpz-t-fits": "tests/mpz/t-fits.c",
    "mpz-t-divis": "tests/mpz/t-divis.c",
    "mpz-t-divis_2exp": "tests/mpz/t-divis_2exp.c",
    "mpz-t-cong": "tests/mpz/t-cong.c",
    "mpz-t-cong_2exp": "tests/mpz/t-cong_2exp.c",
    "mpz-t-sizeinbase": "tests/mpz/t-sizeinbase.c",
    "mpz-t-set_str": "tests/mpz/t-set_str.c",
    "mpz-t-aorsmul": "tests/mpz/t-aorsmul.c",
    "mpz-t-cmp_d": "tests/mpz/t-cmp_d.c",
    "mpz-t-cmp_si": "tests/mpz/t-cmp_si.c",
    "mpz-t-hamdist": "tests/mpz/t-hamdist.c",
    "mpz-t-oddeven": "tests/mpz/t-oddeven.c",
    "mpz-t-popcount": "tests/mpz/t-popcount.c",
    "mpz-t-set_f": "tests/mpz/t-set_f.c",
    "mpz-t-import": "tests/mpz/t-import.c",
    "mpz-t-export": "tests/mpz/t-export.c",
    "mpz-t-pprime_p": "tests/mpz/t-pprime_p.c",
    "mpz-t-nextprime": "tests/mpz/t-nextprime.c",
    "mpz-t-remove": "tests/mpz/t-remove.c",
    "mpz-t-limbs": "tests/mpz/t-limbs.c",
    "mpq-t-aors": "tests/mpq/t-aors.c",
    "mpq-t-cmp": "tests/mpq/t-cmp.c",
    "mpq-t-cmp_ui": "tests/mpq/t-cmp_ui.c",
    "mpq-t-cmp_si": "tests/mpq/t-cmp_si.c",
    "mpq-t-equal": "tests/mpq/t-equal.c",
    "mpq-t-get_d": "tests/mpq/t-get_d.c",
    "mpq-t-get_str": "tests/mpq/t-get_str.c",
    "mpq-t-inv": "tests/mpq/t-inv.c",
    "mpq-t-md_2exp": "tests/mpq/t-md_2exp.c",
    "mpq-t-set_f": "tests/mpq/t-set_f.c",
    "mpq-t-set_str": "tests/mpq/t-set_str.c",
    "mpq-reuse": "tests/mpq/reuse.c",
    "mpq-t-cmp_z": "tests/mpq/t-cmp_z.c",
    "mpf-t-dm2exp": "tests/mpf/t-dm2exp.c",
    "mpf-t-conv": "tests/mpf/t-conv.c",
    "mpf-t-add": "tests/mpf/t-add.c",
    "mpf-t-sub": "tests/mpf/t-sub.c",
    "mpf-t-sqrt": "tests/mpf/t-sqrt.c",
    "mpf-t-sqrt_ui": "tests/mpf/t-sqrt_ui.c",
    "mpf-t-muldiv": "tests/mpf/t-muldiv.c",
    "mpf-reuse": "tests/mpf/reuse.c",
    "mpf-t-cmp_d": "tests/mpf/t-cmp_d.c",
    "mpf-t-cmp_si": "tests/mpf/t-cmp_si.c",
    "mpf-t-div": "tests/mpf/t-div.c",
    "mpf-t-fits": "tests/mpf/t-fits.c",
    "mpf-t-get_d": "tests/mpf/t-get_d.c",
    "mpf-t-get_d_2exp": "tests/mpf/t-get_d_2exp.c",
    "mpf-t-get_si": "tests/mpf/t-get_si.c",
    "mpf-t-get_ui": "tests/mpf/t-get_ui.c",
    "mpf-t-gsprec": "tests/mpf/t-gsprec.c",
    "mpf-t-int_p": "tests/mpf/t-int_p.c",
    "mpf-t-mul_ui": "tests/mpf/t-mul_ui.c",
    "mpf-t-set": "tests/mpf/t-set.c",
    "mpf-t-set_q": "tests/mpf/t-set_q.c",
    "mpf-t-set_si": "tests/mpf/t-set_si.c",
    "mpf-t-set_ui": "tests/mpf/t-set_ui.c",
    "mpf-t-trunc": "tests/mpf/t-trunc.c",
    "mpf-t-ui_div": "tests/mpf/t-ui_div.c",
    "mpf-t-eq": "tests/mpf/t-eq.c",
    "mpf-t-pow_ui": "tests/mpf/t-pow_ui.c",
    "mpn-t-aors_1": "tests/mpn/t-aors_1.c",
    "mpn-t-divrem_1": "tests/mpn/t-divrem_1.c",
    "mpn-t-mod_1": "tests/mpn/t-mod_1.c",
    "mpn-t-get_d": "tests/mpn/t-get_d.c",
    "mpn-t-iord_u": "tests/mpn/t-iord_u.c",
    "mpn-t-mp_bases": "tests/mpn/t-mp_bases.c",
    "mpn-t-perfsqr": "tests/mpn/t-perfsqr.c",
    "mpn-t-scan": "tests/mpn/t-scan.c",
    "mpn-logic": "tests/mpn/logic.c",
    "mpn-t-toom22": "tests/mpn/t-toom22.c",
    "mpn-t-toom32": "tests/mpn/t-toom32.c",
    "mpn-t-toom33": "tests/mpn/t-toom33.c",
    "mpn-t-toom42": "tests/mpn/t-toom42.c",
    "mpn-t-toom43": "tests/mpn/t-toom43.c",
    "mpn-t-toom44": "tests/mpn/t-toom44.c",
    "mpn-t-toom52": "tests/mpn/t-toom52.c",
    "mpn-t-toom53": "tests/mpn/t-toom53.c",
    "mpn-t-toom54": "tests/mpn/t-toom54.c",
    "mpn-t-toom62": "tests/mpn/t-toom62.c",
    "mpn-t-toom63": "tests/mpn/t-toom63.c",
    "mpn-t-toom6h": "tests/mpn/t-toom6h.c",
    "mpn-t-toom8h": "tests/mpn/t-toom8h.c",
    "mpn-t-toom2-sqr": "tests/mpn/t-toom2-sqr.c",
    "mpn-t-toom3-sqr": "tests/mpn/t-toom3-sqr.c",
    "mpn-t-toom4-sqr": "tests/mpn/t-toom4-sqr.c",
    "mpn-t-toom6-sqr": "tests/mpn/t-toom6-sqr.c",
    "mpn-t-toom8-sqr": "tests/mpn/t-toom8-sqr.c",
    "mpn-t-div": "tests/mpn/t-div.c",
    "mpn-t-mul": "tests/mpn/t-mul.c",
    "mpn-t-mullo": "tests/mpn/t-mullo.c",
    "mpn-t-sqrlo": "tests/mpn/t-sqrlo.c",
    "mpn-t-mulmod_bnm1": "tests/mpn/t-mulmod_bnm1.c",
    "mpn-t-sqrmod_bnm1": "tests/mpn/t-sqrmod_bnm1.c",
    "mpn-t-mulmid": "tests/mpn/t-mulmid.c",
    "mpn-t-hgcd": "tests/mpn/t-hgcd.c",
    "mpn-t-hgcd_appr": "tests/mpn/t-hgcd_appr.c",
    "mpn-t-matrix22": "tests/mpn/t-matrix22.c",
    "mpn-t-invert": "tests/mpn/t-invert.c",
    "mpn-t-bdiv": "tests/mpn/t-bdiv.c",
    "mpn-t-fib2m": "tests/mpn/t-fib2m.c",
    "mpn-t-broot": "tests/mpn/t-broot.c",
    "mpn-t-brootinv": "tests/mpn/t-brootinv.c",
    "mpn-t-minvert": "tests/mpn/t-minvert.c",
    "mpn-t-sizeinbase": "tests/mpn/t-sizeinbase.c",
    "mpn-t-gcd_11": "tests/mpn/t-gcd_11.c",
    "mpn-t-gcd_22": "tests/mpn/t-gcd_22.c",
    "mpn-t-gcdext_1": "tests/mpn/t-gcdext_1.c",
    "rand-t-iset": "tests/rand/t-iset.c",
    "rand-t-lc2exp": "tests/rand/t-lc2exp.c",
    "rand-t-mt": "tests/rand/t-mt.c",
    "rand-t-urbui": "tests/rand/t-urbui.c",
    "rand-t-urmui": "tests/rand/t-urmui.c",
    "rand-t-urndmm": "tests/rand/t-urndmm.c",
    "misc-t-printf": "tests/misc/t-printf.c",
    "misc-t-scanf": "tests/misc/t-scanf.c",
}

SOURCE_FILES = [
    "assert.c",
    "bootstrap.c",
    "compat.c",
    "errno.c",
    "extract-dbl.c",
    "gen-bases.c",
    "gen-fac.c",
    "gen-fib.c",
    "gen-jacobitab.c",
    "gen-psqr.c",
    "gen-trialdivtab.c",
    "gmp-h.in",
    "gmp-impl.h",
    "gmpxx.h",
    "invalid.c",
    "longlong.h",
    "memory.c",
    "mini-gmp/mini-gmp.c",
    "mini-gmp/mini-gmp.h",
    "mp_bpl.c",
    "mp_clz_tab.c",
    "mp_dv_tab.c",
    "mp_get_fns.c",
    "mp_minv_tab.c",
    "mp_set_fns.c",
    "mpf/abs.c",
    "mpf/add.c",
    "mpf/add_ui.c",
    "mpf/ceilfloor.c",
    "mpf/clear.c",
    "mpf/clears.c",
    "mpf/cmp.c",
    "mpf/cmp_d.c",
    "mpf/cmp_si.c",
    "mpf/cmp_ui.c",
    "mpf/cmp_z.c",
    "mpf/div.c",
    "mpf/div_2exp.c",
    "mpf/div_ui.c",
    "mpf/dump.c",
    "mpf/eq.c",
    "mpf/fits_s.h",
    "mpf/fits_sint.c",
    "mpf/fits_slong.c",
    "mpf/fits_sshort.c",
    "mpf/fits_u.h",
    "mpf/fits_uint.c",
    "mpf/fits_ulong.c",
    "mpf/fits_ushort.c",
    "mpf/get_d.c",
    "mpf/get_d_2exp.c",
    "mpf/get_dfl_prec.c",
    "mpf/get_prc.c",
    "mpf/get_si.c",
    "mpf/get_str.c",
    "mpf/get_ui.c",
    "mpf/init.c",
    "mpf/init2.c",
    "mpf/inits.c",
    "mpf/inp_str.c",
    "mpf/int_p.c",
    "mpf/iset.c",
    "mpf/iset_d.c",
    "mpf/iset_si.c",
    "mpf/iset_str.c",
    "mpf/iset_ui.c",
    "mpf/mul.c",
    "mpf/mul_2exp.c",
    "mpf/mul_ui.c",
    "mpf/neg.c",
    "mpf/out_str.c",
    "mpf/pow_ui.c",
    "mpf/random2.c",
    "mpf/reldiff.c",
    "mpf/set.c",
    "mpf/set_d.c",
    "mpf/set_dfl_prec.c",
    "mpf/set_prc.c",
    "mpf/set_prc_raw.c",
    "mpf/set_q.c",
    "mpf/set_si.c",
    "mpf/set_str.c",
    "mpf/set_ui.c",
    "mpf/set_z.c",
    "mpf/size.c",
    "mpf/sqrt.c",
    "mpf/sqrt_ui.c",
    "mpf/sub.c",
    "mpf/sub_ui.c",
    "mpf/swap.c",
    "mpf/trunc.c",
    "mpf/ui_div.c",
    "mpf/ui_sub.c",
    "mpf/urandomb.c",
    "mpn/generic/add.c",
    "mpn/generic/add_1.c",
    "mpn/generic/add_err1_n.c",
    "mpn/generic/add_err2_n.c",
    "mpn/generic/add_err3_n.c",
    "mpn/generic/add_n.c",
    "mpn/generic/add_n_sub_n.c",
    "mpn/generic/addmul_1.c",
    "mpn/generic/bdiv_dbm1c.c",
    "mpn/generic/bdiv_q.c",
    "mpn/generic/bdiv_q_1.c",
    "mpn/generic/bdiv_qr.c",
    "mpn/generic/binvert.c",
    "mpn/generic/broot.c",
    "mpn/generic/brootinv.c",
    "mpn/generic/bsqrt.c",
    "mpn/generic/bsqrtinv.c",
    "mpn/generic/cmp.c",
    "mpn/generic/cnd_add_n.c",
    "mpn/generic/cnd_sub_n.c",
    "mpn/generic/cnd_swap.c",
    "mpn/generic/com.c",
    "mpn/generic/comb_tables.c",
    "mpn/generic/compute_powtab.c",
    "mpn/generic/copyd.c",
    "mpn/generic/copyi.c",
    "mpn/generic/dcpi1_bdiv_q.c",
    "mpn/generic/dcpi1_bdiv_qr.c",
    "mpn/generic/dcpi1_div_q.c",
    "mpn/generic/dcpi1_div_qr.c",
    "mpn/generic/dcpi1_divappr_q.c",
    "mpn/generic/div_q.c",
    "mpn/generic/div_qr_1.c",
    "mpn/generic/div_qr_1n_pi1.c",
    "mpn/generic/div_qr_2.c",
    "mpn/generic/div_qr_2n_pi1.c",
    "mpn/generic/div_qr_2u_pi1.c",
    "mpn/generic/dive_1.c",
    "mpn/generic/diveby3.c",
    "mpn/generic/divexact.c",
    "mpn/generic/divis.c",
    "mpn/generic/divrem.c",
    "mpn/generic/divrem_1.c",
    "mpn/generic/divrem_2.c",
    "mpn/generic/dump.c",
    "mpn/generic/fib2_ui.c",
    "mpn/generic/fib2m.c",
    "mpn/generic/gcd.c",
    "mpn/generic/gcd_1.c",
    "mpn/generic/gcd_11.c",
    "mpn/generic/gcd_22.c",
    "mpn/generic/gcd_subdiv_step.c",
    "mpn/generic/gcdext.c",
    "mpn/generic/gcdext_1.c",
    "mpn/generic/gcdext_lehmer.c",
    "mpn/generic/get_d.c",
    "mpn/generic/get_str.c",
    "mpn/generic/gmp-mparam.h",
    "mpn/generic/hgcd.c",
    "mpn/generic/hgcd2.c",
    "mpn/generic/hgcd2_jacobi.c",
    "mpn/generic/hgcd_appr.c",
    "mpn/generic/hgcd_jacobi.c",
    "mpn/generic/hgcd_matrix.c",
    "mpn/generic/hgcd_reduce.c",
    "mpn/generic/hgcd_step.c",
    "mpn/generic/invert.c",
    "mpn/generic/invertappr.c",
    "mpn/generic/jacbase.c",
    "mpn/generic/jacobi.c",
    "mpn/generic/jacobi_2.c",
    "mpn/generic/logops_n.c",
    "mpn/generic/lshift.c",
    "mpn/generic/lshiftc.c",
    "mpn/generic/matrix22_mul.c",
    "mpn/generic/matrix22_mul1_inverse_vector.c",
    "mpn/generic/mod_1.c",
    "mpn/generic/mod_1_1.c",
    "mpn/generic/mod_1_2.c",
    "mpn/generic/mod_1_3.c",
    "mpn/generic/mod_1_4.c",
    "mpn/generic/mod_34lsub1.c",
    "mpn/generic/mode1o.c",
    "mpn/generic/mu_bdiv_q.c",
    "mpn/generic/mu_bdiv_qr.c",
    "mpn/generic/mu_div_q.c",
    "mpn/generic/mu_div_qr.c",
    "mpn/generic/mu_divappr_q.c",
    "mpn/generic/mul.c",
    "mpn/generic/mul_1.c",
    "mpn/generic/mul_basecase.c",
    "mpn/generic/mul_fft.c",
    "mpn/generic/mul_n.c",
    "mpn/generic/mullo_basecase.c",
    "mpn/generic/mullo_n.c",
    "mpn/generic/mulmid.c",
    "mpn/generic/mulmid_basecase.c",
    "mpn/generic/mulmid_n.c",
    "mpn/generic/mulmod_bnm1.c",
    "mpn/generic/neg.c",
    "mpn/generic/nussbaumer_mul.c",
    "mpn/generic/perfpow.c",
    "mpn/generic/perfsqr.c",
    "mpn/generic/popham.c",
    "mpn/generic/pow_1.c",
    "mpn/generic/powlo.c",
    "mpn/generic/powm.c",
    "mpn/generic/pre_divrem_1.c",
    "mpn/generic/pre_mod_1.c",
    "mpn/generic/random.c",
    "mpn/generic/random2.c",
    "mpn/generic/redc_1.c",
    "mpn/generic/redc_2.c",
    "mpn/generic/redc_n.c",
    "mpn/generic/remove.c",
    "mpn/generic/rootrem.c",
    "mpn/generic/rshift.c",
    "mpn/generic/sbpi1_bdiv_q.c",
    "mpn/generic/sbpi1_bdiv_qr.c",
    "mpn/generic/sbpi1_bdiv_r.c",
    "mpn/generic/sbpi1_div_q.c",
    "mpn/generic/sbpi1_div_qr.c",
    "mpn/generic/sbpi1_divappr_q.c",
    "mpn/generic/scan0.c",
    "mpn/generic/scan1.c",
    "mpn/generic/sec_aors_1.c",
    "mpn/generic/sec_div.c",
    "mpn/generic/sec_invert.c",
    "mpn/generic/sec_mul.c",
    "mpn/generic/sec_pi1_div.c",
    "mpn/generic/sec_powm.c",
    "mpn/generic/sec_sqr.c",
    "mpn/generic/sec_tabselect.c",
    "mpn/generic/set_str.c",
    "mpn/generic/sizeinbase.c",
    "mpn/generic/sqr.c",
    "mpn/generic/sqr_basecase.c",
    "mpn/generic/sqrlo.c",
    "mpn/generic/sqrlo_basecase.c",
    "mpn/generic/sqrmod_bnm1.c",
    "mpn/generic/sqrtrem.c",
    "mpn/generic/strongfibo.c",
    "mpn/generic/sub.c",
    "mpn/generic/sub_1.c",
    "mpn/generic/sub_err1_n.c",
    "mpn/generic/sub_err2_n.c",
    "mpn/generic/sub_err3_n.c",
    "mpn/generic/sub_n.c",
    "mpn/generic/submul_1.c",
    "mpn/generic/tdiv_qr.c",
    "mpn/generic/toom22_mul.c",
    "mpn/generic/toom2_sqr.c",
    "mpn/generic/toom32_mul.c",
    "mpn/generic/toom33_mul.c",
    "mpn/generic/toom3_sqr.c",
    "mpn/generic/toom42_mul.c",
    "mpn/generic/toom42_mulmid.c",
    "mpn/generic/toom43_mul.c",
    "mpn/generic/toom44_mul.c",
    "mpn/generic/toom4_sqr.c",
    "mpn/generic/toom52_mul.c",
    "mpn/generic/toom53_mul.c",
    "mpn/generic/toom54_mul.c",
    "mpn/generic/toom62_mul.c",
    "mpn/generic/toom63_mul.c",
    "mpn/generic/toom6_sqr.c",
    "mpn/generic/toom6h_mul.c",
    "mpn/generic/toom8_sqr.c",
    "mpn/generic/toom8h_mul.c",
    "mpn/generic/toom_couple_handling.c",
    "mpn/generic/toom_eval_dgr3_pm1.c",
    "mpn/generic/toom_eval_dgr3_pm2.c",
    "mpn/generic/toom_eval_pm1.c",
    "mpn/generic/toom_eval_pm2.c",
    "mpn/generic/toom_eval_pm2exp.c",
    "mpn/generic/toom_eval_pm2rexp.c",
    "mpn/generic/toom_interpolate_12pts.c",
    "mpn/generic/toom_interpolate_16pts.c",
    "mpn/generic/toom_interpolate_5pts.c",
    "mpn/generic/toom_interpolate_6pts.c",
    "mpn/generic/toom_interpolate_7pts.c",
    "mpn/generic/toom_interpolate_8pts.c",
    "mpn/generic/trialdiv.c",
    "mpn/generic/zero.c",
    "mpn/generic/zero_p.c",
    "mpq/abs.c",
    "mpq/aors.c",
    "mpq/canonicalize.c",
    "mpq/clear.c",
    "mpq/clears.c",
    "mpq/cmp.c",
    "mpq/cmp_si.c",
    "mpq/cmp_ui.c",
    "mpq/div.c",
    "mpq/equal.c",
    "mpq/get_d.c",
    "mpq/get_den.c",
    "mpq/get_num.c",
    "mpq/get_str.c",
    "mpq/init.c",
    "mpq/inits.c",
    "mpq/inp_str.c",
    "mpq/inv.c",
    "mpq/md_2exp.c",
    "mpq/mul.c",
    "mpq/neg.c",
    "mpq/out_str.c",
    "mpq/set.c",
    "mpq/set_d.c",
    "mpq/set_den.c",
    "mpq/set_f.c",
    "mpq/set_num.c",
    "mpq/set_si.c",
    "mpq/set_str.c",
    "mpq/set_ui.c",
    "mpq/set_z.c",
    "mpq/swap.c",
    "mpz/2fac_ui.c",
    "mpz/abs.c",
    "mpz/add.c",
    "mpz/add_ui.c",
    "mpz/and.c",
    "mpz/aors.h",
    "mpz/aors_ui.h",
    "mpz/aorsmul.c",
    "mpz/aorsmul_i.c",
    "mpz/array_init.c",
    "mpz/bin_ui.c",
    "mpz/bin_uiui.c",
    "mpz/cdiv_q.c",
    "mpz/cdiv_q_ui.c",
    "mpz/cdiv_qr.c",
    "mpz/cdiv_qr_ui.c",
    "mpz/cdiv_r.c",
    "mpz/cdiv_r_ui.c",
    "mpz/cdiv_ui.c",
    "mpz/cfdiv_q_2exp.c",
    "mpz/cfdiv_r_2exp.c",
    "mpz/clear.c",
    "mpz/clears.c",
    "mpz/clrbit.c",
    "mpz/cmp.c",
    "mpz/cmp_d.c",
    "mpz/cmp_si.c",
    "mpz/cmp_ui.c",
    "mpz/cmpabs.c",
    "mpz/cmpabs_d.c",
    "mpz/cmpabs_ui.c",
    "mpz/com.c",
    "mpz/combit.c",
    "mpz/cong.c",
    "mpz/cong_2exp.c",
    "mpz/cong_ui.c",
    "mpz/dive_ui.c",
    "mpz/divegcd.c",
    "mpz/divexact.c",
    "mpz/divis.c",
    "mpz/divis_2exp.c",
    "mpz/divis_ui.c",
    "mpz/dump.c",
    "mpz/export.c",
    "mpz/fac_ui.c",
    "mpz/fdiv_q.c",
    "mpz/fdiv_q_ui.c",
    "mpz/fdiv_qr.c",
    "mpz/fdiv_qr_ui.c",
    "mpz/fdiv_r.c",
    "mpz/fdiv_r_ui.c",
    "mpz/fdiv_ui.c",
    "mpz/fib2_ui.c",
    "mpz/fib_ui.c",
    "mpz/fits_s.h",
    "mpz/fits_sint.c",
    "mpz/fits_slong.c",
    "mpz/fits_sshort.c",
    "mpz/fits_uint.c",
    "mpz/fits_ulong.c",
    "mpz/fits_ushort.c",
    "mpz/gcd.c",
    "mpz/gcd_ui.c",
    "mpz/gcdext.c",
    "mpz/get_d.c",
    "mpz/get_d_2exp.c",
    "mpz/get_si.c",
    "mpz/get_str.c",
    "mpz/get_ui.c",
    "mpz/getlimbn.c",
    "mpz/hamdist.c",
    "mpz/import.c",
    "mpz/init.c",
    "mpz/init2.c",
    "mpz/inits.c",
    "mpz/inp_raw.c",
    "mpz/inp_str.c",
    "mpz/invert.c",
    "mpz/ior.c",
    "mpz/iset.c",
    "mpz/iset_d.c",
    "mpz/iset_si.c",
    "mpz/iset_str.c",
    "mpz/iset_ui.c",
    "mpz/jacobi.c",
    "mpz/kronsz.c",
    "mpz/kronuz.c",
    "mpz/kronzs.c",
    "mpz/kronzu.c",
    "mpz/lcm.c",
    "mpz/lcm_ui.c",
    "mpz/limbs_finish.c",
    "mpz/limbs_modify.c",
    "mpz/limbs_read.c",
    "mpz/limbs_write.c",
    "mpz/lucmod.c",
    "mpz/lucnum2_ui.c",
    "mpz/lucnum_ui.c",
    "mpz/mfac_uiui.c",
    "mpz/millerrabin.c",
    "mpz/mod.c",
    "mpz/mul.c",
    "mpz/mul_2exp.c",
    "mpz/mul_i.h",
    "mpz/mul_si.c",
    "mpz/mul_ui.c",
    "mpz/n_pow_ui.c",
    "mpz/neg.c",
    "mpz/nextprime.c",
    "mpz/oddfac_1.c",
    "mpz/out_raw.c",
    "mpz/out_str.c",
    "mpz/perfpow.c",
    "mpz/perfsqr.c",
    "mpz/popcount.c",
    "mpz/pow_ui.c",
    "mpz/powm.c",
    "mpz/powm_sec.c",
    "mpz/powm_ui.c",
    "mpz/pprime_p.c",
    "mpz/primorial_ui.c",
    "mpz/prodlimbs.c",
    "mpz/random.c",
    "mpz/random2.c",
    "mpz/realloc.c",
    "mpz/realloc2.c",
    "mpz/remove.c",
    "mpz/roinit_n.c",
    "mpz/root.c",
    "mpz/rootrem.c",
    "mpz/rrandomb.c",
    "mpz/scan0.c",
    "mpz/scan1.c",
    "mpz/set.c",
    "mpz/set_d.c",
    "mpz/set_f.c",
    "mpz/set_q.c",
    "mpz/set_si.c",
    "mpz/set_str.c",
    "mpz/set_ui.c",
    "mpz/setbit.c",
    "mpz/size.c",
    "mpz/sizeinbase.c",
    "mpz/sqrt.c",
    "mpz/sqrtrem.c",
    "mpz/stronglucas.c",
    "mpz/sub.c",
    "mpz/sub_ui.c",
    "mpz/swap.c",
    "mpz/tdiv_q.c",
    "mpz/tdiv_q_2exp.c",
    "mpz/tdiv_q_ui.c",
    "mpz/tdiv_qr.c",
    "mpz/tdiv_qr_ui.c",
    "mpz/tdiv_r.c",
    "mpz/tdiv_r_2exp.c",
    "mpz/tdiv_r_ui.c",
    "mpz/tdiv_ui.c",
    "mpz/tstbit.c",
    "mpz/ui_pow_ui.c",
    "mpz/ui_sub.c",
    "mpz/urandomb.c",
    "mpz/urandomm.c",
    "mpz/xor.c",
    "nextprime.c",
    "primesieve.c",
    "printf/asprintf.c",
    "printf/asprntffuns.c",
    "printf/doprnt.c",
    "printf/doprntf.c",
    "printf/doprnti.c",
    "printf/fprintf.c",
    "printf/obprintf.c",
    "printf/obprntffuns.c",
    "printf/obvprintf.c",
    "printf/printf.c",
    "printf/printffuns.c",
    "printf/repl-vsnprintf.c",
    "printf/snprintf.c",
    "printf/snprntffuns.c",
    "printf/sprintf.c",
    "printf/sprintffuns.c",
    "printf/vasprintf.c",
    "printf/vfprintf.c",
    "printf/vprintf.c",
    "printf/vsnprintf.c",
    "printf/vsprintf.c",
    "rand/rand.c",
    "rand/randbui.c",
    "rand/randclr.c",
    "rand/randdef.c",
    "rand/randiset.c",
    "rand/randlc2s.c",
    "rand/randlc2x.c",
    "rand/randmt.c",
    "rand/randmt.h",
    "rand/randmts.c",
    "rand/randmui.c",
    "rand/rands.c",
    "rand/randsd.c",
    "rand/randsdui.c",
    "scanf/doscan.c",
    "scanf/fscanf.c",
    "scanf/fscanffuns.c",
    "scanf/scanf.c",
    "scanf/sscanf.c",
    "scanf/sscanffuns.c",
    "scanf/vfscanf.c",
    "scanf/vscanf.c",
    "scanf/vsscanf.c",
    "tal-reent.c",
    "tests/cxx/t-ops2.h",
    "tests/memory.c",
    "tests/misc.c",
    "tests/misc/t-printf.c",
    "tests/misc/t-scanf.c",
    "tests/mpf/reuse.c",
    "tests/mpf/t-add.c",
    "tests/mpf/t-cmp_d.c",
    "tests/mpf/t-cmp_si.c",
    "tests/mpf/t-conv.c",
    "tests/mpf/t-div.c",
    "tests/mpf/t-dm2exp.c",
    "tests/mpf/t-eq.c",
    "tests/mpf/t-fits.c",
    "tests/mpf/t-get_d.c",
    "tests/mpf/t-get_d_2exp.c",
    "tests/mpf/t-get_si.c",
    "tests/mpf/t-get_ui.c",
    "tests/mpf/t-gsprec.c",
    "tests/mpf/t-int_p.c",
    "tests/mpf/t-mul_ui.c",
    "tests/mpf/t-muldiv.c",
    "tests/mpf/t-pow_ui.c",
    "tests/mpf/t-set.c",
    "tests/mpf/t-set_q.c",
    "tests/mpf/t-set_si.c",
    "tests/mpf/t-set_ui.c",
    "tests/mpf/t-sqrt.c",
    "tests/mpf/t-sqrt_ui.c",
    "tests/mpf/t-sub.c",
    "tests/mpf/t-trunc.c",
    "tests/mpf/t-ui_div.c",
    "tests/mpn/logic.c",
    "tests/mpn/t-aors_1.c",
    "tests/mpn/t-bdiv.c",
    "tests/mpn/t-broot.c",
    "tests/mpn/t-brootinv.c",
    "tests/mpn/t-div.c",
    "tests/mpn/t-divrem_1.c",
    "tests/mpn/t-fib2m.c",
    "tests/mpn/t-gcd_11.c",
    "tests/mpn/t-gcd_22.c",
    "tests/mpn/t-gcdext_1.c",
    "tests/mpn/t-get_d.c",
    "tests/mpn/t-hgcd.c",
    "tests/mpn/t-hgcd_appr.c",
    "tests/mpn/t-invert.c",
    "tests/mpn/t-iord_u.c",
    "tests/mpn/t-matrix22.c",
    "tests/mpn/t-minvert.c",
    "tests/mpn/t-mod_1.c",
    "tests/mpn/t-mp_bases.c",
    "tests/mpn/t-mul.c",
    "tests/mpn/t-mullo.c",
    "tests/mpn/t-mulmid.c",
    "tests/mpn/t-mulmod_bnm1.c",
    "tests/mpn/t-perfsqr.c",
    "tests/mpn/t-scan.c",
    "tests/mpn/t-sizeinbase.c",
    "tests/mpn/t-sqrlo.c",
    "tests/mpn/t-sqrmod_bnm1.c",
    "tests/mpn/t-toom2-sqr.c",
    "tests/mpn/t-toom22.c",
    "tests/mpn/t-toom3-sqr.c",
    "tests/mpn/t-toom32.c",
    "tests/mpn/t-toom33.c",
    "tests/mpn/t-toom4-sqr.c",
    "tests/mpn/t-toom42.c",
    "tests/mpn/t-toom43.c",
    "tests/mpn/t-toom44.c",
    "tests/mpn/t-toom52.c",
    "tests/mpn/t-toom53.c",
    "tests/mpn/t-toom54.c",
    "tests/mpn/t-toom6-sqr.c",
    "tests/mpn/t-toom62.c",
    "tests/mpn/t-toom63.c",
    "tests/mpn/t-toom6h.c",
    "tests/mpn/t-toom8-sqr.c",
    "tests/mpn/t-toom8h.c",
    "tests/mpn/toom-shared.h",
    "tests/mpn/toom-sqr-shared.h",
    "tests/mpq/reuse.c",
    "tests/mpq/t-aors.c",
    "tests/mpq/t-cmp.c",
    "tests/mpq/t-cmp_si.c",
    "tests/mpq/t-cmp_ui.c",
    "tests/mpq/t-cmp_z.c",
    "tests/mpq/t-equal.c",
    "tests/mpq/t-get_d.c",
    "tests/mpq/t-get_str.c",
    "tests/mpq/t-inv.c",
    "tests/mpq/t-md_2exp.c",
    "tests/mpq/t-set_f.c",
    "tests/mpq/t-set_str.c",
    "tests/mpz/convert.c",
    "tests/mpz/dive.c",
    "tests/mpz/dive_ui.c",
    "tests/mpz/logic.c",
    "tests/mpz/reuse.c",
    "tests/mpz/t-addsub.c",
    "tests/mpz/t-aorsmul.c",
    "tests/mpz/t-bin.c",
    "tests/mpz/t-bit.c",
    "tests/mpz/t-cdiv_ui.c",
    "tests/mpz/t-cmp.c",
    "tests/mpz/t-cmp_d.c",
    "tests/mpz/t-cmp_si.c",
    "tests/mpz/t-cong.c",
    "tests/mpz/t-cong_2exp.c",
    "tests/mpz/t-div_2exp.c",
    "tests/mpz/t-divis.c",
    "tests/mpz/t-divis_2exp.c",
    "tests/mpz/t-export.c",
    "tests/mpz/t-fac_ui.c",
    "tests/mpz/t-fdiv.c",
    "tests/mpz/t-fdiv_ui.c",
    "tests/mpz/t-fib_ui.c",
    "tests/mpz/t-fits.c",
    "tests/mpz/t-gcd.c",
    "tests/mpz/t-gcd_ui.c",
    "tests/mpz/t-get_d.c",
    "tests/mpz/t-get_d_2exp.c",
    "tests/mpz/t-get_si.c",
    "tests/mpz/t-hamdist.c",
    "tests/mpz/t-import.c",
    "tests/mpz/t-invert.c",
    "tests/mpz/t-jac.c",
    "tests/mpz/t-lcm.c",
    "tests/mpz/t-limbs.c",
    "tests/mpz/t-lucm.c",
    "tests/mpz/t-lucnum_ui.c",
    "tests/mpz/t-mfac_uiui.c",
    "tests/mpz/t-mul.c",
    "tests/mpz/t-mul_i.c",
    "tests/mpz/t-nextprime.c",
    "tests/mpz/t-oddeven.c",
    "tests/mpz/t-perfpow.c",
    "tests/mpz/t-perfsqr.c",
    "tests/mpz/t-popcount.c",
    "tests/mpz/t-pow.c",
    "tests/mpz/t-powm.c",
    "tests/mpz/t-powm_ui.c",
    "tests/mpz/t-pprime_p.c",
    "tests/mpz/t-primorial_ui.c",
    "tests/mpz/t-remove.c",
    "tests/mpz/t-root.c",
    "tests/mpz/t-scan.c",
    "tests/mpz/t-set_d.c",
    "tests/mpz/t-set_f.c",
    "tests/mpz/t-set_si.c",
    "tests/mpz/t-set_str.c",
    "tests/mpz/t-sizeinbase.c",
    "tests/mpz/t-sqrtrem.c",
    "tests/mpz/t-tdiv.c",
    "tests/mpz/t-tdiv_ui.c",
    "tests/rand/gmpstat.h",
    "tests/rand/t-iset.c",
    "tests/rand/t-lc2exp.c",
    "tests/rand/t-mt.c",
    "tests/rand/t-urbui.c",
    "tests/rand/t-urmui.c",
    "tests/rand/t-urndmm.c",
    "tests/refmpf.c",
    "tests/refmpn.c",
    "tests/refmpq.c",
    "tests/refmpz.c",
    "tests/spinner.c",
    "tests/t-bswap.c",
    "tests/t-constants.c",
    "tests/t-count_zeros.c",
    "tests/t-hightomask.c",
    "tests/t-modlinv.c",
    "tests/t-parity.c",
    "tests/t-popc.c",
    "tests/t-sub.c",
    "tests/tests.h",
    "tests/trace.c",
    "version.c",
]
