# SPDX-FileCopyrightText: © 2024-2025 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@prelude//toolchains:erlang.bzl", "system_erlang_toolchain")

system_erlang_toolchain(
    name = "erlang",
    visibility=["PUBLIC"],
)
