# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@root//buck/shims:shims.bzl", "shims")

shims.constraint(
    name = "instrumentation",
    default = "none",
    values = [
        "none",
        "fozzie",
        "fozzie-asan",
    ],
)
