# SPDX-FileCopyrightText: © 2024-2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@root//buck/shims:shims.bzl", depot = "shims")

# Export the demo script
depot.export_file(
    name = 'create-hunt-demo',
    src = 'create-hunt-demo.sh',
    visibility = ['PUBLIC'],
)
