vendor = false
precise_srcs = true
include_top_level = true

[buck]
file_name = "BUILD"

alias = "shims.alias"
filegroup = "shims.filegroup"
http_archive = "shims.http_archive"
git_fetch = "shims.git_fetch"

rust_library = "third_party_rust.rust_library"
rust_binary = "third_party_rust.rust_binary"
cxx_library = "third_party_rust.cxx_library"
prebuilt_cxx_library = "third_party_rust.prebuilt_cxx_library"
buildscript_genrule = "third_party_rust.buildscript_run"

buckfile_imports = """
# XXX (aseipp): use our shims for builds here to enforce more settings
load("@root//buck/shims/third_party_rust.bzl", "third_party_rust")
load("@root//buck/shims/shims.bzl", "shims")

# XXX: normal reindeer-generated code below
"""
