# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

HEADERS = [
    "lib/__fpending.h",
    "lib/alloca_.h",
    "lib/binary-io.h",
    "lib/cloexec.h",
    "lib/close-stream.h",
    "lib/error.h",
    "lib/exit.h",
    "lib/exitfail.h",
    "lib/getopt_.h",
    "lib/getopt_int.h",
    "lib/gettext.h",
    "lib/mbchar.h",
    "lib/mbuiter.h",
    "lib/mkstemp.h",
    "lib/obstack.h",
    "lib/printf-args.h",
    "lib/printf-parse.h",
    "lib/regex.h",
    "lib/regex_internal.h",
    "lib/size_max.h",
    "lib/stat-macros.h",
    "lib/stat_.h",
    "lib/stdbool_.h",
    "lib/stdint_.h",
    "lib/stdio--.h",
    "lib/stdio-safer.h",
    "lib/stdlib--.h",
    "lib/stdlib-safer.h",
    "lib/strcase.h",
    "lib/strnlen1.h",
    "lib/unistd--.h",
    "lib/unistd-safer.h",
    "lib/unlocked-io.h",
    "lib/vasnprintf.h",
    "lib/vasprintf.h",
    "lib/verror.h",
    "lib/wcwidth.h",
    "lib/xalloc.h",
    "lib/xsize.h",
    "lib/xvasprintf.h",
    "src/m4.h",
]
