# SPDX-FileCopyrightText: © 2024-2025 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@toolchains//deno:defs.bzl", "deno")

deno.run(
    name = "ccusage",
    package_id = "npm:ccusage@15.3.1",
    permissions = ["read", "write", "net", "env", "sys"],
)
