# SPDX-FileCopyrightText: © 2024-2025 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# TODO FIXME (aseipp): this is broken in CI somehow? i kind of dislike semgrep
# at this point; maybe we should look into gritql
#
# load("@root//buck/shims:shims.bzl", "shims")
#
# shims.command_test(
#     name = 'semgrep',
#     cmd = [
#         'semgrep',
#         '--config=buck/etc/semgrep/',
#         'src',
#         'tilde',
#     ],
# )
