# SPDX-FileCopyrightText: © 2024-2025 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@root//buck/shims:shims.bzl", depot = "shims")

depot.export_file(
    name = "settings.json",
    src = "settings.json",
    visibility = ["//src/tools/brainiac/..."],
)
