# SPDX-FileCopyrightText: © 2024-2025 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

load("@depot//buck/lib/tar:toolchain.bzl", "tar_toolchain")

# Create the tar toolchain
tar_toolchain(
    name = "tar",
    visibility = ["PUBLIC"],
)
