# SPDX-FileCopyrightText: © 2024-2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# check-spdx: a script to check the SPDX license headers of all files in the
# repository that are source code, and ensure they are correct. Run on change
# integration.

import re, sys, subprocess

# The year that copyright ranges are expected to end at. This is pinned rather
# than read from the clock so a run's verdict is a function of its inputs alone;
# a wall-clock year would flip every header in the repository from passing to
# failing at midnight on January 1st with nothing having changed, and would let
# a cached pass hide that. Bumping this is the deliberate act that opens the
# new year's header sweep.
COPYRIGHT_YEAR = 2026

# MARK: Bad file prefixes, suffixes, directory components, and exact matches

# Directory names that should be ignored anywhere in the path
BAD_DIRECTORY_COMPONENTS = [
    # version control
    ".git",
    ".github",
    # editors
    ".helix",
    ".vscode",
    ".zed",
    # development environments
    ".devcontainer",
    ".direnv",
    # caches
    ".ruff_cache",
    "__pycache__",
    # dependencies
    "node_modules",
]

BAD_PREFIXES = [
    # dev files
    ".watchmanconfig",
    ".envrc",
    # buck stuff: fixups, etc
    "buck/third-party/",
    "buck/prelude/",
    "cellar/bootstrap",
    ".buckconfig.d",
    "src/rtlcc/ulx3s-picosoc",
    # vendored proto files from Google/Bazel
    "src/tools/cache-server/protos/google/",
    "src/tools/cache-server/protos/build/",
]

BAD_SUFFIXES = [
    ".md",
    ".lock",
    ".txt",
    ".json",
    ".jsonc",
    ".jsonl",
    ".pem",
    ".exe",
    # golden test outputs are compared byte-for-byte
    ".expected",
    ".gitattributes",
    ".gitignore",
    ".ignore",
    ".buckconfig",
    ".buckroot",
    ".generated.bzl",
    ".buckargs",
    "Cargo.toml",
    "reindeer.toml",
]

BAD_FILES = [
    # REASON: autogenerated
    "buck/third-party/rust/BUILD",
    # REASON: these get put on command lines, and are not source code
    "buck/mode/local",
    "buck/mode/cached",
    "buck/mode/cached-upload",
    "buck/mode/remote",
    "buck/mode/debug",
    "buck/mode/release",
    "buck/mode/sandbox",
    "buck/mode/sandbox-symlink",
    # REASON FIXME TODO (aseipp): this file is technically MIT and not
    # Apache-2.0, and it has a modified copyright year.
    "buck/third-party/mimalloc/rust/lib.rs",
    # REASON: standard license text files don't need SPDX headers
    "buck/lib/oci/LICENSE",
    # REASON: shell rc file without extension
    "tilde/aseipp/dotfiles/direnv/direnvrc",
    # REASON: standard license text files don't need SPDX headers
    "tilde/aseipp/dotfiles/claude/agents/LICENSE",
    "tilde/aseipp/dotfiles/claude/commands/LICENSE",
    # REASON: these system account databases have no portable comment syntax;
    # adding a header would create malformed records in the resulting image.
    "src/images/minimos/base/config/group",
    "src/images/minimos/base/config/passwd",
    "src/images/minimos/base/config/shadow",
]


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


# MARK: SPDX check
def has_spdx_header(file: str, lines: list[str]) -> bool:
    # Accept both "2024-CURRENT_YEAR" and "CURRENT_YEAR" formats
    year_pattern = re.compile(r"^(2024-{}|{})$".format(COPYRIGHT_YEAR, COPYRIGHT_YEAR))

    # Allowed SPDX license identifiers
    allowed_licenses = ["Apache-2.0", "MIT", "BSD-2-Clause", "BSD-3-Clause", "ISC"]
    # Also allow compound licenses with AND/OR (both orderings)
    allowed_compound_licenses = ["Apache-2.0 AND MIT", "Apache-2.0 OR MIT", "MIT AND Apache-2.0", "MIT OR Apache-2.0"]

    # Comment styles as (copyright prefix, license prefix) pairs, without the
    # years and identifiers that follow.
    bzl_style = ("# SPDX-FileCopyrightText: © ", "# SPDX-License-Identifier: ")
    cxx_style = ("// SPDX-FileCopyrightText: © ", "// SPDX-License-Identifier: ")
    old_cxx_style = ("/* SPDX-FileCopyrightText: © ", "/* SPDX-License-Identifier: ")
    ocaml_style = ("(* SPDX-FileCopyrightText: © ", "(* SPDX-License-Identifier: ")
    lisp_style = (";; SPDX-FileCopyrightText: © ", ";; SPDX-License-Identifier: ")
    erlang_style = ("%% SPDX-FileCopyrightText: © ", "%% SPDX-License-Identifier: ")
    html_style = ("<!-- SPDX-FileCopyrightText: © ", "<!-- SPDX-License-Identifier: ")
    llvm_style = ("; SPDX-FileCopyrightText: © ", "; SPDX-License-Identifier: ")
    lua_style = ("-- SPDX-FileCopyrightText: © ", "-- SPDX-License-Identifier: ")
    # A markup file whose header sits inside a block comment that opens on its
    # own line. Lines are compared after stripping, so the marker is the bare
    # tag; the opening "<!--" is skipped as a preamble below.
    xml_block_style = ("SPDX-FileCopyrightText: © ", "SPDX-License-Identifier: ")

    # lit-style test files use the comment syntax of whatever language the
    # tool under test reads, so they may carry the header in any of these.
    lit_styles = [cxx_style, bzl_style, llvm_style, lisp_style]

    # Every entry lists the styles a file may open with. The file is held to
    # the first one its opening line starts with, else to the first listed.
    file_styles = {
        ".py": [bzl_style],
        "BUILD": [bzl_style],
        "BUCK": [bzl_style],
        "PACKAGE": [bzl_style],
        ".bzl": [bzl_style],
        ".bxl": [bzl_style],
        ".rs": [cxx_style],
        ".cpp": [cxx_style],
        ".hpp": [cxx_style],
        ".h": [cxx_style],
        ".c": [cxx_style],
        ".go": [cxx_style],
        ".ts": [cxx_style],
        ".tsx": [cxx_style],
        ".js": [cxx_style],
        ".mjs": [cxx_style],
        ".cs": [cxx_style],
        ".nix": [bzl_style],
        ".capnp": [bzl_style],
        ".S": [cxx_style],
        ".ld": [old_cxx_style],
        ".css": [old_cxx_style],
        ".ml": [ocaml_style],
        ".yaml": [bzl_style],
        ".fish": [bzl_style],
        ".toml": [bzl_style],
        # D-Bus policy files are XML that convention names ".conf", so this
        # entry has to precede the ".conf" one: the lookup below takes the
        # first matching suffix, not the longest.
        "/dbus-minimos-deny.conf": [xml_block_style],
        ".conf": [bzl_style],
        ".service": [bzl_style],
        # systemd resource-control units; same "#" comments as ".service".
        ".slice": [bzl_style],
        "/hostname": [bzl_style],
        "/hosts": [bzl_style],
        "/os-release": [bzl_style],
        "/profile": [bzl_style],
        ".html": [html_style],
        ".wat": [lisp_style],
        ".wit": [cxx_style],
        ".zuo": [lisp_style],
        ".sv": [cxx_style],
        ".erl": [erlang_style],
        ".luau": [lua_style],
        ".hurl": [bzl_style],
        ".test": lit_styles,
        ".check": lit_styles,
    }

    file_ext = None
    for key in file_styles.keys():
        if file == key or file.endswith(key):
            file_ext = key
            break
    if file_ext is None:
        eprint(f"Error: {file} is an unknown file type, hard failing!")
        return False

    styles = file_styles[file_ext]
    copyright_prefix, license_prefix = styles[0]
    for style in styles:
        if lines and lines[0].strip().startswith(style[0]):
            copyright_prefix, license_prefix = style
            break

    # HTML requires its doctype before other markup. Treat that declaration as
    # a format preamble, then require the SPDX header immediately after it.
    # A block comment that opens on its own line is the same kind of preamble.
    i = 0
    if (
        file_ext == ".html"
        and lines
        and lines[0].strip().lower() == "<!doctype html>"
    ):
        i = 1
    elif (
        copyright_prefix == xml_block_style[0]
        and lines
        and lines[0].strip() == "<!--"
    ):
        i = 1

    # Look for one or more copyright lines followed by license line
    copyright_found = False

    # Check for at least one copyright line
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith(copyright_prefix):
            # Extract the year part from the copyright line
            # Format is: "PREFIX YYYY[-YYYY] Name"
            remainder = line[len(copyright_prefix) :].strip()
            # Extract just the year part (first token)
            parts = remainder.split(None, 1)
            if len(parts) > 0:
                year_part = parts[0]
                if not year_pattern.match(year_part):
                    eprint(
                        f"Error: {file} has incorrect year format '{year_part}'. Expected '2024-{COPYRIGHT_YEAR}' or '{COPYRIGHT_YEAR}'"
                    )
                    return False
            copyright_found = True
            i += 1
        else:
            break

    if not copyright_found:
        eprint(f"Error: {file} does not have the correct SPDX copyright header!")
        return False

    # Check for license line
    if i >= len(lines):
        eprint(f"Error: {file} is missing SPDX license header!")
        return False

    license_line = lines[i].strip()
    if not license_line.startswith(license_prefix):
        eprint(f"Error: {file} does not have the correct SPDX license header format!")
        return False

    # Extract the license identifier
    # Handle different comment closing styles
    license_id = license_line[len(license_prefix) :].strip()
    if license_id.endswith(" */"):
        license_id = license_id[:-3].strip()
    elif license_id.endswith(" *)"):
        license_id = license_id[:-3].strip()
    elif license_id.endswith(" -->"):
        license_id = license_id[:-4].strip()

    # Check if it's an allowed license
    if (
        license_id not in allowed_licenses
        and license_id not in allowed_compound_licenses
    ):
        eprint(
            f"Error: {file} has unsupported license '{license_id}'. Allowed licenses: {', '.join(allowed_licenses + allowed_compound_licenses)}"
        )
        return False

    return True


# MARK: Entry point
def main():
    if len(sys.argv) != 2:
        eprint(f"usage: {sys.argv[0]} <path-to-jj-dotslash-file>")
        exit(2)

    # The jj to run is passed in as a build artifact rather than resolved from
    # PATH, so the file list comes from a version of jj the build graph knows
    # about. It is a DotSlash file, so it is launched the same way the buck2
    # lint test launches buck2: through the interpreter, by name.
    jj = sys.argv[1]

    # run 'jj files' command and get line-by-line output
    files = (
        subprocess.run(
            ["dotslash", jj, "file", "list"],
            stdout=subprocess.PIPE,
            check=True,
        )
        .stdout.decode("utf-8")
        .strip()
        .splitlines()
    )

    exit_code = 0
    for file in files:
        # normalize \ to / on Windows
        file = file.replace("\\", "/")
        # skip exact matches
        if file in BAD_FILES:
            continue
        # skip files that have bad prefixes
        if any(file.startswith(prefix) for prefix in BAD_PREFIXES):
            continue
        # and bad suffixes
        if any(file.endswith(suffix) for suffix in BAD_SUFFIXES):
            continue
        # skip files with banned directory components
        path_parts = file.split("/")
        if any(component in BAD_DIRECTORY_COMPONENTS for component in path_parts):
            continue

        print(f"Checking {file}...")
        with open(file, "r", encoding="utf-8") as f:
            lines = f.readlines()
            # quick path: if the file starts with '#!' it's a script, skip it.
            # An empty file has no first line to test, and no header either, so
            # it falls through and is reported by the check below.
            if lines and lines[0].startswith("#!"):
                continue
            if not has_spdx_header(file, lines):
                exit_code = 1
    exit(exit_code)


if __name__ == "__main__":
    main()
