# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

"""C# toolchain and build rules.

The toolchain drives the .NET SDK's Roslyn compiler directly (no MSBuild, no
NuGet restore): a `csharp_library` is one `csc` invocation producing an IL
assembly, and a `csharp_binary` is that plus whatever the selected *profile*
needs to make it runnable:

  jit     the IL assembly beside a runtimeconfig.json, run by the SDK's
          `dotnet` host with tiered compilation and dynamic PGO switched off
  pgojit  the same layout with dynamic PGO switched on
  r2r     the assemblies precompiled by crossgen2 (ReadyToRun) for fast
          startup; hot code is still re-jitted
  aot     ILCompiler and the platform linker produce one native executable

The profile comes from the `toolchains//cfg/csharp:profile` constraint
(`-m aot`, `-m r2r`, ...) unless the target pins one with `profile = ...`.
`mode//:build-mode` chooses between unoptimized and optimized compilation
for every profile.

Dependencies on NuGet packages are prebuilt assemblies: `nuget_archive`
downloads one pinned .nupkg and `csharp_prebuilt_library` names an assembly
inside it. Nothing here resolves package graphs.
"""

load("@prelude//cxx:cxx_toolchain_types.bzl", "CxxToolchainInfo")

PROFILES = ["jit", "pgojit", "r2r", "aot"]

# Runtime identifiers keyed by the exec-platform constraints that select the
# SDK and compiler packages able to run there.
RID_EXEC_CONSTRAINTS = {
    "linux-arm64": ("config//os:linux", "config//cpu:arm64"),
    "linux-x64": ("config//os:linux", "config//cpu:x86_64"),
    "osx-arm64": ("config//os:macos", "config//cpu:arm64"),
    "osx-x64": ("config//os:macos", "config//cpu:x86_64"),
    "win-arm64": ("config//os:windows", "config//cpu:arm64"),
    "win-x64": ("config//os:windows", "config//cpu:x86_64"),
}

# Runtime identifiers keyed by the target triple the code is built for.
RID_TARGET_CONSTRAINTS = {
    "linux-arm64": "toolchains//cfg/target:target[aarch64-unknown-linux-gnu]",
    "linux-x64": "toolchains//cfg/target:target[x86_64-unknown-linux-gnu]",
    "osx-arm64": "toolchains//cfg/target:target[aarch64-apple-darwin]",
    "osx-x64": "toolchains//cfg/target:target[x86_64-apple-darwin]",
    "win-arm64": "toolchains//cfg/target:target[aarch64-pc-windows-msvc]",
    "win-x64": "toolchains//cfg/target:target[x86_64-pc-windows-msvc]",
}

# What `<ImplicitUsings>enable</ImplicitUsings>` adds to a Microsoft.NET.Sdk
# console project.
IMPLICIT_USINGS = """// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
"""

# MARK: Providers

CSharpToolchainInfo = provider(
    doc = "A .NET SDK plus the packages the binary profiles need",
    fields = {
        # RunInfo of the action helper (tool.py)
        "tool": provider_field(typing.Any),
        # Root directory of the SDK that runs on the exec platform
        "sdk": provider_field(typing.Any),
        "sdk_version": provider_field(str),
        "runtime_version": provider_field(str),
        "tfm": provider_field(str),
        "lang_version": provider_field(str),
        "build_mode": provider_field(str),
        "profile": provider_field(str),
        # Runtime identifier of the target platform
        "rid": provider_field(str),
        # Root of runtime.<rid>.Microsoft.DotNet.ILCompiler for the exec platform
        "ilc": provider_field(typing.Any, default = None),
        # Root of Microsoft.NETCore.App.Crossgen2.<rid> for the exec platform
        "crossgen2": provider_field(typing.Any, default = None),
        # Root of Microsoft.NETCore.App.Runtime.NativeAOT.<rid> for the target
        "nativeaot_pack": provider_field(typing.Any, default = None),
        # Linker the AOT link asks the C compiler driver for (-fuse-ld=)
        "aot_linker_flavor": provider_field(typing.Any, default = None),
    },
)

CSharpAssembly = record(
    name = field(str),
    assembly = field(Artifact),
    pdb = field(Artifact | None, default = None),
)

CSharpLibraryInfo = provider(
    doc = "An IL assembly and everything it references",
    fields = {
        "name": provider_field(str),
        "assembly": provider_field(typing.Any),
        "pdb": provider_field(typing.Any, default = None),
        # Every assembly reachable through deps, keyed by simple name and in
        # dependency order, this one excluded.
        "transitive": provider_field(typing.Any),
    },
)

def _default_output(dep) -> Artifact | None:
    """The single output of a downloaded package, or None for the empty
    filegroup that stands in for a package the platform does not have."""
    if dep == None:
        return None
    outputs = dep[DefaultInfo].default_outputs
    if len(outputs) == 0:
        return None
    if len(outputs) != 1:
        fail("{} should have exactly one output, found {}".format(dep.label, outputs))
    return outputs[0]

def _transitive_deps(deps: list[Dependency]) -> dict[str, CSharpAssembly]:
    """Every assembly the deps reach, dependencies before dependents."""
    result = {}
    for dep in deps:
        info = dep[CSharpLibraryInfo]
        for name, assembly in info.transitive.items():
            if name in result and result[name].assembly != assembly.assembly:
                fail("two different assemblies are both named {}: {} and {}".format(
                    name,
                    result[name].assembly,
                    assembly.assembly,
                ))
            result[name] = assembly
        result[info.name] = CSharpAssembly(name = info.name, assembly = info.assembly, pdb = info.pdb)
    return result

def _warning_level(tfm: str) -> int:
    """The SDK's default WarningLevel for a .NETCoreApp target: the
    framework's major version."""
    if not tfm.startswith("net"):
        return 4
    return int(tfm[3:].split(".")[0])

# MARK: Toolchain

def _csharp_toolchain_impl(ctx: AnalysisContext) -> list[Provider]:
    return [
        DefaultInfo(),
        CSharpToolchainInfo(
            tool = ctx.attrs.tool[RunInfo],
            sdk = _default_output(ctx.attrs.sdk),
            sdk_version = ctx.attrs.sdk_version,
            runtime_version = ctx.attrs.runtime_version,
            tfm = ctx.attrs.tfm,
            lang_version = ctx.attrs.lang_version,
            build_mode = ctx.attrs.build_mode,
            profile = ctx.attrs.profile,
            rid = ctx.attrs.rid,
            ilc = _default_output(ctx.attrs.ilc),
            crossgen2 = _default_output(ctx.attrs.crossgen2),
            nativeaot_pack = _default_output(ctx.attrs.nativeaot_pack),
            aot_linker_flavor = ctx.attrs.aot_linker_flavor,
        ),
    ]

csharp_toolchain = rule(
    impl = _csharp_toolchain_impl,
    attrs = {
        "sdk": attrs.exec_dep(),
        "ilc": attrs.option(attrs.exec_dep(), default = None),
        "crossgen2": attrs.option(attrs.exec_dep(), default = None),
        "nativeaot_pack": attrs.option(attrs.dep(), default = None),
        "tool": attrs.exec_dep(default = "toolchains//csharp:tool"),
        "rid": attrs.string(),
        "sdk_version": attrs.string(),
        "runtime_version": attrs.string(),
        "tfm": attrs.string(),
        "lang_version": attrs.string(default = "latest"),
        "build_mode": attrs.enum(["debug", "release"]),
        "profile": attrs.enum(PROFILES),
        "aot_linker_flavor": attrs.option(attrs.string(), default = None),
    },
    is_toolchain_rule = True,
)

def _dotnet_impl(ctx: AnalysisContext) -> list[Provider]:
    """`buck2 run toolchains//csharp:dotnet -- --info`: the downloaded host."""
    sdk = _default_output(ctx.attrs.sdk)
    return [
        DefaultInfo(default_output = sdk),
        RunInfo(args = cmd_args(sdk, format = "{}/" + ctx.attrs.muxer)),
    ]

dotnet_host = rule(
    impl = _dotnet_impl,
    attrs = {
        "sdk": attrs.exec_dep(),
        "muxer": attrs.string(default = "dotnet"),
    },
)

def _executable_package_impl(ctx: AnalysisContext) -> list[Provider]:
    """A copy of a downloaded NuGet package with its tools marked executable:
    .nupkg zip entries carry no Unix permission bits."""
    out = ctx.actions.declare_output(ctx.label.name, dir = True)
    cmd = cmd_args(
        ctx.attrs.tool[RunInfo],
        "executable",
        "--source",
        _default_output(ctx.attrs.src),
        "--out",
        out.as_output(),
    )
    cmd.add(cmd_args(ctx.attrs.executables, format = "--chmod={}"))
    ctx.actions.run(cmd, category = "csharp_executable_package", identifier = ctx.label.name)
    return [DefaultInfo(default_output = out)]

executable_package = rule(
    impl = _executable_package_impl,
    attrs = {
        "src": attrs.dep(),
        "executables": attrs.list(attrs.string()),
        "tool": attrs.exec_dep(default = "toolchains//csharp:tool"),
    },
)

# MARK: Downloads

def _exec_select(rids: list[str], f):
    """Nested os/cpu select over the exec platforms, mapping each runtime
    identifier to f(rid); resolves in the exec configuration through an
    exec_dep so the chosen package can run where actions run."""
    by_os = {}
    for rid in rids:
        os_constraint, cpu_constraint = RID_EXEC_CONSTRAINTS[rid]
        by_os.setdefault(os_constraint, {})[cpu_constraint] = f(rid)
    return select({os_constraint: select(cpus) for os_constraint, cpus in by_os.items()})

def _target_select(rids: list[str], f, default):
    """Select over the target triples, mapping each runtime identifier to
    f(rid); resolves in the target configuration."""
    choices = {RID_TARGET_CONSTRAINTS[rid]: f(rid) for rid in rids}
    choices["DEFAULT"] = default
    return select(choices)

def download_dotnet_sdk(version: str, hashes: dict[str, str]):
    """Download the official SDK archive for every runtime identifier in
    `hashes` and declare `:sdk-{version}`, selecting among them for the
    exec platform."""
    for rid, sha256 in hashes.items():
        ext = "zip" if rid.startswith("win") else "tar.gz"
        native.http_archive(
            name = "sdk-{}-{}".format(version, rid),
            sha256 = sha256,
            type = ext,
            urls = ["https://builds.dotnet.microsoft.com/dotnet/Sdk/{version}/dotnet-sdk-{version}-{rid}.{ext}".format(
                version = version,
                rid = rid,
                ext = ext,
            )],
            visibility = [],
        )
    native.alias(
        name = "sdk-{}".format(version),
        actual = _exec_select(hashes.keys(), lambda rid: ":sdk-{}-{}".format(version, rid)),
    )

def nuget_url(package: str, version: str, source: str | None = None) -> str:
    """The flat-container URL nuget.org (or the feed whose V3 flat-container
    base URL is `source`) serves a package's .nupkg from."""
    lower_package = package.lower()
    lower_version = version.lower()
    base = source or "https://api.nuget.org/v3-flatcontainer/"
    return "{b}{p}/{v}/{p}.{v}.nupkg".format(b = base, p = lower_package, v = lower_version)

def _feed_archive_impl(ctx: AnalysisContext) -> list[Provider]:
    # buck2's downloads start with a HEAD request, which Azure DevOps feeds
    # refuse, so nugetify downloads the package (GET), checks its SHA-256
    # and unpacks it, locally, where the network is.
    contents = ctx.actions.declare_output("contents", dir = True)
    ctx.actions.run(
        cmd_args(
            ctx.attrs._nugetify[RunInfo],
            "fetch",
            "-sha256",
            ctx.attrs.sha256,
            ctx.attrs.url,
            contents.as_output(),
        ),
        category = "nuget_fetch",
        local_only = True,
    )
    return [DefaultInfo(
        default_output = contents,
        sub_targets = {path: [DefaultInfo(default_output = contents.project(path))] for path in ctx.attrs.sub_targets},
    )]

_feed_archive = rule(
    impl = _feed_archive_impl,
    attrs = {
        "sha256": attrs.string(),
        "sub_targets": attrs.list(attrs.string(), default = []),
        "url": attrs.string(),
        "_nugetify": attrs.exec_dep(default = "root//buck/tools/nugetify:nugetify"),
    },
)

def nuget_archive(name: str, package: str, version: str, sha256: str, sub_targets: list[str] = [], visibility: list[str] = [], source: str | None = None):
    """Download one pinned NuGet package (a zip file) from nuget.org, or the
    feed at `source`. The files named in `sub_targets` are addressable as
    `:name[path]`."""
    if source:
        _feed_archive(
            name = name,
            sha256 = sha256,
            sub_targets = sub_targets,
            url = nuget_url(package, version, source),
            visibility = visibility,
        )
        return
    native.http_archive(
        name = name,
        sha256 = sha256,
        sub_targets = sub_targets,
        type = "zip",
        urls = [nuget_url(package, version, source)],
        visibility = visibility,
    )

def download_runtime_packages(version: str, kind: str, package: str, hashes: dict[str, str], target: bool, executables: list[str] = []):
    """Download the per-RID package `package` (with `{rid}` substituted) for
    every runtime identifier in `hashes` and declare `:{kind}-{version}`.

    Exec-platform packages (compilers) select on the machine running the
    build and fall back to `:unavailable`, an empty filegroup, elsewhere;
    the files named in `executables` are marked so, since zip entries carry
    no permission bits. Target-platform packages (runtime packs) select on
    the target triple and are None where no package exists, so unrelated
    profiles keep working."""
    for rid, sha256 in hashes.items():
        name = "{}-{}-{}".format(kind, version, rid)
        nuget_archive(
            name = name if not executables else name + "-nupkg",
            package = package.format(rid = rid),
            version = version,
            sha256 = sha256,
        )
        if executables:
            executable_package(
                name = name,
                src = ":" + name + "-nupkg",
                executables = executables,
            )
    f = lambda rid: ":{}-{}-{}".format(kind, version, rid)
    if target:
        return _target_select(hashes.keys(), f, None)
    by_os = {}
    for rid in hashes.keys():
        os_constraint, cpu_constraint = RID_EXEC_CONSTRAINTS[rid]
        by_os.setdefault(os_constraint, {})[cpu_constraint] = f(rid)
    choices = {}
    for os_constraint, cpus in by_os.items():
        cpus["DEFAULT"] = ":unavailable"
        choices[os_constraint] = select(cpus)
    choices["DEFAULT"] = ":unavailable"
    native.alias(
        name = "{}-{}".format(kind, version),
        actual = select(choices),
    )
    return ":{}-{}".format(kind, version)

def target_rid_select():
    """The runtime identifier of the target platform, for the toolchain's
    `rid` attribute."""
    return _target_select(RID_TARGET_CONSTRAINTS.keys(), lambda rid: rid, "unsupported")

# MARK: Compilation

def _compile(ctx: AnalysisContext, toolchain: CSharpToolchainInfo, target: str, prefix: str) -> (Artifact, Artifact, dict[str, CSharpAssembly]):
    """Run csc over the target's sources. Returns the assembly, its portable
    PDB and the transitive dependencies it was compiled against."""
    name = ctx.attrs.assembly_name or ctx.label.name
    assembly = ctx.actions.declare_output(prefix + name + ".dll")
    pdb = ctx.actions.declare_output(prefix + name + ".pdb")
    deps = _transitive_deps(ctx.attrs.deps)

    sources = list(ctx.attrs.srcs)
    if ctx.attrs.implicit_usings:
        sources.append(ctx.actions.write(prefix + name + ".GlobalUsings.g.cs", IMPLICIT_USINGS))
    if len(sources) == 0:
        fail("{} has no sources".format(ctx.label))

    cmd = cmd_args(
        toolchain.tool,
        "csc",
        "--sdk",
        toolchain.sdk,
        "--tfm",
        toolchain.tfm,
        "--target",
        target,
        "--out",
        assembly.as_output(),
        "--pdb",
        pdb.as_output(),
        "--lang-version",
        ctx.attrs.lang_version or toolchain.lang_version,
        "--nullable",
        ctx.attrs.nullable,
        "--warn",
        str(_warning_level(toolchain.tfm)),
    )
    if toolchain.build_mode == "release":
        cmd.add("--optimize")
    if ctx.attrs.warnings_as_errors:
        cmd.add("--warnaserror")
    if ctx.attrs.unsafe:
        cmd.add("--unsafe")
    if ctx.attrs.main:
        cmd.add("--main", ctx.attrs.main)
    cmd.add(cmd_args(ctx.attrs.defines, format = "--define={}"))
    cmd.add(cmd_args(ctx.attrs.nowarn, format = "--nowarn={}"))
    for logical_name, file in ctx.attrs.resources.items():
        cmd.add(cmd_args(file, format = "--resource={}," + logical_name))
    cmd.add(cmd_args(ctx.attrs.analyzers, format = "--analyzer={}"))
    for dep in deps.values():
        cmd.add(cmd_args(dep.assembly, format = "--reference={}"))
    cmd.add(cmd_args(ctx.attrs.csc_flags, format = "--extra={}"))
    cmd.add(sources)

    ctx.actions.run(
        cmd,
        category = "csharp_compile",
        identifier = name,
        allow_cache_upload = True,
    )
    return assembly, pdb, deps

def _library_info(name: str, assembly: Artifact, pdb: Artifact | None, deps: dict[str, CSharpAssembly]) -> CSharpLibraryInfo:
    return CSharpLibraryInfo(
        name = name,
        assembly = assembly,
        pdb = pdb,
        transitive = deps,
    )

def _csharp_library_impl(ctx: AnalysisContext) -> list[Provider]:
    toolchain = ctx.attrs._csharp_toolchain[CSharpToolchainInfo]
    name = ctx.attrs.assembly_name or ctx.label.name
    assembly, pdb, deps = _compile(ctx, toolchain, "library", "")
    return [
        DefaultInfo(
            default_output = assembly,
            other_outputs = [pdb],
            sub_targets = {
                "pdb": [DefaultInfo(default_output = pdb)],
            },
        ),
        _library_info(name, assembly, pdb, deps),
    ]

def _csharp_prebuilt_library_impl(ctx: AnalysisContext) -> list[Provider]:
    assembly = ctx.attrs.assembly
    name = ctx.attrs.assembly_name or assembly.basename.removesuffix(".dll")
    deps = _transitive_deps(ctx.attrs.deps)

    # A package's other assemblies travel with the main one: dependents see
    # them as if they were dependencies, and each is addressable as a
    # sub-target.
    sub_targets = {}
    for extra_name, extra in ctx.attrs.extra_assemblies.items():
        if extra_name == name or extra_name in deps:
            fail("{}: extra assembly {} clashes with an assembly already in scope".format(ctx.label, extra_name))
        deps[extra_name] = CSharpAssembly(name = extra_name, assembly = extra, pdb = ctx.attrs.extra_pdbs.get(extra_name))
        sub_targets[extra_name] = [DefaultInfo(default_output = extra)]
    for extra_name in ctx.attrs.extra_pdbs:
        if extra_name not in ctx.attrs.extra_assemblies:
            fail("{}: extra_pdbs names {}, which is not in extra_assemblies".format(ctx.label, extra_name))
    return [
        DefaultInfo(default_output = assembly, sub_targets = sub_targets),
        _library_info(name, assembly, ctx.attrs.pdb, deps),
    ]

def _csharp_reference_assembly_impl(ctx: AnalysisContext) -> list[Provider]:
    """One reference assembly out of the SDK's targeting pack, for targets
    that embed or inspect framework metadata."""
    toolchain = ctx.attrs._csharp_toolchain[CSharpToolchainInfo]
    out = ctx.actions.declare_output(ctx.attrs.assembly + ".dll")
    source = cmd_args(
        toolchain.sdk,
        format = "{}/packs/Microsoft.NETCore.App.Ref/*/ref/" + toolchain.tfm + "/" + ctx.attrs.assembly + ".dll",
    )
    ctx.actions.run(
        cmd_args(toolchain.tool, "copy", "--source", source, "--out", out.as_output()),
        category = "csharp_reference_assembly",
        identifier = ctx.attrs.assembly,
    )
    return [DefaultInfo(default_output = out)]

# MARK: Binaries

def _runtime_config(ctx: AnalysisContext, toolchain: CSharpToolchainInfo, profile: str) -> dict:
    """The runtimeconfig.json of a framework-dependent application."""
    properties = {
        "System.GC.Server": ctx.attrs.server_gc,
        "System.Reflection.Metadata.MetadataUpdater.IsSupported": False,
        "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": False,
    }
    if ctx.attrs.invariant_globalization:
        properties["System.Globalization.Invariant"] = True
    if profile == "jit":
        properties["System.Runtime.TieredCompilation"] = True
        properties["System.Runtime.TieredPGO"] = False
    elif profile == "pgojit":
        properties["System.Runtime.TieredCompilation"] = True
        properties["System.Runtime.TieredCompilation.QuickJitForLoops"] = True
        properties["System.Runtime.TieredPGO"] = True
    elif profile == "r2r":
        properties["System.Runtime.TieredCompilation"] = True
    properties.update(ctx.attrs.runtime_options)
    return {
        "runtimeOptions": {
            "tfm": toolchain.tfm,
            "framework": {
                "name": "Microsoft.NETCore.App",
                "version": toolchain.runtime_version,
            },
            "configProperties": properties,
        },
    }

def _crossgen(ctx: AnalysisContext, toolchain: CSharpToolchainInfo, input: Artifact, references: list[Artifact], file_name: str) -> Artifact:
    if toolchain.crossgen2 == None:
        fail("{}: the r2r profile needs crossgen2, which the toolchain has no package for on this machine".format(ctx.label))
    out = ctx.actions.declare_output("r2r/" + file_name)
    cmd = cmd_args(
        toolchain.tool,
        "crossgen2",
        "--sdk",
        toolchain.sdk,
        "--crossgen2-package",
        toolchain.crossgen2,
        "--rid",
        toolchain.rid,
        "--input",
        input,
        "--out",
        out.as_output(),
    )
    for reference in references:
        cmd.add(cmd_args(reference, format = "--reference={}"))
    if toolchain.build_mode == "release":
        cmd.add("--optimize")
    if ctx.attrs.optimization_preference:
        cmd.add("--optimization-preference", ctx.attrs.optimization_preference)
    cmd.add(cmd_args(ctx.attrs.crossgen2_flags, format = "--extra={}"))
    ctx.actions.run(
        cmd,
        category = "csharp_crossgen2",
        identifier = file_name,
        allow_cache_upload = True,
    )
    return out

def _managed_layout(
        ctx: AnalysisContext,
        toolchain: CSharpToolchainInfo,
        profile: str,
        name: str,
        assembly: Artifact,
        pdb: Artifact,
        deps: dict[str, CSharpAssembly],
        sub_targets: dict) -> (list[Provider], cmd_args):
    """An application directory the SDK's host runs: the assemblies, their
    PDBs, a runtimeconfig.json and an apphost stamped with the app's name."""
    windows = toolchain.rid.startswith("win")
    all_assemblies = {name: assembly} | {dep.name: dep.assembly for dep in deps.values()}

    files = {}
    if profile == "r2r":
        for asm_name, asm in all_assemblies.items():
            if asm_name != name and not ctx.attrs.r2r_dependencies:
                files[asm_name + ".dll"] = asm
                continue
            references = [other for other_name, other in all_assemblies.items() if other_name != asm_name]
            files[asm_name + ".dll"] = _crossgen(ctx, toolchain, asm, references, asm_name + ".dll")
    else:
        for asm_name, asm in all_assemblies.items():
            files[asm_name + ".dll"] = asm
    files[name + ".pdb"] = pdb
    for dep in deps.values():
        if dep.pdb != None:
            files[dep.name + ".pdb"] = dep.pdb

    runtime_config = ctx.actions.write_json(name + ".runtimeconfig.json", _runtime_config(ctx, toolchain, profile))
    files[name + ".runtimeconfig.json"] = runtime_config

    apphost = ctx.actions.declare_output("apphost/" + name + (".exe" if windows else ""))
    ctx.actions.run(
        cmd_args(toolchain.tool, "apphost", "--sdk", toolchain.sdk, "--app", name + ".dll", "--out", apphost.as_output()),
        category = "csharp_apphost",
        identifier = name,
    )
    files[apphost.basename] = apphost

    app_dir = ctx.actions.copied_dir(name, files)
    dotnet = cmd_args(toolchain.sdk, format = "{}/" + ("dotnet.exe" if windows else "dotnet"))
    run = cmd_args(dotnet, "exec", cmd_args(app_dir, format = "{}/" + name + ".dll"))
    sub_targets["runtimeconfig"] = [DefaultInfo(default_output = runtime_config)]
    sub_targets["apphost"] = [DefaultInfo(default_output = apphost)]
    return [
        DefaultInfo(default_output = app_dir, sub_targets = sub_targets),
        RunInfo(args = run),
    ], run

def _native_aot(
        ctx: AnalysisContext,
        toolchain: CSharpToolchainInfo,
        name: str,
        assembly: Artifact,
        deps: dict[str, CSharpAssembly],
        sub_targets: dict) -> (list[Provider], cmd_args):
    """ILCompiler turns the assembly and its dependencies into one object,
    and the C compiler driver links it against the NativeAOT runtime."""
    if toolchain.ilc == None or toolchain.nativeaot_pack == None:
        fail("{}: the aot profile needs ILCompiler and the NativeAOT runtime pack for {}, which the toolchain has no packages for".format(ctx.label, toolchain.rid))
    windows = toolchain.rid.startswith("win")
    apple = toolchain.rid.startswith("osx")
    release = toolchain.build_mode == "release"
    cxx = ctx.attrs._cxx_toolchain[CxxToolchainInfo]

    overrides = dict(ctx.attrs.aot_assembly_overrides)
    references = []
    for dep in deps.values():
        references.append(overrides.pop(dep.name + ".dll", dep.assembly))
    if overrides:
        fail("{}: aot_assembly_overrides names assemblies that are not dependencies: {}".format(ctx.label, overrides.keys()))

    object = ctx.actions.declare_output("native/" + name + ".o")
    exports = ctx.actions.declare_output("native/" + name + ".exports")
    ilc = cmd_args(
        toolchain.tool,
        "ilc",
        "--ilc-package",
        toolchain.ilc,
        "--nativeaot-pack",
        toolchain.nativeaot_pack,
        "--rid",
        toolchain.rid,
        "--tfm",
        toolchain.tfm,
        "--input",
        assembly,
        "--out",
        object.as_output(),
        "--exports",
        exports.as_output(),
    )
    for reference in references:
        ilc.add(cmd_args(reference, format = "--reference={}"))
    if release:
        ilc.add("--optimize")
    else:
        ilc.add("--debugger-support")
    if ctx.attrs.optimization_preference:
        ilc.add("--optimization-preference", ctx.attrs.optimization_preference)
    if ctx.attrs.invariant_globalization:
        ilc.add("--invariant-globalization")
    if ctx.attrs.server_gc:
        ilc.add("--server-gc")
    if ctx.attrs.stack_trace_support:
        ilc.add("--stack-trace-support")
    if ctx.attrs.trimmer_single_warn:
        ilc.add("--single-warn")
    if ctx.attrs.warnings_as_errors:
        ilc.add("--warnaserror")
    ilc.add(cmd_args(ctx.attrs.nowarn, format = "--nowarn={}"))
    ilc.add(cmd_args(ctx.attrs.ilc_flags, format = "--extra={}"))
    ctx.actions.run(
        ilc,
        category = "csharp_ilc",
        identifier = name,
        allow_cache_upload = True,
    )

    executable = ctx.actions.declare_output(name + (".exe" if windows else ""))
    if apple:
        debug_info = ctx.actions.declare_output(name + ".dSYM", dir = True)
    else:
        debug_info = ctx.actions.declare_output(name + ".dbg")
    link = cmd_args(
        toolchain.tool,
        "link",
        "--nativeaot-pack",
        toolchain.nativeaot_pack,
        "--rid",
        toolchain.rid,
        "--tfm",
        toolchain.tfm,
        "--object",
        object,
        "--exports",
        exports,
        "--out",
        executable.as_output(),
        "--dbg",
        debug_info.as_output(),
    )
    if release:
        link.add("--strip")
    else:
        link.add("--debugger-support")
    if toolchain.aot_linker_flavor:
        link.add("--fuse-ld", toolchain.aot_linker_flavor)
    if ctx.attrs.optimization_preference:
        link.add("--optimization-preference", ctx.attrs.optimization_preference)
    if ctx.attrs.invariant_globalization:
        link.add("--invariant-globalization")
    if ctx.attrs.server_gc:
        link.add("--server-gc")
    link.add(cmd_args(cxx.binary_utilities_info.objcopy.args, format = "--objcopy={}"))
    link.add(cmd_args(ctx.attrs.link_flags, format = "--extra={}"))
    link.add("--", cxx.c_compiler_info.compiler)
    ctx.actions.run(
        link,
        category = "csharp_link",
        identifier = name,
        allow_cache_upload = True,
    )

    run = cmd_args(executable)
    sub_targets["object"] = [DefaultInfo(default_output = object)]
    sub_targets["exports"] = [DefaultInfo(default_output = exports)]
    sub_targets["dbg"] = [DefaultInfo(default_output = debug_info)]
    return [
        DefaultInfo(default_output = executable, other_outputs = [debug_info], sub_targets = sub_targets),
        RunInfo(args = run),
    ], run

def _build_binary(ctx: AnalysisContext) -> (list[Provider], cmd_args):
    toolchain = ctx.attrs._csharp_toolchain[CSharpToolchainInfo]
    profile = ctx.attrs.profile or toolchain.profile
    name = ctx.attrs.assembly_name or ctx.label.name
    assembly, pdb, deps = _compile(ctx, toolchain, "exe", "il/")
    sub_targets = {
        "il": [DefaultInfo(default_output = assembly, other_outputs = [pdb])],
    }
    if profile == "aot":
        return _native_aot(ctx, toolchain, name, assembly, deps, sub_targets)
    return _managed_layout(ctx, toolchain, profile, name, assembly, pdb, deps, sub_targets)

def _csharp_binary_impl(ctx: AnalysisContext) -> list[Provider]:
    providers, _ = _build_binary(ctx)
    return providers

def _csharp_test_impl(ctx: AnalysisContext) -> list[Provider]:
    """A program whose exit status is the verdict; there is no NuGet, so
    there is no xunit either."""
    providers, run = _build_binary(ctx)
    return providers + [
        ExternalRunnerTestInfo(
            type = "custom",
            command = [run] + ctx.attrs.args,
            env = ctx.attrs.env,
        ),
    ]

# MARK: Rules

_COMPILE_ATTRS = {
    "srcs": attrs.list(attrs.source(), default = []),
    "deps": attrs.list(attrs.dep(providers = [CSharpLibraryInfo]), default = []),
    # The assembly's simple name; the target name by default
    "assembly_name": attrs.option(attrs.string(), default = None),
    "defines": attrs.list(attrs.string(), default = []),
    "nullable": attrs.enum(["enable", "disable", "warnings", "annotations"], default = "enable"),
    "implicit_usings": attrs.bool(default = True),
    "unsafe": attrs.bool(default = False),
    "warnings_as_errors": attrs.bool(default = False),
    "nowarn": attrs.list(attrs.string(), default = []),
    "lang_version": attrs.option(attrs.string(), default = None),
    # Type containing the entry point, when more than one has a Main
    "main": attrs.option(attrs.string(), default = None),
    # Embedded resources keyed by logical name
    "resources": attrs.dict(attrs.string(), attrs.source(), default = {}),
    "analyzers": attrs.list(attrs.source(), default = []),
    "csc_flags": attrs.list(attrs.string(), default = []),
    "_csharp_toolchain": attrs.toolchain_dep(default = "toolchains//:csharp", providers = [CSharpToolchainInfo]),
}

_BINARY_ATTRS = _COMPILE_ATTRS | {
    # Pins the profile; otherwise toolchains//cfg/csharp:profile decides
    "profile": attrs.option(attrs.enum(PROFILES), default = None),
    # Culture data needs ICU on the machine running the program, which a
    # hermetic build cannot promise; invariant mode needs nothing.
    "invariant_globalization": attrs.bool(default = True),
    "server_gc": attrs.bool(default = False),
    "optimization_preference": attrs.option(attrs.enum(["speed", "size"]), default = None),
    # Whether exceptions carry method names in their stack traces (aot)
    "stack_trace_support": attrs.bool(default = True),
    # Collapse trim warnings from one assembly into one (aot)
    "trimmer_single_warn": attrs.bool(default = True),
    # Precompile dependency assemblies too, not only the application (r2r)
    "r2r_dependencies": attrs.bool(default = True),
    # Assemblies handed to ILCompiler in place of a dependency with the same
    # file name; csc still compiles against the original (aot)
    "aot_assembly_overrides": attrs.dict(attrs.string(), attrs.source(), default = {}),
    # Extra configProperties for runtimeconfig.json (jit, pgojit, r2r)
    "runtime_options": attrs.dict(attrs.string(), attrs.one_of(attrs.bool(), attrs.int(), attrs.string()), default = {}),
    "ilc_flags": attrs.list(attrs.string(), default = []),
    "link_flags": attrs.list(attrs.string(), default = []),
    "crossgen2_flags": attrs.list(attrs.string(), default = []),
    "_cxx_toolchain": attrs.toolchain_dep(default = "toolchains//:cxx", providers = [CxxToolchainInfo]),
}

_csharp_library = rule(
    impl = _csharp_library_impl,
    attrs = _COMPILE_ATTRS,
)

_csharp_binary = rule(
    impl = _csharp_binary_impl,
    attrs = _BINARY_ATTRS,
)

_csharp_test = rule(
    impl = _csharp_test_impl,
    attrs = _BINARY_ATTRS | {
        "args": attrs.list(attrs.arg(), default = []),
        "env": attrs.dict(attrs.string(), attrs.arg(), default = {}),
    },
)

_csharp_prebuilt_library = rule(
    impl = _csharp_prebuilt_library_impl,
    attrs = {
        "assembly": attrs.source(),
        "pdb": attrs.option(attrs.source(), default = None),
        "assembly_name": attrs.option(attrs.string(), default = None),
        # Further assemblies the same package ships, keyed by simple name.
        "extra_assemblies": attrs.dict(attrs.string(), attrs.source(), default = {}),
        "extra_pdbs": attrs.dict(attrs.string(), attrs.source(), default = {}),
        "deps": attrs.list(attrs.dep(providers = [CSharpLibraryInfo]), default = []),
    },
)

_csharp_reference_assembly = rule(
    impl = _csharp_reference_assembly_impl,
    attrs = {
        "assembly": attrs.string(),
        "_csharp_toolchain": attrs.toolchain_dep(default = "toolchains//:csharp", providers = [CSharpToolchainInfo]),
    },
)

# MARK: Public API

def csharp_library(**kwargs):
    """Compile C# sources into one IL assembly."""
    _csharp_library(**kwargs)

def csharp_binary(**kwargs):
    """Compile C# sources into a program, packaged per the selected profile."""
    _csharp_binary(**kwargs)

def csharp_test(**kwargs):
    """A csharp_binary run as a test; its exit status is the verdict."""
    _csharp_test(**kwargs)

def csharp_prebuilt_library(**kwargs):
    """An assembly that already exists, such as one inside a nuget_archive."""
    _csharp_prebuilt_library(**kwargs)

def csharp_reference_assembly(**kwargs):
    """Copy one reference assembly out of the toolchain's targeting pack."""
    _csharp_reference_assembly(**kwargs)

csharp = struct(
    library = csharp_library,
    binary = csharp_binary,
    test = csharp_test,
    prebuilt_library = csharp_prebuilt_library,
    reference_assembly = csharp_reference_assembly,
    nuget_archive = nuget_archive,
)
