// SPDX-FileCopyrightText: © 2026 Austin Seipp
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"sort"
	"strings"
)

const generatedHeader = `# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# @generated by ` + "`buck2 run root//buck/tools/nugetify -- buckify`" + ` from
# nuget.toml and nuget.lock in this directory. Edit nuget.toml and rerun it.

load("@root//buck/shims:third_party_csharp.bzl", "nuget")
`

// emitBuild renders the lock as calls to the nuget.* macros. Packages that
// carry no assemblies get no target; a dependency on one of them becomes
// dependencies on whatever it depends on, so consumers still see every
// assembly NuGet would have given them.
func emitBuild(lock *lockFile) string {
	var out strings.Builder
	out.WriteString(generatedHeader)
	fmt.Fprintf(&out, "\n# Every package is consumed as %s sees it. %s %s\n# decides which packages the framework already provides.\n",
		lock.Framework.TFM, lock.Framework.Package, lock.Framework.Version)

	emitted := make(map[string]bool, len(lock.Packages))
	for _, pkg := range lock.Packages {
		emitted[strings.ToLower(pkg.ID)] = pkg.Assets != ""
	}
	for _, pkg := range lock.Packages {
		if pkg.Assets == "" {
			fmt.Fprintf(&out, "\n# %s %s ships no assemblies for %s.\n", pkg.ID, pkg.Version, lock.Framework.TFM)
			continue
		}
		// Attributes in the order buildifier keeps them: name first, deps
		// last, the rest alphabetical, so `jj fix` leaves the file alone.
		out.WriteString("\nnuget.package(\n")
		fmt.Fprintf(&out, "    name = %q,\n", pkg.ID)
		writeList(&out, "assemblies", pkg.Assemblies)
		fmt.Fprintf(&out, "    assets = %q,\n", pkg.Assets)
		fmt.Fprintf(&out, "    sha256 = %q,\n", pkg.SHA256)
		if len(pkg.Symbols) > 0 {
			writeList(&out, "symbols", pkg.Symbols)
		}
		fmt.Fprintf(&out, "    version = %q,\n", pkg.Version)
		if pkg.Direct {
			out.WriteString("    visibility = [\"PUBLIC\"],\n")
		} else {
			out.WriteString("    visibility = [],\n")
		}
		deps := lock.effectiveDependencies(pkg.ID, emitted)
		if len(deps) > 0 {
			labels := make([]string, len(deps))
			for index, dep := range deps {
				labels[index] = ":" + dep
			}
			writeList(&out, "deps", labels)
		}
		out.WriteString(")\n")
	}
	out.WriteString("\n# The committed lock and this file agree (buck/tools/nugetify check).\nnuget.check(name = \"buckify-check\")\n")
	return out.String()
}

// effectiveDependencies is a package's dependencies with the assembly-less
// ones replaced by their own dependencies, transitively.
func (l *lockFile) effectiveDependencies(id string, emitted map[string]bool) []string {
	seen := make(map[string]struct{})
	var result []string
	var walk func(string)
	walk = func(current string) {
		pkg := l.find(current)
		if pkg == nil {
			return
		}
		for _, dep := range pkg.Dependencies {
			key := strings.ToLower(dep)
			if _, done := seen[key]; done {
				continue
			}
			seen[key] = struct{}{}
			if emitted[key] {
				result = append(result, l.find(dep).ID)
			} else {
				walk(dep)
			}
		}
	}
	walk(id)
	sort.Slice(result, func(i, j int) bool { return lessID(result[i], result[j]) })
	return result
}

// writeList writes a list attribute the way buildifier formats one: a
// single element inline, several one per line.
func writeList(out *strings.Builder, name string, items []string) {
	if len(items) == 1 {
		fmt.Fprintf(out, "    %s = [%q],\n", name, items[0])
		return
	}
	fmt.Fprintf(out, "    %s = [\n", name)
	for _, item := range items {
		fmt.Fprintf(out, "        %q,\n", item)
	}
	out.WriteString("    ],\n")
}
