// SPDX-FileCopyrightText: © 2026 Austin Seipp
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"strings"
	"testing"
)

func exampleLock() *lockFile {
	return &lockFile{
		Version:   lockVersion,
		Framework: lockFramework{Package: "Microsoft.NETCore.App.Ref", Version: "11.0.0-rc.1", TFM: "net11.0"},
		Packages: []lockPackage{
			{ID: "Leaf.Cecil", Version: "0.11.6", SHA256: strings.Repeat("a", 64), SHA512: "AA==", Assets: "lib/netstandard2.0", Assemblies: []string{"Leaf.Cecil", "Leaf.Cecil.Rocks"}, Symbols: []string{"Leaf.Cecil.Rocks"}},
			{ID: "Top.Analyzers", Version: "3.11.0", SHA256: strings.Repeat("b", 64), SHA512: "AA==", Dependencies: []string{"Leaf.Cecil"}},
			{ID: "Top.Common", Version: "5.9.0", SHA256: strings.Repeat("c", 64), SHA512: "AA==", Assets: "lib/net10.0", Assemblies: []string{"Top"}, Symbols: []string{"Top"}, Dependencies: []string{"Top.Analyzers"}},
			{ID: "Top.CSharp", Version: "5.9.0", Direct: true, SHA256: strings.Repeat("d", 64), SHA512: "AA==", Assets: "lib/net10.0", Assemblies: []string{"Top.CSharp"}, Symbols: []string{"Top.CSharp"}, Dependencies: []string{"Top.Common"}},
		},
	}
}

func TestEmitBuild(t *testing.T) {
	want := `# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# @generated by ` + "`buck2 run root//buck/tools/nugetify -- buckify`" + ` from
# nuget.toml and nuget.lock in this directory. Edit nuget.toml and rerun it.

load("@root//buck/shims:third_party_csharp.bzl", "nuget")

# Every package is consumed as net11.0 sees it. Microsoft.NETCore.App.Ref 11.0.0-rc.1
# decides which packages the framework already provides.

nuget.package(
    name = "Leaf.Cecil",
    assemblies = [
        "Leaf.Cecil",
        "Leaf.Cecil.Rocks",
    ],
    assets = "lib/netstandard2.0",
    sha256 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    symbols = ["Leaf.Cecil.Rocks"],
    version = "0.11.6",
    visibility = [],
)

# Top.Analyzers 3.11.0 ships no assemblies for net11.0.

nuget.package(
    name = "Top.Common",
    assemblies = ["Top"],
    assets = "lib/net10.0",
    sha256 = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
    symbols = ["Top"],
    version = "5.9.0",
    visibility = [],
    deps = [":Leaf.Cecil"],
)

nuget.package(
    name = "Top.CSharp",
    assemblies = ["Top.CSharp"],
    assets = "lib/net10.0",
    sha256 = "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
    symbols = ["Top.CSharp"],
    version = "5.9.0",
    visibility = ["PUBLIC"],
    deps = [":Top.Common"],
)

# The committed lock and this file agree (buck/tools/nugetify check).
nuget.check(name = "buckify-check")
`
	if got := emitBuild(exampleLock()); got != want {
		t.Fatalf("emitBuild differs:\n%s", firstDifference(got, want))
	}
}

func TestLockRoundTrip(t *testing.T) {
	lock := exampleLock()
	encoded, err := lock.encode()
	if err != nil {
		t.Fatal(err)
	}
	decoded, err := parseLock(encoded)
	if err != nil {
		t.Fatal(err)
	}
	again, err := decoded.encode()
	if err != nil {
		t.Fatal(err)
	}
	if string(again) != string(encoded) {
		t.Fatalf("lock did not round-trip:\n%s", firstDifference(string(again), string(encoded)))
	}
	m := &manifest{Framework: packageRef{ID: "Microsoft.NETCore.App.Ref", Version: "11.0.0-rc.1"}, Packages: []packageRef{{ID: "Top.CSharp", Version: "5.9.0"}}}
	if !decoded.matches(m) {
		t.Fatal("the lock should match the manifest it was resolved from")
	}
	m.Packages[0].Version = "5.10.0"
	if decoded.matches(m) {
		t.Fatal("a changed pin should not match")
	}
}

func TestLockValidateRejectsInconsistency(t *testing.T) {
	broken := func(mutate func(*lockFile)) error {
		lock := exampleLock()
		mutate(lock)
		return lock.validate()
	}
	cases := map[string]func(*lockFile){
		"version":         func(l *lockFile) { l.Version = 2 },
		"unsorted":        func(l *lockFile) { l.Packages[0], l.Packages[1] = l.Packages[1], l.Packages[0] },
		"bad sha":         func(l *lockFile) { l.Packages[0].SHA256 = "abc" },
		"dangling dep":    func(l *lockFile) { l.Packages[1].Dependencies = []string{"Nowhere"} },
		"orphan symbol":   func(l *lockFile) { l.Packages[0].Symbols = []string{"Other"} },
		"assets mismatch": func(l *lockFile) { l.Packages[0].Assemblies = nil },
	}
	for name, mutate := range cases {
		if broken(mutate) == nil {
			t.Fatalf("%s: validated", name)
		}
	}
}
