// SPDX-FileCopyrightText: © 2026 Austin Seipp
// SPDX-License-Identifier: Apache-2.0

//! The frontend and the reference interpreter against WABT's interpreter.
//!
//! Every fixture module, and every module wasm-smith draws from
//! Hegel-generated bytes, is run both ways; see `wedge_testing::differential`
//! for what is compared and what is inconclusive.

use arbitrary::Unstructured;
use hegel::{HealthCheck, TestCase, generators as gs};
use wedge_testing::differential::{self, Verdict, Wabt};
use wedge_testing::smith;

mod fixture_support;

#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;

const FIXTURES: &[&str] = &[
    "add",
    "answer",
    "bulk_memory",
    "canonical_types",
    "catch_after_catch_all",
    "chacha20",
    "control_flow",
    "default_locals",
    "exception_routing",
    "exceptions",
    "extended_const",
    "function_references",
    "gc_types",
    "loop_label_arguments",
    "memory",
    "memory64",
    "module_entities",
    "multi_memory",
    "multi_value",
    "mutable_globals",
    "named_functions",
    "numeric",
    "reference_br_on_non_null",
    "reference_br_on_null",
    "reference_const_expr",
    "reference_types",
    "relaxed_simd",
    "saturating_conversions",
    "scalar_leaf_operations",
    "segments",
    "sign_extension",
    "simd",
    "simd_lane_operations",
    "ssa_locals",
    "structured_control",
    "table64",
    "table_leaf_operations",
    "tables",
    "tag_aliasing",
    "tail_calls",
];

fn wabt() -> Wabt {
    Wabt::new(
        buck_resources::get("aseipp/wedge/spectest-interp")
            .expect("the test target carries spectest-interp"),
    )
}

#[test]
fn fixtures_execute_like_wabt() {
    let wabt = wabt();
    let mut conclusive = Vec::new();
    let mut inconclusive = Vec::new();
    for fixture in FIXTURES {
        let wasm = fixture_support::fixture(fixture);
        match differential::check(&wabt, &wasm, &mut Unstructured::new(&[])) {
            Verdict::Agree { invocations } => conclusive.push((*fixture, invocations)),
            Verdict::Inconclusive(why) => inconclusive.push((*fixture, why)),
            Verdict::Disagree(why) => panic!("{fixture}.wat: {why}"),
        }
    }
    eprintln!("agreed on {conclusive:?}\ninconclusive: {inconclusive:#?}");
    // The interesting fixtures, at least, must actually be compared.
    for expected in [
        "chacha20",
        "numeric",
        "simd",
        "memory64",
        "exceptions",
        "tail_calls",
    ] {
        assert!(
            conclusive.iter().any(|(fixture, _)| *fixture == expected),
            "{expected}.wat was not compared: {inconclusive:?}"
        );
    }
}

/// A fixed pseudo-random byte stream, so the sample below is the same on
/// every run.
fn entropy(seed: u64, len: usize) -> Vec<u8> {
    let mut state = seed.wrapping_mul(0x9e37_79b9_7f4a_7c15) ^ 0x2545_f491_4f6c_dd1d;
    (0..len)
        .map(|_| {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            (state >> 24) as u8
        })
        .collect()
}

/// WABT is only an oracle where it can run the module, so this keeps an
/// eye on how much of the generated language it actually compares.
#[test]
fn generated_modules_are_mostly_conclusive() {
    let wabt = wabt();
    let mut agreed = 0;
    let mut invocations = 0;
    let mut inconclusive = Vec::new();
    for seed in 1..=32 {
        let module = smith::executable_module(&entropy(seed, 4096)).expect("a module");
        match differential::check(
            &wabt,
            &module,
            &mut Unstructured::new(&entropy(seed ^ 0xabcd, 512)),
        ) {
            Verdict::Agree { invocations: count } => {
                agreed += 1;
                invocations += count;
            }
            Verdict::Inconclusive(why) => inconclusive.push(why),
            Verdict::Disagree(why) => panic!("seed {seed}: {why}"),
        }
    }
    eprintln!(
        "{agreed}/32 modules agreed over {invocations} invocations; inconclusive: {inconclusive:#?}"
    );
    assert!(
        agreed >= 8,
        "only {agreed} of 32 generated modules could be compared: {inconclusive:?}"
    );
    assert!(
        invocations >= 32,
        "only {invocations} invocations were compared"
    );
}

#[test]
fn the_executable_generator_stays_within_the_standard_profile() {
    let needed = smith::executable_config().features();
    assert!(
        wedge::STANDARD_WASM_3_FEATURES.contains(needed),
        "wasm-smith needs {needed:?}, beyond the standard profile"
    );
}

#[hegel::test(
    test_cases = 64,
    derandomize = true,
    database = None,
    suppress_health_check = [HealthCheck::FilterTooMuch]
)]
fn generated_modules_execute_like_wabt(tc: TestCase) {
    let entropy = tc.draw_silent(gs::binary().max_size(4096));
    let arguments = tc.draw_silent(gs::binary().max_size(512));
    let module =
        smith::executable_module(&entropy).expect("wasm-smith draws a module from any byte string");
    tc.note(&smith::text(&module));
    match differential::check(&wabt(), &module, &mut Unstructured::new(&arguments)) {
        Verdict::Agree { .. } => {}
        Verdict::Inconclusive(why) => {
            tc.note(&why);
            tc.assume(false);
        }
        Verdict::Disagree(why) => panic!("{why}"),
    }
}
