;; SPDX-FileCopyrightText: © 2026 Austin Seipp
;; SPDX-License-Identifier: Apache-2.0

;; Calls `test:async/server` through every lowering: strings and lists
;; through async calls, a stream of strings read between components,
;; thread-local storage across a callback, resources through async calls,
;; and calls in flight at once. Each `run-*` is an async function lifted
;; synchronously, so it may wait: it returns its check's value, or a code
;; of 100 and up naming the step that went wrong.
(component
  (import "test:async/server" (instance $server
    (export "token" (type $token (sub resource)))
    (export "upper" (func async (param "s" string) (result string)))
    (type $numbers (list u32))
    (export "sum" (func async (param "xs" $numbers) (result u32)))
    (type $words (stream string))
    (export "words" (func async (param "n" u32) (result $words)))
    (export "counter" (func async (result u32)))
    (type $own (own $token))
    (export "make" (func async (param "n" u32) (result $own)))
    (type $borrowed (borrow $token))
    (export "peek" (func async (param "t" $borrowed) (result u32)))
    (export "destroyed" (func (result u32)))))
  (alias export $server "token" (type $token))
  (type $words (stream string))
  (core module $Mem
    (memory (export "memory") 1)
    (global $heap (mut i32) (i32.const 8192))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32) (local $at i32)
      (local.set $at (i32.and (i32.add (global.get $heap) (i32.sub (local.get 2) (i32.const 1)))
        (i32.sub (i32.const 0) (local.get 2))))
      (global.set $heap (i32.add (local.get $at) (local.get 3)))
      (local.get $at))
    (data (i32.const 200) "hello")
    (data (i32.const 210) "HELLO")
    (data (i32.const 220) "abc")
    (data (i32.const 230) "defg")
    (data (i32.const 240) "hi")
    (data (i32.const 250) "ABCDEFGHI")
    (data (i32.const 260) "w0w1w2")
    (data (i32.const 500) "\01\00\00\00\02\00\00\00\03\00\00\00\04\00\00\00"))
  (core instance $mem (instantiate $Mem))
  (alias core export $mem "memory" (core memory $memory))
  (alias core export $mem "realloc" (core func $realloc))
  (core func $upper (canon lower (func $server "upper") async (memory $memory) (realloc $realloc)))
  (core func $sum (canon lower (func $server "sum") (memory $memory) (realloc $realloc)))
  (core func $words (canon lower (func $server "words")))
  (core func $counter (canon lower (func $server "counter") async (memory $memory)))
  (core func $make (canon lower (func $server "make") async (memory $memory)))
  (core func $peek (canon lower (func $server "peek") async (memory $memory)))
  (core func $destroyed (canon lower (func $server "destroyed")))
  (canon waitable-set.new (core func $ws_new))
  (canon waitable-set.wait (memory $memory) (core func $wait))
  (canon waitable.join (core func $join))
  (canon subtask.drop (core func $subtask_drop))
  (canon stream.read $words async (memory $memory) (realloc $realloc) (core func $read))
  (canon stream.drop-readable $words (core func $read_drop))
  (canon resource.drop $token (core func $token_drop))
  (core module $M
    (import "env" "memory" (memory 1))
    (import "" "upper" (func $upper (param i32 i32 i32) (result i32)))
    (import "" "sum" (func $sum (param i32 i32) (result i32)))
    (import "" "words" (func $words (param i32) (result i32)))
    (import "" "counter" (func $counter (param i32) (result i32)))
    (import "" "make" (func $make (param i32 i32) (result i32)))
    (import "" "peek" (func $peek (param i32 i32) (result i32)))
    (import "" "destroyed" (func $destroyed (result i32)))
    (import "" "ws-new" (func $ws_new (result i32)))
    (import "" "wait" (func $wait (param i32 i32) (result i32)))
    (import "" "join" (func $join (param i32 i32)))
    (import "" "subtask-drop" (func $subtask_drop (param i32)))
    (import "" "read" (func $read (param i32 i32 i32) (result i32)))
    (import "" "read-drop" (func $read_drop (param i32)))
    (import "" "token-drop" (func $token_drop (param i32)))

    (func $streq (param $a i32) (param $b i32) (param $len i32) (result i32) (local $i i32)
      (block $differ
        (loop $next
          (if (i32.ge_u (local.get $i) (local.get $len)) (then (return (i32.const 1))))
          (br_if $differ (i32.ne (i32.load8_u (i32.add (local.get $a) (local.get $i)))
            (i32.load8_u (i32.add (local.get $b) (local.get $i)))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (i32.const 0))

    ;; Waits for subtask `sub` to return, then drops it: 0, or a failure.
    (func $await (param $sub i32) (param $fail i32) (result i32) (local $ws i32)
      (local.set $ws (call $ws_new))
      (call $join (local.get $sub) (local.get $ws))
      (if (i32.ne (call $wait (local.get $ws) (i32.const 400)) (i32.const 1 (; SUBTASK ;)))
        (then (return (local.get $fail))))
      (if (i32.ne (i32.load (i32.const 400)) (local.get $sub))
        (then (return (i32.add (local.get $fail) (i32.const 1)))))
      (if (i32.ne (i32.load (i32.const 404)) (i32.const 2 (; RETURNED ;)))
        (then (return (i32.add (local.get $fail) (i32.const 2)))))
      (call $subtask_drop (local.get $sub))
      (i32.const 0))

    (func (export "run-upper") (result i32) (local $ret i32) (local $failed i32)
      (local.set $ret (call $upper (i32.const 200) (i32.const 5) (i32.const 300)))
      ;; The callee yields before returning.
      (if (i32.ne (i32.and (local.get $ret) (i32.const 15)) (i32.const 1 (; STARTED ;)))
        (then (return (i32.const 100))))
      (local.set $failed (call $await (i32.shr_u (local.get $ret) (i32.const 4)) (i32.const 101)))
      (if (local.get $failed) (then (return (local.get $failed))))
      (if (i32.ne (i32.load (i32.const 304)) (i32.const 5)) (then (return (i32.const 110))))
      (if (i32.eqz (call $streq (i32.load (i32.const 300)) (i32.const 210) (i32.const 5)))
        (then (return (i32.const 111))))
      (i32.const 1))

    (func (export "run-sum") (result i32)
      (call $sum (i32.const 500) (i32.const 4)))

    (func (export "run-words") (result i32)
      (local $r i32) (local $ws i32) (local $ret i32) (local $count i32) (local $i i32)
      (local $acc i32) (local $e i32)
      (local.set $r (call $words (i32.const 3)))
      (local.set $ws (call $ws_new))
      (block $finished
        (loop $read
          (local.set $ret (call $read (local.get $r) (i32.const 600) (i32.const 2)))
          (if (i32.eq (local.get $ret) (i32.const -1 (; BLOCKED ;)))
            (then
              (call $join (local.get $r) (local.get $ws))
              (if (i32.ne (call $wait (local.get $ws) (i32.const 400)) (i32.const 2 (; STREAM_READ ;)))
                (then (return (i32.const 200))))
              (call $join (local.get $r) (i32.const 0))
              (local.set $ret (i32.load (i32.const 404)))))
          ;; Append the strings the read delivered.
          (local.set $count (i32.shr_u (local.get $ret) (i32.const 4)))
          (local.set $i (i32.const 0))
          (block $copied
            (loop $copy
              (br_if $copied (i32.ge_u (local.get $i) (local.get $count)))
              (local.set $e (i32.add (i32.const 600) (i32.shl (local.get $i) (i32.const 3))))
              (memory.copy (i32.add (i32.const 700) (local.get $acc))
                (i32.load (local.get $e)) (i32.load offset=4 (local.get $e)))
              (local.set $acc (i32.add (local.get $acc) (i32.load offset=4 (local.get $e))))
              (local.set $i (i32.add (local.get $i) (i32.const 1)))
              (br $copy)))
          (br_if $finished (i32.eq (i32.and (local.get $ret) (i32.const 15)) (i32.const 1 (; DROPPED ;))))
          (br $read)))
      (call $read_drop (local.get $r))
      (if (i32.ne (local.get $acc) (i32.const 6)) (then (return (i32.const 201))))
      (if (i32.eqz (call $streq (i32.const 700) (i32.const 260) (i32.const 6)))
        (then (return (i32.const 202))))
      (local.get $acc))

    (func (export "run-counter") (result i32) (local $ret i32) (local $failed i32)
      (local.set $ret (call $counter (i32.const 800)))
      (if (i32.ne (i32.and (local.get $ret) (i32.const 15)) (i32.const 1 (; STARTED ;)))
        (then (return (i32.const 300))))
      (local.set $failed (call $await (i32.shr_u (local.get $ret) (i32.const 4)) (i32.const 301)))
      (if (local.get $failed) (then (return (local.get $failed))))
      (i32.load (i32.const 800)))

    (func (export "run-token") (result i32) (local $t i32)
      ;; Both return at once.
      (if (i32.ne (call $make (i32.const 5) (i32.const 820)) (i32.const 2 (; RETURNED ;)))
        (then (return (i32.const 400))))
      (local.set $t (i32.load (i32.const 820)))
      (if (i32.ne (call $peek (local.get $t) (i32.const 824)) (i32.const 2 (; RETURNED ;)))
        (then (return (i32.const 401))))
      (call $token_drop (local.get $t))
      (i32.add (i32.mul (i32.load (i32.const 824)) (i32.const 10)) (call $destroyed)))

    (func (export "run-concurrent") (result i32)
      (local $a i32) (local $b i32) (local $c i32) (local $ws i32) (local $n i32)
      (local.set $a (call $upper (i32.const 220) (i32.const 3) (i32.const 900)))
      (local.set $b (call $upper (i32.const 230) (i32.const 4) (i32.const 908)))
      (local.set $c (call $upper (i32.const 240) (i32.const 2) (i32.const 916)))
      (if (i32.ne (i32.and (i32.and (local.get $a) (local.get $b)) (i32.and (local.get $c) (i32.const 15)))
            (i32.const 1 (; STARTED ;)))
        (then (return (i32.const 500))))
      (local.set $ws (call $ws_new))
      (call $join (i32.shr_u (local.get $a) (i32.const 4)) (local.get $ws))
      (call $join (i32.shr_u (local.get $b) (i32.const 4)) (local.get $ws))
      (call $join (i32.shr_u (local.get $c) (i32.const 4)) (local.get $ws))
      (block $all
        (loop $next
          (br_if $all (i32.eq (local.get $n) (i32.const 3)))
          (if (i32.ne (call $wait (local.get $ws) (i32.const 400)) (i32.const 1 (; SUBTASK ;)))
            (then (return (i32.const 501))))
          (if (i32.ne (i32.load (i32.const 404)) (i32.const 2 (; RETURNED ;)))
            (then (return (i32.const 502))))
          (call $join (i32.load (i32.const 400)) (i32.const 0))
          (call $subtask_drop (i32.load (i32.const 400)))
          (local.set $n (i32.add (local.get $n) (i32.const 1)))
          (br $next)))
      (if (i32.eqz (call $streq (i32.load (i32.const 900)) (i32.const 250) (i32.const 3)))
        (then (return (i32.const 503))))
      (if (i32.eqz (call $streq (i32.load (i32.const 908)) (i32.const 253) (i32.const 4)))
        (then (return (i32.const 504))))
      (if (i32.eqz (call $streq (i32.load (i32.const 916)) (i32.const 257) (i32.const 2)))
        (then (return (i32.const 505))))
      (i32.const 3)))
  (core instance $m (instantiate $M
    (with "env" (instance (export "memory" (memory $memory))))
    (with "" (instance
      (export "upper" (func $upper))
      (export "sum" (func $sum))
      (export "words" (func $words))
      (export "counter" (func $counter))
      (export "make" (func $make))
      (export "peek" (func $peek))
      (export "destroyed" (func $destroyed))
      (export "ws-new" (func $ws_new))
      (export "wait" (func $wait))
      (export "join" (func $join))
      (export "subtask-drop" (func $subtask_drop))
      (export "read" (func $read))
      (export "read-drop" (func $read_drop))
      (export "token-drop" (func $token_drop))))))
  (func (export "run-upper") async (result u32) (canon lift (core func $m "run-upper")))
  (func (export "run-sum") async (result u32) (canon lift (core func $m "run-sum")))
  (func (export "run-words") async (result u32) (canon lift (core func $m "run-words")))
  (func (export "run-counter") async (result u32) (canon lift (core func $m "run-counter")))
  (func (export "run-token") async (result u32) (canon lift (core func $m "run-token")))
  (func (export "run-concurrent") async (result u32) (canon lift (core func $m "run-concurrent")))
)
