;; SPDX-FileCopyrightText: © 2026 Austin Seipp
;; SPDX-License-Identifier: Apache-2.0

;; Implements `test:async/server` with the async ABI, every function lifted
;; with a callback: `upper` keeps its string in thread-local storage and
;; yields once before returning it uppercased, `sum` returns at once,
;; `words` returns a stream of strings it then writes one at a time,
;; `counter` returns what it put in thread-local storage a callback ago,
;; and `make` and `peek` hand out and read a resource.
(component
  (core module $Mem
    (memory (export "memory") 1)
    (global $heap (mut i32) (i32.const 4096))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32) (local $at i32)
      (local.set $at (i32.and (i32.add (global.get $heap) (i32.sub (local.get 2) (i32.const 1)))
        (i32.sub (i32.const 0) (local.get 2))))
      (global.set $heap (i32.add (local.get $at) (local.get 3)))
      (local.get $at))
    (data (i32.const 100) "w0w1w2w3w4w5w6w7w8w9"))
  (core instance $mem (instantiate $Mem))
  (alias core export $mem "memory" (core memory $memory))
  (alias core export $mem "realloc" (core func $realloc))
  (core module $D
    (global $destroyed (export "destroyed") (mut i32) (i32.const 0))
    (func (export "dtor") (param i32)
      (global.set $destroyed (i32.add (global.get $destroyed) (local.get 0)))))
  (core instance $d (instantiate $D))
  (type $token (resource (rep i32) (dtor (core func $d "dtor"))))
  (type $words (stream string))
  (type $own (own $token))
  (canon task.return (result string) (memory $memory) (core func $ret_string))
  (canon task.return (result u32) (core func $ret_u32))
  (canon task.return (result $words) (core func $ret_stream))
  (canon task.return (result $own) (core func $ret_token))
  (canon context.get i32 0 (core func $ctx_get))
  (canon context.set i32 0 (core func $ctx_set))
  (canon stream.new $words (core func $stream_new))
  (canon stream.write $words async (memory $memory) (core func $stream_write))
  (canon stream.drop-writable $words (core func $stream_drop))
  (canon waitable-set.new (core func $ws_new))
  (canon waitable.join (core func $join))
  (canon resource.new $token (core func $token_new))
  (core module $M
    (import "env" "memory" (memory 1))
    (import "env" "destroyed" (global $destroyed (mut i32)))
    (import "env" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
    (import "" "ret-string" (func $ret_string (param i32 i32)))
    (import "" "ret-u32" (func $ret_u32 (param i32)))
    (import "" "ret-stream" (func $ret_stream (param i32)))
    (import "" "ret-token" (func $ret_token (param i32)))
    (import "" "ctx-get" (func $ctx_get (result i32)))
    (import "" "ctx-set" (func $ctx_set (param i32)))
    (import "" "stream-new" (func $stream_new (result i64)))
    (import "" "stream-write" (func $stream_write (param i32 i32 i32) (result i32)))
    (import "" "stream-drop" (func $stream_drop (param i32)))
    (import "" "ws-new" (func $ws_new (result i32)))
    (import "" "join" (func $join (param i32 i32)))
    (import "" "token-new" (func $token_new (param i32) (result i32)))

    ;; upper: the string's record goes in thread-local storage, and the
    ;; task yields once.
    (func (export "upper") (param $ptr i32) (param $len i32) (result i32) (local $rec i32)
      (local.set $rec (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 8)))
      (i32.store (local.get $rec) (local.get $ptr))
      (i32.store offset=4 (local.get $rec) (local.get $len))
      (call $ctx_set (local.get $rec))
      (i32.const 1 (; YIELD ;)))
    (func (export "upper-cb") (param i32 i32 i32) (result i32)
      (local $rec i32) (local $p i32) (local $i i32) (local $c i32)
      (local.set $rec (call $ctx_get))
      (local.set $p (i32.load (local.get $rec)))
      (block $done
        (loop $next
          (br_if $done (i32.ge_u (local.get $i) (i32.load offset=4 (local.get $rec))))
          (local.set $c (i32.load8_u (i32.add (local.get $p) (local.get $i))))
          (if (i32.and (i32.ge_u (local.get $c) (i32.const 97)) (i32.le_u (local.get $c) (i32.const 122)))
            (then (i32.store8 (i32.add (local.get $p) (local.get $i))
              (i32.sub (local.get $c) (i32.const 32)))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (call $ret_string (local.get $p) (i32.load offset=4 (local.get $rec)))
      (i32.const 0 (; EXIT ;)))

    (func (export "sum") (param $ptr i32) (param $len i32) (result i32) (local $i i32) (local $s i32)
      (block $done
        (loop $next
          (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
          (local.set $s (i32.add (local.get $s)
            (i32.load (i32.add (local.get $ptr) (i32.shl (local.get $i) (i32.const 2))))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (call $ret_u32 (local.get $s))
      (i32.const 0 (; EXIT ;)))

    ;; words: the writable end, how many words to write, how many are
    ;; written, and the set the task waits on.
    (global $w (mut i32) (i32.const 0))
    (global $n (mut i32) (i32.const 0))
    (global $i (mut i32) (i32.const 0))
    (global $ws (mut i32) (i32.const 0))
    ;; Writes words until a write blocks (wait) or none are left (exit).
    (func $write-next (result i32) (local $r i32)
      (loop $again
        (if (i32.ge_u (global.get $i) (global.get $n))
          (then
            (call $stream_drop (global.get $w))
            (return (i32.const 0 (; EXIT ;)))))
        (i32.store (i32.const 64) (i32.add (i32.const 100) (i32.shl (global.get $i) (i32.const 1))))
        (i32.store (i32.const 68) (i32.const 2))
        (local.set $r (call $stream_write (global.get $w) (i32.const 64) (i32.const 1)))
        (if (i32.eq (local.get $r) (i32.const -1 (; BLOCKED ;)))
          (then (return (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (global.get $ws) (i32.const 4))))))
        (if (i32.eq (i32.and (local.get $r) (i32.const 15)) (i32.const 1 (; DROPPED ;)))
          (then
            (call $stream_drop (global.get $w))
            (return (i32.const 0 (; EXIT ;)))))
        (global.set $i (i32.add (global.get $i) (i32.const 1)))
        (br $again))
      unreachable)
    (func (export "words") (param $n i32) (result i32) (local $pair i64)
      (local.set $pair (call $stream_new))
      (global.set $w (i32.wrap_i64 (i64.shr_u (local.get $pair) (i64.const 32))))
      (global.set $n (local.get $n))
      (global.set $i (i32.const 0))
      (global.set $ws (call $ws_new))
      (call $join (global.get $w) (global.get $ws))
      (call $ret_stream (i32.wrap_i64 (local.get $pair)))
      (call $write-next))
    (func (export "words-cb") (param $event i32) (param $index i32) (param $payload i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 3 (; STREAM_WRITE ;))) (then unreachable))
      (if (i32.ne (local.get $index) (global.get $w)) (then unreachable))
      (if (i32.eq (i32.and (local.get $payload) (i32.const 15)) (i32.const 1 (; DROPPED ;)))
        (then
          (call $stream_drop (global.get $w))
          (return (i32.const 0 (; EXIT ;)))))
      (global.set $i (i32.add (global.get $i) (i32.const 1)))
      (call $write-next))

    (func (export "counter") (result i32)
      (call $ctx_set (i32.const 7))
      (i32.const 1 (; YIELD ;)))
    (func (export "counter-cb") (param i32 i32 i32) (result i32)
      (call $ret_u32 (call $ctx_get))
      (i32.const 0 (; EXIT ;)))

    (func (export "make") (param $n i32) (result i32)
      (call $ret_token (call $token_new (local.get $n)))
      (i32.const 0 (; EXIT ;)))
    ;; A borrow reaches the implementation as the representation.
    (func (export "peek") (param $rep i32) (result i32)
      (call $ret_u32 (local.get $rep))
      (i32.const 0 (; EXIT ;)))
    (func (export "destroyed") (result i32) (global.get $destroyed))
    (func (export "never-cb") (param i32 i32 i32) (result i32) unreachable))
  (core instance $m (instantiate $M
    (with "env" (instance
      (export "memory" (memory $memory))
      (export "destroyed" (global $d "destroyed"))
      (export "realloc" (func $realloc))))
    (with "" (instance
      (export "ret-string" (func $ret_string))
      (export "ret-u32" (func $ret_u32))
      (export "ret-stream" (func $ret_stream))
      (export "ret-token" (func $ret_token))
      (export "ctx-get" (func $ctx_get))
      (export "ctx-set" (func $ctx_set))
      (export "stream-new" (func $stream_new))
      (export "stream-write" (func $stream_write))
      (export "stream-drop" (func $stream_drop))
      (export "ws-new" (func $ws_new))
      (export "join" (func $join))
      (export "token-new" (func $token_new))))))
  (func $upper async (param "s" string) (result string)
    (canon lift (core func $m "upper") async (callback (core func $m "upper-cb"))
      (memory $memory) (realloc $realloc)))
  (type $numbers (list u32))
  (func $sum async (param "xs" $numbers) (result u32)
    (canon lift (core func $m "sum") async (callback (core func $m "never-cb"))
      (memory $memory) (realloc $realloc)))
  (func $words_fn async (param "n" u32) (result $words)
    (canon lift (core func $m "words") async (callback (core func $m "words-cb"))))
  (func $counter async (result u32)
    (canon lift (core func $m "counter") async (callback (core func $m "counter-cb"))))
  (func $make async (param "n" u32) (result $own)
    (canon lift (core func $m "make") async (callback (core func $m "never-cb"))))
  (type $borrowed (borrow $token))
  (func $peek async (param "t" $borrowed) (result u32)
    (canon lift (core func $m "peek") async (callback (core func $m "never-cb"))))
  (func $destroyed (result u32) (canon lift (core func $m "destroyed")))
  (instance $exports
    (export "token" (type $token))
    (export "upper" (func $upper))
    (export "sum" (func $sum))
    (export "words" (func $words_fn))
    (export "counter" (func $counter))
    (export "make" (func $make))
    (export "peek" (func $peek))
    (export "destroyed" (func $destroyed)))
  (export "test:async/server" (instance $exports))
)
