;; SPDX-FileCopyrightText: © 2026 Austin Seipp
;; SPDX-License-Identifier: Apache-2.0

;; The host's async edge, both ways. The host implements `fetch` and `echo`
;; as async imports, resolving them later, and `delay` synchronously; it
;; calls `total`, `shout` and `sleepy`, async exports lifted with a
;; callback, which return through the host's `wlink:task-return` imports,
;; and `blocking` and `delayed`, async exports lifted synchronously, which
;; it calls as it would any other export. `spinner` only yields until it
;; returns, a turn a pump.
(component
  (import "host:async/io" (instance $io
    (export "fetch" (func async (param "n" u32) (result u32)))
    (export "echo" (func async (param "s" string) (result string)))
    (export "delay" (func async (param "n" u32) (result u32)))))
  (core module $Mem
    (memory (export "memory") 1)
    (global $heap (mut i32) (i32.const 8192))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32) (local $at i32)
      (local.set $at (i32.and (i32.add (global.get $heap) (i32.sub (local.get 2) (i32.const 1)))
        (i32.sub (i32.const 0) (local.get 2))))
      (global.set $heap (i32.add (local.get $at) (local.get 3)))
      (local.get $at)))
  (core instance $mem (instantiate $Mem))
  (alias core export $mem "memory" (core memory $memory))
  (alias core export $mem "realloc" (core func $realloc))
  (core func $fetch (canon lower (func $io "fetch") async (memory $memory)))
  (core func $echo (canon lower (func $io "echo") async (memory $memory) (realloc $realloc)))
  (core func $delay (canon lower (func $io "delay")))
  (canon task.return (result u32) (core func $ret_u32))
  (canon task.return (result string) (memory $memory) (core func $ret_string))
  (canon task.cancel (core func $task_cancel))
  (canon waitable-set.new (core func $ws_new))
  (canon waitable-set.wait (memory $memory) (core func $wait))
  (canon waitable-set.drop (core func $ws_drop))
  (canon waitable.join (core func $join))
  (canon subtask.drop (core func $subtask_drop))
  (canon subtask.cancel async (core func $subtask_cancel))
  (core module $M
    (import "env" "memory" (memory 1))
    (import "" "fetch" (func $fetch (param i32 i32) (result i32)))
    (import "" "echo" (func $echo (param i32 i32 i32) (result i32)))
    (import "" "delay" (func $delay (param i32) (result i32)))
    (import "" "ret-u32" (func $ret_u32 (param i32)))
    (import "" "ret-string" (func $ret_string (param i32 i32)))
    (import "" "task-cancel" (func $task_cancel))
    (import "" "ws-new" (func $ws_new (result i32)))
    (import "" "wait" (func $wait (param i32 i32) (result i32)))
    (import "" "ws-drop" (func $ws_drop (param i32)))
    (import "" "join" (func $join (param i32 i32)))
    (import "" "subtask-drop" (func $subtask_drop (param i32)))
    (import "" "subtask-cancel" (func $subtask_cancel (param i32) (result i32)))

    ;; total(n): fetch(0) .. fetch(n - 1) at once, and the sum of what they
    ;; return. Each subtask's result area is 1000 + 4i, recorded by index
    ;; at 2000.
    (global $pending (mut i32) (i32.const 0))
    (global $sum (mut i32) (i32.const 0))
    (global $ws (mut i32) (i32.const 0))
    (func $total-done (result i32)
      (if (global.get $pending)
        (then (return (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (global.get $ws) (i32.const 4))))))
      (call $ws_drop (global.get $ws))
      (call $ret_u32 (global.get $sum))
      (i32.const 0 (; EXIT ;)))
    (func (export "total") (param $n i32) (result i32) (local $i i32) (local $out i32) (local $ret i32)
      (global.set $sum (i32.const 0))
      (global.set $pending (i32.const 0))
      (global.set $ws (call $ws_new))
      (block $started
        (loop $next
          (br_if $started (i32.ge_u (local.get $i) (local.get $n)))
          (local.set $out (i32.add (i32.const 1000) (i32.shl (local.get $i) (i32.const 2))))
          (local.set $ret (call $fetch (local.get $i) (local.get $out)))
          (if (i32.eq (local.get $ret) (i32.const 2 (; RETURNED ;)))
            (then (global.set $sum (i32.add (global.get $sum) (i32.load (local.get $out)))))
            (else
              (i32.store (i32.add (i32.const 2000) (i32.shl (i32.shr_u (local.get $ret) (i32.const 4)) (i32.const 2)))
                (local.get $out))
              (call $join (i32.shr_u (local.get $ret) (i32.const 4)) (global.get $ws))
              (global.set $pending (i32.add (global.get $pending) (i32.const 1)))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (call $total-done))
    (func (export "total-cb") (param $event i32) (param $sub i32) (param $state i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 1 (; SUBTASK ;))) (then unreachable))
      (if (i32.ne (local.get $state) (i32.const 2 (; RETURNED ;))) (then unreachable))
      (global.set $sum (i32.add (global.get $sum)
        (i32.load (i32.load (i32.add (i32.const 2000) (i32.shl (local.get $sub) (i32.const 2)))))))
      (call $join (local.get $sub) (i32.const 0))
      (call $subtask_drop (local.get $sub))
      (global.set $pending (i32.sub (global.get $pending) (i32.const 1)))
      (call $total-done))

    ;; shout(s): echo(s), uppercased.
    (global $shout-sub (mut i32) (i32.const 0))
    (global $shout-ws (mut i32) (i32.const 0))
    (func $shout-done (result i32) (local $p i32) (local $len i32) (local $i i32) (local $c i32)
      (local.set $p (i32.load (i32.const 1200)))
      (local.set $len (i32.load (i32.const 1204)))
      (block $done
        (loop $next
          (br_if $done (i32.ge_u (local.get $i) (local.get $len)))
          (local.set $c (i32.load8_u (i32.add (local.get $p) (local.get $i))))
          (if (i32.and (i32.ge_u (local.get $c) (i32.const 97)) (i32.le_u (local.get $c) (i32.const 122)))
            (then (i32.store8 (i32.add (local.get $p) (local.get $i))
              (i32.sub (local.get $c) (i32.const 32)))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (call $ret_string (local.get $p) (local.get $len))
      (i32.const 0 (; EXIT ;)))
    (func (export "shout") (param $ptr i32) (param $len i32) (result i32) (local $ret i32)
      (local.set $ret (call $echo (local.get $ptr) (local.get $len) (i32.const 1200)))
      (if (i32.eq (local.get $ret) (i32.const 2 (; RETURNED ;))) (then (return (call $shout-done))))
      (global.set $shout-sub (i32.shr_u (local.get $ret) (i32.const 4)))
      (global.set $shout-ws (call $ws_new))
      (call $join (global.get $shout-sub) (global.get $shout-ws))
      (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (global.get $shout-ws) (i32.const 4))))
    (func (export "shout-cb") (param $event i32) (param $sub i32) (param $state i32) (result i32)
      (if (i32.ne (local.get $state) (i32.const 2 (; RETURNED ;))) (then unreachable))
      (call $join (local.get $sub) (i32.const 0))
      (call $subtask_drop (local.get $sub))
      (call $ws_drop (global.get $shout-ws))
      (call $shout-done))

    ;; blocking(n): fetch(n), waited for synchronously, doubled.
    (func (export "blocking") (param $n i32) (result i32) (local $ret i32) (local $ws i32)
      (local.set $ret (call $fetch (local.get $n) (i32.const 1300)))
      (if (i32.ne (local.get $ret) (i32.const 2 (; RETURNED ;)))
        (then
          (local.set $ws (call $ws_new))
          (call $join (i32.shr_u (local.get $ret) (i32.const 4)) (local.get $ws))
          (if (i32.ne (call $wait (local.get $ws) (i32.const 1310)) (i32.const 1 (; SUBTASK ;)))
            (then unreachable))
          (if (i32.ne (i32.load (i32.const 1314)) (i32.const 2 (; RETURNED ;))) (then unreachable))
          (call $join (i32.shr_u (local.get $ret) (i32.const 4)) (i32.const 0))
          (call $subtask_drop (i32.shr_u (local.get $ret) (i32.const 4)))
          (call $ws_drop (local.get $ws))))
      (i32.mul (i32.load (i32.const 1300)) (i32.const 2)))

    (func (export "delayed") (param $n i32) (result i32)
      (call $delay (local.get $n)))

    ;; sleepy(): fetches what never comes, until the host cancels it; then
    ;; it cancels the fetch and confirms.
    (global $sleepy-sub (mut i32) (i32.const 0))
    (global $sleepy-ws (mut i32) (i32.const 0))
    (func (export "sleepy") (result i32) (local $ret i32)
      (local.set $ret (call $fetch (i32.const 99) (i32.const 1400)))
      (if (i32.ne (i32.and (local.get $ret) (i32.const 15)) (i32.const 1 (; STARTED ;))) (then unreachable))
      (global.set $sleepy-sub (i32.shr_u (local.get $ret) (i32.const 4)))
      (global.set $sleepy-ws (call $ws_new))
      (call $join (global.get $sleepy-sub) (global.get $sleepy-ws))
      (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (global.get $sleepy-ws) (i32.const 4))))
    ;; spinner(n): yields until it has had n turns, then returns n.
    (global $spins (mut i32) (i32.const 0))
    (global $spin-limit (mut i32) (i32.const 0))
    (func $spin (result i32)
      (global.set $spins (i32.add (global.get $spins) (i32.const 1)))
      (if (i32.lt_u (global.get $spins) (global.get $spin-limit))
        (then (return (i32.const 1 (; YIELD ;)))))
      (call $ret_u32 (global.get $spins))
      (i32.const 0 (; EXIT ;)))
    (func (export "spinner") (param $n i32) (result i32)
      (global.set $spins (i32.const 0))
      (global.set $spin-limit (local.get $n))
      (call $spin))
    (func (export "spinner-cb") (param i32 i32 i32) (result i32)
      (call $spin))

    (func (export "sleepy-cb") (param $event i32) (param i32) (param i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 6 (; TASK_CANCELLED ;))) (then unreachable))
      (call $join (global.get $sleepy-sub) (i32.const 0))
      ;; The host resolves the cancelled fetch before `cancel` returns.
      (if (i32.ne (call $subtask_cancel (global.get $sleepy-sub))
            (i32.const 4 (; CANCELLED_BEFORE_RETURNED ;)))
        (then unreachable))
      (call $subtask_drop (global.get $sleepy-sub))
      (call $ws_drop (global.get $sleepy-ws))
      (call $task_cancel)
      (i32.const 0 (; EXIT ;))))
  (core instance $m (instantiate $M
    (with "env" (instance (export "memory" (memory $memory))))
    (with "" (instance
      (export "fetch" (func $fetch))
      (export "echo" (func $echo))
      (export "delay" (func $delay))
      (export "ret-u32" (func $ret_u32))
      (export "ret-string" (func $ret_string))
      (export "task-cancel" (func $task_cancel))
      (export "ws-new" (func $ws_new))
      (export "wait" (func $wait))
      (export "ws-drop" (func $ws_drop))
      (export "join" (func $join))
      (export "subtask-drop" (func $subtask_drop))
      (export "subtask-cancel" (func $subtask_cancel))))))
  (func (export "total") async (param "n" u32) (result u32)
    (canon lift (core func $m "total") async (callback (core func $m "total-cb"))))
  (func (export "shout") async (param "s" string) (result string)
    (canon lift (core func $m "shout") async (callback (core func $m "shout-cb"))
      (memory $memory) (realloc $realloc)))
  (func (export "blocking") async (param "n" u32) (result u32)
    (canon lift (core func $m "blocking")))
  (func (export "delayed") async (param "n" u32) (result u32)
    (canon lift (core func $m "delayed")))
  (func (export "spinner") async (param "n" u32) (result u32)
    (canon lift (core func $m "spinner") async (callback (core func $m "spinner-cb"))))
  (func (export "sleepy") async (result u32)
    (canon lift (core func $m "sleepy") async (callback (core func $m "sleepy-cb"))))
)
