;; SPDX-FileCopyrightText: © 2026 Austin Seipp
;; SPDX-License-Identifier: Apache-2.0

;; Streams and futures across the host's edge, both ways. The host reads
;; what `count-to`, `names` and `later` write, and writes what `sum`,
;; `join` and `wait-for` read, all async exports lifted with a callback;
;; `relay`, lifted synchronously, copies a stream the host's `produce`
;; makes into one it hands the host's `consume`, blocking on every copy;
;; `hold`, `give` and `release` keep an end idle, for the host to cancel
;; its copies and hear of the drop. `nested` hands the host a stream of
;; streams through its `inbox`, and `gather` reads one the host makes: the
;; ends inside move between the host's table and the component's as they
;; are copied. `tokens` streams owned handles to the host, which holds
;; their representations, and `redeem` takes them back.
(component
  (import "host:streams/io" (instance $io
    (type $bytes (stream u8))
    (type $nest (stream $bytes))
    (export "produce" (func (param "n" u32) (result $bytes)))
    (export "consume" (func (param "s" $bytes)))
    (export "inbox" (func (param "s" $nest)))))
  (core module $Mem
    (memory (export "memory") 16)
    (global $heap (mut i32) (i32.const 65536))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32) (local $at i32)
      (local.set $at (i32.and (i32.add (global.get $heap) (i32.sub (local.get 2) (i32.const 1)))
        (i32.sub (i32.const 0) (local.get 2))))
      (global.set $heap (i32.add (local.get $at) (local.get 3)))
      (local.get $at))
    (data (i32.const 200) "abcdefghij"))
  (core instance $mem (instantiate $Mem))
  (alias core export $mem "memory" (core memory $memory))
  (alias core export $mem "realloc" (core func $realloc))
  (core module $D
    (global $destroyed (export "destroyed") (mut i32) (i32.const 0))
    (func (export "dtor") (param i32)
      (global.set $destroyed (i32.add (global.get $destroyed) (local.get 0)))))
  (core instance $d (instantiate $D))
  (type $token (resource (rep i32) (dtor (core func $d "dtor"))))
  (export $token-export "token" (type $token))
  (type $tokens (stream (own $token-export)))
  (type $numbers (stream u32))
  (type $strings (stream string))
  (type $bytes (stream u8))
  (type $later (future u32))
  (type $nest (stream $bytes))
  (core func $produce (canon lower (func $io "produce")))
  (core func $consume (canon lower (func $io "consume")))
  (core func $inbox (canon lower (func $io "inbox")))
  (canon task.return (result u32) (core func $ret_u32))
  (canon task.return (result string) (memory $memory) (core func $ret_string))
  (canon task.return (result $numbers) (core func $ret_numbers))
  (canon task.return (result $strings) (core func $ret_strings))
  (canon task.return (result $later) (core func $ret_later))
  (canon task.return (result $tokens) (core func $ret_tokens))
  (canon resource.new $token (core func $token_new))
  (canon resource.rep $token (core func $token_rep))
  (canon resource.drop $token (core func $token_drop))
  (canon stream.new $tokens (core func $tokens_new))
  (canon stream.write $tokens async (memory $memory) (core func $tokens_write))
  (canon stream.read $tokens async (memory $memory) (core func $tokens_read))
  (canon stream.drop-writable $tokens (core func $tokens_drop_w))
  (canon stream.drop-readable $tokens (core func $tokens_drop_r))
  (canon waitable-set.new (core func $ws_new))
  (canon waitable-set.drop (core func $ws_drop))
  (canon waitable.join (core func $join))
  (canon stream.new $numbers (core func $numbers_new))
  (canon stream.write $numbers async (memory $memory) (core func $numbers_write))
  (canon stream.read $numbers async (memory $memory) (core func $numbers_read))
  (canon stream.drop-writable $numbers (core func $numbers_drop_w))
  (canon stream.drop-readable $numbers (core func $numbers_drop_r))
  (canon stream.new $strings (core func $strings_new))
  (canon stream.write $strings async (memory $memory) (core func $strings_write))
  (canon stream.read $strings async (memory $memory) (realloc $realloc) (core func $strings_read))
  (canon stream.drop-writable $strings (core func $strings_drop_w))
  (canon stream.drop-readable $strings (core func $strings_drop_r))
  (canon stream.new $bytes (core func $bytes_new))
  (canon stream.read $bytes (memory $memory) (core func $bytes_read))
  (canon stream.write $bytes (memory $memory) (core func $bytes_write))
  (canon stream.drop-writable $bytes (core func $bytes_drop_w))
  (canon stream.drop-readable $bytes (core func $bytes_drop_r))
  (canon future.new $later (core func $later_new))
  (canon future.write $later async (memory $memory) (core func $later_write))
  (canon future.read $later async (memory $memory) (core func $later_read))
  (canon future.drop-writable $later (core func $later_drop_w))
  (canon future.drop-readable $later (core func $later_drop_r))
  (canon stream.new $nest (core func $nest_new))
  (canon stream.write $nest (memory $memory) (core func $nest_write))
  (canon stream.read $nest (memory $memory) (core func $nest_read))
  (canon stream.drop-writable $nest (core func $nest_drop_w))
  (canon stream.drop-readable $nest (core func $nest_drop_r))
  (core module $M
    (import "env" "memory" (memory 1))
    (import "env" "destroyed" (global $destroyed (mut i32)))
    (import "" "produce" (func $produce (param i32) (result i32)))
    (import "" "consume" (func $consume (param i32)))
    (import "" "inbox" (func $inbox (param i32)))
    (import "" "ret-u32" (func $ret_u32 (param i32)))
    (import "" "ret-string" (func $ret_string (param i32 i32)))
    (import "" "ret-numbers" (func $ret_numbers (param i32)))
    (import "" "ret-strings" (func $ret_strings (param i32)))
    (import "" "ret-later" (func $ret_later (param i32)))
    (import "" "ws-new" (func $ws_new (result i32)))
    (import "" "ws-drop" (func $ws_drop (param i32)))
    (import "" "join" (func $join (param i32 i32)))
    (import "" "numbers-new" (func $numbers_new (result i64)))
    (import "" "numbers-write" (func $numbers_write (param i32 i32 i32) (result i32)))
    (import "" "numbers-read" (func $numbers_read (param i32 i32 i32) (result i32)))
    (import "" "numbers-drop-w" (func $numbers_drop_w (param i32)))
    (import "" "numbers-drop-r" (func $numbers_drop_r (param i32)))
    (import "" "strings-new" (func $strings_new (result i64)))
    (import "" "strings-write" (func $strings_write (param i32 i32 i32) (result i32)))
    (import "" "strings-read" (func $strings_read (param i32 i32 i32) (result i32)))
    (import "" "strings-drop-w" (func $strings_drop_w (param i32)))
    (import "" "strings-drop-r" (func $strings_drop_r (param i32)))
    (import "" "bytes-new" (func $bytes_new (result i64)))
    (import "" "bytes-read" (func $bytes_read (param i32 i32 i32) (result i32)))
    (import "" "bytes-write" (func $bytes_write (param i32 i32 i32) (result i32)))
    (import "" "bytes-drop-w" (func $bytes_drop_w (param i32)))
    (import "" "bytes-drop-r" (func $bytes_drop_r (param i32)))
    (import "" "later-new" (func $later_new (result i64)))
    (import "" "later-write" (func $later_write (param i32 i32) (result i32)))
    (import "" "later-read" (func $later_read (param i32 i32) (result i32)))
    (import "" "later-drop-w" (func $later_drop_w (param i32)))
    (import "" "later-drop-r" (func $later_drop_r (param i32)))
    (import "" "nest-new" (func $nest_new (result i64)))
    (import "" "nest-write" (func $nest_write (param i32 i32 i32) (result i32)))
    (import "" "nest-read" (func $nest_read (param i32 i32 i32) (result i32)))
    (import "" "nest-drop-w" (func $nest_drop_w (param i32)))
    (import "" "nest-drop-r" (func $nest_drop_r (param i32)))
    (import "" "ret-tokens" (func $ret_tokens (param i32)))
    (import "" "token-new" (func $token_new (param i32) (result i32)))
    (import "" "token-rep" (func $token_rep (param i32) (result i32)))
    (import "" "token-drop" (func $token_drop (param i32)))
    (import "" "tokens-new" (func $tokens_new (result i64)))
    (import "" "tokens-write" (func $tokens_write (param i32 i32 i32) (result i32)))
    (import "" "tokens-read" (func $tokens_read (param i32 i32 i32) (result i32)))
    (import "" "tokens-drop-w" (func $tokens_drop_w (param i32)))
    (import "" "tokens-drop-r" (func $tokens_drop_r (param i32)))

    (func $wait-on (param $ws i32) (result i32)
      (i32.or (i32.const 2 (; WAIT ;)) (i32.shl (local.get $ws) (i32.const 4))))
    (func $readable (param $ends i64) (result i32)
      (i32.wrap_i64 (local.get $ends)))
    (func $writable (param $ends i64) (result i32)
      (i32.wrap_i64 (i64.shr_u (local.get $ends) (i64.const 32))))

    ;; count-to(n): a stream of 3i + 1 for i below n, written from 1024 in
    ;; one write, rewritten from where each partial write stopped.
    (global $ct-w (mut i32) (i32.const 0))
    (global $ct-n (mut i32) (i32.const 0))
    (global $ct-done (mut i32) (i32.const 0))
    (global $ct-ws (mut i32) (i32.const 0))
    (func (export "count-to") (param $n i32) (result i32) (local $ends i64) (local $i i32)
      (block $filled
        (loop $next
          (br_if $filled (i32.ge_u (local.get $i) (local.get $n)))
          (i32.store (i32.add (i32.const 1024) (i32.shl (local.get $i) (i32.const 2)))
            (i32.add (i32.mul (local.get $i) (i32.const 3)) (i32.const 1)))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (local.set $ends (call $numbers_new))
      (global.set $ct-w (call $writable (local.get $ends)))
      (global.set $ct-n (local.get $n))
      (global.set $ct-done (i32.const 0))
      (global.set $ct-ws (call $ws_new))
      (call $join (global.get $ct-w) (global.get $ct-ws))
      (call $ret_numbers (call $readable (local.get $ends)))
      (call $ct-next))
    ;; Counts a write's progress: whether the reader is still there.
    (func $ct-progress (param $r i32) (result i32)
      (global.set $ct-done (i32.add (global.get $ct-done) (i32.shr_u (local.get $r) (i32.const 4))))
      (i32.eqz (i32.and (local.get $r) (i32.const 15))))
    (func $ct-next (result i32) (local $r i32)
      (loop $again
        (if (i32.lt_u (global.get $ct-done) (global.get $ct-n))
          (then
            (local.set $r (call $numbers_write (global.get $ct-w)
              (i32.add (i32.const 1024) (i32.shl (global.get $ct-done) (i32.const 2)))
              (i32.sub (global.get $ct-n) (global.get $ct-done))))
            (if (i32.eq (local.get $r) (i32.const -1))
              (then (return (call $wait-on (global.get $ct-ws)))))
            (br_if $again (call $ct-progress (local.get $r))))))
      (call $numbers_drop_w (global.get $ct-w))
      (call $ws_drop (global.get $ct-ws))
      (i32.const 0 (; EXIT ;)))
    (func (export "count-to-cb") (param $event i32) (param i32) (param $r i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 3 (; STREAM_WRITE ;))) (then unreachable))
      (if (i32.eqz (call $ct-progress (local.get $r)))
        (then (global.set $ct-n (global.get $ct-done))))
      (call $ct-next))

    ;; sum(values): reads up to four at a time into 2048.
    (global $sum-r (mut i32) (i32.const 0))
    (global $sum-total (mut i32) (i32.const 0))
    (global $sum-ws (mut i32) (i32.const 0))
    (func (export "sum") (param $r i32) (result i32)
      (global.set $sum-r (local.get $r))
      (global.set $sum-total (i32.const 0))
      (global.set $sum-ws (call $ws_new))
      (call $join (local.get $r) (global.get $sum-ws))
      (call $sum-next))
    ;; Adds up what a read brought: whether the writer is still there.
    (func $sum-progress (param $r i32) (result i32) (local $i i32)
      (block $added
        (loop $next
          (br_if $added (i32.ge_u (local.get $i) (i32.shr_u (local.get $r) (i32.const 4))))
          (global.set $sum-total (i32.add (global.get $sum-total)
            (i32.load (i32.add (i32.const 2048) (i32.shl (local.get $i) (i32.const 2))))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (i32.eqz (i32.and (local.get $r) (i32.const 15))))
    (func $sum-next (result i32) (local $r i32)
      (loop $again
        (local.set $r (call $numbers_read (global.get $sum-r) (i32.const 2048) (i32.const 4)))
        (if (i32.eq (local.get $r) (i32.const -1))
          (then (return (call $wait-on (global.get $sum-ws)))))
        (br_if $again (call $sum-progress (local.get $r))))
      (call $sum-finish))
    (func $sum-finish (result i32)
      (call $numbers_drop_r (global.get $sum-r))
      (call $ws_drop (global.get $sum-ws))
      (call $ret_u32 (global.get $sum-total))
      (i32.const 0 (; EXIT ;)))
    (func (export "sum-cb") (param $event i32) (param i32) (param $r i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 2 (; STREAM_READ ;))) (then unreachable))
      (if (call $sum-progress (local.get $r)) (then (return (call $sum-next))))
      (call $sum-finish))

    ;; names(n): the strings "a", "ab", ... "abcdefghij", "a", ..., their
    ;; records at 3072, written as count-to writes.
    (global $nm-w (mut i32) (i32.const 0))
    (global $nm-n (mut i32) (i32.const 0))
    (global $nm-done (mut i32) (i32.const 0))
    (global $nm-ws (mut i32) (i32.const 0))
    (func (export "names") (param $n i32) (result i32) (local $ends i64) (local $i i32) (local $rec i32)
      (block $filled
        (loop $next
          (br_if $filled (i32.ge_u (local.get $i) (local.get $n)))
          (local.set $rec (i32.add (i32.const 3072) (i32.shl (local.get $i) (i32.const 3))))
          (i32.store (local.get $rec) (i32.const 200))
          (i32.store offset=4 (local.get $rec)
            (i32.add (i32.rem_u (local.get $i) (i32.const 10)) (i32.const 1)))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (local.set $ends (call $strings_new))
      (global.set $nm-w (call $writable (local.get $ends)))
      (global.set $nm-n (local.get $n))
      (global.set $nm-done (i32.const 0))
      (global.set $nm-ws (call $ws_new))
      (call $join (global.get $nm-w) (global.get $nm-ws))
      (call $ret_strings (call $readable (local.get $ends)))
      (call $nm-next))
    (func $nm-progress (param $r i32) (result i32)
      (global.set $nm-done (i32.add (global.get $nm-done) (i32.shr_u (local.get $r) (i32.const 4))))
      (i32.eqz (i32.and (local.get $r) (i32.const 15))))
    (func $nm-next (result i32) (local $r i32)
      (loop $again
        (if (i32.lt_u (global.get $nm-done) (global.get $nm-n))
          (then
            (local.set $r (call $strings_write (global.get $nm-w)
              (i32.add (i32.const 3072) (i32.shl (global.get $nm-done) (i32.const 3)))
              (i32.sub (global.get $nm-n) (global.get $nm-done))))
            (if (i32.eq (local.get $r) (i32.const -1))
              (then (return (call $wait-on (global.get $nm-ws)))))
            (br_if $again (call $nm-progress (local.get $r))))))
      (call $strings_drop_w (global.get $nm-w))
      (call $ws_drop (global.get $nm-ws))
      (i32.const 0 (; EXIT ;)))
    (func (export "names-cb") (param $event i32) (param i32) (param $r i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 3 (; STREAM_WRITE ;))) (then unreachable))
      (if (i32.eqz (call $nm-progress (local.get $r)))
        (then (global.set $nm-n (global.get $nm-done))))
      (call $nm-next))

    ;; join(parts): reads one string at a time into its record at 4096 and
    ;; appends it at 16384.
    (global $jn-r (mut i32) (i32.const 0))
    (global $jn-len (mut i32) (i32.const 0))
    (global $jn-ws (mut i32) (i32.const 0))
    (func (export "join") (param $r i32) (result i32)
      (global.set $jn-r (local.get $r))
      (global.set $jn-len (i32.const 0))
      (global.set $jn-ws (call $ws_new))
      (call $join (local.get $r) (global.get $jn-ws))
      (call $jn-next))
    (func $jn-progress (param $r i32) (result i32)
      (if (i32.shr_u (local.get $r) (i32.const 4))
        (then
          (memory.copy (i32.add (i32.const 16384) (global.get $jn-len))
            (i32.load (i32.const 4096)) (i32.load (i32.const 4100)))
          (global.set $jn-len (i32.add (global.get $jn-len) (i32.load (i32.const 4100))))))
      (i32.eqz (i32.and (local.get $r) (i32.const 15))))
    (func $jn-next (result i32) (local $r i32)
      (loop $again
        (local.set $r (call $strings_read (global.get $jn-r) (i32.const 4096) (i32.const 1)))
        (if (i32.eq (local.get $r) (i32.const -1))
          (then (return (call $wait-on (global.get $jn-ws)))))
        (br_if $again (call $jn-progress (local.get $r))))
      (call $jn-finish))
    (func $jn-finish (result i32)
      (call $strings_drop_r (global.get $jn-r))
      (call $ws_drop (global.get $jn-ws))
      (call $ret_string (i32.const 16384) (global.get $jn-len))
      (i32.const 0 (; EXIT ;)))
    (func (export "join-cb") (param $event i32) (param i32) (param $r i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 2 (; STREAM_READ ;))) (then unreachable))
      (if (call $jn-progress (local.get $r)) (then (return (call $jn-next))))
      (call $jn-finish))

    ;; later(v): a future of v + 1, written once it is returned.
    (global $lt-w (mut i32) (i32.const 0))
    (global $lt-ws (mut i32) (i32.const 0))
    (func (export "later") (param $v i32) (result i32) (local $ends i64)
      (local.set $ends (call $later_new))
      (global.set $lt-w (call $writable (local.get $ends)))
      (call $ret_later (call $readable (local.get $ends)))
      (i32.store (i32.const 2100) (i32.add (local.get $v) (i32.const 1)))
      (if (i32.ne (call $later_write (global.get $lt-w) (i32.const 2100)) (i32.const -1))
        (then
          (call $later_drop_w (global.get $lt-w))
          (return (i32.const 0 (; EXIT ;)))))
      (global.set $lt-ws (call $ws_new))
      (call $join (global.get $lt-w) (global.get $lt-ws))
      (call $wait-on (global.get $lt-ws)))
    (func (export "later-cb") (param $event i32) (param i32) (param $r i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 5 (; FUTURE_WRITE ;))) (then unreachable))
      (if (i32.ne (local.get $r) (i32.const 0 (; COMPLETED ;))) (then unreachable))
      (call $later_drop_w (global.get $lt-w))
      (call $ws_drop (global.get $lt-ws))
      (i32.const 0 (; EXIT ;)))

    ;; wait-for(f): twice the future's value.
    (global $wf-r (mut i32) (i32.const 0))
    (global $wf-ws (mut i32) (i32.const 0))
    (func (export "wait-for") (param $f i32) (result i32) (local $r i32)
      (global.set $wf-r (local.get $f))
      (global.set $wf-ws (call $ws_new))
      (local.set $r (call $later_read (local.get $f) (i32.const 2104)))
      (if (i32.ne (local.get $r) (i32.const -1)) (then (return (call $wf-finish (local.get $r)))))
      (call $join (local.get $f) (global.get $wf-ws))
      (call $wait-on (global.get $wf-ws)))
    (func $wf-finish (param $r i32) (result i32)
      (if (i32.ne (local.get $r) (i32.const 0 (; COMPLETED ;))) (then unreachable))
      (call $later_drop_r (global.get $wf-r))
      (call $ws_drop (global.get $wf-ws))
      (call $ret_u32 (i32.mul (i32.load (i32.const 2104)) (i32.const 2)))
      (i32.const 0 (; EXIT ;)))
    (func (export "wait-for-cb") (param $event i32) (param i32) (param $r i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 4 (; FUTURE_READ ;))) (then unreachable))
      (call $wf-finish (local.get $r)))

    ;; hold(s) keeps a readable end, give() a writable end, both idle, until
    ;; release() drops them.
    (global $held-r (mut i32) (i32.const 0))
    (global $held-w (mut i32) (i32.const 0))
    (func (export "hold") (param $r i32)
      (global.set $held-r (local.get $r)))
    (func (export "give") (result i32) (local $ends i64)
      (local.set $ends (call $numbers_new))
      (global.set $held-w (call $writable (local.get $ends)))
      (call $readable (local.get $ends)))
    (func (export "release")
      (if (global.get $held-r)
        (then
          (call $numbers_drop_r (global.get $held-r))
          (global.set $held-r (i32.const 0))))
      (if (global.get $held-w)
        (then
          (call $numbers_drop_w (global.get $held-w))
          (global.set $held-w (i32.const 0)))))

    ;; relay(n): copies produce(n), each byte plus one, into a stream it
    ;; hands consume, sixteen bytes at a time through 8192, blocking on every
    ;; read and write; returns how many bytes it copied.
    (func (export "relay") (param $n i32) (result i32)
      (local $in i32) (local $ends i64) (local $out i32) (local $r i32) (local $count i32)
      (local $sent i32) (local $w i32) (local $i i32) (local $total i32)
      (local.set $in (call $produce (local.get $n)))
      (local.set $ends (call $bytes_new))
      (local.set $out (call $writable (local.get $ends)))
      (call $consume (call $readable (local.get $ends)))
      (loop $next
        (local.set $r (call $bytes_read (local.get $in) (i32.const 8192) (i32.const 16)))
        (local.set $count (i32.shr_u (local.get $r) (i32.const 4)))
        (local.set $i (i32.const 0))
        (block $bumped
          (loop $bump
            (br_if $bumped (i32.ge_u (local.get $i) (local.get $count)))
            (i32.store8 (i32.add (i32.const 8192) (local.get $i))
              (i32.add (i32.load8_u (i32.add (i32.const 8192) (local.get $i))) (i32.const 1)))
            (local.set $i (i32.add (local.get $i) (i32.const 1)))
            (br $bump)))
        (local.set $sent (i32.const 0))
        (block $written
          (loop $write
            (br_if $written (i32.ge_u (local.get $sent) (local.get $count)))
            (local.set $w (call $bytes_write (local.get $out)
              (i32.add (i32.const 8192) (local.get $sent))
              (i32.sub (local.get $count) (local.get $sent))))
            ;; The host reads to the end.
            (if (i32.and (local.get $w) (i32.const 15)) (then unreachable))
            (local.set $sent (i32.add (local.get $sent) (i32.shr_u (local.get $w) (i32.const 4))))
            (br $write)))
        (local.set $total (i32.add (local.get $total) (local.get $count)))
        (br_if $next (i32.eqz (i32.and (local.get $r) (i32.const 15)))))
      (call $bytes_drop_r (local.get $in))
      (call $bytes_drop_w (local.get $out))
      (local.get $total))

    ;; nested(n): hands the host a stream of n streams, the i-th holding i
    ;; bytes of value i, written once the host has taken it; blocks on every
    ;; copy.
    (func (export "nested") (param $n i32) (result i32)
      (local $ends i64) (local $out i32) (local $inner i64) (local $i i32) (local $r i32)
      (local $sent i32)
      (local.set $ends (call $nest_new))
      (local.set $out (call $writable (local.get $ends)))
      (call $inbox (call $readable (local.get $ends)))
      (block $done
        (loop $next
          (br_if $done (i32.ge_u (local.get $i) (local.get $n)))
          (local.set $inner (call $bytes_new))
          (i32.store (i32.const 8448) (call $readable (local.get $inner)))
          (if (i32.ne (call $nest_write (local.get $out) (i32.const 8448) (i32.const 1))
                (i32.const 0x10 (; one, COMPLETED ;)))
            (then unreachable))
          (memory.fill (i32.const 8464) (local.get $i) (local.get $i))
          (local.set $sent (i32.const 0))
          (block $written
            (loop $write
              (br_if $written (i32.ge_u (local.get $sent) (local.get $i)))
              (local.set $r (call $bytes_write (call $writable (local.get $inner))
                (i32.add (i32.const 8464) (local.get $sent))
                (i32.sub (local.get $i) (local.get $sent))))
              (if (i32.and (local.get $r) (i32.const 15)) (then unreachable))
              (local.set $sent (i32.add (local.get $sent) (i32.shr_u (local.get $r) (i32.const 4))))
              (br $write)))
          (call $bytes_drop_w (call $writable (local.get $inner)))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (call $nest_drop_w (local.get $out))
      (local.get $n))

    ;; gather(s): the sum of the bytes of every stream s holds, read in turn.
    (func (export "gather") (param $in i32) (result i32)
      (local $r i32) (local $inner i32) (local $got i32) (local $i i32) (local $sum i32)
      (loop $next
        (local.set $r (call $nest_read (local.get $in) (i32.const 8448) (i32.const 1)))
        (if (i32.shr_u (local.get $r) (i32.const 4))
          (then
            (local.set $inner (i32.load (i32.const 8448)))
            (loop $bytes
              (local.set $got (call $bytes_read (local.get $inner) (i32.const 8464) (i32.const 16)))
              (local.set $i (i32.const 0))
              (block $added
                (loop $add
                  (br_if $added (i32.ge_u (local.get $i) (i32.shr_u (local.get $got) (i32.const 4))))
                  (local.set $sum (i32.add (local.get $sum)
                    (i32.load8_u (i32.add (i32.const 8464) (local.get $i)))))
                  (local.set $i (i32.add (local.get $i) (i32.const 1)))
                  (br $add)))
              (br_if $bytes (i32.eqz (i32.and (local.get $got) (i32.const 15)))))
            (call $bytes_drop_r (local.get $inner))))
        (br_if $next (i32.eqz (i32.and (local.get $r) (i32.const 15)))))
      (call $nest_drop_r (local.get $in))
      (local.get $sum))

    ;; tokens(n): a stream of n new tokens, representations 100 + i, their
    ;; handles at 5120, written as count-to writes.
    (global $tk-w (mut i32) (i32.const 0))
    (global $tk-n (mut i32) (i32.const 0))
    (global $tk-done (mut i32) (i32.const 0))
    (global $tk-ws (mut i32) (i32.const 0))
    (func (export "tokens") (param $n i32) (result i32) (local $ends i64) (local $i i32)
      (block $filled
        (loop $next
          (br_if $filled (i32.ge_u (local.get $i) (local.get $n)))
          (i32.store (i32.add (i32.const 5120) (i32.shl (local.get $i) (i32.const 2)))
            (call $token_new (i32.add (local.get $i) (i32.const 100))))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (local.set $ends (call $tokens_new))
      (global.set $tk-w (call $writable (local.get $ends)))
      (global.set $tk-n (local.get $n))
      (global.set $tk-done (i32.const 0))
      (global.set $tk-ws (call $ws_new))
      (call $join (global.get $tk-w) (global.get $tk-ws))
      (call $ret_tokens (call $readable (local.get $ends)))
      (call $tk-next))
    (func $tk-progress (param $r i32) (result i32)
      (global.set $tk-done (i32.add (global.get $tk-done) (i32.shr_u (local.get $r) (i32.const 4))))
      (i32.eqz (i32.and (local.get $r) (i32.const 15))))
    (func $tk-next (result i32) (local $r i32)
      (loop $again
        (if (i32.lt_u (global.get $tk-done) (global.get $tk-n))
          (then
            (local.set $r (call $tokens_write (global.get $tk-w)
              (i32.add (i32.const 5120) (i32.shl (global.get $tk-done) (i32.const 2)))
              (i32.sub (global.get $tk-n) (global.get $tk-done))))
            (if (i32.eq (local.get $r) (i32.const -1))
              (then (return (call $wait-on (global.get $tk-ws)))))
            (br_if $again (call $tk-progress (local.get $r))))))
      (call $tokens_drop_w (global.get $tk-w))
      (call $ws_drop (global.get $tk-ws))
      (i32.const 0 (; EXIT ;)))
    (func (export "tokens-cb") (param $event i32) (param i32) (param $r i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 3 (; STREAM_WRITE ;))) (then unreachable))
      ;; The host reads them all.
      (if (i32.eqz (call $tk-progress (local.get $r))) (then unreachable))
      (call $tk-next))

    ;; redeem(s): the sum of the representations of the tokens s holds, each
    ;; dropped as it is counted; reads up to four at a time into 5632.
    (global $rd-r (mut i32) (i32.const 0))
    (global $rd-total (mut i32) (i32.const 0))
    (global $rd-ws (mut i32) (i32.const 0))
    (func (export "redeem") (param $r i32) (result i32)
      (global.set $rd-r (local.get $r))
      (global.set $rd-total (i32.const 0))
      (global.set $rd-ws (call $ws_new))
      (call $join (local.get $r) (global.get $rd-ws))
      (call $rd-next))
    (func $rd-progress (param $r i32) (result i32) (local $i i32) (local $handle i32)
      (block $counted
        (loop $next
          (br_if $counted (i32.ge_u (local.get $i) (i32.shr_u (local.get $r) (i32.const 4))))
          (local.set $handle (i32.load (i32.add (i32.const 5632) (i32.shl (local.get $i) (i32.const 2)))))
          (global.set $rd-total (i32.add (global.get $rd-total) (call $token_rep (local.get $handle))))
          (call $token_drop (local.get $handle))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $next)))
      (i32.eqz (i32.and (local.get $r) (i32.const 15))))
    (func $rd-next (result i32) (local $r i32)
      (loop $again
        (local.set $r (call $tokens_read (global.get $rd-r) (i32.const 5632) (i32.const 4)))
        (if (i32.eq (local.get $r) (i32.const -1))
          (then (return (call $wait-on (global.get $rd-ws)))))
        (br_if $again (call $rd-progress (local.get $r))))
      (call $tokens_drop_r (global.get $rd-r))
      (call $ws_drop (global.get $rd-ws))
      (call $ret_u32 (global.get $rd-total))
      (i32.const 0 (; EXIT ;)))
    (func (export "redeem-cb") (param $event i32) (param i32) (param $r i32) (result i32)
      (if (i32.ne (local.get $event) (i32.const 2 (; STREAM_READ ;))) (then unreachable))
      (if (call $rd-progress (local.get $r)) (then (return (call $rd-next))))
      (call $tokens_drop_r (global.get $rd-r))
      (call $ws_drop (global.get $rd-ws))
      (call $ret_u32 (global.get $rd-total))
      (i32.const 0 (; EXIT ;)))

    (func (export "destroyed") (result i32)
      (global.get $destroyed)))
  (core instance $m (instantiate $M
    (with "env" (instance
      (export "memory" (memory $memory))
      (export "destroyed" (global $d "destroyed"))))
    (with "" (instance
      (export "produce" (func $produce))
      (export "consume" (func $consume))
      (export "inbox" (func $inbox))
      (export "ret-u32" (func $ret_u32))
      (export "ret-string" (func $ret_string))
      (export "ret-numbers" (func $ret_numbers))
      (export "ret-strings" (func $ret_strings))
      (export "ret-later" (func $ret_later))
      (export "ws-new" (func $ws_new))
      (export "ws-drop" (func $ws_drop))
      (export "join" (func $join))
      (export "numbers-new" (func $numbers_new))
      (export "numbers-write" (func $numbers_write))
      (export "numbers-read" (func $numbers_read))
      (export "numbers-drop-w" (func $numbers_drop_w))
      (export "numbers-drop-r" (func $numbers_drop_r))
      (export "strings-new" (func $strings_new))
      (export "strings-write" (func $strings_write))
      (export "strings-read" (func $strings_read))
      (export "strings-drop-w" (func $strings_drop_w))
      (export "strings-drop-r" (func $strings_drop_r))
      (export "bytes-new" (func $bytes_new))
      (export "bytes-read" (func $bytes_read))
      (export "bytes-write" (func $bytes_write))
      (export "bytes-drop-w" (func $bytes_drop_w))
      (export "bytes-drop-r" (func $bytes_drop_r))
      (export "later-new" (func $later_new))
      (export "later-write" (func $later_write))
      (export "later-read" (func $later_read))
      (export "later-drop-w" (func $later_drop_w))
      (export "later-drop-r" (func $later_drop_r))
      (export "nest-new" (func $nest_new))
      (export "nest-write" (func $nest_write))
      (export "nest-read" (func $nest_read))
      (export "nest-drop-w" (func $nest_drop_w))
      (export "nest-drop-r" (func $nest_drop_r))
      (export "ret-tokens" (func $ret_tokens))
      (export "token-new" (func $token_new))
      (export "token-rep" (func $token_rep))
      (export "token-drop" (func $token_drop))
      (export "tokens-new" (func $tokens_new))
      (export "tokens-write" (func $tokens_write))
      (export "tokens-read" (func $tokens_read))
      (export "tokens-drop-w" (func $tokens_drop_w))
      (export "tokens-drop-r" (func $tokens_drop_r))))))
  (func (export "count-to") async (param "n" u32) (result $numbers)
    (canon lift (core func $m "count-to") async (callback (core func $m "count-to-cb"))))
  (func (export "sum") async (param "values" $numbers) (result u32)
    (canon lift (core func $m "sum") async (callback (core func $m "sum-cb"))))
  (func (export "names") async (param "n" u32) (result $strings)
    (canon lift (core func $m "names") async (callback (core func $m "names-cb"))))
  (func (export "join") async (param "parts" $strings) (result string)
    (canon lift (core func $m "join") async (callback (core func $m "join-cb")) (memory $memory)))
  (func (export "later") async (param "v" u32) (result $later)
    (canon lift (core func $m "later") async (callback (core func $m "later-cb"))))
  (func (export "wait-for") async (param "f" $later) (result u32)
    (canon lift (core func $m "wait-for") async (callback (core func $m "wait-for-cb"))))
  (func (export "hold") (param "s" $numbers)
    (canon lift (core func $m "hold")))
  (func (export "give") (result $numbers)
    (canon lift (core func $m "give")))
  (func (export "release")
    (canon lift (core func $m "release")))
  (func (export "relay") async (param "n" u32) (result u32)
    (canon lift (core func $m "relay")))
  (func (export "nested") async (param "n" u32) (result u32)
    (canon lift (core func $m "nested")))
  (func (export "gather") async (param "s" $nest) (result u32)
    (canon lift (core func $m "gather")))
  (func (export "tokens") async (param "n" u32) (result $tokens)
    (canon lift (core func $m "tokens") async (callback (core func $m "tokens-cb"))))
  (func (export "redeem") async (param "s" $tokens) (result u32)
    (canon lift (core func $m "redeem") async (callback (core func $m "redeem-cb"))))
  (func (export "destroyed") (result u32)
    (canon lift (core func $m "destroyed")))
)
