# SPDX-FileCopyrightText: © 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# The configuration headers binutils_stage writes for binutils 2.41, as
# configure would for native x86_64 Linux with musl: each component's
# macros set to 1 (*_ON), then its valued macros (*_VALUES).

LIBIBERTY_ON = [
    "STDC_HEADERS",
    "TIME_WITH_SYS_TIME",
    "HAVE_ALLOCA_H",
    "HAVE_ASPRINTF",
    "HAVE_ATEXIT",
    "HAVE_BASENAME",
    "HAVE_BCMP",
    "HAVE_BCOPY",
    "HAVE_BSEARCH",
    "HAVE_BZERO",
    "HAVE_CALLOC",
    "HAVE_CLOCK",
    "HAVE_DUP3",
    "HAVE_FCNTL_H",
    "HAVE_FFS",
    "HAVE_FORK",
    "HAVE_GETCWD",
    "HAVE_GETPAGESIZE",
    "HAVE_GETRLIMIT",
    "HAVE_GETRUSAGE",
    "HAVE_GETTIMEOFDAY",
    "HAVE_INDEX",
    "HAVE_INSQUE",
    "HAVE_INTPTR_T",
    "HAVE_INTTYPES_H",
    "HAVE_LIMITS_H",
    "HAVE_LONG_LONG",
    "HAVE_MALLOC_H",
    "HAVE_MEMCHR",
    "HAVE_MEMCMP",
    "HAVE_MEMCPY",
    "HAVE_MEMMEM",
    "HAVE_MEMMOVE",
    "HAVE_MEMORY_H",
    "HAVE_MEMSET",
    "HAVE_MKSTEMPS",
    "HAVE_MMAP",
    "HAVE_PIPE2",
    "HAVE_PSIGNAL",
    "HAVE_PUTENV",
    "HAVE_RANDOM",
    "HAVE_REALPATH",
    "HAVE_RENAME",
    "HAVE_RINDEX",
    "HAVE_SBRK",
    "HAVE_SETENV",
    "HAVE_SETRLIMIT",
    "HAVE_SNPRINTF",
    "HAVE_STDINT_H",
    "HAVE_STDIO_EXT_H",
    "HAVE_STDLIB_H",
    "HAVE_STPCPY",
    "HAVE_STPNCPY",
    "HAVE_STRCASECMP",
    "HAVE_STRCHR",
    "HAVE_STRDUP",
    "HAVE_STRERROR",
    "HAVE_STRINGS_H",
    "HAVE_STRING_H",
    "HAVE_STRNCASECMP",
    "HAVE_STRNDUP",
    "HAVE_STRNLEN",
    "HAVE_STRRCHR",
    "HAVE_STRSIGNAL",
    "HAVE_STRSTR",
    "HAVE_STRTOD",
    "HAVE_STRTOL",
    "HAVE_STRTOLL",
    "HAVE_STRTOUL",
    "HAVE_STRTOULL",
    "HAVE_STRVERSCMP",
    "HAVE_SYSCONF",
    "HAVE_SYS_FILE_H",
    "HAVE_SYS_MMAN_H",
    "HAVE_SYS_PARAM_H",
    "HAVE_SYS_PRCTL_H",
    "HAVE_SYS_RESOURCE_H",
    "HAVE_SYS_STAT_H",
    "HAVE_SYS_SYSINFO_H",
    "HAVE_SYS_TIME_H",
    "HAVE_SYS_TYPES_H",
    "HAVE_SYS_WAIT_H",
    "HAVE_TIMES",
    "HAVE_TIME_H",
    "HAVE_TMPNAM",
    "HAVE_UINTPTR_T",
    "HAVE_UNISTD_H",
    "HAVE_VASPRINTF",
    "HAVE_VFORK",
    "HAVE_VFPRINTF",
    "HAVE_VPRINTF",
    "HAVE_VSPRINTF",
    "HAVE_WAIT3",
    "HAVE_WAIT4",
    "HAVE_WAITPID",
    "HAVE_WORKING_FORK",
    "HAVE_WORKING_VFORK",
    "HAVE___FSETLOCKING",
    "HAVE_DECL_ASPRINTF",
    "HAVE_DECL_CALLOC",
    "HAVE_DECL_FFS",
    "HAVE_DECL_GETENV",
    "HAVE_DECL_GETOPT",
    "HAVE_DECL_MALLOC",
    "HAVE_DECL_REALLOC",
    "HAVE_DECL_SBRK",
    "HAVE_DECL_SNPRINTF",
    "HAVE_DECL_STRNLEN",
    "HAVE_DECL_STRTOL",
    "HAVE_DECL_STRTOLL",
    "HAVE_DECL_STRTOUL",
    "HAVE_DECL_STRTOULL",
    "HAVE_DECL_STRVERSCMP",
    "HAVE_DECL_VASPRINTF",
    "HAVE_DECL_VSNPRINTF",
]

LIBIBERTY_VALUES = {
    # musl 1.2.5 declares basename only in <libgen.h>, so libiberty.h declares it.
    "HAVE_DECL_BASENAME": "0",
    "SIZEOF_INT": "4",
    "SIZEOF_LONG": "8",
    "SIZEOF_LONG_LONG": "8",
    "SIZEOF_SIZE_T": "8",
    "STACK_DIRECTION": "-1",
    "UNSIGNED_64BIT_TYPE": "unsigned long",
    "PACKAGE": '"binutils"',
    "PACKAGE_VERSION": '"2.41"',
}

# Native BFD ABI configuration, independent of compiler output paths.
BFD_NATIVE = {
    "supports_plugins": "0",
    "wordsize": "64",
    "bfd_default_target_size": "64",
    "bfd_file_ptr": "int64_t",
    "bfd_ufile_ptr": "uint64_t",
}

BFD_ON = [
    "HAVE_DLFCN_H",
    "HAVE_FCNTL",
    "HAVE_FCNTL_H",
    "HAVE_FDOPEN",
    "HAVE_FILENO",
    "HAVE_FSEEKO",
    "HAVE_FTELLO",
    "HAVE_GETGID",
    "HAVE_GETPAGESIZE",
    "HAVE_GETRLIMIT",
    "HAVE_GETUID",
    "HAVE_HIDDEN",
    "HAVE_INTTYPES_H",
    "HAVE_MADVISE",
    "HAVE_MEMORY_H",
    "HAVE_MMAP",
    "HAVE_MPROTECT",
    "HAVE_PRPSINFO_T",
    "HAVE_PRPSINFO_T_PR_PID",
    "HAVE_PRSTATUS_T",
    "HAVE_STDINT_H",
    "HAVE_STDLIB_H",
    "HAVE_STRINGS_H",
    "HAVE_STRING_H",
    "HAVE_SYSCONF",
    "HAVE_SYS_FILE_H",
    "HAVE_SYS_PARAM_H",
    "HAVE_SYS_PROCFS_H",
    "HAVE_SYS_RESOURCE_H",
    "HAVE_SYS_STAT_H",
    "HAVE_SYS_TYPES_H",
    "HAVE_UNISTD_H",
    "STDC_HEADERS",
    "USE_MMAP",
    "USE_SECUREPLT",
    "_STRUCTURED_PROC",
    "HAVE_DECL_ASPRINTF",
    "HAVE_DECL_FFS",
    "HAVE_DECL_FSEEKO",
    "HAVE_DECL_FTELLO",
    "HAVE_DECL_STPCPY",
    "HAVE_DECL_STRNLEN",
    "HAVE_DECL_VASPRINTF",
]

# musl 1.2.5 has no LFS64 symbols, fls or basename declaration in string.h.
BFD_VALUES = {
    "_GNU_SOURCE": "1",
    "PACKAGE": '"bfd"',
    "PACKAGE_VERSION": '"2.41"',
    "VERSION": '"2.41"',
    "SIZEOF_INT": "4",
    "SIZEOF_LONG": "8",
    "SIZEOF_LONG_LONG": "8",
    "SIZEOF_OFF_T": "8",
    "SIZEOF_VOID_P": "8",
    "DEFAULT_LD_Z_SEPARATE_CODE": "1",
    "HAVE_DECL_BASENAME": "0",
    "HAVE_DECL_FOPEN64": "0",
    "HAVE_DECL_FSEEKO64": "0",
    "HAVE_DECL_FTELLO64": "0",
    "HAVE_DECL____LC_CODEPAGE_FUNC": "0",
    "BINDIR": '"/nonexistent-bootstrap-binutils/bin"',
    "DEBUGDIR": '"/nonexistent-bootstrap-binutils/debug"',
    "DEFAULT_VECTOR": "x86_64_elf64_vec",
    "SELECT_VECS": "&x86_64_elf64_vec",
    "HAVE_x86_64_elf64_vec": "1",
    "SELECT_ARCHITECTURES": "&bfd_i386_arch",
}

LIBSFRAME_ON = [
    "HAVE_BYTESWAP_H",
    "HAVE_DECL_BSWAP_16",
    "HAVE_DECL_BSWAP_32",
    "HAVE_DECL_BSWAP_64",
    "HAVE_DLFCN_H",
    "HAVE_ENDIAN_H",
    "HAVE_GETPAGESIZE",
    "HAVE_INTTYPES_H",
    "HAVE_MEMORY_H",
    "HAVE_MMAP",
    "HAVE_STDINT_H",
    "HAVE_STDLIB_H",
    "HAVE_STRINGS_H",
    "HAVE_STRING_H",
    "HAVE_SYS_PARAM_H",
    "HAVE_SYS_STAT_H",
    "HAVE_SYS_TYPES_H",
    "HAVE_UNISTD_H",
    "STDC_HEADERS",
]

LIBSFRAME_VALUES = {
    "_GNU_SOURCE": "1",
    "PACKAGE": '"libsframe"',
    "PACKAGE_VERSION": '"2.41"',
    "VERSION": '"2.41"',
}

OPCODES_ON = [
    "HAVE_DECL_STPCPY",
    "HAVE_DLFCN_H",
    "HAVE_INTTYPES_H",
    "HAVE_MEMORY_H",
    "HAVE_SIGSETJMP",
    "HAVE_STDINT_H",
    "HAVE_STDLIB_H",
    "HAVE_STRINGS_H",
    "HAVE_STRING_H",
    "HAVE_SYS_STAT_H",
    "HAVE_SYS_TYPES_H",
    "HAVE_UNISTD_H",
    "STDC_HEADERS",
    "ARCH_i386",
]

OPCODES_VALUES = {
    "_GNU_SOURCE": "1",
    "HAVE_DECL_BASENAME": "0",
    "PACKAGE": '"opcodes"',
    "PACKAGE_VERSION": '"2.41"',
    "SIZEOF_VOID_P": "8",
    "VERSION": '"2.41"',
}

GAS_ON = [
    "HAVE_DLFCN_H",
    "HAVE_INTTYPES_H",
    "HAVE_LC_MESSAGES",
    "HAVE_MEMORY_H",
    "HAVE_STDINT_H",
    "HAVE_STDLIB_H",
    "HAVE_STRINGS_H",
    "HAVE_STRING_H",
    "HAVE_STRSIGNAL",
    "HAVE_ST_MTIM_TV_NSEC",
    "HAVE_ST_MTIM_TV_SEC",
    "HAVE_SYS_STAT_H",
    "HAVE_SYS_TYPES_H",
    "HAVE_TM_GMTOFF",
    "HAVE_UNISTD_H",
    "STDC_HEADERS",
    "HAVE_DECL_ASPRINTF",
    "HAVE_DECL_GETOPT",
    "HAVE_DECL_MEMPCPY",
    "HAVE_DECL_STPCPY",
    "DEFAULT_FLAG_COMPRESS_DEBUG",
]

GAS_VALUES = {
    "_GNU_SOURCE": "1",
    "DEFAULT_ARCH": '"x86_64"',
    "DEFAULT_COMPRESSED_DEBUG_ALGORITHM": "COMPRESS_DEBUG_GABI_ZLIB",
    "DEFAULT_GENERATE_BUILD_NOTES": "0",
    "DEFAULT_GENERATE_ELF_STT_COMMON": "0",
    "DEFAULT_GENERATE_X86_RELAX_RELOCATIONS": "1",
    "DEFAULT_X86_USED_NOTE": "1",
    "PACKAGE": '"gas"',
    "PACKAGE_VERSION": '"2.41"',
    "VERSION": '"2.41"',
    "TARGET_ALIAS": '"x86_64-linux-musl"',
    "TARGET_CANONICAL": '"x86_64-unknown-linux-musl"',
    "TARGET_CPU": '"x86_64"',
    "TARGET_OS": '"linux-musl"',
    "TARGET_VENDOR": '"unknown"',
    "TARGET_BYTES_BIG_ENDIAN": "0",
    "LOCALEDIR": '"/nonexistent-bootstrap-binutils/locale"',
}

LD_ON = [
    "HAVE_CLOSE",
    "HAVE_DECL_ASPRINTF",
    "HAVE_DECL_ENVIRON",
    "HAVE_DECL_GETOPT",
    "HAVE_FCNTL_H",
    "HAVE_GETPAGESIZE",
    "HAVE_GLOB",
    "HAVE_INITFINI_ARRAY",
    "HAVE_INTTYPES_H",
    "HAVE_LC_MESSAGES",
    "HAVE_LIMITS_H",
    "HAVE_LSEEK",
    "HAVE_MEMORY_H",
    "HAVE_MKSTEMP",
    "HAVE_MMAP",
    "HAVE_OPEN",
    "HAVE_REALPATH",
    "HAVE_STDINT_H",
    "HAVE_STDLIB_H",
    "HAVE_STRINGS_H",
    "HAVE_STRING_H",
    "HAVE_SYS_FILE_H",
    "HAVE_SYS_MMAN_H",
    "HAVE_SYS_PARAM_H",
    "HAVE_SYS_STAT_H",
    "HAVE_SYS_TIME_H",
    "HAVE_SYS_TYPES_H",
    "HAVE_UNISTD_H",
    "HAVE_WAITPID",
    "STDC_HEADERS",
    "YYTEXT_POINTER",
    # Compress debug sections by default, as the assembler does. This is
    # configure's --enable-compressed-debug-sections=ld.
    "DEFAULT_FLAG_COMPRESS_DEBUG",
]

# configure's x86_64 Linux defaults.
LD_VALUES = {
    "_GNU_SOURCE": "1",
    "ELF_LIST_OPTIONS": "1",
    "ELF_SHLIB_LIST_OPTIONS": "1",
    "ELF_PLT_UNWIND_LIST_OPTIONS": "1",
    "DEFAULT_COMPRESSED_DEBUG_ALGORITHM": "COMPRESS_DEBUG_GABI_ZLIB",
    "DEFAULT_EMIT_GNU_HASH": "1",
    "DEFAULT_EMIT_SYSV_HASH": "1",
    "DEFAULT_LD_EXECSTACK": "1",
    "DEFAULT_LD_TEXTREL_CHECK": "textrel_check_warning",
    "DEFAULT_LD_TEXTREL_CHECK_WARNING": "1",
    "DEFAULT_LD_WARN_EXECSTACK": "2",
    "DEFAULT_LD_WARN_RWX_SEGMENTS": "1",
    "DEFAULT_LD_Z_RELRO": "1",
    "DEFAULT_LD_Z_SEPARATE_CODE": "1",
    "DEFAULT_NEW_DTAGS": "0",
    "GOT_HANDLING_DEFAULT": "GOT_HANDLING_TARGET_DEFAULT",
    "SUPPORT_ERROR_HANDLING_SCRIPT": "1",
    "SIZEOF_VOID_P": "8",
    "PACKAGE": '\"ld\"',
    "PACKAGE_VERSION": '\"2.41\"',
    "VERSION": '\"2.41\"',
    "DEFAULT_EMULATION": '\"elf_x86_64\"',
    "TARGET": '\"x86_64-unknown-linux-musl\"',
    "TARGET_SYSTEM_ROOT": '\"/nonexistent-bootstrap-sysroot\"',
    "BINDIR": '\"/nonexistent-bootstrap-binutils/bin\"',
    "TOOLBINDIR": '\"/nonexistent-bootstrap-binutils/bin\"',
    "SCRIPTDIR": '\"/nonexistent-bootstrap-binutils/lib\"',
    "LOCALEDIR": '\"/nonexistent-bootstrap-binutils/locale\"',
}

BINUTILS_ON = [
    "HAVE_DECL_ASPRINTF",
    "HAVE_DECL_ENVIRON",
    "HAVE_DECL_GETC_UNLOCKED",
    "HAVE_DECL_GETOPT",
    "HAVE_DECL_STPCPY",
    "HAVE_DECL_STRNLEN",
    "HAVE_FCNTL_H",
    "HAVE_FSEEKO",
    "HAVE_GETC_UNLOCKED",
    "HAVE_GETPAGESIZE",
    "HAVE_GOOD_UTIME_H",
    "HAVE_ICONV",
    "HAVE_INTTYPES_H",
    "HAVE_LC_MESSAGES",
    "HAVE_MBSTATE_T",
    "HAVE_MEMORY_H",
    "HAVE_MKDTEMP",
    "HAVE_MKSTEMP",
    "HAVE_MMAP",
    "HAVE_STDINT_H",
    "HAVE_STDLIB_H",
    "HAVE_STRINGS_H",
    "HAVE_STRING_H",
    "HAVE_STRUCT_STAT_ST_ATIM_TV_NSEC",
    "HAVE_SYS_FILE_H",
    "HAVE_SYS_PARAM_H",
    "HAVE_SYS_STAT_H",
    "HAVE_SYS_TIME_H",
    "HAVE_SYS_TYPES_H",
    "HAVE_SYS_WAIT_H",
    "HAVE_UNISTD_H",
    "HAVE_UTIMENSAT",
    "HAVE_UTIMES",
    "STDC_HEADERS",
    "TYPEOF_STRUCT_STAT_ST_ATIM_IS_STRUCT_TIMESPEC",
    "YYTEXT_POINTER",
]

# Deterministic archives by default. Separate debug files are looked up
# only below a nonexistent directory.
BINUTILS_VALUES = {
    "_GNU_SOURCE": "1",
    "DEFAULT_AR_DETERMINISTIC": "1",
    "DEFAULT_STRINGS_ALL": "1",
    "DEFAULT_F_FOR_IFUNC_SYMBOLS": "0",
    "DEFAULT_FOR_FOLLOW_LINKS": "1",
    "DEFAULT_FOR_COLORED_DISASSEMBLY": "0",
    "DEBUGDIR": '\"/nonexistent-bootstrap-binutils/debug\"',
    "EXECUTABLE_SUFFIX": '\"\"',
    "TARGET_PREPENDS_UNDERSCORE": "0",
    "ICONV_CONST": "",
    "OBJDUMP_PRIVATE_VECTORS": "",
    "bin_dummy_emulation": "bin_vanilla_emulation",
    "PACKAGE": '\"binutils\"',
    "PACKAGE_VERSION": '\"2.41\"',
    "VERSION": '\"2.41\"',
    "TARGET": '\"x86_64-unknown-linux-musl\"',
    "LOCALEDIR": '\"/nonexistent-bootstrap-binutils/locale\"',
}

GPROF_CONFIG = "\n".join([
    '#define PACKAGE "gprof"',
    '#define PACKAGE_VERSION "2.41"',
    "#define HAVE_DECL_GETOPT 1",
    "#define HAVE_SETITIMER 1",
    "#define HAVE_SYS_TIME_H 1",
]) + "\n"

CONFIG = struct(
    libiberty_on = LIBIBERTY_ON,
    libiberty_values = LIBIBERTY_VALUES,
    bfd_native = BFD_NATIVE,
    bfd_on = BFD_ON,
    bfd_values = BFD_VALUES,
    libsframe_on = LIBSFRAME_ON,
    libsframe_values = LIBSFRAME_VALUES,
    opcodes_on = OPCODES_ON,
    opcodes_values = OPCODES_VALUES,
    gas_on = GAS_ON,
    gas_values = GAS_VALUES,
    ld_on = LD_ON,
    ld_values = LD_VALUES,
    binutils_on = BINUTILS_ON,
    binutils_values = BINUTILS_VALUES,
    gprof = GPROF_CONFIG,
)
