# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# The binutils 2.41 release paths that binutils_stage reads, and the layout
# facts it needs, collected in SOURCES at the end.

COMMON_HEADERS = [
    "include/alloca-conf.h",
    "include/ansidecl.h",
    "include/bfdlink.h",
    "include/binary-io.h",
    "include/bout.h",
    "include/demangle.h",
    "include/diagnostics.h",
    "include/dis-asm.h",
    "include/dwarf2.def",
    "include/dwarf2.h",
    "include/dyn-string.h",
    "include/environ.h",
    "include/fibheap.h",
    "include/filenames.h",
    "include/floatformat.h",
    "include/fnmatch.h",
    "include/fopen-bin.h",
    "include/fopen-same.h",
    "include/fopen-vms.h",
    "include/gcc-c-fe.def",
    "include/gcc-c-interface.h",
    "include/gcc-cp-fe.def",
    "include/gcc-cp-interface.h",
    "include/gcc-interface.h",
    "include/getopt.h",
    "include/hashtab.h",
    "include/hp-symtab.h",
    "include/leb128.h",
    "include/libiberty.h",
    "include/longlong.h",
    "include/lto-symtab.h",
    "include/md5.h",
    "include/oasys.h",
    "include/objalloc.h",
    "include/obstack.h",
    "include/os9k.h",
    "include/partition.h",
    "include/plugin-api.h",
    "include/safe-ctype.h",
    "include/sframe-api.h",
    "include/sframe.h",
    "include/sha1.h",
    "include/simple-object.h",
    "include/sort.h",
    "include/splay-tree.h",
    "include/symcat.h",
    "include/timeval-utils.h",
    "include/vtv-change-permission.h",
    "include/xregex.h",
    "include/xregex2.h",
    "include/xtensa-config.h",
    "include/xtensa-isa-internal.h",
    "include/xtensa-isa.h",
    "libiberty/cp-demangle.h",
    "libiberty/pex-common.h",
    "libiberty/simple-object-common.h",
    "libiberty/vprintf-support.h",
]

# Readelf also decodes foreign ELF metadata; this does not enable BFD backends.
BINUTILS_HEADERS = [
    "include/alloca-conf.h",
    "include/ansidecl.h",
    "include/aout/aout64.h",
    "include/aout/ar.h",
    "include/aout/ranlib.h",
    "include/aout/stab.def",
    "include/aout/stab_gnu.h",
    "include/bfdlink.h",
    "include/binary-io.h",
    "include/coff/external.h",
    "include/coff/i386.h",
    "include/coff/internal.h",
    "include/coff/msdos.h",
    "include/coff/pe.h",
    "include/ctf-api.h",
    "include/ctf.h",
    "include/demangle.h",
    "include/dis-asm.h",
    "include/dwarf2.def",
    "include/dwarf2.h",
    "include/elf/aarch64.h",
    "include/elf/alpha.h",
    "include/elf/amdgpu.h",
    "include/elf/arc-reloc.def",
    "include/elf/arc.h",
    "include/elf/arm.h",
    "include/elf/avr.h",
    "include/elf/bfin.h",
    "include/elf/bpf.h",
    "include/elf/common.h",
    "include/elf/cr16.h",
    "include/elf/cris.h",
    "include/elf/crx.h",
    "include/elf/csky.h",
    "include/elf/d10v.h",
    "include/elf/d30v.h",
    "include/elf/dlx.h",
    "include/elf/epiphany.h",
    "include/elf/external.h",
    "include/elf/fr30.h",
    "include/elf/frv.h",
    "include/elf/ft32.h",
    "include/elf/h8.h",
    "include/elf/hppa.h",
    "include/elf/i370.h",
    "include/elf/i386.h",
    "include/elf/i860.h",
    "include/elf/i960.h",
    "include/elf/ia64.h",
    "include/elf/internal.h",
    "include/elf/ip2k.h",
    "include/elf/iq2000.h",
    "include/elf/lm32.h",
    "include/elf/loongarch.h",
    "include/elf/m32c.h",
    "include/elf/m32r.h",
    "include/elf/m68hc11.h",
    "include/elf/m68k.h",
    "include/elf/mcore.h",
    "include/elf/mep.h",
    "include/elf/metag.h",
    "include/elf/microblaze.h",
    "include/elf/mips.h",
    "include/elf/mmix.h",
    "include/elf/mn10200.h",
    "include/elf/mn10300.h",
    "include/elf/moxie.h",
    "include/elf/msp430.h",
    "include/elf/mt.h",
    "include/elf/nds32.h",
    "include/elf/nfp.h",
    "include/elf/nios2.h",
    "include/elf/or1k.h",
    "include/elf/pj.h",
    "include/elf/ppc.h",
    "include/elf/ppc64.h",
    "include/elf/pru.h",
    "include/elf/reloc-macros.h",
    "include/elf/riscv.h",
    "include/elf/rl78.h",
    "include/elf/rx.h",
    "include/elf/s12z.h",
    "include/elf/s390.h",
    "include/elf/score.h",
    "include/elf/sh.h",
    "include/elf/sparc.h",
    "include/elf/spu.h",
    "include/elf/tic6x-attrs.h",
    "include/elf/tic6x.h",
    "include/elf/tilegx.h",
    "include/elf/tilepro.h",
    "include/elf/v850.h",
    "include/elf/vax.h",
    "include/elf/visium.h",
    "include/elf/wasm32.h",
    "include/elf/x86-64.h",
    "include/elf/xgate.h",
    "include/elf/xstormy16.h",
    "include/elf/xtensa.h",
    "include/elf/z80.h",
    "include/filenames.h",
    "include/fnmatch.h",
    "include/fopen-bin.h",
    "include/fopen-same.h",
    "include/gdb/gdb-index.h",
    "include/getopt.h",
    "include/hashtab.h",
    "include/libiberty.h",
    "include/opcode/riscv-opc.h",
    "include/plugin-api.h",
    "include/safe-ctype.h",
    "include/sframe-api.h",
    "include/sframe.h",
]

LIBIBERTY = [
    "regex",
    "cplus-dem",
    "cp-demangle",
    "md5",
    "sha1",
    "alloca",
    "argv",
    "bsearch_r",
    "choose-temp",
    "concat",
    "cp-demint",
    "crc32",
    "d-demangle",
    "dwarfnames",
    "dyn-string",
    "fdmatch",
    "fibheap",
    "filedescriptor",
    "filename_cmp",
    "floatformat",
    "fnmatch",
    "fopen_unlocked",
    "getopt",
    "getopt1",
    "getpwd",
    "getruntime",
    "hashtab",
    "hex",
    "lbasename",
    "lrealpath",
    "make-relative-prefix",
    "make-temp-file",
    "objalloc",
    "obstack",
    "partition",
    "pexecute",
    "physmem",
    "pex-common",
    "pex-one",
    "pex-unix",
    "vprintf-support",
    "rust-demangle",
    "safe-ctype",
    "simple-object",
    "simple-object-coff",
    "simple-object-elf",
    "simple-object-mach-o",
    "simple-object-xcoff",
    "sort",
    "spaces",
    "splay-tree",
    "stack-limit",
    "strerror",
    "strsignal",
    "timeval-utils",
    "unlink-if-ordinary",
    "xasprintf",
    "xatexit",
    "xexit",
    "xmalloc",
    "xmemdup",
    "xstrdup",
    "xstrerror",
    "xstrndup",
    "xvasprintf",
]

BFD_HEADER_INPUTS = [
    "bfd/archive.c",
    "bfd/archures.c",
    "bfd/bfd-in.h",
    "bfd/bfd.c",
    "bfd/bfdio.c",
    "bfd/bfdwin.c",
    "bfd/cache.c",
    "bfd/coffcode.h",
    "bfd/compress.c",
    "bfd/corefile.c",
    "bfd/format.c",
    "bfd/hash.c",
    "bfd/libbfd-in.h",
    "bfd/libbfd.c",
    "bfd/libcoff-in.h",
    "bfd/linker.c",
    "bfd/opncls.c",
    "bfd/reloc.c",
    "bfd/section.c",
    "bfd/simple.c",
    "bfd/stab-syms.c",
    "bfd/stabs.c",
    "bfd/syms.c",
    "bfd/targets.c",
    "bfd/doc/chew.c",
    "bfd/doc/proto.str",
    "bfd/doc/header.sed",
    "bfd/elfxx-target.h",
    "bfd/targmatch.sed",
    "bfd/config.bfd",
    "bfd/version.h",
]

# bfd/Makefile.am's BFD_H_FILES, LIBBFD_H_FILES and LIBCOFF_H_FILES. Each
# entry holds the generated header's name, the header it starts from and the
# sources chew extracts declarations from, whether chew extracts internal
# declarations, and whether the first header opens an include guard that the
# generated header closes.
BFD_HEADER_GROUPS = [
    (
        "bfd",
        [
            "bfd-in.h",
            "libbfd.c",
            "hash.c",
            "section.c",
            "syms.c",
            "archive.c",
            "archures.c",
            "bfd.c",
            "bfdio.c",
            "bfdwin.c",
            "cache.c",
            "compress.c",
            "corefile.c",
            "format.c",
            "linker.c",
            "opncls.c",
            "reloc.c",
            "simple.c",
            "stab-syms.c",
            "stabs.c",
            "targets.c",
        ],
        False,
        True,
    ),
    (
        "libbfd",
        [
            "libbfd-in.h",
            "libbfd.c",
            "bfd.c",
            "bfdio.c",
            "archive.c",
            "archures.c",
            "bfdwin.c",
            "cache.c",
            "hash.c",
            "linker.c",
            "opncls.c",
            "reloc.c",
            "section.c",
            "stabs.c",
            "targets.c",
        ],
        True,
        True,
    ),
    (
        "libcoff",
        [
            "libcoff-in.h",
            "coffcode.h",
        ],
        True,
        True,
    ),
]

BFD = [
    "archive",
    "archures",
    "bfd",
    "bfdio",
    "bfdwin",
    "cache",
    "coff-bfd",
    "compress",
    "corefile",
    "elf-properties",
    "format",
    "hash",
    "libbfd",
    "linker",
    "merge",
    "opncls",
    "reloc",
    "section",
    "simple",
    "stab-syms",
    "stabs",
    "syms",
    "targets",
    "binary",
    "ihex",
    "srec",
    "tekhex",
    "verilog",
    "archive64",
    "cpu-i386",
    "elf64-x86-64",
    "elfxx-x86",
    "elf-ifunc",
    "elf-vxworks",
    "elf64",
    # elf.c and elf64-x86-64.c take elf32_r_info and elf32_r_sym, which only
    # elf32.c defines, even with only ELF64 selected.
    "elf32",
    "elf",
    "elflink",
    "elf-attrs",
    "elf-strtab",
    "elf-eh-frame",
    "elf-sframe",
    "dwarf1",
    "dwarf2",
]

BFD_SOURCE_HEADERS = [
    "bfd/coff-bfd.h",
    "bfd/elf-bfd.h",
    "bfd/elf-linker-x86.h",
    "bfd/elf-linux-core.h",
    "bfd/elf-vxworks.h",
    "bfd/elfcode.h",
    "bfd/elfcore.h",
    "bfd/elfxx-x86.h",
    "bfd/genlink.h",
    "bfd/libaout.h",
    "bfd/libecoff.h",
    "bfd/plugin.h",
    "bfd/sysdep.h",
    "include/aout/aout64.h",
    "include/aout/ar.h",
    "include/aout/ranlib.h",
    "include/aout/stab.def",
    "include/aout/stab_gnu.h",
    "include/coff/ecoff.h",
    "include/coff/internal.h",
    "include/coff/sym.h",
    "include/elf/common.h",
    "include/elf/dwarf.h",
    "include/elf/external.h",
    "include/elf/i386.h",
    "include/elf/internal.h",
    "include/elf/reloc-macros.h",
    "include/elf/vxworks.h",
    "include/elf/x86-64.h",
    "include/opcode/i386.h",
    "include/sframe.h",
    "include/sframe-api.h",
    # ld includes libctf's interface unconditionally, even without libctf.
    "include/ctf-api.h",
    "include/ctf.h",
]

LIBSFRAME = [
    "sframe",
    "sframe-dump",
    "sframe-error",
]

OPCODES = [
    "dis-buf",
    "disassemble",
    "dis-init",
    "i386-dis",
]

OPCODES_FILES = [
    "opcodes/dis-buf.c",
    "opcodes/disassemble.c",
    "opcodes/dis-init.c",
    "opcodes/i386-dis.c",
    "opcodes/sysdep.h",
    "opcodes/disassemble.h",
    "opcodes/opintl.h",
    "opcodes/i386-dis-evex.h",
    "opcodes/i386-dis-evex-len.h",
    "opcodes/i386-dis-evex-mod.h",
    "opcodes/i386-dis-evex-prefix.h",
    "opcodes/i386-dis-evex-reg.h",
    "opcodes/i386-dis-evex-w.h",
    "opcodes/i386-gen.c",
    "opcodes/i386-opc.h",
    "opcodes/i386-opc.tbl",
    "opcodes/i386-reg.tbl",
]

# Only gas includes the generated x86 tables.
I386_TABLES = [
    "i386-init.h",
    "i386-mnem.h",
    "i386-tbl.h",
]

# i386-gen's source changes, applied in order.
I386_GEN_PATCHES = [
    "gen-input-dir",
    "gen-local-dir",
    "gen-no-chdir",
    "gen-opcodes-input",
    "gen-registers-path",
]

GAS = [
    "app",
    "as",
    "atof-generic",
    "codeview",
    "compress-debug",
    "cond",
    "depend",
    "dwarf2dbg",
    "dw2gencfi",
    "ecoff",
    "ehopt",
    "expr",
    "flonum-copy",
    "flonum-konst",
    "flonum-mult",
    "frags",
    "gen-sframe",
    "hash",
    "input-file",
    "input-scrub",
    "listing",
    "literal",
    "macro",
    "messages",
    "output-file",
    "read",
    "remap",
    "sb",
    "sframe-opt",
    "stabs",
    "subsegs",
    "symbols",
    "write",
    "config/tc-i386",
    "config/obj-elf",
    "config/atof-ieee",
]

GAS_HEADERS = [
    "gas/as.h",
    "gas/asintl.h",
    "gas/bignum.h",
    "gas/bit_fix.h",
    "gas/cgen.h",
    "gas/codeview.h",
    "gas/compress-debug.h",
    "gas/dwarf2dbg.h",
    "gas/dw2gencfi.h",
    "gas/ecoff.h",
    "gas/emul-target.h",
    "gas/emul.h",
    "gas/expr.h",
    "gas/flonum.h",
    "gas/frags.h",
    "gas/gen-sframe.h",
    "gas/hash.h",
    "gas/input-file.h",
    "gas/itbl-lex.h",
    "gas/itbl-ops.h",
    "gas/listing.h",
    "gas/macro.h",
    "gas/obj.h",
    "gas/output-file.h",
    "gas/read.h",
    "gas/sb.h",
    "gas/subsegs.h",
    "gas/symbols.h",
    "gas/tc.h",
    "gas/write.h",
    "gas/config/tc-i386.h",
    "gas/config/obj-elf.h",
    "gas/config/te-linux.h",
    "gas/config/tc-i386-intel.c",
]

LD = [
    "ldgram",
    "ldlex-wrapper",
    "lexsup",
    "ldlang",
    "mri",
    "ldctor",
    "ldmain",
    "ldwrite",
    "ldexp",
    "ldemul",
    "ldver",
    "ldmisc",
    "ldfile",
    "ldcref",
    "ldbuildid",
    "eelf_x86_64",
    "ldelf",
    "ldelfgen",
]

LD_HEADERS = [
    "ld/ld.h",
    "ld/ldctor.h",
    "ld/ldelf.h",
    "ld/ldelfgen.h",
    "ld/ldemul.h",
    "ld/ldexp.h",
    "ld/ldfile.h",
    "ld/ldlang.h",
    "ld/ldlex.h",
    "ld/ldmain.h",
    "ld/ldmisc.h",
    "ld/ldver.h",
    "ld/ldwrite.h",
    "ld/mri.h",
    "ld/elf-hints-local.h",
    "ld/ldbuildid.h",
    "ld/sysdep.h",
]

LD_GENERATOR_INPUTS = [
    "ld/genscripts.sh",
    "ld/genscrba.sh",
    "ld/emultempl/astring.sed",
    "ld/emultempl/elf.em",
    "ld/emultempl/elf-generic.em",
    "ld/emultempl/elf-x86.em",
    "ld/emultempl/emulation.em",
    "ld/scripttempl/elf.sc",
    "ld/scripttempl/misc-sections.sc",
    "ld/scripttempl/DWARF.sc",
    "ld/emulparams/elf_x86_64.sh",
    "ld/emulparams/plt_unwind.sh",
    "ld/emulparams/extern_protected_data.sh",
    "ld/emulparams/dynamic_undefined_weak.sh",
    "ld/emulparams/reloc_overflow.sh",
    "ld/emulparams/call_nop.sh",
    "ld/emulparams/cet.sh",
    "ld/emulparams/x86-report-relative.sh",
    "ld/emulparams/x86-64-level.sh",
    "ld/emulparams/x86-64-lam.sh",
    "ld/emulparams/static.sh",
    "ld/emulparams/dt-relr.sh",
]

BINUTILS_PROGRAMS = {
    "size": [
        "size",
        "bucomm",
        "version",
        "filemode",
    ],
    "objcopy": [
        "objcopy",
        "not-strip",
        "rename",
        "rddbg",
        "debug",
        "stabs",
        "rdcoff",
        "wrstabs",
        "bucomm",
        "version",
        "filemode",
    ],
    "strings": [
        "strings",
        "bucomm",
        "version",
        "filemode",
    ],
    "readelf": [
        "readelf",
        "version",
        "unwind-ia64",
        "dwarf",
        "demanguse",
        "elfcomm",
    ],
    "elfedit": [
        "elfedit",
        "version",
        "elfcomm",
    ],
    "strip": [
        "objcopy",
        "is-strip",
        "rename",
        "rddbg",
        "debug",
        "stabs",
        "rdcoff",
        "wrstabs",
        "bucomm",
        "version",
        "filemode",
    ],
    "nm": [
        "nm",
        "demanguse",
        "bucomm",
        "version",
        "filemode",
    ],
    "objdump": [
        "objdump",
        "dwarf",
        "prdbg",
        "demanguse",
        "rddbg",
        "debug",
        "stabs",
        "rdcoff",
        "bucomm",
        "version",
        "filemode",
        "elfcomm",
    ],
    "c++filt": [
        "cxxfilt",
        "bucomm",
        "version",
        "filemode",
    ],
    "ar": [
        "arparse",
        "arlex",
        "ar",
        "not-ranlib",
        "arsup",
        "rename",
        "binemul",
        "emul_vanilla",
        "bucomm",
        "version",
        "filemode",
    ],
    "ranlib": [
        "ar",
        "is-ranlib",
        "arparse",
        "arlex",
        "arsup",
        "rename",
        "binemul",
        "emul_vanilla",
        "bucomm",
        "version",
        "filemode",
    ],
    "addr2line": [
        "addr2line",
        "bucomm",
        "version",
        "filemode",
    ],
}

BINUTILS_FILES = [
    "binutils/addr2line.c",
    "binutils/ar.c",
    "binutils/arsup.c",
    "binutils/binemul.c",
    "binutils/bucomm.c",
    "binutils/cxxfilt.c",
    "binutils/debug.c",
    "binutils/demanguse.c",
    "binutils/dwarf.c",
    "binutils/elfcomm.c",
    "binutils/elfedit.c",
    "binutils/emul_vanilla.c",
    "binutils/filemode.c",
    "binutils/is-ranlib.c",
    "binutils/is-strip.c",
    "binutils/nm.c",
    "binutils/not-ranlib.c",
    "binutils/not-strip.c",
    "binutils/objcopy.c",
    "binutils/objdump.c",
    "binutils/prdbg.c",
    "binutils/rdcoff.c",
    "binutils/rddbg.c",
    "binutils/readelf.c",
    "binutils/rename.c",
    "binutils/size.c",
    "binutils/stabs.c",
    "binutils/strings.c",
    "binutils/unwind-ia64.c",
    "binutils/version.c",
    "binutils/wrstabs.c",
    "binutils/arsup.h",
    "binutils/binemul.h",
    "binutils/bucomm.h",
    "binutils/budbg.h",
    "binutils/debug.h",
    "binutils/demanguse.h",
    "binutils/dwarf.h",
    "binutils/elfcomm.h",
    "binutils/objdump.h",
    "binutils/sysdep.h",
    "binutils/unwind-ia64.h",
    "binutils/arparse.y",
    "binutils/arlex.l",
]

SOURCES = struct(
    version = "2.41",
    common_headers = COMMON_HEADERS,
    binutils_headers = BINUTILS_HEADERS,
    libiberty = LIBIBERTY,
    bfd_header_inputs = BFD_HEADER_INPUTS,
    bfd_header_groups = BFD_HEADER_GROUPS,
    bfd = BFD,
    bfd_source_headers = BFD_SOURCE_HEADERS,
    opcodes = OPCODES,
    opcodes_files = OPCODES_FILES,
    i386_tables = I386_TABLES,
    i386_gen_patches = I386_GEN_PATCHES,
    gas = GAS,
    gas_headers = GAS_HEADERS,
    ld = LD,
    ld_headers = LD_HEADERS,
    ld_generator_inputs = LD_GENERATOR_INPUTS,
    ld_emulation_template = "elf.em",
    binutils_programs = BINUTILS_PROGRAMS,
    binutils_files = BINUTILS_FILES,
    # libbfd reads and writes SFrame sections through libsframe.
    libsframe = LIBSFRAME,
    # libsframe includes libctf's byte-swapping header even without libctf.
    libsframe_headers = [
        "libsframe/sframe-impl.h",
        "libctf/swap.h",
    ],
    # The release's generated zlib tables, as comparison fixtures only.
    zlib_fixtures = [
        "crc32.h",
        "trees.h",
        "inffixed.h",
    ],
    # zlib 1.2.12's crc32.c writes crc32.h from its own main.
    zlib_crc32_main = True,
    # i386-gen reads the C-preprocessed opcode table.
    preprocessed_opcode_table = True,
    # GNU as compiles the x86 tables into tc-i386 and links no libopcodes.
    gas_includes_opcode_tables = True,
    # genscripts.sh takes the dependency directory and the default library
    # search path as arguments.
    ld_libpath_argument = True,
    # ld includes libctf's interface, which includes zlib.h.
    ld_zlib_headers = True,
)
