# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# Programs that are not built from src/<name>.c alone.
_SOURCES = {
    "uname": ["uname", "uname-uname"],
    "chgrp": ["chgrp", "chown-core"],
    "chown": ["chown", "chown-core"],
    "cp": ["cp", "copy", "cp-hash"],
    "install": ["install", "copy", "cp-hash"],
    "dir": ["ls", "ls-dir"],
    "vdir": ["ls", "ls-vdir"],
    "ls": ["ls", "ls-ls"],
    "mv": ["mv", "remove", "copy", "cp-hash"],
    "rm": ["rm", "remove"],
}

# The default programs of src/Makefile.am, each with the sources it links.
# Upstream does not install arch, hostname or the privileged su program by
# default. lbracket installs as [.
PROGRAMS = {name: _SOURCES.get(name, [name]) for name in [
    "chroot",
    "df",
    "hostid",
    "nice",
    "pinky",
    "stty",
    "uname",
    "uptime",
    "users",
    "who",
    "lbracket",
    "chcon",
    "chgrp",
    "chown",
    "chmod",
    "cp",
    "dd",
    "dircolors",
    "du",
    "install",
    "link",
    "ln",
    "dir",
    "vdir",
    "ls",
    "mkdir",
    "mkfifo",
    "mknod",
    "mktemp",
    "mv",
    "nohup",
    "readlink",
    "rm",
    "rmdir",
    "shred",
    "stat",
    "sync",
    "touch",
    "unlink",
    "cat",
    "cksum",
    "comm",
    "csplit",
    "cut",
    "expand",
    "fmt",
    "fold",
    "head",
    "join",
    "md5sum",
    "nl",
    "od",
    "paste",
    "pr",
    "ptx",
    "sha1sum",
    "sha224sum",
    "sha256sum",
    "sha384sum",
    "sha512sum",
    "shuf",
    "sort",
    "split",
    "sum",
    "tac",
    "tail",
    "tr",
    "tsort",
    "unexpand",
    "uniq",
    "wc",
    "basename",
    "date",
    "dirname",
    "echo",
    "env",
    "expr",
    "factor",
    "false",
    "id",
    "kill",
    "logname",
    "pathchk",
    "printenv",
    "printf",
    "pwd",
    "runcon",
    "seq",
    "sleep",
    "tee",
    "test",
    "true",
    "tty",
    "whoami",
    "yes",
    "base64",
]}
