/* SPDX-FileCopyrightText: 2026 Austin Seipp
 * SPDX-License-Identifier: Apache-2.0 */
/* Exact powers of ten, retaining the highest 30 base-65536 digits.
 * No floating arithmetic, locale data, or precomputed numeric tables are used.
 * The reciprocal is floor(B^(digits(10^n)+29) / 10^n), where B=65536.
 * Truncating to 480 bits supplies far more than GAS's target precisions. */
#include <stdio.h>
#include <string.h>
#define CAPACITY 1024
#define PRECISION 30
static unsigned short number[CAPACITY];
static unsigned lengths[2][14];
static int exponents[2][14];
static void emit(unsigned kind, unsigned power, unsigned length, int exponent) {
    unsigned i, skip=length>PRECISION ? length-PRECISION : 0;
    const char *name=kind ? "minus" : "plus";
    lengths[kind][power]=length-skip;
    exponents[kind][power]=exponent+skip;
    printf("static const LITTLENUM_TYPE %s_%u[] = {",name,power);
    for(i=skip;i<length;i++) printf("%s%u",i==skip ? "" : ",",(unsigned)number[i]);
    puts("};");
}
int main(void) {
    unsigned k, power, length, i, j, carry, value, top, kind;
    puts("/* Generated by cellar/bootstrap/stage1/binutils/generators/flonum.c. */");
    puts("#include <flonum.h>");
    puts("const int table_size_of_flonum_powers_of_ten = 13;");
    puts("static const LITTLENUM_TYPE zero[] = {1};");
    for(k=1;k<=13;k++) {
        power=1U<<(k-1); memset(number,0,sizeof(number)); number[0]=1; length=1;
        for(j=0;j<power;j++) {
            carry=0;
            for(i=0;i<length;i++) { value=number[i]*10U+carry; number[i]=value; carry=value>>16; }
            if(carry) { if(length==CAPACITY) return 1; number[length++]=carry; }
        }
        emit(0,k,length,0);
        top=length+PRECISION-1; if(top>=CAPACITY) return 2;
        memset(number,0,sizeof(number)); number[top]=1; length=top+1;
        for(j=0;j<power;j++) {
            carry=0;
            for(i=length;i>0;i--) { value=(carry<<16)+number[i-1]; number[i-1]=value/10; carry=value%10; }
            while(length>1 && !number[length-1]) length--;
        }
        if(!number[length-1]) return 3;
        emit(1,k,length,-(int)top);
    }
    puts("#define X (LITTLENUM_TYPE *)");
    for(kind=0;kind<2;kind++) {
        const char *name=kind ? "minus" : "plus";
        printf("const FLONUM_TYPE flonum_%s_powers_of_ten[] = {\n",kind ? "negative" : "positive");
        puts("{X zero,X zero,X zero,0,'+'},");
        for(k=1;k<=13;k++) printf("{X %s_%u,X %s_%u+%u,X %s_%u+%u,%d,'+'},\n",name,k,name,k,lengths[kind][k]-1,name,k,lengths[kind][k]-1,exponents[kind][k]);
        puts("};");
    }
    return ferror(stdout)!=0;
}
