// SPDX-FileCopyrightText: © 2026 Austin Seipp
// SPDX-License-Identifier: Apache-2.0

// <auto-generated/>
// Bindings for world test of test:features@1.0.0, generated by witgen for gameplayc.
// The module implements the world's exports and calls its imports; edit
// the WIT and regenerate rather than this file.
#nullable disable

namespace Test.Features;

// Imported from test:features/shapes@1.0.0.
public static class Shapes
{
    /// <summary>
    /// A packed colour.
    /// </summary>
    /// <param name="A">
    /// Opacity: 0 is transparent.
    /// </param>
    public sealed record Color(byte R, byte G, byte B, byte A);

    public sealed record Rect(int X, int Y, uint W, uint H);

    /// <summary>
    /// A record inside a record flattens field by field.
    /// </summary>
    public sealed record Sprite(Shapes.Rect Bounds, Shapes.Color Tint, bool Visible);

    public enum ShapeKind
    {
        Circle,
        Square,
        List,
    }

    [global::System.Flags]
    public enum Style : uint
    {
        None = 0,
        Filled = 1u << 0,
        Outlined = 1u << 1,
        Dashed = 1u << 2,
    }

    /// <summary>
    /// A flag called `none` takes the name of the empty set.
    /// </summary>
    [global::System.Flags]
    public enum Mode : uint
    {
        None = 1u << 0,
        Fast = 1u << 1,
    }

    public sealed record Tagged(Shapes.ShapeKind Kind, bool Visible);

    /// <summary>
    /// An optional record as a field lowers like an optional parameter.
    /// </summary>
    public sealed record Window(Shapes.Rect Frame, Shapes.Tagged Tag);

    internal static uint Fill(Shapes.Rect bounds, Shapes.Color tint) => Imports.Fill(bounds.X, bounds.Y, bounds.W, bounds.H, tint.R, tint.G, tint.B, tint.A);

    internal static double Blit(Shapes.Sprite sprite, float scale) => Imports.Blit(sprite.Bounds.X, sprite.Bounds.Y, sprite.Bounds.W, sprite.Bounds.H, sprite.Tint.R, sprite.Tint.G, sprite.Tint.B, sprite.Tint.A, sprite.Visible, scale);

    internal static void SetClip(Shapes.Rect bounds)
    {
        int bounds_Some = 0;
        int bounds_0 = 0;
        int bounds_1 = 0;
        uint bounds_2 = 0;
        uint bounds_3 = 0;
        if (bounds != null)
        {
            bounds_Some = 1;
            bounds_0 = bounds.X;
            bounds_1 = bounds.Y;
            bounds_2 = bounds.W;
            bounds_3 = bounds.H;
        }

        Imports.SetClip(bounds_Some, bounds_0, bounds_1, bounds_2, bounds_3);
    }

    internal static Shapes.ShapeKind KindOf(uint sides) => Imports.KindOf(sides);

    internal static Shapes.Style StyleOf(Shapes.ShapeKind kind) => Imports.StyleOf(kind);

    internal static long Wide(long a, ulong b, sbyte c, ushort d, int e) => Imports.Wide(a, b, c, d, e);

    /// <summary>
    /// Each option lowers on its own.
    /// </summary>
    internal static uint SetClips(Shapes.Rect first, Shapes.Rect second)
    {
        int first_Some = 0;
        int first_0 = 0;
        int first_1 = 0;
        uint first_2 = 0;
        uint first_3 = 0;
        if (first != null)
        {
            first_Some = 1;
            first_0 = first.X;
            first_1 = first.Y;
            first_2 = first.W;
            first_3 = first.H;
        }
        int second_Some = 0;
        int second_0 = 0;
        int second_1 = 0;
        uint second_2 = 0;
        uint second_3 = 0;
        if (second != null)
        {
            second_Some = 1;
            second_0 = second.X;
            second_1 = second.Y;
            second_2 = second.W;
            second_3 = second.H;
        }

        return Imports.SetClips(first_Some, first_0, first_1, first_2, first_3, second_Some, second_0, second_1, second_2, second_3);
    }

    internal static uint Show(Shapes.Window window, Shapes.Tagged overlay)
    {
        int window_Tag_Some = 0;
        Shapes.ShapeKind window_Tag_0 = 0;
        bool window_Tag_1 = false;
        if (window.Tag != null)
        {
            window_Tag_Some = 1;
            window_Tag_0 = window.Tag.Kind;
            window_Tag_1 = window.Tag.Visible;
        }
        int overlay_Some = 0;
        Shapes.ShapeKind overlay_0 = 0;
        bool overlay_1 = false;
        if (overlay != null)
        {
            overlay_Some = 1;
            overlay_0 = overlay.Kind;
            overlay_1 = overlay.Visible;
        }

        return Imports.Show(window.Frame.X, window.Frame.Y, window.Frame.W, window.Frame.H, window_Tag_Some, window_Tag_0, window_Tag_1, overlay_Some, overlay_0, overlay_1);
    }

    internal static Shapes.Mode ModeOf(Shapes.Mode mode) => Imports.ModeOf(mode);

    /// <summary>
    /// A string crosses through the boundary memory.
    /// </summary>
    [global::Gameplay.CanonicalAbi]
    internal static void Label(Shapes.Rect bounds, string text)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        int pointer_2 = global::Gameplay.Runtime.Canonical.StoreString(text, out int length_3);
        Imports.Label(bounds.X, bounds.Y, unchecked((int)bounds.W), unchecked((int)bounds.H), pointer_2, length_3);
        global::Gameplay.Runtime.Canonical.Release(mark_1);
    }

    /// <summary>
    /// So does a record that comes back.
    /// </summary>
    [global::Gameplay.CanonicalAbi]
    internal static Shapes.Rect Measure(uint sides)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        int result_2 = global::Gameplay.Runtime.Canonical.Allocate(16, 4);
        Imports.Measure(unchecked((int)sides), result_2);
        int value_3 = global::Gameplay.Runtime.Memory.Load32(result_2 + 0);
        int value_4 = global::Gameplay.Runtime.Memory.Load32(result_2 + 4);
        uint value_5 = unchecked((uint)global::Gameplay.Runtime.Memory.Load32(result_2 + 8));
        uint value_6 = unchecked((uint)global::Gameplay.Runtime.Memory.Load32(result_2 + 12));
        var value_7 = new Shapes.Rect(value_3, value_4, value_5, value_6);
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_7;
    }

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "fill")]
        internal static extern uint Fill(int bounds_X, int bounds_Y, uint bounds_W, uint bounds_H, byte tint_R, byte tint_G, byte tint_B, byte tint_A);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "blit")]
        internal static extern double Blit(int sprite_Bounds_X, int sprite_Bounds_Y, uint sprite_Bounds_W, uint sprite_Bounds_H, byte sprite_Tint_R, byte sprite_Tint_G, byte sprite_Tint_B, byte sprite_Tint_A, bool sprite_Visible, float scale);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "set-clip")]
        internal static extern void SetClip(int bounds_Some, int bounds_0, int bounds_1, uint bounds_2, uint bounds_3);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "kind-of")]
        internal static extern Shapes.ShapeKind KindOf(uint sides);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "style-of")]
        internal static extern Shapes.Style StyleOf(Shapes.ShapeKind kind);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "wide")]
        internal static extern long Wide(long a, ulong b, sbyte c, ushort d, int e);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "set-clips")]
        internal static extern uint SetClips(int first_Some, int first_0, int first_1, uint first_2, uint first_3, int second_Some, int second_0, int second_1, uint second_2, uint second_3);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "show")]
        internal static extern uint Show(int window_Frame_X, int window_Frame_Y, uint window_Frame_W, uint window_Frame_H, int window_Tag_Some, Shapes.ShapeKind window_Tag_0, bool window_Tag_1, int overlay_Some, Shapes.ShapeKind overlay_0, bool overlay_1);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "mode-of")]
        internal static extern Shapes.Mode ModeOf(Shapes.Mode mode);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "label")]
        internal static extern void Label(int in_0, int in_1, int in_2, int in_3, int in_4, int in_5);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "measure")]
        internal static extern void Measure(int in_0, int in_1);
    }
}

// Imported from test:features/handles@1.0.0.
public static class Handles
{
    /// <summary>
    /// A host object addressed by handle.
    /// </summary>
    public sealed class Canvas
    {
        internal int Handle;
        internal bool Dropped;

        private enum Adopt_
        {
            Handle,
        }

        private Canvas(Adopt_ adopt, int handle)
        {
            Handle = handle;
        }

        /// <summary>Wraps a handle the host handed over; the caller owns it.</summary>
        public static Canvas FromHandle(int handle) => new Canvas(Adopt_.Handle, handle);

        /// <summary>The handle as the host sees it.</summary>
        public int ToHandle() => Handle;

        /// <summary>Drops the handle; later calls through it fault.</summary>
        public void Dispose()
        {
            if (!Dropped)
            {
                Dropped = true;
                Imports.CanvasDrop(Handle);
                Handle = 0;
            }
        }

        public Canvas(uint width, uint height)
        {
            Handle = Imports.CanvasConstructor(width, height);
        }

        public void Clear(byte value) => Imports.CanvasClear(Handle, value);

        public ulong Area() => Imports.CanvasArea(Handle);

        internal static Handles.Canvas Merge(Handles.Canvas first, Handles.Canvas second)
        {
            var result_ = Handles.Canvas.FromHandle(Imports.CanvasMerge(first.Handle, second.Handle));
            second.Dropped = true;
            second.Handle = 0;
            return result_;
        }

        public bool TakeClip(Shapes.Rect bounds)
        {
            int bounds_Some = 0;
            int bounds_0 = 0;
            int bounds_1 = 0;
            uint bounds_2 = 0;
            uint bounds_3 = 0;
            if (bounds != null)
            {
                bounds_Some = 1;
                bounds_0 = bounds.X;
                bounds_1 = bounds.Y;
                bounds_2 = bounds.W;
                bounds_3 = bounds.H;
            }

            return Imports.CanvasTakeClip(Handle, bounds_Some, bounds_0, bounds_1, bounds_2, bounds_3);
        }
    }

    /// <summary>
    /// A constructor taking one s32, the shape of the handle wrapper's.
    /// </summary>
    public sealed class Counter
    {
        internal int Handle;
        internal bool Dropped;

        private enum Adopt_
        {
            Handle,
        }

        private Counter(Adopt_ adopt, int handle)
        {
            Handle = handle;
        }

        /// <summary>Wraps a handle the host handed over; the caller owns it.</summary>
        public static Counter FromHandle(int handle) => new Counter(Adopt_.Handle, handle);

        /// <summary>The handle as the host sees it.</summary>
        public int ToHandle() => Handle;

        /// <summary>Drops the handle; later calls through it fault.</summary>
        public void Dispose()
        {
            if (!Dropped)
            {
                Dropped = true;
                Imports.CounterDrop(Handle);
                Handle = 0;
            }
        }

        public Counter(int start)
        {
            Handle = Imports.CounterConstructor(start);
        }

        public int Get() => Imports.CounterGet(Handle);
    }

    /// <summary>
    /// A constructor with an owned argument and an option.
    /// </summary>
    public sealed class Layer
    {
        internal int Handle;
        internal bool Dropped;

        private enum Adopt_
        {
            Handle,
        }

        private Layer(Adopt_ adopt, int handle)
        {
            Handle = handle;
        }

        /// <summary>Wraps a handle the host handed over; the caller owns it.</summary>
        public static Layer FromHandle(int handle) => new Layer(Adopt_.Handle, handle);

        /// <summary>The handle as the host sees it.</summary>
        public int ToHandle() => Handle;

        /// <summary>Drops the handle; later calls through it fault.</summary>
        public void Dispose()
        {
            if (!Dropped)
            {
                Dropped = true;
                Imports.LayerDrop(Handle);
                Handle = 0;
            }
        }

        public Layer(Handles.Canvas @base, Shapes.Rect clip)
        {
            int clip_Some = 0;
            int clip_0 = 0;
            int clip_1 = 0;
            uint clip_2 = 0;
            uint clip_3 = 0;
            if (clip != null)
            {
                clip_Some = 1;
                clip_0 = clip.X;
                clip_1 = clip.Y;
                clip_2 = clip.W;
                clip_3 = clip.H;
            }

            Handle = Imports.LayerConstructor(@base.Handle, clip_Some, clip_0, clip_1, clip_2, clip_3);
            @base.Dropped = true;
            @base.Handle = 0;
        }
    }

    internal static Handles.Canvas Open(uint id) => Handles.Canvas.FromHandle(Imports.Open(id));

    internal static void DisposeAll() => Imports.DisposeAll();

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[constructor]canvas")]
        internal static extern int CanvasConstructor(uint width, uint height);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[method]canvas.clear")]
        internal static extern void CanvasClear(int self, byte value);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[method]canvas.area")]
        internal static extern ulong CanvasArea(int self);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[static]canvas.merge")]
        internal static extern int CanvasMerge(int first, int second);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[method]canvas.take-clip")]
        internal static extern bool CanvasTakeClip(int self, int bounds_Some, int bounds_0, int bounds_1, uint bounds_2, uint bounds_3);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[constructor]counter")]
        internal static extern int CounterConstructor(int start);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[method]counter.get")]
        internal static extern int CounterGet(int self);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[constructor]layer")]
        internal static extern int LayerConstructor(int @base, int clip_Some, int clip_0, int clip_1, uint clip_2, uint clip_3);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "open")]
        internal static extern int Open(uint id);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "dispose-all")]
        internal static extern void DisposeAll();

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[resource-drop]canvas")]
        internal static extern void CanvasDrop(int handle);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[resource-drop]counter")]
        internal static extern void CounterDrop(int handle);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[resource-drop]layer")]
        internal static extern void LayerDrop(int handle);
    }
}

/// <summary>
/// Handles of a resource another interface defines.
/// </summary>
// Imported from test:features/gifts@1.0.0.
public static class Gifts
{
    internal static Handles.Canvas Give(uint n) => Handles.Canvas.FromHandle(Imports.Give(n));

    internal static Handles.Canvas Swap(Handles.Canvas old)
    {
        var result_ = Handles.Canvas.FromHandle(Imports.Swap(old.Handle));
        old.Dropped = true;
        old.Handle = 0;
        return result_;
    }

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/gifts@1.0.0", "give")]
        internal static extern int Give(uint n);

        [global::Gameplay.WasmImport("test:features/gifts@1.0.0", "swap")]
        internal static extern int Swap(int old);
    }
}

/// <summary>
/// Shares its name with test:other/util.
/// </summary>
// Imported from test:features/util@1.0.0.
public static class TestFeaturesUtil
{
    internal static uint Ping(uint x) => Imports.Ping(x);

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/util@1.0.0", "ping")]
        internal static extern uint Ping(uint x);
    }
}

/// <summary>
/// Strings, lists, tuples, options and wide signatures: canonical ABI glue
/// through the boundary memory.
/// </summary>
// Imported from test:features/text@1.0.0.
public static class Text
{
    [global::Gameplay.CanonicalAbi]
    public sealed record Entry(string Name, uint Size, string[] Tags);

    [global::Gameplay.CanonicalAbi]
    public sealed record ShapeCircle(float Value);

    [global::Gameplay.CanonicalAbi]
    public sealed record ShapeRect(Test.Tuple2<uint, uint> Value);

    [global::Gameplay.CanonicalAbi]
    public sealed record ShapeLabel(string Value);

    [global::Gameplay.CanonicalAbi]
    public sealed record ShapeEmpty;

    /// <summary>
    /// Variants: a C# 15 union of a class per case.
    /// </summary>
    public union Shape(ShapeCircle, ShapeRect, ShapeLabel, ShapeEmpty);

    [global::Gameplay.CanonicalAbi]
    public sealed record MixedSmall(float Value);

    [global::Gameplay.CanonicalAbi]
    public sealed record MixedBig(ulong Value);

    [global::Gameplay.CanonicalAbi]
    public sealed record MixedText(string Value);

    [global::Gameplay.CanonicalAbi]
    public sealed record MixedNothing;

    /// <summary>
    /// Payloads of every width: flat, they join (f32 into i64 bits).
    /// </summary>
    public union Mixed(MixedSmall, MixedBig, MixedText, MixedNothing);

    /// <summary>
    /// A variant without payloads is an enum.
    /// </summary>
    public enum Signal
    {
        Go,
        Stop,
    }

    [global::Gameplay.CanonicalAbi]
    internal static string Greet(string name)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        int pointer_2 = global::Gameplay.Runtime.Canonical.StoreString(name, out int length_3);
        int result_4 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
        Imports.Greet(pointer_2, length_3, result_4);
        var value_5 = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(result_4), global::Gameplay.Runtime.Memory.Load32(result_4 + 4));
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_5;
    }

    [global::Gameplay.CanonicalAbi]
    internal static int[] Reverse(int[] values)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        var array_2 = values;
        int elements_3 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_2.Length, 4), 4);
        for (int index_4 = 0; index_4 < array_2.Length; index_4++)
        {
            global::Gameplay.Runtime.Memory.Store32(elements_3 + index_4 * 4, array_2[index_4]);
        }
        int result_5 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
        Imports.Reverse(elements_3, array_2.Length, result_5);
        int pointer_6 = global::Gameplay.Runtime.Memory.Load32(result_5);
        int length_7 = global::Gameplay.Runtime.Memory.Load32(result_5 + 4);
        var array_8 = new int[length_7];
        for (int index_9 = 0; index_9 < length_7; index_9++)
        {
            array_8[index_9] = global::Gameplay.Runtime.Memory.Load32(pointer_6 + index_9 * 4);
        }
        var value_10 = array_8;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_10;
    }

    [global::Gameplay.CanonicalAbi]
    internal static Text.Entry[] Entries(string prefix, uint count)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        int pointer_2 = global::Gameplay.Runtime.Canonical.StoreString(prefix, out int length_3);
        int result_4 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
        Imports.Entries(pointer_2, length_3, unchecked((int)count), result_4);
        int pointer_5 = global::Gameplay.Runtime.Memory.Load32(result_4);
        int length_6 = global::Gameplay.Runtime.Memory.Load32(result_4 + 4);
        var array_7 = new Text.Entry[length_6];
        for (int index_8 = 0; index_8 < length_6; index_8++)
        {
            int address_9 = pointer_5 + index_8 * 20;
            int address_10 = address_9 + 0;
            string value_11 = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_10), global::Gameplay.Runtime.Memory.Load32(address_10 + 4));
            uint value_12 = unchecked((uint)global::Gameplay.Runtime.Memory.Load32(address_9 + 8));
            int address_13 = address_9 + 12;
            int pointer_14 = global::Gameplay.Runtime.Memory.Load32(address_13);
            int length_15 = global::Gameplay.Runtime.Memory.Load32(address_13 + 4);
            var array_16 = new string[length_15];
            for (int index_17 = 0; index_17 < length_15; index_17++)
            {
                int address_18 = pointer_14 + index_17 * 8;
                array_16[index_17] = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_18), global::Gameplay.Runtime.Memory.Load32(address_18 + 4));
            }
            array_7[index_8] = new Text.Entry(value_11, value_12, array_16);
        }
        var value_19 = array_7;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_19;
    }

    [global::Gameplay.CanonicalAbi]
    internal static Test.Tuple2<string, string> Split(string text, uint at)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        int pointer_2 = global::Gameplay.Runtime.Canonical.StoreString(text, out int length_3);
        int result_4 = global::Gameplay.Runtime.Canonical.Allocate(16, 4);
        Imports.Split(pointer_2, length_3, unchecked((int)at), result_4);
        int address_5 = result_4 + 0;
        string value_6 = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_5), global::Gameplay.Runtime.Memory.Load32(address_5 + 4));
        int address_7 = result_4 + 8;
        string value_8 = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_7), global::Gameplay.Runtime.Memory.Load32(address_7 + 4));
        var value_9 = new Test.Tuple2<string, string>(value_6, value_8);
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_9;
    }

    [global::Gameplay.CanonicalAbi]
    internal static Test.Option<uint> Find(ushort[] values, ushort wanted)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        var array_2 = values;
        int elements_3 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_2.Length, 2), 2);
        for (int index_4 = 0; index_4 < array_2.Length; index_4++)
        {
            global::Gameplay.Runtime.Memory.Store16(elements_3 + index_4 * 2, array_2[index_4]);
        }
        int result_5 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
        Imports.Find(elements_3, array_2.Length, (int)wanted, result_5);
        Test.Option<uint> option_6 = default;
        if (global::Gameplay.Runtime.Memory.Load8U(result_5) != 0)
        {
            option_6 = new Test.Option<uint>(unchecked((uint)global::Gameplay.Runtime.Memory.Load32(result_5 + 4)));
        }
        var value_7 = option_6;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_7;
    }

    [global::Gameplay.CanonicalAbi]
    internal static string MaybeName(uint id)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        int result_2 = global::Gameplay.Runtime.Canonical.Allocate(12, 4);
        Imports.MaybeName(unchecked((int)id), result_2);
        string option_3 = default;
        if (global::Gameplay.Runtime.Memory.Load8U(result_2) != 0)
        {
            int address_4 = result_2 + 4;
            option_3 = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_4), global::Gameplay.Runtime.Memory.Load32(address_4 + 4));
        }
        var value_5 = option_3;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_5;
    }

    /// <summary>
    /// Seventeen flat parameters: they go through memory.
    /// </summary>
    [global::Gameplay.CanonicalAbi]
    internal static ulong Many(uint a, uint b, uint c, uint d, uint e, uint f, uint g, uint h, uint i, uint j, uint k, uint l, uint m, uint n, uint o, uint p, uint q)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        int params_2 = global::Gameplay.Runtime.Canonical.Allocate(68, 4);
        global::Gameplay.Runtime.Memory.Store32(params_2 + 0, unchecked((int)a));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 4, unchecked((int)b));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 8, unchecked((int)c));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 12, unchecked((int)d));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 16, unchecked((int)e));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 20, unchecked((int)f));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 24, unchecked((int)g));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 28, unchecked((int)h));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 32, unchecked((int)i));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 36, unchecked((int)j));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 40, unchecked((int)k));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 44, unchecked((int)l));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 48, unchecked((int)m));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 52, unchecked((int)n));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 56, unchecked((int)o));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 60, unchecked((int)p));
        global::Gameplay.Runtime.Memory.Store32(params_2 + 64, unchecked((int)q));
        var raw_3 = Imports.Many(params_2);
        var value_4 = unchecked((ulong)raw_3);
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_4;
    }

    [global::Gameplay.CanonicalAbi]
    internal static uint Checksum(byte[] data)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        var array_2 = data;
        int elements_3 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_2.Length, 1), 1);
        for (int index_4 = 0; index_4 < array_2.Length; index_4++)
        {
            global::Gameplay.Runtime.Memory.Store8(elements_3 + index_4 * 1, array_2[index_4]);
        }
        var raw_5 = Imports.Checksum(elements_3, array_2.Length);
        var value_6 = unchecked((uint)raw_5);
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_6;
    }

    [global::Gameplay.CanonicalAbi]
    internal static byte[][] Transpose(byte[][] rows)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        var array_2 = rows;
        int elements_3 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_2.Length, 8), 4);
        for (int index_4 = 0; index_4 < array_2.Length; index_4++)
        {
            var array_5 = array_2[index_4];
            int elements_6 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_5.Length, 1), 1);
            for (int index_7 = 0; index_7 < array_5.Length; index_7++)
            {
                global::Gameplay.Runtime.Memory.Store8(elements_6 + index_7 * 1, array_5[index_7]);
            }
            global::Gameplay.Runtime.Memory.Store32(elements_3 + index_4 * 8, elements_6);
            global::Gameplay.Runtime.Memory.Store32(elements_3 + index_4 * 8 + 4, array_5.Length);
        }
        int result_8 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
        Imports.Transpose(elements_3, array_2.Length, result_8);
        int pointer_9 = global::Gameplay.Runtime.Memory.Load32(result_8);
        int length_10 = global::Gameplay.Runtime.Memory.Load32(result_8 + 4);
        var array_11 = new byte[length_10][];
        for (int index_12 = 0; index_12 < length_10; index_12++)
        {
            int address_13 = pointer_9 + index_12 * 8;
            int pointer_14 = global::Gameplay.Runtime.Memory.Load32(address_13);
            int length_15 = global::Gameplay.Runtime.Memory.Load32(address_13 + 4);
            var array_16 = new byte[length_15];
            for (int index_17 = 0; index_17 < length_15; index_17++)
            {
                array_16[index_17] = (byte)global::Gameplay.Runtime.Memory.Load8U(pointer_14 + index_17 * 1);
            }
            array_11[index_12] = array_16;
        }
        var value_18 = array_11;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_18;
    }

    [global::Gameplay.CanonicalAbi]
    internal static uint Pairs(Test.Tuple2<string, Test.Option<long>>[] items)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        var array_2 = items;
        int elements_3 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_2.Length, 24), 8);
        for (int index_4 = 0; index_4 < array_2.Length; index_4++)
        {
            var tuple_5 = array_2[index_4];
            global::Gameplay.Runtime.Memory.Store32(elements_3 + index_4 * 24 + 0, global::Gameplay.Runtime.Canonical.StoreString(tuple_5.Item0, out int length_6));
            global::Gameplay.Runtime.Memory.Store32(elements_3 + index_4 * 24 + 0 + 4, length_6);
            var option_7 = tuple_5.Item1;
            if (option_7.HasValue)
            {
                global::Gameplay.Runtime.Memory.Store8(elements_3 + index_4 * 24 + 8, 1);
                global::Gameplay.Runtime.Memory.Store64(elements_3 + index_4 * 24 + 8 + 8, option_7.Value);
            }
            else
            {
                global::Gameplay.Runtime.Memory.Store8(elements_3 + index_4 * 24 + 8, 0);
            }
        }
        var raw_8 = Imports.Pairs(elements_3, array_2.Length);
        var value_9 = unchecked((uint)raw_8);
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_9;
    }

    [global::Gameplay.CanonicalAbi]
    internal static double Area(Text.Shape shape)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        var variant_2 = shape;
        int case_3 = 0;
        int flat_4 = 0;
        int flat_5 = 0;
        if (variant_2 is Text.ShapeCircle value_6)
        {
            case_3 = 0;
            flat_4 = global::Gameplay.Runtime.Memory.F32Bits(value_6.Value);
        }
        else if (variant_2 is Text.ShapeRect value_7)
        {
            case_3 = 1;
            flat_4 = unchecked((int)value_7.Value.Item0);
            flat_5 = unchecked((int)value_7.Value.Item1);
        }
        else if (variant_2 is Text.ShapeLabel value_8)
        {
            case_3 = 2;
            int pointer_9 = global::Gameplay.Runtime.Canonical.StoreString(value_8.Value, out int length_10);
            flat_4 = pointer_9;
            flat_5 = length_10;
        }
        else if (variant_2 is Text.ShapeEmpty value_11)
        {
            case_3 = 3;
        }
        else
        {
            throw new global::System.InvalidOperationException();
        }
        var raw_12 = Imports.Area(case_3, flat_4, flat_5);
        var value_13 = raw_12;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_13;
    }

    [global::Gameplay.CanonicalAbi]
    internal static Test.Result<uint, string> Parse(string text)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        int pointer_2 = global::Gameplay.Runtime.Canonical.StoreString(text, out int length_3);
        int result_4 = global::Gameplay.Runtime.Canonical.Allocate(12, 4);
        Imports.Parse(pointer_2, length_3, result_4);
        int case_5 = global::Gameplay.Runtime.Memory.Load8U(result_4);
        Test.Result<uint, string> variant_6 = default;
        if (case_5 == 0)
        {
            variant_6 = new Test.Ok<uint>(unchecked((uint)global::Gameplay.Runtime.Memory.Load32(result_4 + 4)));
        }
        else if (case_5 == 1)
        {
            int address_7 = result_4 + 4;
            variant_6 = new Test.Err<string>(global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_7), global::Gameplay.Runtime.Memory.Load32(address_7 + 4)));
        }
        else
        {
            throw new global::System.InvalidOperationException();
        }
        var value_8 = variant_6;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_8;
    }

    [global::Gameplay.CanonicalAbi]
    internal static Text.Mixed Mix(Text.Mixed value)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        var variant_2 = value;
        int case_3 = 0;
        long flat_4 = 0;
        int flat_5 = 0;
        if (variant_2 is Text.MixedSmall value_6)
        {
            case_3 = 0;
            flat_4 = (long)unchecked((uint)(global::Gameplay.Runtime.Memory.F32Bits(value_6.Value)));
        }
        else if (variant_2 is Text.MixedBig value_7)
        {
            case_3 = 1;
            flat_4 = unchecked((long)value_7.Value);
        }
        else if (variant_2 is Text.MixedText value_8)
        {
            case_3 = 2;
            int pointer_9 = global::Gameplay.Runtime.Canonical.StoreString(value_8.Value, out int length_10);
            flat_4 = (long)unchecked((uint)(pointer_9));
            flat_5 = length_10;
        }
        else if (variant_2 is Text.MixedNothing value_11)
        {
            case_3 = 3;
        }
        else
        {
            throw new global::System.InvalidOperationException();
        }
        int result_12 = global::Gameplay.Runtime.Canonical.Allocate(16, 8);
        Imports.Mix(case_3, flat_4, flat_5, result_12);
        int case_13 = global::Gameplay.Runtime.Memory.Load8U(result_12);
        Text.Mixed variant_14 = default;
        if (case_13 == 0)
        {
            variant_14 = new Text.MixedSmall(global::Gameplay.Runtime.Memory.LoadF32(result_12 + 8));
        }
        else if (case_13 == 1)
        {
            variant_14 = new Text.MixedBig(unchecked((ulong)global::Gameplay.Runtime.Memory.Load64(result_12 + 8)));
        }
        else if (case_13 == 2)
        {
            int address_15 = result_12 + 8;
            variant_14 = new Text.MixedText(global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_15), global::Gameplay.Runtime.Memory.Load32(address_15 + 4)));
        }
        else if (case_13 == 3)
        {
            variant_14 = new Text.MixedNothing();
        }
        else
        {
            throw new global::System.InvalidOperationException();
        }
        var value_16 = variant_14;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_16;
    }

    internal static Text.Signal SignalOf(uint value) => Imports.SignalOf(value);

    [global::Gameplay.CanonicalAbi]
    internal static Test.Result<Test.Unit, string[]> Validate(Test.Result<Text.Shape, byte>[] values)
    {
        int mark_1 = global::Gameplay.Runtime.Canonical.Mark();
        var array_2 = values;
        int elements_3 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_2.Length, 16), 4);
        for (int index_4 = 0; index_4 < array_2.Length; index_4++)
        {
            int address_5 = elements_3 + index_4 * 16;
            var variant_6 = array_2[index_4];
            if (variant_6 is Test.Ok<Text.Shape> value_7)
            {
                global::Gameplay.Runtime.Memory.Store8(address_5, 0);
                int address_8 = address_5 + 4;
                var variant_9 = value_7.Value;
                if (variant_9 is Text.ShapeCircle value_10)
                {
                    global::Gameplay.Runtime.Memory.Store8(address_8, 0);
                    global::Gameplay.Runtime.Memory.StoreF32(address_8 + 4, value_10.Value);
                }
                else if (variant_9 is Text.ShapeRect value_11)
                {
                    global::Gameplay.Runtime.Memory.Store8(address_8, 1);
                    var tuple_12 = value_11.Value;
                    global::Gameplay.Runtime.Memory.Store32(address_8 + 4 + 0, unchecked((int)tuple_12.Item0));
                    global::Gameplay.Runtime.Memory.Store32(address_8 + 4 + 4, unchecked((int)tuple_12.Item1));
                }
                else if (variant_9 is Text.ShapeLabel value_13)
                {
                    global::Gameplay.Runtime.Memory.Store8(address_8, 2);
                    global::Gameplay.Runtime.Memory.Store32(address_8 + 4, global::Gameplay.Runtime.Canonical.StoreString(value_13.Value, out int length_14));
                    global::Gameplay.Runtime.Memory.Store32(address_8 + 4 + 4, length_14);
                }
                else if (variant_9 is Text.ShapeEmpty value_15)
                {
                    global::Gameplay.Runtime.Memory.Store8(address_8, 3);
                }
                else
                {
                    throw new global::System.InvalidOperationException();
                }
            }
            else if (variant_6 is Test.Err<byte> value_16)
            {
                global::Gameplay.Runtime.Memory.Store8(address_5, 1);
                global::Gameplay.Runtime.Memory.Store8(address_5 + 4, value_16.Value);
            }
            else
            {
                throw new global::System.InvalidOperationException();
            }
        }
        int result_17 = global::Gameplay.Runtime.Canonical.Allocate(12, 4);
        Imports.Validate(elements_3, array_2.Length, result_17);
        int case_18 = global::Gameplay.Runtime.Memory.Load8U(result_17);
        Test.Result<Test.Unit, string[]> variant_19 = default;
        if (case_18 == 0)
        {
            variant_19 = new Test.Ok<Test.Unit>(null);
        }
        else if (case_18 == 1)
        {
            int address_20 = result_17 + 4;
            int pointer_21 = global::Gameplay.Runtime.Memory.Load32(address_20);
            int length_22 = global::Gameplay.Runtime.Memory.Load32(address_20 + 4);
            var array_23 = new string[length_22];
            for (int index_24 = 0; index_24 < length_22; index_24++)
            {
                int address_25 = pointer_21 + index_24 * 8;
                array_23[index_24] = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_25), global::Gameplay.Runtime.Memory.Load32(address_25 + 4));
            }
            variant_19 = new Test.Err<string[]>(array_23);
        }
        else
        {
            throw new global::System.InvalidOperationException();
        }
        var value_26 = variant_19;
        global::Gameplay.Runtime.Canonical.Release(mark_1);
        return value_26;
    }

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/text@1.0.0", "greet")]
        internal static extern void Greet(int in_0, int in_1, int in_2);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "reverse")]
        internal static extern void Reverse(int in_0, int in_1, int in_2);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "entries")]
        internal static extern void Entries(int in_0, int in_1, int in_2, int in_3);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "split")]
        internal static extern void Split(int in_0, int in_1, int in_2, int in_3);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "find")]
        internal static extern void Find(int in_0, int in_1, int in_2, int in_3);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "maybe-name")]
        internal static extern void MaybeName(int in_0, int in_1);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "many")]
        internal static extern long Many(int in_0);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "checksum")]
        internal static extern int Checksum(int in_0, int in_1);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "transpose")]
        internal static extern void Transpose(int in_0, int in_1, int in_2);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "pairs")]
        internal static extern int Pairs(int in_0, int in_1);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "area")]
        internal static extern double Area(int in_0, int in_1, int in_2);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "parse")]
        internal static extern void Parse(int in_0, int in_1, int in_2);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "mix")]
        internal static extern void Mix(int in_0, long in_1, int in_2, int in_3);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "signal-of")]
        internal static extern Text.Signal SignalOf(uint value);

        [global::Gameplay.WasmImport("test:features/text@1.0.0", "validate")]
        internal static extern void Validate(int in_0, int in_1, int in_2);
    }
}

// Imported from test:other/util.
public static class TestOtherUtil
{
    internal static uint Ping(uint x) => Imports.Ping(x);

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:other/util", "ping")]
        internal static extern uint Ping(uint x);
    }
}

/// <summary>
/// Every export is implementable, so a module can be componentized against
/// this world.
/// </summary>
public static partial class Test
{
    internal static void Log(uint level, int code) => Imports.Log(level, code);

    [global::Gameplay.WasmExport("run")]
    public static partial uint Run(uint steps);

    [global::Gameplay.WasmExport("finish")]
    public static partial long Finish();

    public static partial string Describe();

    [global::Gameplay.WasmExport("describe")]
    [global::Gameplay.CanonicalAbi]
    public static int DescribeExport()
    {
        var result_1 = Describe();
        int area_2 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
        global::Gameplay.Runtime.Memory.Store32(area_2, global::Gameplay.Runtime.Canonical.StoreString(result_1, out int length_3));
        global::Gameplay.Runtime.Memory.Store32(area_2 + 4, length_3);
        return area_2;
    }

    // Exported as test:features/callbacks@1.0.0: implement the partial methods.
    public static partial class Callbacks
    {
        public sealed record Hit(Shapes.Rect Where, Shapes.ShapeKind What);

        public static partial bool OnHit(Test.Callbacks.Hit hit, Shapes.Color tint);

        [global::Gameplay.WasmExport("test:features/callbacks@1.0.0#on-hit")]
        public static bool OnHitExport(int hit_Where_X, int hit_Where_Y, uint hit_Where_W, uint hit_Where_H, Shapes.ShapeKind hit_What, byte tint_R, byte tint_G, byte tint_B, byte tint_A) => OnHit(new Test.Callbacks.Hit(new Shapes.Rect(hit_Where_X, hit_Where_Y, hit_Where_W, hit_Where_H), hit_What), new Shapes.Color(tint_R, tint_G, tint_B, tint_A));

        [global::Gameplay.WasmExport("test:features/callbacks@1.0.0#on-tick")]
        public static partial int OnTick(ulong frame);

        public static partial int OnWindow(Shapes.Window window, Shapes.Rect extra);

        [global::Gameplay.WasmExport("test:features/callbacks@1.0.0#on-window")]
        public static int OnWindowExport(int window_Frame_X, int window_Frame_Y, uint window_Frame_W, uint window_Frame_H, int window_Tag_Some, Shapes.ShapeKind window_Tag_0, bool window_Tag_1, int extra_Some, int extra_0, int extra_1, uint extra_2, uint extra_3) => OnWindow(new Shapes.Window(new Shapes.Rect(window_Frame_X, window_Frame_Y, window_Frame_W, window_Frame_H), (window_Tag_Some != 0 ? new Shapes.Tagged(window_Tag_0, window_Tag_1) : null)), (extra_Some != 0 ? new Shapes.Rect(extra_0, extra_1, extra_2, extra_3) : null));

        /// <summary>
        /// Handles cross exports as their i32 representation.
        /// </summary>
        public static partial Handles.Canvas OnCanvas(Handles.Canvas seen, Handles.Canvas kept);

        [global::Gameplay.WasmExport("test:features/callbacks@1.0.0#on-canvas")]
        public static int OnCanvasExport(int seen, int kept)
        {
            var result_ = OnCanvas(Handles.Canvas.FromHandle(seen), Handles.Canvas.FromHandle(kept));
            int handle_ = result_.Handle;
            result_.Dropped = true;
            result_.Handle = 0;
            return handle_;
        }
    }

    // Exported as test:features/text-callbacks@1.0.0: implement the partial methods.
    public static partial class TextCallbacks
    {
        public static partial string OnText(string text);

        [global::Gameplay.WasmExport("test:features/text-callbacks@1.0.0#on-text")]
        [global::Gameplay.CanonicalAbi]
        public static int OnTextExport(int in_0, int in_1)
        {
            string argument_1 = global::Gameplay.Runtime.Canonical.LoadString(in_0, in_1);
            var result_2 = OnText(argument_1);
            int area_3 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
            global::Gameplay.Runtime.Memory.Store32(area_3, global::Gameplay.Runtime.Canonical.StoreString(result_2, out int length_4));
            global::Gameplay.Runtime.Memory.Store32(area_3 + 4, length_4);
            return area_3;
        }

        public static partial string[] OnValues(double[] values);

        [global::Gameplay.WasmExport("test:features/text-callbacks@1.0.0#on-values")]
        [global::Gameplay.CanonicalAbi]
        public static int OnValuesExport(int in_0, int in_1)
        {
            var array_1 = new double[in_1];
            for (int index_2 = 0; index_2 < in_1; index_2++)
            {
                array_1[index_2] = global::Gameplay.Runtime.Memory.LoadF64(in_0 + index_2 * 8);
            }
            double[] argument_3 = array_1;
            var result_4 = OnValues(argument_3);
            int area_5 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
            var array_6 = result_4;
            int elements_7 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_6.Length, 8), 4);
            for (int index_8 = 0; index_8 < array_6.Length; index_8++)
            {
                global::Gameplay.Runtime.Memory.Store32(elements_7 + index_8 * 8, global::Gameplay.Runtime.Canonical.StoreString(array_6[index_8], out int length_9));
                global::Gameplay.Runtime.Memory.Store32(elements_7 + index_8 * 8 + 4, length_9);
            }
            global::Gameplay.Runtime.Memory.Store32(area_5, elements_7);
            global::Gameplay.Runtime.Memory.Store32(area_5 + 4, array_6.Length);
            return area_5;
        }

        public static partial Text.Entry OnEntry(Text.Entry entry, Test.Option<byte> extra);

        [global::Gameplay.WasmExport("test:features/text-callbacks@1.0.0#on-entry")]
        [global::Gameplay.CanonicalAbi]
        public static int OnEntryExport(int in_0, int in_1, int in_2, int in_3, int in_4, int in_5, int in_6)
        {
            string value_1 = global::Gameplay.Runtime.Canonical.LoadString(in_0, in_1);
            uint value_2 = unchecked((uint)in_2);
            var array_3 = new string[in_4];
            for (int index_4 = 0; index_4 < in_4; index_4++)
            {
                int address_5 = in_3 + index_4 * 8;
                array_3[index_4] = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_5), global::Gameplay.Runtime.Memory.Load32(address_5 + 4));
            }
            Text.Entry argument_6 = new Text.Entry(value_1, value_2, array_3);
            Test.Option<byte> option_7 = default;
            if (in_5 != 0)
            {
                option_7 = new Test.Option<byte>(unchecked((byte)in_6));
            }
            Test.Option<byte> argument_8 = option_7;
            var result_9 = OnEntry(argument_6, argument_8);
            int area_10 = global::Gameplay.Runtime.Canonical.Allocate(24, 4);
            var option_11 = result_9;
            if (option_11 != null)
            {
                global::Gameplay.Runtime.Memory.Store8(area_10, 1);
                var record_12 = option_11;
                global::Gameplay.Runtime.Memory.Store32(area_10 + 4 + 0, global::Gameplay.Runtime.Canonical.StoreString(record_12.Name, out int length_13));
                global::Gameplay.Runtime.Memory.Store32(area_10 + 4 + 0 + 4, length_13);
                global::Gameplay.Runtime.Memory.Store32(area_10 + 4 + 8, unchecked((int)record_12.Size));
                var array_14 = record_12.Tags;
                int elements_15 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_14.Length, 8), 4);
                for (int index_16 = 0; index_16 < array_14.Length; index_16++)
                {
                    global::Gameplay.Runtime.Memory.Store32(elements_15 + index_16 * 8, global::Gameplay.Runtime.Canonical.StoreString(array_14[index_16], out int length_17));
                    global::Gameplay.Runtime.Memory.Store32(elements_15 + index_16 * 8 + 4, length_17);
                }
                global::Gameplay.Runtime.Memory.Store32(area_10 + 4 + 12, elements_15);
                global::Gameplay.Runtime.Memory.Store32(area_10 + 4 + 12 + 4, array_14.Length);
            }
            else
            {
                global::Gameplay.Runtime.Memory.Store8(area_10, 0);
            }
            return area_10;
        }

        public static partial Test.Tuple2<long, string> OnMany(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j, int k, int l, int m, int n, int o, int p, string q);

        [global::Gameplay.WasmExport("test:features/text-callbacks@1.0.0#on-many")]
        [global::Gameplay.CanonicalAbi]
        public static int OnManyExport(int in_0)
        {
            int argument_1 = global::Gameplay.Runtime.Memory.Load32(in_0 + 0);
            int argument_2 = global::Gameplay.Runtime.Memory.Load32(in_0 + 4);
            int argument_3 = global::Gameplay.Runtime.Memory.Load32(in_0 + 8);
            int argument_4 = global::Gameplay.Runtime.Memory.Load32(in_0 + 12);
            int argument_5 = global::Gameplay.Runtime.Memory.Load32(in_0 + 16);
            int argument_6 = global::Gameplay.Runtime.Memory.Load32(in_0 + 20);
            int argument_7 = global::Gameplay.Runtime.Memory.Load32(in_0 + 24);
            int argument_8 = global::Gameplay.Runtime.Memory.Load32(in_0 + 28);
            int argument_9 = global::Gameplay.Runtime.Memory.Load32(in_0 + 32);
            int argument_10 = global::Gameplay.Runtime.Memory.Load32(in_0 + 36);
            int argument_11 = global::Gameplay.Runtime.Memory.Load32(in_0 + 40);
            int argument_12 = global::Gameplay.Runtime.Memory.Load32(in_0 + 44);
            int argument_13 = global::Gameplay.Runtime.Memory.Load32(in_0 + 48);
            int argument_14 = global::Gameplay.Runtime.Memory.Load32(in_0 + 52);
            int argument_15 = global::Gameplay.Runtime.Memory.Load32(in_0 + 56);
            int argument_16 = global::Gameplay.Runtime.Memory.Load32(in_0 + 60);
            int address_17 = in_0 + 64;
            string argument_18 = global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_17), global::Gameplay.Runtime.Memory.Load32(address_17 + 4));
            var result_19 = OnMany(argument_1, argument_2, argument_3, argument_4, argument_5, argument_6, argument_7, argument_8, argument_9, argument_10, argument_11, argument_12, argument_13, argument_14, argument_15, argument_16, argument_18);
            int area_20 = global::Gameplay.Runtime.Canonical.Allocate(16, 8);
            var tuple_21 = result_19;
            global::Gameplay.Runtime.Memory.Store64(area_20 + 0, tuple_21.Item0);
            global::Gameplay.Runtime.Memory.Store32(area_20 + 8, global::Gameplay.Runtime.Canonical.StoreString(tuple_21.Item1, out int length_22));
            global::Gameplay.Runtime.Memory.Store32(area_20 + 8 + 4, length_22);
            return area_20;
        }

        public static partial Test.Result<string, uint> OnShape(Text.Shape shape);

        [global::Gameplay.WasmExport("test:features/text-callbacks@1.0.0#on-shape")]
        [global::Gameplay.CanonicalAbi]
        public static int OnShapeExport(int in_0, int in_1, int in_2)
        {
            Text.Shape variant_1 = default;
            if (in_0 == 0)
            {
                float flat_2 = global::Gameplay.Runtime.Memory.F32FromBits(in_1);
                variant_1 = new Text.ShapeCircle(flat_2);
            }
            else if (in_0 == 1)
            {
                int flat_3 = in_1;
                int flat_4 = in_2;
                uint value_5 = unchecked((uint)flat_3);
                uint value_6 = unchecked((uint)flat_4);
                variant_1 = new Text.ShapeRect(new Test.Tuple2<uint, uint>(value_5, value_6));
            }
            else if (in_0 == 2)
            {
                int flat_7 = in_1;
                int flat_8 = in_2;
                variant_1 = new Text.ShapeLabel(global::Gameplay.Runtime.Canonical.LoadString(flat_7, flat_8));
            }
            else if (in_0 == 3)
            {
                variant_1 = new Text.ShapeEmpty();
            }
            else
            {
                throw new global::System.InvalidOperationException();
            }
            Text.Shape argument_9 = variant_1;
            var result_10 = OnShape(argument_9);
            int area_11 = global::Gameplay.Runtime.Canonical.Allocate(12, 4);
            var variant_12 = result_10;
            if (variant_12 is Test.Ok<string> value_13)
            {
                global::Gameplay.Runtime.Memory.Store8(area_11, 0);
                global::Gameplay.Runtime.Memory.Store32(area_11 + 4, global::Gameplay.Runtime.Canonical.StoreString(value_13.Value, out int length_14));
                global::Gameplay.Runtime.Memory.Store32(area_11 + 4 + 4, length_14);
            }
            else if (variant_12 is Test.Err<uint> value_15)
            {
                global::Gameplay.Runtime.Memory.Store8(area_11, 1);
                global::Gameplay.Runtime.Memory.Store32(area_11 + 4, unchecked((int)value_15.Value));
            }
            else
            {
                throw new global::System.InvalidOperationException();
            }
            return area_11;
        }

        public static partial Test.Result<Test.Unit, string>[] OnMixed(Text.Mixed[] values);

        [global::Gameplay.WasmExport("test:features/text-callbacks@1.0.0#on-mixed")]
        [global::Gameplay.CanonicalAbi]
        public static int OnMixedExport(int in_0, int in_1)
        {
            var array_1 = new Text.Mixed[in_1];
            for (int index_2 = 0; index_2 < in_1; index_2++)
            {
                int address_3 = in_0 + index_2 * 16;
                int case_4 = global::Gameplay.Runtime.Memory.Load8U(address_3);
                Text.Mixed variant_5 = default;
                if (case_4 == 0)
                {
                    variant_5 = new Text.MixedSmall(global::Gameplay.Runtime.Memory.LoadF32(address_3 + 8));
                }
                else if (case_4 == 1)
                {
                    variant_5 = new Text.MixedBig(unchecked((ulong)global::Gameplay.Runtime.Memory.Load64(address_3 + 8)));
                }
                else if (case_4 == 2)
                {
                    int address_6 = address_3 + 8;
                    variant_5 = new Text.MixedText(global::Gameplay.Runtime.Canonical.LoadString(global::Gameplay.Runtime.Memory.Load32(address_6), global::Gameplay.Runtime.Memory.Load32(address_6 + 4)));
                }
                else if (case_4 == 3)
                {
                    variant_5 = new Text.MixedNothing();
                }
                else
                {
                    throw new global::System.InvalidOperationException();
                }
                array_1[index_2] = variant_5;
            }
            Text.Mixed[] argument_7 = array_1;
            var result_8 = OnMixed(argument_7);
            int area_9 = global::Gameplay.Runtime.Canonical.Allocate(8, 4);
            var array_10 = result_8;
            int elements_11 = global::Gameplay.Runtime.Canonical.Allocate(global::Gameplay.Runtime.Canonical.Size(array_10.Length, 12), 4);
            for (int index_12 = 0; index_12 < array_10.Length; index_12++)
            {
                int address_13 = elements_11 + index_12 * 12;
                var variant_14 = array_10[index_12];
                if (variant_14 is Test.Ok<Test.Unit> value_15)
                {
                    global::Gameplay.Runtime.Memory.Store8(address_13, 0);
                }
                else if (variant_14 is Test.Err<string> value_16)
                {
                    global::Gameplay.Runtime.Memory.Store8(address_13, 1);
                    global::Gameplay.Runtime.Memory.Store32(address_13 + 4, global::Gameplay.Runtime.Canonical.StoreString(value_16.Value, out int length_17));
                    global::Gameplay.Runtime.Memory.Store32(address_13 + 4 + 4, length_17);
                }
                else
                {
                    throw new global::System.InvalidOperationException();
                }
            }
            global::Gameplay.Runtime.Memory.Store32(area_9, elements_11);
            global::Gameplay.Runtime.Memory.Store32(area_9 + 4, array_10.Length);
            return area_9;
        }
    }

    /// <summary>A WIT <c>tuple</c> of 2.</summary>
    public record struct Tuple2<T0, T1>(T0 Item0, T1 Item1);

    /// <summary>A WIT <c>result</c>'s side without a payload.</summary>
    [global::Gameplay.CanonicalAbi]
    public sealed record Unit;

    /// <summary>A WIT <c>result</c>'s success.</summary>
    public sealed record Ok<T>(T Value);

    /// <summary>A WIT <c>result</c>'s error.</summary>
    public sealed record Err<T>(T Value);

    /// <summary>A WIT <c>result</c>.</summary>
    public union Result<T, E>(Ok<T>, Err<E>);

    /// <summary>A WIT <c>option</c> of a value that cannot be null.</summary>
    public struct Option<T>
    {
        public bool HasValue;
        public T Value;

        public Option(T value)
        {
            HasValue = true;
            Value = value;
        }
    }

    private static class Imports
    {
        [global::Gameplay.WasmImport("$root", "log")]
        internal static extern void Log(uint level, int code);
    }
}
