// SPDX-FileCopyrightText: © 2026 Austin Seipp
// SPDX-License-Identifier: Apache-2.0

// <auto-generated/>
// Bindings for world test of test:features@1.0.0, generated by witgen for gameplayc.
// The module implements the world's exports and calls its imports; edit
// the WIT and regenerate rather than this file.
#nullable disable

namespace Test.Features;

// Imported from test:features/shapes@1.0.0.
public static class Shapes
{
    /// <summary>
    /// A packed colour.
    /// </summary>
    public sealed class Color
    {
        public byte R;
        public byte G;
        public byte B;
        public byte A;

        public Color()
        {
        }

        public Color(byte r, byte g, byte b, byte a)
        {
            R = r;
            G = g;
            B = b;
            A = a;
        }
    }

    public sealed class Rect
    {
        public int X;
        public int Y;
        public uint W;
        public uint H;

        public Rect()
        {
        }

        public Rect(int x, int y, uint w, uint h)
        {
            X = x;
            Y = y;
            W = w;
            H = h;
        }
    }

    /// <summary>
    /// A record inside a record flattens field by field.
    /// </summary>
    public sealed class Sprite
    {
        public Shapes.Rect Bounds;
        public Shapes.Color Tint;
        public bool Visible;

        public Sprite()
        {
        }

        public Sprite(Shapes.Rect bounds, Shapes.Color tint, bool visible)
        {
            Bounds = bounds;
            Tint = tint;
            Visible = visible;
        }
    }

    public enum ShapeKind
    {
        Circle,
        Square,
        List,
    }

    [global::System.Flags]
    public enum Style : uint
    {
        None = 0,
        Filled = 1u << 0,
        Outlined = 1u << 1,
        Dashed = 1u << 2,
    }

    /// <summary>
    /// A flag called `none` takes the name of the empty set.
    /// </summary>
    [global::System.Flags]
    public enum Mode : uint
    {
        None = 1u << 0,
        Fast = 1u << 1,
    }

    public sealed class Tagged
    {
        public Shapes.ShapeKind Kind;
        public bool Visible;

        public Tagged()
        {
        }

        public Tagged(Shapes.ShapeKind kind, bool visible)
        {
            Kind = kind;
            Visible = visible;
        }
    }

    /// <summary>
    /// An optional record as a field lowers like an optional parameter.
    /// </summary>
    public sealed class Window
    {
        public Shapes.Rect Frame;
        public Shapes.Tagged Tag;

        public Window()
        {
        }

        public Window(Shapes.Rect frame, Shapes.Tagged tag)
        {
            Frame = frame;
            Tag = tag;
        }
    }

    internal static uint Fill(Shapes.Rect bounds, Shapes.Color tint) => Imports.Fill(bounds.X, bounds.Y, bounds.W, bounds.H, tint.R, tint.G, tint.B, tint.A);

    internal static double Blit(Shapes.Sprite sprite, float scale) => Imports.Blit(sprite.Bounds.X, sprite.Bounds.Y, sprite.Bounds.W, sprite.Bounds.H, sprite.Tint.R, sprite.Tint.G, sprite.Tint.B, sprite.Tint.A, sprite.Visible, scale);

    internal static void SetClip(Shapes.Rect bounds)
    {
        int bounds_Some = 0;
        int bounds_0 = 0;
        int bounds_1 = 0;
        uint bounds_2 = 0;
        uint bounds_3 = 0;
        if (bounds != null)
        {
            bounds_Some = 1;
            bounds_0 = bounds.X;
            bounds_1 = bounds.Y;
            bounds_2 = bounds.W;
            bounds_3 = bounds.H;
        }

        Imports.SetClip(bounds_Some, bounds_0, bounds_1, bounds_2, bounds_3);
    }

    internal static Shapes.ShapeKind KindOf(uint sides) => Imports.KindOf(sides);

    internal static Shapes.Style StyleOf(Shapes.ShapeKind kind) => Imports.StyleOf(kind);

    internal static long Wide(long a, ulong b, sbyte c, ushort d, int e) => Imports.Wide(a, b, c, d, e);

    /// <summary>
    /// Each option lowers on its own.
    /// </summary>
    internal static uint SetClips(Shapes.Rect first, Shapes.Rect second)
    {
        int first_Some = 0;
        int first_0 = 0;
        int first_1 = 0;
        uint first_2 = 0;
        uint first_3 = 0;
        if (first != null)
        {
            first_Some = 1;
            first_0 = first.X;
            first_1 = first.Y;
            first_2 = first.W;
            first_3 = first.H;
        }
        int second_Some = 0;
        int second_0 = 0;
        int second_1 = 0;
        uint second_2 = 0;
        uint second_3 = 0;
        if (second != null)
        {
            second_Some = 1;
            second_0 = second.X;
            second_1 = second.Y;
            second_2 = second.W;
            second_3 = second.H;
        }

        return Imports.SetClips(first_Some, first_0, first_1, first_2, first_3, second_Some, second_0, second_1, second_2, second_3);
    }

    internal static uint Show(Shapes.Window window, Shapes.Tagged overlay)
    {
        int window_Tag_Some = 0;
        Shapes.ShapeKind window_Tag_0 = 0;
        bool window_Tag_1 = false;
        if (window.Tag != null)
        {
            window_Tag_Some = 1;
            window_Tag_0 = window.Tag.Kind;
            window_Tag_1 = window.Tag.Visible;
        }
        int overlay_Some = 0;
        Shapes.ShapeKind overlay_0 = 0;
        bool overlay_1 = false;
        if (overlay != null)
        {
            overlay_Some = 1;
            overlay_0 = overlay.Kind;
            overlay_1 = overlay.Visible;
        }

        return Imports.Show(window.Frame.X, window.Frame.Y, window.Frame.W, window.Frame.H, window_Tag_Some, window_Tag_0, window_Tag_1, overlay_Some, overlay_0, overlay_1);
    }

    internal static Shapes.Mode ModeOf(Shapes.Mode mode) => Imports.ModeOf(mode);

    // Not generated: label: needs memory (strings, lists, records as results), is asynchronous or uses an unsupported type

    // Not generated: measure: needs memory (strings, lists, records as results), is asynchronous or uses an unsupported type

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "fill")]
        internal static extern uint Fill(int bounds_X, int bounds_Y, uint bounds_W, uint bounds_H, byte tint_R, byte tint_G, byte tint_B, byte tint_A);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "blit")]
        internal static extern double Blit(int sprite_Bounds_X, int sprite_Bounds_Y, uint sprite_Bounds_W, uint sprite_Bounds_H, byte sprite_Tint_R, byte sprite_Tint_G, byte sprite_Tint_B, byte sprite_Tint_A, bool sprite_Visible, float scale);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "set-clip")]
        internal static extern void SetClip(int bounds_Some, int bounds_0, int bounds_1, uint bounds_2, uint bounds_3);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "kind-of")]
        internal static extern Shapes.ShapeKind KindOf(uint sides);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "style-of")]
        internal static extern Shapes.Style StyleOf(Shapes.ShapeKind kind);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "wide")]
        internal static extern long Wide(long a, ulong b, sbyte c, ushort d, int e);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "set-clips")]
        internal static extern uint SetClips(int first_Some, int first_0, int first_1, uint first_2, uint first_3, int second_Some, int second_0, int second_1, uint second_2, uint second_3);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "show")]
        internal static extern uint Show(int window_Frame_X, int window_Frame_Y, uint window_Frame_W, uint window_Frame_H, int window_Tag_Some, Shapes.ShapeKind window_Tag_0, bool window_Tag_1, int overlay_Some, Shapes.ShapeKind overlay_0, bool overlay_1);

        [global::Gameplay.WasmImport("test:features/shapes@1.0.0", "mode-of")]
        internal static extern Shapes.Mode ModeOf(Shapes.Mode mode);
    }
}

// Imported from test:features/handles@1.0.0.
public static class Handles
{
    /// <summary>
    /// A host object addressed by handle.
    /// </summary>
    public sealed class Canvas
    {
        internal int Handle;
        internal bool Dropped;

        private enum Adopt_
        {
            Handle,
        }

        private Canvas(Adopt_ adopt, int handle)
        {
            Handle = handle;
        }

        /// <summary>Wraps a handle the host handed over; the caller owns it.</summary>
        public static Canvas FromHandle(int handle) => new Canvas(Adopt_.Handle, handle);

        /// <summary>The handle as the host sees it.</summary>
        public int ToHandle() => Handle;

        /// <summary>Drops the handle; later calls through it fault.</summary>
        public void Dispose()
        {
            if (!Dropped)
            {
                Dropped = true;
                Imports.CanvasDrop(Handle);
                Handle = 0;
            }
        }

        public Canvas(uint width, uint height)
        {
            Handle = Imports.CanvasConstructor(width, height);
        }

        public void Clear(byte value) => Imports.CanvasClear(Handle, value);

        public ulong Area() => Imports.CanvasArea(Handle);

        internal static Handles.Canvas Merge(Handles.Canvas first, Handles.Canvas second)
        {
            var result_ = Handles.Canvas.FromHandle(Imports.CanvasMerge(first.Handle, second.Handle));
            second.Dropped = true;
            second.Handle = 0;
            return result_;
        }

        public bool TakeClip(Shapes.Rect bounds)
        {
            int bounds_Some = 0;
            int bounds_0 = 0;
            int bounds_1 = 0;
            uint bounds_2 = 0;
            uint bounds_3 = 0;
            if (bounds != null)
            {
                bounds_Some = 1;
                bounds_0 = bounds.X;
                bounds_1 = bounds.Y;
                bounds_2 = bounds.W;
                bounds_3 = bounds.H;
            }

            return Imports.CanvasTakeClip(Handle, bounds_Some, bounds_0, bounds_1, bounds_2, bounds_3);
        }
    }

    /// <summary>
    /// A constructor taking one s32, the shape of the handle wrapper's.
    /// </summary>
    public sealed class Counter
    {
        internal int Handle;
        internal bool Dropped;

        private enum Adopt_
        {
            Handle,
        }

        private Counter(Adopt_ adopt, int handle)
        {
            Handle = handle;
        }

        /// <summary>Wraps a handle the host handed over; the caller owns it.</summary>
        public static Counter FromHandle(int handle) => new Counter(Adopt_.Handle, handle);

        /// <summary>The handle as the host sees it.</summary>
        public int ToHandle() => Handle;

        /// <summary>Drops the handle; later calls through it fault.</summary>
        public void Dispose()
        {
            if (!Dropped)
            {
                Dropped = true;
                Imports.CounterDrop(Handle);
                Handle = 0;
            }
        }

        public Counter(int start)
        {
            Handle = Imports.CounterConstructor(start);
        }

        public int Get() => Imports.CounterGet(Handle);
    }

    /// <summary>
    /// A constructor with an owned argument and an option.
    /// </summary>
    public sealed class Layer
    {
        internal int Handle;
        internal bool Dropped;

        private enum Adopt_
        {
            Handle,
        }

        private Layer(Adopt_ adopt, int handle)
        {
            Handle = handle;
        }

        /// <summary>Wraps a handle the host handed over; the caller owns it.</summary>
        public static Layer FromHandle(int handle) => new Layer(Adopt_.Handle, handle);

        /// <summary>The handle as the host sees it.</summary>
        public int ToHandle() => Handle;

        /// <summary>Drops the handle; later calls through it fault.</summary>
        public void Dispose()
        {
            if (!Dropped)
            {
                Dropped = true;
                Imports.LayerDrop(Handle);
                Handle = 0;
            }
        }

        public Layer(Handles.Canvas @base, Shapes.Rect clip)
        {
            int clip_Some = 0;
            int clip_0 = 0;
            int clip_1 = 0;
            uint clip_2 = 0;
            uint clip_3 = 0;
            if (clip != null)
            {
                clip_Some = 1;
                clip_0 = clip.X;
                clip_1 = clip.Y;
                clip_2 = clip.W;
                clip_3 = clip.H;
            }

            Handle = Imports.LayerConstructor(@base.Handle, clip_Some, clip_0, clip_1, clip_2, clip_3);
            @base.Dropped = true;
            @base.Handle = 0;
        }
    }

    internal static Handles.Canvas Open(uint id) => Handles.Canvas.FromHandle(Imports.Open(id));

    internal static void DisposeAll() => Imports.DisposeAll();

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[constructor]canvas")]
        internal static extern int CanvasConstructor(uint width, uint height);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[method]canvas.clear")]
        internal static extern void CanvasClear(int self, byte value);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[method]canvas.area")]
        internal static extern ulong CanvasArea(int self);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[static]canvas.merge")]
        internal static extern int CanvasMerge(int first, int second);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[method]canvas.take-clip")]
        internal static extern bool CanvasTakeClip(int self, int bounds_Some, int bounds_0, int bounds_1, uint bounds_2, uint bounds_3);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[constructor]counter")]
        internal static extern int CounterConstructor(int start);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[method]counter.get")]
        internal static extern int CounterGet(int self);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[constructor]layer")]
        internal static extern int LayerConstructor(int @base, int clip_Some, int clip_0, int clip_1, uint clip_2, uint clip_3);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "open")]
        internal static extern int Open(uint id);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "dispose-all")]
        internal static extern void DisposeAll();

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[resource-drop]canvas")]
        internal static extern void CanvasDrop(int handle);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[resource-drop]counter")]
        internal static extern void CounterDrop(int handle);

        [global::Gameplay.WasmImport("test:features/handles@1.0.0", "[resource-drop]layer")]
        internal static extern void LayerDrop(int handle);
    }
}

/// <summary>
/// Handles of a resource another interface defines.
/// </summary>
// Imported from test:features/gifts@1.0.0.
public static class Gifts
{
    internal static Handles.Canvas Give(uint n) => Handles.Canvas.FromHandle(Imports.Give(n));

    internal static Handles.Canvas Swap(Handles.Canvas old)
    {
        var result_ = Handles.Canvas.FromHandle(Imports.Swap(old.Handle));
        old.Dropped = true;
        old.Handle = 0;
        return result_;
    }

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/gifts@1.0.0", "give")]
        internal static extern int Give(uint n);

        [global::Gameplay.WasmImport("test:features/gifts@1.0.0", "swap")]
        internal static extern int Swap(int old);
    }
}

/// <summary>
/// Shares its name with test:other/util.
/// </summary>
// Imported from test:features/util@1.0.0.
public static class TestFeaturesUtil
{
    internal static uint Ping(uint x) => Imports.Ping(x);

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:features/util@1.0.0", "ping")]
        internal static extern uint Ping(uint x);
    }
}

// Imported from test:other/util.
public static class TestOtherUtil
{
    internal static uint Ping(uint x) => Imports.Ping(x);

    private static class Imports
    {
        [global::Gameplay.WasmImport("test:other/util", "ping")]
        internal static extern uint Ping(uint x);
    }
}

/// <summary>
/// Every export is implementable, so a module can be componentized against
/// this world; two of its imports are not, and appear in the report.
/// </summary>
public static partial class Test
{
    internal static void Log(uint level, int code) => Imports.Log(level, code);

    [global::Gameplay.WasmExport("run")]
    public static partial uint Run(uint steps);

    [global::Gameplay.WasmExport("finish")]
    public static partial long Finish();

    // Exported as test:features/callbacks@1.0.0: implement the partial methods.
    public static partial class Callbacks
    {
        public sealed class Hit
        {
            public Shapes.Rect Where;
            public Shapes.ShapeKind What;

            public Hit()
            {
            }

            public Hit(Shapes.Rect where, Shapes.ShapeKind what)
            {
                Where = where;
                What = what;
            }
        }

        public static partial bool OnHit(Test.Callbacks.Hit hit, Shapes.Color tint);

        [global::Gameplay.WasmExport("test:features/callbacks@1.0.0#on-hit")]
        public static bool OnHitExport(int hit_Where_X, int hit_Where_Y, uint hit_Where_W, uint hit_Where_H, Shapes.ShapeKind hit_What, byte tint_R, byte tint_G, byte tint_B, byte tint_A) => OnHit(new Test.Callbacks.Hit(new Shapes.Rect(hit_Where_X, hit_Where_Y, hit_Where_W, hit_Where_H), hit_What), new Shapes.Color(tint_R, tint_G, tint_B, tint_A));

        [global::Gameplay.WasmExport("test:features/callbacks@1.0.0#on-tick")]
        public static partial int OnTick(ulong frame);

        public static partial int OnWindow(Shapes.Window window, Shapes.Rect extra);

        [global::Gameplay.WasmExport("test:features/callbacks@1.0.0#on-window")]
        public static int OnWindowExport(int window_Frame_X, int window_Frame_Y, uint window_Frame_W, uint window_Frame_H, int window_Tag_Some, Shapes.ShapeKind window_Tag_0, bool window_Tag_1, int extra_Some, int extra_0, int extra_1, uint extra_2, uint extra_3) => OnWindow(new Shapes.Window(new Shapes.Rect(window_Frame_X, window_Frame_Y, window_Frame_W, window_Frame_H), (window_Tag_Some != 0 ? new Shapes.Tagged(window_Tag_0, window_Tag_1) : null)), (extra_Some != 0 ? new Shapes.Rect(extra_0, extra_1, extra_2, extra_3) : null));

        /// <summary>
        /// Handles cross exports as their i32 representation.
        /// </summary>
        public static partial Handles.Canvas OnCanvas(Handles.Canvas seen, Handles.Canvas kept);

        [global::Gameplay.WasmExport("test:features/callbacks@1.0.0#on-canvas")]
        public static int OnCanvasExport(int seen, int kept)
        {
            var result_ = OnCanvas(Handles.Canvas.FromHandle(seen), Handles.Canvas.FromHandle(kept));
            int handle_ = result_.Handle;
            result_.Dropped = true;
            result_.Handle = 0;
            return handle_;
        }
    }

    private static class Imports
    {
        [global::Gameplay.WasmImport("$root", "log")]
        internal static extern void Log(uint level, int code);
    }
}
