buildscript.run = false
cargo_env = true
cfgs = []

['cfg(any(target_os = "linux", target_os = "macos"))']
buildscript.run = false
cfgs = ["asm", "switchable_stack"]

['cfg(all(target_os = "windows"))']
buildscript.run = false
cfgs = ["asm"]

[['cfg(all(target_arch = "x86_64", target_os = "linux"))'.cxx_library]]
name = "cbits-x86_64-linux"
srcs = ["src/arch/x86_64.s"]
include_paths = ["src/arch"]
preferred_linkage = "static"
compiler_flags = [
    "-xassembler-with-cpp",
    "-DCFG_TARGET_OS_linux",
    "-DCFG_TARGET_ARCH_x86_64",
    "-DCFG_TARGET_ENV_gnu",
]

[['cfg(all(target_arch = "aarch64", target_os = "linux"))'.cxx_library]]
name = "cbits-aarch64-linux"
srcs = ["src/arch/aarch_aapcs64.s"]
include_paths = ["src/arch"]
preferred_linkage = "static"
compiler_flags = [
    "-xassembler-with-cpp",
    "-DCFG_TARGET_OS_linux",
    "-DCFG_TARGET_ARCH_aarch64",
    "-DCFG_TARGET_ENV_gnu",
]

[['cfg(all(target_arch = "x86_64", target_os = "macos"))'.cxx_library]]
name = "cbits-x86_64-macos"
srcs = ["src/arch/x86_64.s"]
include_paths = ["src/arch"]
preferred_linkage = "static"
compiler_flags = [
    "-xassembler-with-cpp",
    "-DCFG_TARGET_OS_macos",
    "-DCFG_TARGET_ARCH_x86_64",
]

[['cfg(all(target_arch = "aarch64", target_os = "macos"))'.cxx_library]]
name = "cbits-aarch64-macos"
srcs = ["src/arch/aarch_aapcs64.s"]
include_paths = ["src/arch"]
preferred_linkage = "static"
compiler_flags = [
    "-xassembler-with-cpp",
    "-DCFG_TARGET_OS_macos",
    "-DCFG_TARGET_ARCH_aarch64",
]

[['cfg(all(target_arch = "x86_64", target_os = "windows"))'.cxx_library]]
name = "cbits-x86_64-windows"
srcs = ["src/arch/x86_64_msvc.asm"]
include_paths = ["src/arch"]
preferred_linkage = "static"
