# SPDX-FileCopyrightText: 2026 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# Literal architecture files from the pinned musl 1.2.5 archive.

ARCH_SOURCES = [
    "src/fenv/aarch64/fenv.s",
    "src/ldso/aarch64/dlsym.s",
    "src/ldso/aarch64/tlsdesc.s",
    "src/math/aarch64/ceil.c",
    "src/math/aarch64/ceilf.c",
    "src/math/aarch64/fabs.c",
    "src/math/aarch64/fabsf.c",
    "src/math/aarch64/floor.c",
    "src/math/aarch64/floorf.c",
    "src/math/aarch64/fma.c",
    "src/math/aarch64/fmaf.c",
    "src/math/aarch64/fmax.c",
    "src/math/aarch64/fmaxf.c",
    "src/math/aarch64/fmin.c",
    "src/math/aarch64/fminf.c",
    "src/math/aarch64/llrint.c",
    "src/math/aarch64/llrintf.c",
    "src/math/aarch64/llround.c",
    "src/math/aarch64/llroundf.c",
    "src/math/aarch64/lrint.c",
    "src/math/aarch64/lrintf.c",
    "src/math/aarch64/lround.c",
    "src/math/aarch64/lroundf.c",
    "src/math/aarch64/nearbyint.c",
    "src/math/aarch64/nearbyintf.c",
    "src/math/aarch64/rint.c",
    "src/math/aarch64/rintf.c",
    "src/math/aarch64/round.c",
    "src/math/aarch64/roundf.c",
    "src/math/aarch64/sqrt.c",
    "src/math/aarch64/sqrtf.c",
    "src/math/aarch64/trunc.c",
    "src/math/aarch64/truncf.c",
    "src/process/aarch64/vfork.s",
    "src/setjmp/aarch64/longjmp.s",
    "src/setjmp/aarch64/setjmp.s",
    "src/signal/aarch64/restore.s",
    "src/signal/aarch64/sigsetjmp.s",
    "src/string/aarch64/memcpy.S",
    "src/string/aarch64/memset.S",
    "src/thread/aarch64/__set_thread_area.s",
    "src/thread/aarch64/__unmapself.s",
    "src/thread/aarch64/clone.s",
    "src/thread/aarch64/syscall_cp.s",
]

ARCH_HEADERS = [
    "arch/aarch64/atomic_arch.h",
    "arch/aarch64/bits/fcntl.h",
    "arch/aarch64/bits/fenv.h",
    "arch/aarch64/bits/float.h",
    "arch/aarch64/bits/hwcap.h",
    "arch/aarch64/bits/mman.h",
    "arch/aarch64/bits/posix.h",
    "arch/aarch64/bits/reg.h",
    "arch/aarch64/bits/setjmp.h",
    "arch/aarch64/bits/signal.h",
    "arch/aarch64/bits/stat.h",
    "arch/aarch64/bits/stdint.h",
    "arch/aarch64/bits/user.h",
    "arch/aarch64/crt_arch.h",
    "arch/aarch64/fp_arch.h",
    "arch/aarch64/kstat.h",
    "arch/aarch64/pthread_arch.h",
    "arch/aarch64/reloc.h",
    "arch/aarch64/syscall_arch.h",
]

CRT_SOURCES = [
    "crt/aarch64/crti.s",
    "crt/aarch64/crtn.s",
    "crt/crt1.c",
]
