load(
    "@cellar//bootstrap/stage0-posix:stage0.bzl",
    "stage0_platform",
)

stage0_platform(
    arch = "aarch64",
    arch_dir_upper = "AArch64",
    catm_bin = ":hex1",
    catm_src = "catm.hex1",
    filegroup_name = "aarch64-files",
    m2libc_dir = "aarch64",
)
