// SPDX-FileCopyrightText: © 2026 Austin Seipp
// SPDX-License-Identifier: Apache-2.0

// Host bindings for the imports of world platform of console:hal,
// generated by witgen.
// A host implements each interface below; `bind<Interface>` gives the
// core imports of its module, under wlink's host ABI, calling it.

/** An import's canonical memory. */
export interface GuestMemory {
  /** The `len` bytes at `ptr`, or the guest's trap outside the memory. */
  range(ptr: number, len: number): Uint8Array;
  /** The memory as it is now; an allocation may replace it. */
  data(): DataView;
}

/** An import's canonical memory and allocator. */
export interface GuestBinding {
  readonly mem: GuestMemory;
  /**
   * `len` fresh bytes aligned to `align` from the import's allocator, or
   * `align` itself when `len` is zero.
   */
  alloc(align: number, len: number): number;
}

/** What the bindings need of the guest. */
export interface Guest {
  /** The memory and allocator of the import `name` of `module`. */
  binding(module: string, name: string): GuestBinding;
  /** The error that ends the guest's run with a trap. */
  trap(message: string): Error;
}

export interface KeyEvent {
  /** The ordinal of console:sdk/input.key. */
  key: number;
  pressed: boolean;
}

export interface MouseState {
  x: number;
  y: number;
  dx: number;
  dy: number;
  /** The bits of console:sdk/input.mouse-buttons. */
  buttons: number;
  wheel: number;
}

export interface ReadResult {
  status: number;
  data: Uint8Array;
}

export interface Entry {
  name: Uint8Array | string;
  size: bigint;
  directory: boolean;
}

export interface ListResult {
  status: number;
  entries: ArrayLike<Entry>;
}

/** The core import module of `raw`. */
export const RAW_MODULE = "console:hal/raw@0.1.0";

/** The functions that take or return a pointer, and so have a memory. */
export const RAW_MEMORY: readonly string[] = [
  "write-log",
  "present",
  "present-indexed",
  "host-name",
  "set-title",
  "read-events",
  "read-mouse",
  "read-text",
  "audio-write",
  "file-open",
  "file-read-at",
  "file-write-at",
  "file-list-directory",
  "file-remove",
  "file-rename",
  "file-create-directory",
  "arg",
];

/** The functions that return strings or lists, and so have an allocator. */
export const RAW_REALLOC: readonly string[] = [
  "host-name",
  "read-events",
  "read-text",
  "file-read-at",
  "file-list-directory",
  "arg",
];

export interface Raw {
  writeLog(level: number, message: Uint8Array): void;
  present(width: number, height: number, rgba: Uint8Array): void;
  /**
   * One byte per pixel through a 256-entry palette whose entries hold
   * the bytes of an RGBA8 pixel in memory order.
   */
  presentIndexed(
    width: number,
    height: number,
    pixels: Uint8Array,
    palette: Uint32Array,
  ): void;
  framesPerSecond(): number;
  /** Honoured before the first frame; returns the rate in effect. */
  setFrameRate(hz: number): number;
  unixSeconds(): bigint;
  randomSeed(): bigint;
  hostName(): Uint8Array | string;
  /** The bits of console:sdk/system.features. */
  hostFeatures(): number;
  setTitle(title: Uint8Array): void;
  readEvents(): ArrayLike<KeyEvent>;
  /** The bits of console:sdk/input.capability. */
  inputCapabilities(): number;
  /** Motion and wheel counts are since the previous call. */
  readMouse(): MouseState;
  capturePointer(captured: number): number;
  readText(): Uint8Array | string;
  nowMs(): bigint;
  /**
   * Interleaved signed 16-bit stereo at 44100 Hz. Writing returns the
   * frames accepted; the host plays a frame period's worth of the queue
   * after every frame.
   */
  audioWrite(samples: Int16Array): number;
  audioQueued(): number;
  fileOpen(path: Uint8Array, write: boolean): number;
  fileSize(handle: number): bigint;
  fileReadAt(handle: number, offset: bigint, length: number): ReadResult;
  fileWriteAt(handle: number, offset: bigint, data: Uint8Array): number;
  fileClose(handle: number): void;
  /**
   * The entries directly inside a directory, sorted by name; a nonzero
   * status means there is no such directory. The empty path or "." is
   * the root. Every other operation returns zero on success.
   */
  fileListDirectory(path: Uint8Array): ListResult;
  fileRemove(path: Uint8Array): number;
  fileRename(path: Uint8Array, to: Uint8Array): number;
  fileCreateDirectory(path: Uint8Array): number;
  argCount(): number;
  arg(index: number): Uint8Array | string;
  exit(code: number): void;
}

/** The core imports of `RAW_MODULE`, calling `host`. */
export function bindRaw(host: Raw, guest: Guest): WebAssembly.ModuleImports {
  return {
    "write-log": (a0: number, a1: number, a2: number): void => {
      const b = guest.binding(RAW_MODULE, "write-log");
      host.writeLog(a0 >>> 0, b.mem.range(a1 >>> 0, a2 >>> 0));
    },
    "present": (a0: number, a1: number, a2: number, a3: number): void => {
      const b = guest.binding(RAW_MODULE, "present");
      host.present(a0 >>> 0, a1 >>> 0, b.mem.range(a2 >>> 0, a3 >>> 0));
    },
    "present-indexed": (
      a0: number,
      a1: number,
      a2: number,
      a3: number,
      a4: number,
      a5: number,
    ): void => {
      const b = guest.binding(RAW_MODULE, "present-indexed");
      host.presentIndexed(
        a0 >>> 0,
        a1 >>> 0,
        b.mem.range(a2 >>> 0, a3 >>> 0),
        witTyped(guest, b, a4, a5, 4, Uint32Array),
      );
    },
    "frames-per-second": (): number => {
      const t0 = host.framesPerSecond();
      return t0 >>> 0;
    },
    "set-frame-rate": (a0: number): number => {
      const t0 = host.setFrameRate(a0 >>> 0);
      return t0 >>> 0;
    },
    "unix-seconds": (): bigint => {
      const t0 = host.unixSeconds();
      return BigInt.asIntN(64, t0);
    },
    "random-seed": (): bigint => {
      const t0 = host.randomSeed();
      return BigInt.asUintN(64, t0);
    },
    "host-name": (a0: number): void => {
      const b = guest.binding(RAW_MODULE, "host-name");
      const t0 = host.hostName();
      witView(guest, b, a0, 1, 8, 4);
      const t1 = a0 >>> 0;
      const t2 = witEncode(t0);
      const t3 = b.alloc(1, t2.length);
      b.mem.range(t3, t2.length).set(t2);
      witSet32(b, t1 + 4, t2.length);
      witSet32(b, t1, t3);
    },
    "host-features": (): number => {
      const t0 = host.hostFeatures();
      return t0 >>> 0;
    },
    "set-title": (a0: number, a1: number): void => {
      const b = guest.binding(RAW_MODULE, "set-title");
      host.setTitle(b.mem.range(a0 >>> 0, a1 >>> 0));
    },
    "read-events": (a0: number): void => {
      const b = guest.binding(RAW_MODULE, "read-events");
      const t0 = host.readEvents();
      witView(guest, b, a0, 1, 8, 4);
      const t1 = a0 >>> 0;
      const t2 = b.alloc(4, t0.length * 8);
      if (t0.length > 0) {
        b.mem.range(t2, t0.length * 8).fill(0);
      }
      for (let i1 = 0; i1 < t0.length; i1++) {
        const e1 = t0[i1];
        const base1 = t2 + i1 * 8;
        witSet32(b, base1, e1.key >>> 0);
        witSet8(b, base1 + 4, e1.pressed ? 1 : 0);
      }
      witSet32(b, t1 + 4, t0.length);
      witSet32(b, t1, t2);
    },
    "input-capabilities": (): number => {
      const t0 = host.inputCapabilities();
      return t0 >>> 0;
    },
    "read-mouse": (a0: number): void => {
      const b = guest.binding(RAW_MODULE, "read-mouse");
      const t0 = host.readMouse();
      witView(guest, b, a0, 1, 24, 4);
      const t1 = a0 >>> 0;
      witSet32(b, t1, t0.x | 0);
      witSet32(b, t1 + 4, t0.y | 0);
      witSet32(b, t1 + 8, t0.dx | 0);
      witSet32(b, t1 + 12, t0.dy | 0);
      witSet32(b, t1 + 16, t0.buttons >>> 0);
      witSet32(b, t1 + 20, t0.wheel | 0);
    },
    "capture-pointer": (a0: number): number => {
      const t0 = host.capturePointer(a0 >>> 0);
      return t0 >>> 0;
    },
    "read-text": (a0: number): void => {
      const b = guest.binding(RAW_MODULE, "read-text");
      const t0 = host.readText();
      witView(guest, b, a0, 1, 8, 4);
      const t1 = a0 >>> 0;
      const t2 = witEncode(t0);
      const t3 = b.alloc(1, t2.length);
      b.mem.range(t3, t2.length).set(t2);
      witSet32(b, t1 + 4, t2.length);
      witSet32(b, t1, t3);
    },
    "now-ms": (): bigint => {
      const t0 = host.nowMs();
      return BigInt.asUintN(64, t0);
    },
    "audio-write": (a0: number, a1: number): number => {
      const b = guest.binding(RAW_MODULE, "audio-write");
      const t0 = host.audioWrite(witTyped(guest, b, a0, a1, 2, Int16Array));
      return t0 >>> 0;
    },
    "audio-queued": (): number => {
      const t0 = host.audioQueued();
      return t0 >>> 0;
    },
    "file-open": (a0: number, a1: number, a2: number): number => {
      const b = guest.binding(RAW_MODULE, "file-open");
      const t0 = host.fileOpen(b.mem.range(a0 >>> 0, a1 >>> 0), a2 !== 0);
      return t0 | 0;
    },
    "file-size": (a0: number): bigint => {
      const t0 = host.fileSize(a0 >>> 0);
      return BigInt.asIntN(64, t0);
    },
    "file-read-at": (a0: number, a1: bigint, a2: number, a3: number): void => {
      const b = guest.binding(RAW_MODULE, "file-read-at");
      const t0 = host.fileReadAt(a0 >>> 0, BigInt.asUintN(64, a1), a2 >>> 0);
      witView(guest, b, a3, 1, 12, 4);
      const t1 = a3 >>> 0;
      witSet32(b, t1, t0.status | 0);
      const t2 = b.alloc(1, t0.data.length);
      b.mem.range(t2, t0.data.length).set(t0.data);
      witSet32(b, t1 + 8, t0.data.length);
      witSet32(b, t1 + 4, t2);
    },
    "file-write-at": (
      a0: number,
      a1: bigint,
      a2: number,
      a3: number,
    ): number => {
      const b = guest.binding(RAW_MODULE, "file-write-at");
      const t0 = host.fileWriteAt(
        a0 >>> 0,
        BigInt.asUintN(64, a1),
        b.mem.range(a2 >>> 0, a3 >>> 0),
      );
      return t0 | 0;
    },
    "file-close": (a0: number): void => {
      host.fileClose(a0 >>> 0);
    },
    "file-list-directory": (a0: number, a1: number, a2: number): void => {
      const b = guest.binding(RAW_MODULE, "file-list-directory");
      const t0 = host.fileListDirectory(b.mem.range(a0 >>> 0, a1 >>> 0));
      witView(guest, b, a2, 1, 12, 4);
      const t1 = a2 >>> 0;
      witSet32(b, t1, t0.status | 0);
      const t4 = b.alloc(8, t0.entries.length * 24);
      if (t0.entries.length > 0) {
        b.mem.range(t4, t0.entries.length * 24).fill(0);
      }
      for (let i1 = 0; i1 < t0.entries.length; i1++) {
        const e1 = t0.entries[i1];
        const base1 = t4 + i1 * 24;
        const t2 = witEncode(e1.name);
        const t3 = b.alloc(1, t2.length);
        b.mem.range(t3, t2.length).set(t2);
        witSet32(b, base1 + 4, t2.length);
        witSet32(b, base1, t3);
        witSet64(b, base1 + 8, BigInt.asUintN(64, e1.size));
        witSet8(b, base1 + 16, e1.directory ? 1 : 0);
      }
      witSet32(b, t1 + 8, t0.entries.length);
      witSet32(b, t1 + 4, t4);
    },
    "file-remove": (a0: number, a1: number): number => {
      const b = guest.binding(RAW_MODULE, "file-remove");
      const t0 = host.fileRemove(b.mem.range(a0 >>> 0, a1 >>> 0));
      return t0 | 0;
    },
    "file-rename": (a0: number, a1: number, a2: number, a3: number): number => {
      const b = guest.binding(RAW_MODULE, "file-rename");
      const t0 = host.fileRename(
        b.mem.range(a0 >>> 0, a1 >>> 0),
        b.mem.range(a2 >>> 0, a3 >>> 0),
      );
      return t0 | 0;
    },
    "file-create-directory": (a0: number, a1: number): number => {
      const b = guest.binding(RAW_MODULE, "file-create-directory");
      const t0 = host.fileCreateDirectory(b.mem.range(a0 >>> 0, a1 >>> 0));
      return t0 | 0;
    },
    "arg-count": (): number => {
      const t0 = host.argCount();
      return t0 >>> 0;
    },
    "arg": (a0: number, a1: number): void => {
      const b = guest.binding(RAW_MODULE, "arg");
      const t0 = host.arg(a0 >>> 0);
      witView(guest, b, a1, 1, 8, 4);
      const t1 = a1 >>> 0;
      const t2 = witEncode(t0);
      const t3 = b.alloc(1, t2.length);
      b.mem.range(t3, t2.length).set(t2);
      witSet32(b, t1 + 4, t2.length);
      witSet32(b, t1, t3);
    },
    "exit": (a0: number): void => {
      host.exit(a0 | 0);
    },
  };
}

const encoder = new TextEncoder();

/** A string's UTF-8 bytes. */
function witEncode(value: Uint8Array | string): Uint8Array {
  return typeof value === "string" ? encoder.encode(value) : value;
}

type Typed<T> = new (
  buffer: ArrayBufferLike,
  offset: number,
  length: number,
) => T;

/** A list of numbers, as a typed array over the guest's memory. */
function witTyped<T>(
  guest: Guest,
  b: GuestBinding,
  ptr: number,
  len: number,
  size: number,
  array: Typed<T>,
): T {
  const bytes = witView(guest, b, ptr, len, size, size);
  return new array(bytes.buffer, bytes.byteOffset, len >>> 0);
}

/** The `count` elements of `size` bytes at `ptr`, checked. */
function witView(
  guest: Guest,
  b: GuestBinding,
  ptr: number,
  count: number,
  size: number,
  align: number,
): Uint8Array {
  if ((ptr >>> 0) % align !== 0) throw guest.trap("misaligned pointer");
  return b.mem.range(ptr >>> 0, (count >>> 0) * size);
}

function witSet32(b: GuestBinding, at: number, value: number): void {
  b.mem.range(at, 4);
  b.mem.data().setUint32(at, value >>> 0, true);
}

function witSet64(b: GuestBinding, at: number, value: bigint): void {
  b.mem.range(at, 8);
  b.mem.data().setBigUint64(at, BigInt.asUintN(64, value), true);
}

function witSet8(b: GuestBinding, at: number, value: number): void {
  b.mem.range(at, 1)[0] = value;
}
