name: autoupdate (nix)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake-lock:
    name: Update `buck/nixdev/flake.lock`
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@21a544727d0c62386e78b4befe52d19ad12692e3
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@428c2b58a4b7414dabd372acb6a03dba1084d3ab
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "[automerge] nix: update flake.lock"
          pr-body: Automated update of Nix flake dependencies.
          commit-msg: "nix: update flake.lock"
          path-to-flake-dir: buck/nixdev
