# SPDX-FileCopyrightText: © 2025 Austin Seipp
# SPDX-License-Identifier: Apache-2.0

# OCI image manipulation helpers

python_bootstrap_binary(
    name = "oci_pull",
    main = "oci_pull.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "oci_image",
    main = "oci_image.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "oci_unpack",
    main = "oci_unpack.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "oci_repack",
    main = "oci_repack.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "oci_index",
    main = "oci_index.py",
    visibility = ["PUBLIC"],
)

python_bootstrap_binary(
    name = "validate_image",
    main = "validate_image.py",
)
